### ISSUE TITLE
Does 'wine-tkg-staging-fsync-vkd3d-opt-git' replace 'wine-tkg-staging-fsync-git'?

### ISSUE THREAD

**Issue by jnines** [Frogging-Family/wine-tkg-git#100]
I'm assuming so, just want to make sure as it's not specified in the release notes.

**Comment by Mel34** [comment]
> I'm assuming so, just want to make sure as it's not specified in the release notes.

It does not, this package unpacks wine to /opt it seems.

**Comment by Tk-Glitch** [comment]
-opt builds will not conflict with normal builds, and will not conflict with different versions -opt builds. Those will get installed in /opt instead of /usr/bin, in their own versioned dir.
