### ISSUE TITLE
[Fix] Implement DiscardVirtualMemory(). for X Labs Launcher 

### ISSUE THREAD

**Issue by Heus-Sueh** [Frogging-Family/wine-tkg-git#1000]
this function is required for x labs launcher to be able to start
https://gitlab.winehq.org/wine/wine/-/commit/d7d94ed0df6931907d1c89d7d7551dd40f5214c5

![Screenshot from 2023-05-03 11-06-04](https://user-images.githubusercontent.com/98482469/236006886-7bed1b2f-f7c8-4b5e-90e9-3451b165171d.png)
![Screenshot from 2023-05-03 11-17-23](https://user-images.githubusercontent.com/98482469/236006832-7d95a1d9-50c8-46b2-b606-427b252ba53c.png)

**Comment by sonic2kk** [comment]
This is also needed for other applications, such as Vortex Mod Manager 1.8.0 and above.

**Comment by Fox2Code** [comment]
@Heus-Sueh do you want a hot fix for older wine version and valve versions?

Cause wine-tkg build on top of wine-staging which itself is built on top of regular wine.

So the latest version of wine-tkg should contain the commit you mentioned.

**Comment by therealmate** [comment]
https://github.com/GloriousEggroll/wine-ge-custom/commit/ef4e70bdb46381c8543ad26858a58d29fda7002b

**Comment by Heus-Sueh** [comment]
> [GloriousEggroll/wine-ge-custom@ef4e70b](https://github.com/GloriousEggroll/wine-ge-custom/commit/ef4e70bdb46381c8543ad26858a58d29fda7002b)

I didn't see that a new version of it had been released with the fix already included, sorry for the unnecessary issue
