### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by Swoiksdmop** [Frogging-Family/wine-tkg-git#1001]
I just see this but one question. How do I build this and use it :((

**Comment by Sukid** [comment]
git clone this, open the folder in a terminal, and type ./proton-tkg.sh

**Comment by Tk-Glitch** [comment]
For wine:
https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git#quick-how-to-

For proton:
https://github.com/Frogging-Family/wine-tkg-git/tree/master/proton-tkg#quick-how-to-

For prebuilts:
https://github.com/Frogging-Family/wine-tkg-git#wine-to-rule-them-all-
