### ISSUE TITLE
New issues with shared-gpu-resources patchset

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#1005]
Due to changes upstream, `sharedgpures-textures.patch` fails, and after I fixed the errors there, `sharedgpures-fences.patch` also fails because of a malformed error patch (even though when I try to just cut the offending hunk out of the patch and put it in a standalone one, it patches fine).  I was going to fix it to file a PR for you, but then I hit the malformed patch bullshit and it's 530 AM here lol.

**Comment by gardotd426** [comment]
For more information, the offending hunk on `sharedgpures-textures.patch` is hunk 4:

```
@@ -211,12 +211,12 @@ FUNCTION_OVERRIDES = {
     "vkGetDeviceProcAddr" : {"dispatch" : False, "driver" : True, "thunk" : ThunkType.NONE, "loader_thunk" : ThunkType.NONE},
     "vkGetDeviceQueue" : {"dispatch": True, "driver" : False, "thunk" : ThunkType.NONE},
     "vkGetDeviceQueue2" : {"dispatch": True, "driver" : False, "thunk" : ThunkType.NONE},
-    "vkAllocateMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
-    "vkFreeMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
+    "vkAllocateMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.NONE},
+    "vkFreeMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.NONE},
     "vkMapMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
     "vkUnmapMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
-    "vkCreateBuffer" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
-    "vkCreateImage" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
+    "vkCreateBuffer" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.NONE},
+    "vkCreateImage" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.NONE},

     # VK_KHR_surface
     "vkDestroySurfaceKHR" : {"dispatch" : True, "driver" : True, "thunk" : ThunkType.NONE},
```

The problem is the end of the hunk has new lines added:

```
    "vkMapMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
    "vkMapMemory2KHR" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
    "vkUnmapMemory" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
    "vkUnmapMemory2KHR" : {"dispatch" : True, "driver" : False, "thunk" : ThunkType.PRIVATE},
```

Then it's hunk 2 (line 29) in `sharedgpures-fences.patch` that fails.

**Comment by therealmate** [comment]
You might need to modify the lines that start with @@

**Comment by gardotd426** [comment]
I tried that. I corrected them to match the actual line numbers and number of starting and ending lines, and like I said the patch worked as a standalone patch with JUST the offending hunk, but it fails as a malformed patch at that line when included as hunk 2 of `sharedgpures-fences.patch`

**Comment by therealmate** [comment]
it patches for me after doing those changes(+sharedgpures-fixup-staging.patch)

**Comment by gardotd426** [comment]
@therealmate can you copy the three patch files you edited and paste each one to pastebin for me?

**Comment by therealmate** [comment]
[sharedgpures-.zip](https://github.com/Frogging-Family/wine-tkg-git/files/11421227/sharedgpures.zip)

**Comment by therealmate** [comment]
[sharedgpures-.zip](https://github.com/Frogging-Family/wine-tkg-git/files/11421269/sharedgpures-.zip)

**Comment by therealmate** [comment]
good luck!

**Comment by PhantomX** [comment]
I did some minor editions to sharedgpures-fixup-staging.patch. It builds and I think it worked.
[sharedgpures.zip](https://github.com/Frogging-Family/wine-tkg-git/files/11424860/sharedgpures.zip)

**Comment by gardotd426** [comment]
Jesus Christ guys, now upstream updated and broke goddamn `sharedgpures-fixup-staging.patch`, because of their complete overhaul of media-source.c. @Tk-Glitch hey Etienne, I'm sorry to ping you but when you git time could you look at the patches for media-source.c in that patch on lines 358, 872, 892, 855 and 876? (That's the order they fail in during the patching). The commits upstream to wine have reworked a ton of `media-source.c` and although I've been able to find most of the replaced lines in the current file so far, a lot of them failed because their immediate surroundings have completely changed/been removed/etc, so if I'm going to file a PR with an update to the patch I wanna make sure that I'm not breaking some video/mf compatibility or some nonsense by doing it and that might be hard to just test and I figured you could maybe take a look and see if anything needs to be rebased. 

If you don't have time let me know and I'll maybe hit up GE or someone else that can look at it that knows enough about C and Wine (and its MF stuff, I would ask Guy but I haven't talked to him in forever).

**Comment by csutcliff** [comment]
I think I've got it all compiling/working here: https://github.com/csutcliff/wine-tkg-git/tree/sharedgpuresources

let me know if it works for you too.

**Comment by llde** [comment]
@gardotd426 Wine reworked a lot of the format stuff. First they manage the flip status by format in a lot of different places, while before it was in a single function (commit 6c11a4af5885c6485a908ea5c547e072fe71aa23). Then they change the format initializer  handling using the WG format instead. 
Considering everything, the additional format should be put in another place, while the flag for mf handling of flip behaviour may not even be needed anymore

**Comment by Tk-Glitch** [comment]
The patch is not useful in its current form anyway even if it builds (it doesn't work at all for any game needing shared resources). So just skip it, you won't be missing anything. Use a valve base instead to have a working implementation if needed.

**Comment by gardotd426** [comment]
I'll go ahead and close this then. Do you know what games need it? If I don't play any of them I don't even have to worry about it.
