### ISSUE TITLE
proton-tkg-steamclient-swap patch fails to apply on wine master

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#1008]
Trying to build Proton targeting latest wine master fails with \
` -> Applying proton-tkg-steamclient-swap.patch
 ==> ERROR: Patch application has failed. The error was logged to /home/shaumux/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.`

The log file
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/11471504/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/eadc0e1f00e9dc62a188d0926098088e801ec7c0
