### ISSUE TITLE
Hotfix apply failure with latest git on tests/om.c

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#101]
Hello, everyone! The hotfixes have failed to apply since the last few commits. Here is the output of prepare.log:

```
[1m[34m  ->(B[m[1m Cleaning wine-staging source code tree...(B[m
HEAD is now at 3b24c1cf Rebase against f7895ef25a4cb2115ffbe04d28b87bcb6ee3c0b7.
[1m[34m  ->(B[m[1m Cleaning wine source code tree...(B[m
HEAD is now at f7895ef25a ntdll: Generate "system boot information" SMBIOS table.
Removing .gitignore

f4e55565470938d31e21f4a35aa14e5a950f81c8 reverted (hotfix)
Auto-merging dlls/ntdll/tests/om.c
CONFLICT (content): Merge conflict in dlls/ntdll/tests/om.c
Auto-merging dlls/ntdll/tests/file.c
```
Thanks!

**Comment by Tk-Glitch** [comment]
That error and that commit id would point to a non-up-to-date tree. I assume you have a PKGBUILDS repo clone. I'll push a sync commit, that should fix your issue.

**Comment by Tk-Glitch** [comment]
Okay you should be good to go after your next pull as of https://github.com/Tk-Glitch/PKGBUILDS/commit/830ce2b43ac7fe52fbf0ba9e0957e6c8d9472394

**Comment by CartoonFan** [comment]
Thanks, @Tk-Glitch! Is there anything I can do on my end to prevent this in the future?

**Comment by Tk-Glitch** [comment]
The current version of the `TkgThingy` script at the root of the PKGBUILDS repo will pull recursively from master when using the update option, so you should get the latest version of all submodules from their respective master branches, independently of the synchronization state of PKGBUILDS upstream.

**Comment by CartoonFan** [comment]
All right, thanks for the tip!

Closing #101!
