### ISSUE TITLE
-NO32LIBS = true - Doesn't work anymore apparently, 32-bit build will fail on Pop!_Os thanks to this

### ISSUE THREAD

**Issue by gabriele2000** [Frogging-Family/wine-tkg-git#1019]
FIX: **I'm stupid, I've been setting "default-tkg" as profile instead of nothing, overriding my customization.**

I'm trying to build wine-staging-8.+ and I've done it a week ago, now I wanted to do another build with different options and this option doesn't work anymore, 32-bit build will start even if it shouldn't.

Options:

```
_nomakepkg_prefix_path=""
_nomakepkg_nover="true"
_nomakepkg_midbuild_prompt="false"
_nomakepkg_dep_resolution_distro=""

_staging_version=""

_LOCAL_PRESET="default-tkg"
_PKGNAME_OVERRIDE="none"

CUSTOM_MINGW_PATH=""
CUSTOM_GCC_PATH=""

_GCC_FLAGS="-O3 -march=native -mtune=native -pipe"

_CROSS_FLAGS="-O3 -march=native -mtune=native -pipe"

_pkg_strip="true"
_NUKR="true"
_NOLIB32="true"
_NOLIB64="false"

_prefer_external_faudio="true"
_nopatchmsg="false"


#### WINE FLAVOUR SETTINGS ####

_configure_userargs64="--with-gstreamer --without-ldap --without-oss --disable-winemenubuilder"

_use_esync="false"
_use_fsync="true"
_fsync_spincounts="false"

_use_vkd3dlib="false"
_dxvk_dxgi="true"

#### GAME-SPECIFIC PATCHES ####

_proton_battleye_support="true"
_proton_eac_support="true"
_childwindow_fix="true"
_mk11_fix="false"


#### OTHER PATCHES ####

_GLSL_toggle="true"
_MIME_NOPE="true"
_FOAS_NOPE="true"
_stg_shared_mem_default="true"
_use_josh_flat_theme="true"


#### PROTON PATCHES ####

_sdl_joy_support="true"
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_proton_rawinput="true"
_msvcrt_nativebuiltin="false"
_large_address_aware="true"
_protonify="true"

# Disable those patches
_use_pba="false"
_sims2_fix="false"
_server_send_hwmsg_disable="false"
_poe_fix="false"
_warframelauncher_fix="false"
_OW_fix="false"
_318python_fix="false"
_f4skyrimse_fix="false"
_steam_fix="false"
_highcorecount_fix="false"
_c6b6935_revert="false"
_nativedotnet_fix="false"
_usvfs_fix="false"
_use_faudio="false"
_kernelbase_reverts="false"
_update_winevulkan="false"
_fake_refresh_rate=""
_mtga_fix="false"
_plasma_systray_fix="false"
_fsync_legacy="false"
_fsync_futex2="false"
_clock_monotonic="false"

#### USER PATCHES - See README in ./wine-tkg-userpatches dir for instructions ####

_community_patches=""
```

**Comment by TheComputerGuy96** [comment]
@gabriele2000 Enabling _NOLIB32 will enable the new-style WoW64 support on newer Wine versions thanks to a configure argument being added in the wine-tkg build script

**Comment by TheComputerGuy96** [comment]
Here's the line that does this: https://github.com/Frogging-Family/wine-tkg-git/blob/9b0af1dfb4ed66b43713b48d0d19f4cd8eb2b722/wine-tkg-git/wine-tkg-scripts/build-64.sh#L31

**Comment by gabriele2000** [comment]
> @gabriele2000 Enabling _NOLIB32 will enable the new-style WoW64 support on newer Wine versions thanks to a configure argument being added in the wine-tkg build script

Yeah, I know that, but it's weird that now I can't compile WINE anymore because it asks for dependencies that apparently I don't have... remember that I've built wine 6.9 last week.

**Comment by TheComputerGuy96** [comment]
@gabriele2000 For now you can replace the line I showed with `--enable-win64`

**Comment by gabriele2000** [comment]
> @gabriele2000 For now you can replace the line I showed with `--enable-win64`

Since we're at it, `--without-vkd3d` is not recognized anymore

**Comment by TheComputerGuy96** [comment]
@gabriele2000 That line instructs Wine to build both 32-bit and 64-bit parts but in a special WoW64 way (without any 32-bit Unix libraries)

**Comment by gabriele2000** [comment]
> @gabriele2000 That line instructs Wine to build both 32-bit and 64-bit parts but in a special WoW64 way (without any 32-bit Unix libraries)

Apparently it's not working, since it builds everything... weird.

I deleted everything and cloned everything back, to no avail.

**Comment by Tk-Glitch** [comment]
I have restored the old behavior, and added a wow64 path
https://github.com/Frogging-Family/wine-tkg-git/commit/96d0bfd61ccdc213b61e187f38ed19385fbf8528
