### ISSUE TITLE
new-style wow64 build linking errors

### ISSUE THREAD

**Issue by hurricane-dorian** [Frogging-Family/wine-tkg-git#1027]
Arch linux (no 32 bit libraries at all)
My understanding is that _NOLIB32="true" now enables wow64 instead of disabling 32bit entirely.

 dlls/ntdll/x86_64-windows/libntdll.a -Wl,-O1,--sort-common,--as-needed
/usr/lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld: dlls/d3d10/i386-windows/effect.o:effect.c:(.text+0xacd): undefined reference to `atanf'
/usr/lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld: dlls/d3d10/i386-windows/effect.o:effect.c:(.text+0xb1d): undefined reference to `acosf'
/usr/lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld: dlls/d3d10/i386-windows/effect.o:effect.c:(.text+0xb6d): undefined reference to `asinf'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/i686-w64-mingw32-gcc failed
make: *** [Makefile:20331: dlls/d3d10/i386-windows/d3d10.dll] Error 2

**Comment by Tk-Glitch** [comment]
Actually it seems it was a staging issue that got fixed since. Closing.
