### ISSUE TITLE
Patch application has failed on manjaro kde

### ISSUE THREAD

**Issue by filde472006** [Frogging-Family/wine-tkg-git#1028]
[Console.log](https://github.com/Frogging-Family/wine-tkg-git/files/11737136/Console.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/11737140/prepare.log)

I tested on a Manjaro Cinnamon with the same config and compiling went smoothly, both OS's were freshly installed.

**Comment by filde472006** [comment]
[Console.log](https://github.com/Frogging-Family/wine-tkg-git/files/11738269/Console.log)

I'm sorry, the file had not registered properly

**Comment by TheComputerGuy96** [comment]
@filde472006 `sudo pacman -S patch` should fix your issue

**Comment by filde472006** [comment]
The solution was so simple, thanks for your help.

**Comment by Iglu47** [comment]
the `base-devel` group is required when building with _makepkg_
so `sudo pacman -S base-devel` would be preferred
https://gitlab.manjaro.org/packages/core/base-devel/-/blob/0868e98f8d666fa5c5f37fa95d325b4af51f1a51/PKGBUILD#L33
