### ISSUE TITLE
[Proton-tkg] "Failed to Initialize Steam" Error Has Returned

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#1031]
Version: `TKG-proton-8.7.r0.g00ec1171.Staging-fsync_futex2-NoGST`

Was attempting to run Gears 5 because "Steam Deck" support was supposedly added but found that attempting to do so with Proton-tkg immediately fails to do so:

![Screenshot_20230622_202742](https://github.com/Frogging-Family/wine-tkg-git/assets/28468662/909f8885-a44f-485c-8d4e-220b7418567b)

[steam-1097840.log](https://github.com/Frogging-Family/wine-tkg-git/files/11842973/steam-1097840.log)

**Comment by Tk-Glitch** [comment]
Our steamclient swap is currently broken on wine upstream bases. I tried rebasing it a couple times but couldn't get it to work correctly yet. It only affects upstream based proton builds. Wine builds and Valve based proton builds are not affected.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/461f4d9a1d4ed33d2e2ad01a038105ad39b007a1
