### ISSUE TITLE
(Arch/Manjaro) Failure in prepare(): Patch application has failed.

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [Frogging-Family/wine-tkg-git#1033]
`makepkg -si` fails on fresh installation of Manjaro.

Pastebins for:

1. [customization.cfg](https://pastebin.com/zf7tgsP7)
2. [terminal output](https://pastebin.com/DcPm4AFX)
3. [prepare.log](https://pastebin.com/8MLQNHaV)

**Comment by rchris494** [comment]
i get the same error when trying to build on ubuntu 22.04

**Comment by th3foxx** [comment]
I get the same thing on ArchLinux

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/8d25c0f147367a667e097d8ff76f55ada00cb9ac
