### ISSUE TITLE
[Proton-tkg] cp: cannot create regular file 'proton_dist_tmp/lib/wine/i386-windows/steam.exe': No such file or directory

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1041]
Commit: 57fa14541affdc1d7f9799fda9befdeb8f72be0b
Arch Linux
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/11990489/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/11990490/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/11990491/prepare.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/11990494/proton-tkg.cfg.zip)
![Screenshot from 2023-07-07 14-06-35](https://github.com/Frogging-Family/wine-tkg-git/assets/36989404/50b19f01-ca33-4766-a6bb-2e94d1bd7b86)

**Comment by Tk-Glitch** [comment]
You cannot build proton with `_NOLIB32="true"`.

**Comment by Kerrung** [comment]
> You cannot build proton with `_NOLIB32="true"`.

If this is the case, you should remove this option from the configs.

**Comment by Fox2Code** [comment]
Heh, `_NOLIB32` have use cases for wine WoW builds.

I think what should happens is a check on proton instead.
