### ISSUE TITLE
`proton-tkg` with _use_fastsync fails to apply patches

### ISSUE THREAD

**Issue by dtomvan** [Frogging-Family/wine-tkg-git#1046]
Steps to reproduce:

1. `git reset --hard`
2. `git clean -ffxd`
3. `git pull`
4. `cd proton-tkg`
5. `sed -Ei '/^_use_fastsync/s|false|true|' proton-tkg.cfg`
6. `./proton-tkg.sh` and select tree 4 (wine upstream proton)

As far as the configuration file and `prepare.sh` go, this should work as this isn't a valve tree.

Relevant output:
`==> ERROR: Patch application has failed. The error was logged to /home/tomvd/repos/aur/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.`

Log:
[../wine-tkg-git/prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/12093390/prepare.log)

**Comment by csutcliff** [comment]
It also fails to apply on regular wine recently.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/406d1dc911d54d26b9e0d10ce6b33eae7e6f172d
