### ISSUE TITLE
[wine-tkg-protonified] error when trying to build

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/wine-tkg-git#1058]
i get the following error when trying to build wine-tkg-protonified

pdate-alternatives: using /usr/bin/i686-w64-mingw32-g++-posix to provide /usr/bin/i686-w64-mingw32-g++ (i686-w64-mingw32-g++) in manual mode
 -> Overriding default pkgname. New pkgname: wine-tkg-protonified-git
 -> Cloning and preparing sources... Please be patient.
Fetching origin
Cloning into '/home/legion/wine-tkg-git/wine-tkg-git/src/wine-staging-git'...
done.
Switched to a new branch 'makepkg'
Fetching origin
Cloning into '/home/legion/wine-tkg-git/wine-tkg-git/src/wine-git'...
done.
Updating files: 100% (9992/9992), done.
Switched to a new branch 'makepkg'
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 -> Changing wine HEAD to the wine-staging base commit...
 -> Using upstream-commit file
HEAD is now at bd102523324 mmdevapi: Use CRT allocation functions.
 ==> WARNING: fshack (and associated patches) currently disabled until conflicts are resolved
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 -> cherry picking...
 -> Hotfixing...
error: could not revert bd89ab3040e... kernelbase: Add GetPackagesByPackageFamily stub.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/legion/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="" in your .cfg
 -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

[prepare.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12448241/prepare.txt)
[customization.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12448243/customization.txt)
[last_build_config.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12448239/last_build_config.txt)

**Comment by llde** [comment]
Commit bd89ab3040e30c11b34a95072d88f635ade03bdc doesn't revert cleanly anymore.
There is need to revert  240556e2b8cb94fc9cc85949b7e043f392b1802a before to allow a clean revert

**Comment by rchris494** [comment]
changing the revert got me a little closer now i ended up with

witched to a new branch 'makepkg'
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 -> Changing wine HEAD to the wine-staging base commit...
 -> Using upstream-commit file
HEAD is now at 221d5aba3f1 wow64: Reimplement syscall resolution using the syscall dispatcher name table.
 ==> WARNING: fshack (and associated patches) currently disabled until conflicts are resolved
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 -> cherry picking...
 -> Hotfixing...
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: 
 -> Applying fsync-unix-staging.patch
 -> Applying server_Abort_waiting_on_a_completion_port_when_closing_it.patch
 -> Applying fsync_futex_waitv.patch
 -> Applying childwindow-proton.patch
 -> Applying OPWR-proton.patch
 -> Applying LAA-unix-staging.patch
 -> Applying proton-tkg-staging.patch
 ==> ERROR: Patch application has failed. The error was logged to /home/legion/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

[prepare.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12449149/prepare.txt)
[last_build_config.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12449150/last_build_config.txt)

**Comment by llde** [comment]
You need to revert both commits

**Comment by rchris494** [comment]
i found the one /wine-tkg-git/wine-tkg-git/wine-tkg-patches/reverts

but for some reason i can not seem where the 2nd revert is located? i must be looking at the screen too long and can't seem to find it.

**Comment by llde** [comment]
@rchris494  no no  maybe I explained it badly. 

In the wine-tkg-patches/reverts script there is revert for commit bd89ab3040e30c11b34a95072d88f635ade03bdc

What you need to do is to Add as a separate revert (before the bd89ab3040e30c11b34a95072d88f635ade03bdc revert) the  240556e2b8cb94fc9cc85949b7e043f392b1802a commit.
You can add by copying the revert already present to a new line and change the commit id

**Comment by rchris494** [comment]
so i took line 103 in the revert script and changed it from
  _committorevert=bd89ab3040e30c11b34a95072d88f635ade03bdc && nonuser_reverter
 to 
  _committorevert=240556e2b8cb94fc9cc85949b7e043f392b1802a && nonuser_reverter

or does it need to be  for lines 103 and 104
  _committorevert=240556e2b8cb94fc9cc85949b7e043f392b1802a && nonuser_reverter
  _committorevert=bd89ab3040e30c11b34a95072d88f635ade03bdc && nonuser_reverter
     fi
