### ISSUE TITLE
Proton-TkG does not build--goes straight to exit cleanup

### ISSUE THREAD

**Issue by Glitched2099** [Frogging-Family/wine-tkg-git#1063]
When building proton-tkg on Valve Experimental Bleeding Edge (after building wine and running the makepkg to install dependencies), the script does not build. I took a look inside of the script, and there does not seem to be any switches I need to input, no options--it should just build out of the gate or fail. However, it does neither of those and goes directly to exit cleanup, as seen in the following video:

[The build attempt and my config file in video](https://pomf2.lain.la/f/35glysde.mp4)

You can also see that I have turned on, in advanced customization config, the option to log compiler warnings and errors:

[Screenshot](https://pomf2.lain.la/f/nksmn1at.png)

Evidently, I cannot diagnose the problem if there are no logs at all, even in proton-tkg.log.

**Comment by Glitched2099** [comment]
Update: valve experimental, not experimental bleeding edge works out of the box and is compiling right now.

**Comment by Tk-Glitch** [comment]
The wine-side log is `wine-tkg-git/wine-tkg-git/prepare.log`. Proton-tkg is only a wrapper script, so `proton-tkg-log` is only used for that specific part, which doesn't include wine source handling and compilation.

**Comment by Glitched2099** [comment]
Ah, gotcha. At any rate, the issue is resolved with the fix in the new commit you closed the issue on--experimental bleeding edge is building as we speak. Many thanks for your hard work on these tools, especially in this case where the fix was done so quickly. The work done here seems monolithic and I can only imagine what it's like to maintain such a project. God bless.
