### ISSUE TITLE
Building in NixOS

### ISSUE THREAD

**Issue by Melechtna** [Frogging-Family/wine-tkg-git#1064]
I'm trying to figure out how to build it in NixOS, and how to enable the Wayland Driver specifically. Thing is, I have no idea where it's main issue is, and nothing in the manual would lead me to believe I've missed something.

` ______              __                      __   __
|   __ \.----.-----.|  |_.-----.-----.______|  |_|  |--.-----.
|    __/|   _|  _  ||   _|  _  |     |______|   _|    <|  _  |
|___|   |__| |_____||____|_____|__|__|      |____|__|__|___  |
                                                       |_____|

Also known as "Some kind of build wrapper for wine-tkg-git"

Using Steam runtime

./proton-tkg.sh: line 820: /home/user/src/wine-tkg-git/proton-tkg/steam-runtime/run.sh: cannot execute: required file not found
`
Which obviously this directory doesn't exist, but I've made 0 changes to the config so far, fresh git pull, just trying to get it to compile before I start messing with stuff

**Comment by Melechtna** [comment]
I'm an idiot, and didn't consider to use steam-run to run the script before proceeding. Seems to build fine now, but I have absolutely no idea where it moved the folder too.

**Comment by Melechtna** [comment]
It didn't build fine, and there seems to be a dependancy issue, but only if I bother to slot in a distro, otherwise it seems to not actually compile, but it just does nothing if I don't slot in a distro.

**Comment by mikeserv-git** [comment]
You're going to have a lot of trouble with this on NixOS. That's a pretty odd system configuration and you would have a lot of unexpected issues with this build. Moreover, Steam and games are not very well supported.

Your initial show stopping problem is likely that it's not finding your Steam installation, for starters. You've probably got broken links in ~/.steam because it runs in a chroot.

https://nixos.wiki/wiki/Explaining_the_current_Steam_Package_build

Read that (I almost got coffee up my nose)

**Comment by Melechtna** [comment]
> You're going to have a lot of trouble with this on NixOS. That's a pretty odd system configuration and you would have a lot of unexpected issues with this build. Moreover, Steam and games are not very well supported.
> 
> Your initial show stopping problem is likely that it's not finding your Steam installation, for starters. You've probably got broken links in ~/.steam because it runs in a chroot.
> 
> https://nixos.wiki/wiki/Explaining_the_current_Steam_Package_build
> 
> Read that (I almost got coffee up my nose)

1. steam works JUST fine, so this article is likely out of date
2. There's a nix package for that, I just forgot about this
3. I moved on to a different kernel because TKG didn't function very well for what I needed it for

So, closing this
