### ISSUE TITLE
broken 32bit dependencies (even if I enable dependency res) on Fedora

### ISSUE THREAD

**Issue by avoladrian1** [Frogging-Family/wine-tkg-git#1068]
When I try to compile wine-tkg-git (With Fedora Dependency resolution) It just stops at 32bit and says that "32bit dependencies not found."
Thanks.

**Comment by Tk-Glitch** [comment]
Should be alright with wow64 at least. 32-bit packages are still conflicting and broken on Fedora. Nothing we can do about it.
