### ISSUE TITLE
valve-exp-bleeding fails to apply de-steamify-80-be.mypatch

### ISSUE THREAD

**Issue by adolfintel** [Frogging-Family/wine-tkg-git#1083]
Started happening a couple days ago.

Here's the log:
```
Applying your own patch de-steamify-80-be.mypatch
patching file dlls/advapi32/advapi.c
patching file dlls/dbghelp/dwarf.c
patching file dlls/hidclass.sys/device.c
patching file dlls/hidclass.sys/hid.h
patching file dlls/hidclass.sys/pnp.c
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 1226 (offset 3 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 87 with fuzz 2 (offset 1 line).
patching file dlls/ntdll/unix/loader.c
patching file dlls/secur32/secur32.c
patching file dlls/winebus.sys/bus_sdl.c
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1052 (offset -4 lines).
patching file dlls/xinput1_3/main.c
Hunk #1 succeeded at 122 with fuzz 2 (offset -2 lines).
Hunk #2 succeeded at 337 (offset -2 lines).
Hunk #3 succeeded at 357 (offset -2 lines).
Hunk #4 succeeded at 453 (offset -2 lines).
Hunk #5 succeeded at 481 (offset -2 lines).
Hunk #6 FAILED at 527.
Hunk #7 FAILED at 538.
Hunk #8 succeeded at 721 with fuzz 2 (offset -16 lines).
Hunk #9 succeeded at 807 (offset -26 lines).
Hunk #10 succeeded at 825 (offset -26 lines).
2 out of 10 hunks FAILED -- saving rejects to file dlls/xinput1_3/main.c.rej
patching file loader/wine.inf.in
Hunk #1 succeeded at 340 with fuzz 2 (offset 5 lines).
patching file programs/winedbg/debugger.h
patching file programs/winedbg/tgt_active.c
patching file programs/winedbg/winedbg.c
```

**Comment by daktras420** [comment]
I have experienced the same issue.. When i try compiling against the valve experimental and experimental bleeding edge. The issue it seems if it am not mistaken is that tue patch is aimed at plain wine. From what i read on github from valve the branch valve is based on plain wine, where valve-experimental and valve-experimental-bleeding-edge are based off wine staging. So two patches are needed one as it currently works for wine-proton-valve and then a second one that works on the staging branch for wine-proton-valve-exp-bleeding-edge and wine-proton-valve-exp. It used to all compile before the patch was included and forced.

**Comment by xioren** [comment]
Hi I am not sure this should be closed as the fix seems to cause another exception:
```
../ValveSoftware-winegit/dlls/xinput1_3/main.c:541:17: error: ‘steam_overlay_event’ undeclared (first use in this function)
  541 |     CloseHandle(steam_overlay_event);
      |                 ^~~~~~~~~~~~~~~~~~~
../ValveSoftware-winegit/dlls/xinput1_3/main.c:541:17: note: each undeclared identifier is reported only once for each function it appears in
../ValveSoftware-winegit/dlls/xinput1_3/main.c:542:17: error: ‘steam_keyboard_event’ undeclared (first use in this function)
  542 |     CloseHandle(steam_keyboard_event);
      |                 ^~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:269267: dlls/xinput1_2/x86_64-windows/main.o] Error 1
```

**Comment by Tk-Glitch** [comment]
This looks minor. I'll fix that asap.

**Comment by xioren** [comment]
A little context: Because of the original bug I reverted to using ```proton_8.0``` instead of ```experimental_8.0``` because it would still build. After the your merge I got the above exception building ```proton_8.0``` but I just retried building against ```experimental_8.0``` and while it hasn't crashed with that exception and i'm almost 15 minutes further into the build. So hopefully that's useful information.

**Comment by Thaodan** [comment]
The fix didn't work. 

> Hi @Tk-Glitch I am not sure this should be closed as the fix seems to cause another exception:
> 
> ```
> ../ValveSoftware-winegit/dlls/xinput1_3/main.c:541:17: error: ‘steam_overlay_event’ undeclared (first use in this function)
>   541 |     CloseHandle(steam_overlay_event);
>       |                 ^~~~~~~~~~~~~~~~~~~
> ../ValveSoftware-winegit/dlls/xinput1_3/main.c:541:17: note: each undeclared identifier is reported only once for each function it appears in
> ../ValveSoftware-winegit/dlls/xinput1_3/main.c:542:17: error: ‘steam_keyboard_event’ undeclared (first use in this function)
>   542 |     CloseHandle(steam_keyboard_event);
>       |                 ^~~~~~~~~~~~~~~~~~~~
> make: *** [Makefile:269267: dlls/xinput1_2/x86_64-windows/main.o] Error 1
> ```

The fix didn't work as mentioned above.

**Comment by Lumenohr** [comment]
Getting the following when building with valve-exp-bleeding:
`Applying your own patch de-steamify-80-be.mypatch
patching file dlls/advapi32/advapi.c
patching file dlls/dbghelp/dwarf.c
patching file dlls/hidclass.sys/device.c
patching file dlls/hidclass.sys/hid.h
patching file dlls/hidclass.sys/pnp.c
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 1226 (offset 3 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 87 with fuzz 2 (offset 1 line).
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 774 (offset 1 line).
Hunk #2 succeeded at 2113 (offset 6 lines).
Hunk #3 succeeded at 2125 (offset 6 lines).
Hunk #4 succeeded at 2137 (offset 6 lines).
Hunk #5 succeeded at 2151 (offset 6 lines).
Hunk #6 succeeded at 2159 (offset 6 lines).
patching file dlls/secur32/secur32.c
patching file dlls/winebus.sys/bus_sdl.c
Hunk #1 FAILED at 965.
Hunk #2 FAILED at 1021.
2 out of 2 hunks FAILED -- saving rejects to file dlls/winebus.sys/bus_sdl.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1052 (offset -4 lines).
patching file dlls/xinput1_3/main.c
Hunk #1 succeeded at 122 with fuzz 2 (offset -2 lines).
Hunk #2 succeeded at 337 (offset -2 lines).
Hunk #3 succeeded at 357 (offset -2 lines).
Hunk #4 succeeded at 453 (offset -2 lines).
Hunk #5 FAILED at 483.
Hunk #6 succeeded at 572 (offset 8 lines).
Hunk #7 succeeded at 788 with fuzz 2 (offset -6 lines).
Hunk #8 succeeded at 874 (offset -16 lines).
Hunk #9 succeeded at 892 (offset -16 lines).
1 out of 9 hunks FAILED -- saving rejects to file dlls/xinput1_3/main.c.rej
patching file loader/wine.inf.in
Hunk #1 succeeded at 340 with fuzz 2 (offset 5 lines).
patching file programs/winedbg/debugger.h
patching file programs/winedbg/tgt_active.c
patching file programs/winedbg/winedbg.c`

**Comment by Lumenohr** [comment]
Getting an error when applying the same patch:
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/13973291/prepare.log)

**Comment by adolfintel** [comment]
Looks like it's broken again

```
Applying your own patch de-steamify-80-be.mypatch
patching file dlls/advapi32/advapi.c
patching file dlls/dbghelp/dwarf.c
patching file dlls/hidclass.sys/device.c
patching file dlls/hidclass.sys/hid.h
patching file dlls/hidclass.sys/pnp.c
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 1226 (offset 3 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 87 with fuzz 2 (offset 1 line).
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 774 (offset 1 line).
Hunk #2 succeeded at 2113 (offset 6 lines).
Hunk #3 succeeded at 2125 (offset 6 lines).
Hunk #4 succeeded at 2137 (offset 6 lines).
Hunk #5 succeeded at 2151 (offset 6 lines).
Hunk #6 succeeded at 2159 (offset 6 lines).
patching file dlls/secur32/secur32.c
patching file dlls/winebus.sys/bus_sdl.c
Hunk #1 FAILED at 965.
Hunk #2 FAILED at 1021.
2 out of 2 hunks FAILED -- saving rejects to file dlls/winebus.sys/bus_sdl.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1052 (offset -4 lines).
patching file dlls/xinput1_3/main.c
Hunk #1 succeeded at 122 with fuzz 2 (offset -2 lines).
Hunk #2 succeeded at 337 (offset -2 lines).
Hunk #3 succeeded at 357 (offset -2 lines).
Hunk #4 succeeded at 453 (offset -2 lines).
Hunk #5 FAILED at 483.
Hunk #6 succeeded at 562 (offset -2 lines).
Hunk #7 succeeded at 778 with fuzz 2 (offset -16 lines).
Hunk #8 succeeded at 864 (offset -26 lines).
Hunk #9 succeeded at 882 (offset -26 lines).
1 out of 9 hunks FAILED -- saving rejects to file dlls/xinput1_3/main.c.rej
patching file loader/wine.inf.in
Hunk #1 succeeded at 340 with fuzz 2 (offset 5 lines).
patching file programs/winedbg/debugger.h
patching file programs/winedbg/tgt_active.c
patching file programs/winedbg/winedbg.c
```

**Comment by Tk-Glitch** [comment]
Was fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/fd23f0bced821b784a55523342f6129636ef47e3
Please `git pull` for latest changes.

**Comment by adolfintel** [comment]
This is a clean build, I cloned this repo to an empty folder. Does tkg cache something elsewhere?

**Comment by Tk-Glitch** [comment]
Did you clone `Frogging-Family/wine-tkg-git` or `Tk-Glitch/PKGBUILDS`? The latter will need a pull in respective projects dirs as it's not getting sync'ed on every change (more like every couple weeks/months).
If it's indeed a clone of `Frogging-Family/wine-tkg-git`, the patch applies fine on my end and your failing hunks definitely are what I fixed on that mentioned commit. Unless you're targeting an older proton-exp-be commit?

**Comment by adolfintel** [comment]
I cloned the repo manually to an empty folder and used the valve-exp-bleeding preset.

From what I can see it pulls valve's version of wine at commit bb66944d9d7a0fc7692f05d4a2db418b468d3021 (HEAD -> proton_8.0, tag: proton-wine-8.0-5c)

That does not seem to be the right commit, it didn't switch to experimental_8.0 nor bleeding-edge.

**Comment by Tk-Glitch** [comment]
There's no tag set in the preset: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg

**Comment by adolfintel** [comment]
Is there some special behavior in your code for wine-tkg-valve-exp-bleeding.cfg? If I just make a copy of that file with a different name it fails to build

**Comment by Tk-Glitch** [comment]
That's expected. The filename is the profile "id" and indeed there are specific behavior changes for Valve trees (and even more special handling for bleeding edge).

**Comment by adolfintel** [comment]
Ah, that explains it, I was making a copy and adding stuff to it.

So what would be the proper way to make a couple of changes to this profile? Do I just modify it?

**Comment by Tk-Glitch** [comment]
That's fine indeed. That being said, having the profile id behind a variable set in the file might be worth investigating.

**Comment by adolfintel** [comment]
Maybe you could add a variable like `TKG_QUIRKS="valve,experimental"`
