### ISSUE TITLE
wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by xioren** [Frogging-Family/wine-tkg-git#1084]
Greetings, when I build against [valve wine 8.0](https://github.com/ValveSoftware/wine) and load the built runner into [Bottles](https://github.com/bottlesdevs/Bottles) my terminal is full of warnings about gstreamer plugins. All along the lines of: 

```(wine:188): GStreamer-WARNING **: 11:40:34.543: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsttranscode.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsttranscode.so: wrong ELF class: ELFCLASS64```

However if I build against ```7.0``` I get no such warnings. My assumption is that they are benign warnings but I am wondering if there is some flag or setting I am missing that is the cause. Any thoughts?

**Comment by xioren** [comment]
solution: ```_NOLIB32="wow64"```

**Comment by Tk-Glitch** [comment]
You're missing some 32-bit gstreamer dependencies. Using wow64 bypasses the issue since it only uses 64-bit libs. Depending on your distro, the 32-bit dependencies may be broken so you might have to resolve this by hand. Once the wow64 path will be more robust upstream this won't be an issue anymore but it's not there just yet.

**Comment by xioren** [comment]
Thanks, just to clarify you're suggesting I am missing 32 bit gstreamer dependencies when compiling or when trying to load/use the compiled WINE in Bottles? And are these warnings harmless or should I expect problems?

I compile with (and 64 bit versions as well):
```
libgstreamer1.0-dev:i386
libgstreamer-plugins-base1.0-dev:i386
libgstreamer-plugins-bad1.0-dev:i386
gstreamer1.0-plugins-base:i386
gstreamer1.0-plugins-good:i386
gstreamer1.0-plugins-bad:i386 \
gstreamer1.0-plugins-ugly:i386
gstreamer1.0-libav:i386
gstreamer1.0-tools:i386
gstreamer1.0-x:i386
gstreamer1.0-alsa:i386
gstreamer1.0-gl:i386 
gstreamer1.0-gtk3:i386 
gstreamer1.0-qt5:i386 
gstreamer1.0-pulseaudio:i386
```
