### ISSUE TITLE
proton-tkg-additions-ad5cb83.patch failing

### ISSUE THREAD

**Issue by fiercebrake** [Frogging-Family/wine-tkg-git#1085]
Hey there!

I am getting the errors below when trying to build v817.1, v.8.18 and v8.19. Any ideas on what I should do?

I am on tkg kernel v6.5.9-273, latest tkg Nvidia drivers, on archlinux

`proton-tkg-additions-ad5cb83.patch -- ( Using additional Proton-tkg patches )
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 FAILED at 68.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/x11drv_main.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 2783 (offset 168 lines).
Hunk #2 succeeded at 2817 (offset 168 lines).
patching file dlls/winex11.drv/mouse.c
Hunk #1 FAILED at 579. 
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/mouse.c.rej
patching file dlls/winex11.drv/mouse.c
Hunk #1 FAILED at 1571.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/mouse.c.rej
patching file dlls/winex11.drv/event.c
Hunk #1 succeeded at 1106 (offset -23 lines).
Hunk #2 succeeded at 1346 (offset -22 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1229 (offset -31 lines).
Hunk #2 succeeded at 1246 (offset -31 lines).
Hunk #3 succeeded at 1751 (offset -10 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 641 (offset 20 lines).
patching file dlls/winex11.drv/event.c
Hunk #1 FAILED at 821. 
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/event.c.rej
`

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/041e4705cce43fc5030c77f6d073c9606697c4d7
