### ISSUE TITLE
No rule to make target vrclient_x64.spec

### ISSUE THREAD

**Issue by fiercebrake** [Frogging-Family/wine-tkg-git#1087]
Hey guys, hope everyone is doing great!

Starting a few weeks back, I am getting this error when trying to build proton-tkg, any ideas on what I am doing wrong?

`make: *** No rule to make target 'vrclient_x64.spec', needed by 'vrclient_x64.dll.so'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/fierce_brake/Downloads/linux-tkg/wine-tkg-git/proton-tkg/external-resources/openvr/build/vrclient.win64/vrclient_x64''

**Comment by EliasTheGrandMasterOfMistakes** [comment]
i have this same problem

**Comment by EliasTheGrandMasterOfMistakes** [comment]
this repo looks very automatized, the latest commit is from 2 week ago, i think the developer not have time and just use this repo more for generate CI/CD releases, if you open protonplus software, you can view this release very fast, you can view the same in github actions.

**Comment by fiercebrake** [comment]
@EliasTheGrandMasterOfMistakes 
In the meantime, unless you have a specific requirement that demands you run the script yourself, you could download the latest compilation from here

https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/proton-valvexbe-arch-nopackage.yml

**Comment by EliasTheGrandMasterOfMistakes** [comment]
try to build without openvr, disable this using: _steamvr_support="false" in your config file.
but is necessary to you firstly remove the wine-tkg and clone this.
for some whatever reason modify options in config file not modified the build if you already has a building step

**Comment by fiercebrake** [comment]
@EliasTheGrandMasterOfMistakes 
no luck on my side using the '_steamvr_support="false"' switch.

let me know if you find any fix/workaround

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/7aa0f27cf8ca41a5b36ac725ccc0e15e85396049
