### ISSUE TITLE
clarification: wine-tkg vs wine-ge ?

### ISSUE THREAD

**Issue by Ryder17z** [Frogging-Family/wine-tkg-git#1089]
How do they differ?

From a quick glance, I do not see why one is better than the other, except wine-ge seems to be more more well known?

**Comment by xioren** [comment]
Well for one, Glorious Eggroll's version is customized by the maintainer and comes as is, take it or leave it. The tkg script is used to build your own custom wine version according to your needs.

**Comment by Ryder17z** [comment]
Alright, thanks for the explanation.
