### ISSUE TITLE
[Patch] Proton Wayland is giving patch error

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [Frogging-Family/wine-tkg-git#1090]
Proton Wayland patch is giving error in patch in all 3 versions: bleeding edge, valve proton experimental and valve proton, all of these have error, i think is necessary to rebase this patch on top of bleeding edge.
others information:
_wayland_driver="true".

If are necessary i can send the prepare.log for view what part of patch is give error

**Comment by shaumux** [comment]
The wayland patches in its current form is kinda dead
More info [here](https://github.com/Frogging-Family/wine-tkg-git/issues/1065)

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> The wayland patches in its current form is kinda dead More info [here](https://github.com/Frogging-Family/wine-tkg-git/issues/1065)

thank you
