### ISSUE TITLE
unable to build latest wine-tkg default

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/wine-tkg-git#1091]
hello,

i am unable to build the latest wine-tkg default. i get the following error.

/usr/bin/x86_64-w64-mingw32-ld: tmp654b298c/d3d12core-00000000.spec.o:fake:(.edata+0x28): undefined reference to `D3D12GetInterface'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make: *** [Makefile:16771: dlls/d3d12core/x86_64-windows/d3d12core.dll] Error 2
make: *** Waiting for unfinished jobs....
In file included from ../wine-git/dlls/mshtml/htmlstyle.c:30:
../wine-git/dlls/mshtml/mshtml_private.h: In function ‘strndupWtoU’:
../wine-git/dlls/mshtml/mshtml_private.h:1443: note: ‘-Wmisleading-indentation’ is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
 1443 |             ret[size] = '\0';
      | 
In file included from ../wine-git/dlls/mshtml/xmlhttprequest.c:30:
../wine-git/dlls/mshtml/mshtml_private.h: In function ‘strndupWtoU’:
../wine-git/dlls/mshtml/mshtml_private.h:1443: note: ‘-Wmisleading-indentation’ is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
 1443 |             ret[size] = '\0';
      | 
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/13283173/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/13283174/prepare.log)
[customization.txt](https://github.com/Frogging-Family/wine-tkg-git/files/13283175/customization.txt)

anyone have an idea what is causing this?

**Comment by EliasTheGrandMasterOfMistakes** [comment]
is the same error that i have when build wine v8.19
i will try with wine 8.18 now

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/f15448f371fc5ccbc872b21af399e7282371be28

**Comment by rchris494** [comment]
thanks!
