### ISSUE TITLE
[Question] How i can use a custom wine git and a custom branch?

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [Frogging-Family/wine-tkg-git#1093]
Have a build flag in customize.cfg for define a custom wine source?
my idea is trying this wine source https://gitlab.collabora.com/alf/wine/-/tree/wayland?ref_type=heads
and use branch: wayland.
this is wine 8.2 based release
is possible to use this?
have a options in customization.cfg to modify the source and branch?

**Comment by Tk-Glitch** [comment]
For the source:
`_custom_wine_source=""`

For the branch/commit:
`_plain_version=""`

If the upstream commit ids are respected it should detect 8.2, otherwise you'll need to disable some patches by hand to prevent conflicts.

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> For the source: `_custom_wine_source=""`
> 
> For the branch/commit: `_plain_version=""`
> 
> If the upstream commit ids are respected it should detect 8.2, otherwise you'll need to disable some patches by hand to prevent conflicts.

thank you, sadly have a build error because of toolchain, in this case i will wait patietly to this be upstream or the dev rebase wayland repo with 8.20
