### ISSUE TITLE
[Feature] Can't disable Proton TKG Steam Client Swap Patch

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [Frogging-Family/wine-tkg-git#1094]
Steam Client Swap Patch have a conflict in patching in https://gitlab.collabora.com/alf/wine/ repo with wayland branch 
For some whatever reason _steam_fix="false" not work and the patch continues
# GAME-SPECIFIC PATCHES
_steam_fix="false"
_MIME_NOPE="false"
_update_winevulkan="false"
_proton_mf_hacks="false"
_proton_rawinput="false"

have a way to remove this patch?

 Applying proton-tkg-steamclient-swap-f5d272f.patch
 ==> ERROR: Patch application has failed. The error was logged to /home/ratatouillegamer/Documentos/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.

**Comment by Tk-Glitch** [comment]
`_steamclient_noswap="true"`
The resulting proton build will be unable to run most steam games though.

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> unable

thank you
