### ISSUE TITLE
Protonify option enabled crashes Assassin's Creed Odyssey

### ISSUE THREAD

**Issue by robzombie91** [Frogging-Family/wine-tkg-git#11]
[output.log](https://github.com/Frogging-Family/wine-tkg-git/files/4431817/output.log)

**Comment by Tk-Glitch** [comment]
Might be some DRM BS. Can you please try that? Remove the trailing `.txt` and drop in `wine-tkg-userpatches`:
[satanic_drm_friend.myrevert.txt](https://github.com/Frogging-Family/wine-tkg-git/files/4431843/satanic_drm_friend.myrevert.txt)

**Comment by Tk-Glitch** [comment]
By the way, the output you have posted contains nothing helpful 🐸

**Comment by robzombie91** [comment]
Hmm wierd, but one thing to note is that it does work if protonify is not enabled

**Comment by Tk-Glitch** [comment]
Yeah that's why I suspect DRM bullcrap. The patch I have posted above reverts a possible culprit.

**Comment by robzombie91** [comment]
nope, the patch did not work

**Comment by robzombie91** [comment]
I am running a legit purchased version of Odyssey but with the drm free option

**Comment by robzombie91** [comment]
![Screenshot from 2020-04-04 12-08-27](https://user-images.githubusercontent.com/7533790/78455619-65d21100-766d-11ea-91a9-6fd59e69e285.png)

**Comment by robzombie91** [comment]
PROTON_NO_FSYNC=1 fixes this issue

**Comment by Tk-Glitch** [comment]
I was aware of an issue with the game and esync/fsync but it was only with ingame interactions. That's new. @Vash63 is likely much more familiar with the game and its quirks with wine. HALP

**Comment by Vash63** [comment]
I just run the stock executable provided by Steam with a proton-tkg from 5.0. I haven't updated my AC proton for a while as I'm using the user32.dll patch which helps with the aspect ratio detection.

**Comment by SR-dude** [comment]
Something broke along the way. Reverting to tkg 5.5 gets the game working again for me

**Comment by Tk-Glitch** [comment]
It seems to be related to an upstream change that wasn't correctly handled in esync/fsync (moving to server_select). Apparently Zeb is aware so we'll hopefully see a fix in staging soon-ish and I'll port it over to fsync eventually.

**Comment by Tk-Glitch** [comment]
It seems to be fixed. Please retest.

**Comment by Tk-Glitch** [comment]
Considered fixed from other reports.

**Comment by robzombie91** [comment]
> 2020-07-04 08:58:02,856: Running Lutris 0.5.6
2020-07-04 08:58:02,856: Using NVIDIA drivers 440.66.17 for x86_64
2020-07-04 08:58:02,858: GPU: GeForce GTX 1070
2020-07-04 08:58:02,858: GPU: 10DE:1B81 3842:6173 using nvidia drivers
2020-07-04 08:58:02,874: Vulkan is supported
2020-07-04 08:58:02,875: Updating DXVK versions
2020-07-04 08:58:10,699: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,699: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,721: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,812: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,812: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,812: Replacing /home/rob/.wine/drive_c/windows/system32/dxgi with DXVK version
2020-07-04 08:58:10,813: Replacing /home/rob/.wine/drive_c/windows/system32/d3d11 with DXVK version
2020-07-04 08:58:10,814: Replacing /home/rob/.wine/drive_c/windows/system32/d3d10core with DXVK version
2020-07-04 08:58:10,815: Replacing /home/rob/.wine/drive_c/windows/system32/d3d9 with DXVK version
2020-07-04 08:58:10,815: Replacing /home/rob/.wine/drive_c/windows/syswow64/dxgi with DXVK version
2020-07-04 08:58:10,816: Replacing /home/rob/.wine/drive_c/windows/syswow64/d3d11 with DXVK version
2020-07-04 08:58:10,817: Replacing /home/rob/.wine/drive_c/windows/syswow64/d3d10core with DXVK version
2020-07-04 08:58:10,818: Replacing /home/rob/.wine/drive_c/windows/syswow64/d3d9 with DXVK version
2020-07-04 08:58:10,818: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,818: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,873: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,873: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-07-04 08:58:10,873: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
Running /usr/bin/wine /mnt/GAMEZ/Games/Assassin's Creed Odyssey/ACOdyssey.exe
Initial process has started with pid 11475
Game is considered started.
002c:fixme:winediag:__wine_start_process Wine TkG 5.12 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
00a4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00a4:fixme:ntdll:NtQuerySystemInformation (0x00000007,0x9407f8,0x00000018,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation (0x00000050,0x9407f8,0x000000a8,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
00a4:fixme:ntdll:NtQuerySystemInformation (0x00000021,0x940980,0x00000010,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation (0x0000002d,0x940980,0x00000020,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation (0x0000003d,0x940998,0x00000a58,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation (0x00000012,0x940998,0x00000a58,0x31c340) stub
00a4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_INTERRUPT_INFORMATION
00a4:fixme:ntdll:NtQuerySystemInformation (0x0000002a,0x9409b0,0x00000a40,0x31c340) stub
00a4:fixme:ntdll:EtwEventRegister ({968f313b-097f-4e09-9cdd-bc62692d138b}, 0x7ff7b4129dc, 0x7ff7b56f918, 0x7ff7b56f910) stub.
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:fixme:dwmapi:DwmIsCompositionEnabled 0000000005250434
00d4:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x118306d, context 0xdcd6e0, init_notify 0, handle 0x604fa00): stub
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\devenum.dll"
00a4:err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x1
00a4:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0124:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0124:fixme:ntdll:NtQuerySystemInformation (0x00000007,0xa56168,0x00000018,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation (0x00000050,0xa56168,0x00000054,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
0124:fixme:ntdll:NtQuerySystemInformation (0x00000021,0xa562d0,0x00000010,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation (0x0000002d,0xa562d0,0x00000020,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation (0x0000003d,0xa562e8,0x00000a90,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation (0x00000012,0xa562e8,0x00000a90,0x60cce8) stub
0124:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_INTERRUPT_INFORMATION
0124:fixme:ntdll:NtQuerySystemInformation (0x0000002a,0xa56300,0x00000a78,0x60cce8) stub
0124:fixme:ntdll:EtwEventRegister ({968f313b-097f-4e09-9cdd-bc62692d138b}, 0x76014479, 0x76136520, 0x76136278) stub.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:reg:RegQueryInfoKeyW security argument not supported.
0124:fixme:dwmapi:DwmIsCompositionEnabled 04A2DD14
012c:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x11af537, context 0xb9abd8, init_notify 0, handle 0x580fce8): stub
0124:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
wine: configuration in L"/home/rob/.wine" has been updated.
0178:fixme:heap:RtlSetHeapInformation 0x880000 0 0x21e730 4 stub
0178:fixme:ntdll:NtQuerySystemInformation returning fake driver list
0178:fixme:heap:RtlSetHeapInformation 0x9b0000 0 0x21de80 4 stub
0178:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenSessionId, ...) semi-stub
01e0:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000489FDA0
01f4:fixme:ver:GetCurrentPackageId (0000000004BEFDA0 0000000000000000): stub
0178:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
0178:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0178:fixme:wbemprox:client_security_SetBlanket 000000006775ECF0, 00000000015BCFD0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0178:fixme:wbemprox:client_security_Release 000000006775ECF0
info:  Game: ACOdyssey.exe
info:  DXVK: v1.7-63-gc4f37d39-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 1070:
info:    Driver: 440.66.17
info:    Vulkan: 1.2.145
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8945 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  Adapter LUID 0: 0:3fd
2020-07-04 08:58:22,910: Game still running (state: running)
2020-07-04 08:58:22,910: Stopping Assassin's Creed Odyssey (wine)
