### ISSUE TITLE
Patch application fails for any staging-enabled build, with an error during `patchinstall.py` around `bcrypt-ECDHSecretAgreement` 

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#1102]
After Mine and Riesi's commits earlier, I succesfully built a default-tkg build, but hours later I try to build the same thing again, and even tried a fresh git clone, and I get a failure during: `Applying wine-staging patches using staging/patchinstall.py...`

```
 -> Applying wine-staging patches using staging/patchinstall.py...
     Staging overrides used, if any: -W bcrypt-ECDHSecretAgreement
 ==> ERROR: Patch application has failed. The error was logged to /home/matt/dev/winetkg/wine-tkg-git/prepare.log for your convenience.
```

And `prepare.log` shows:

```
Cloning into bare repository 'wine-git'...
Cloning into bare repository 'wine-staging-git'...
HEAD is now at 66c86503 Rebase against 1e4db62e0ba0b8595748c94b032dfb0064207de1.
HEAD is now at 1e4db62e0ba setupapi: Add stubs for SetupDiGetCustomDeviceProperty{A|W}().

CSMT-toggle.patch -- ( Applied CSMT toggle logic patch )
patching file patches/winecfg-Staging/0006-winecfg-Toggle-upstream-CSMT-implementation.patch

Applying wine-staging patches...
Traceback (most recent call last):
  File "/home/matt/tmp/winetkg/wine-tkg-git/src/wine-staging-git/staging/patchinstall.py", line 256, in <module>
    main()
  File "/home/matt/tmp/winetkg/wine-tkg-git/src/wine-staging-git/staging/patchinstall.py", line 223, in main
    for p in excluded: del patchlist[p]
                           ~~~~~~~~~^^^
KeyError: 'bcrypt-ECDHSecretAgreement'
```

And that staging override seems to be default, I didn't choose it, and even just running a completely fresh git-clone and modifying NOTHING and running `./non-makepkg-build.sh` gives the same error.

**Comment by gardotd426** [comment]
Found the culprit. Staging removed the patches upstream: https://github.com/wine-staging/wine-staging/commit/66c86503bdcb19dbe4348b4162672a14a4b60800#diff-3f44cd620196693cc5145b1287342952b859aa94eac5f77597aa7ef8fde6f75c

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/ac0776cacbbc5556a507be1b5cc5f5a1391b4b09

**Comment by FlitPix** [comment]
I'm currently running into this issue.

**Comment by mirh** [comment]
Any version between `v8.14` and `v9.0-rc1` is still affected

**Comment by mirh** [comment]
Every version before `v9.0-rc1` (except somehow `v8.13`) is still affected
