### ISSUE TITLE
[Question] How is possible to build Wine Upstream Proton with Custom DXVK 

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [Frogging-Family/wine-tkg-git#1107]
I have tried to build using prebuilt and try to download the release and add in external-resources in the dxvk folder
the same with vkd3d, but nothing works, DXVK can't working and idk if the new DXVK-NVAPI can be a reason.

Yes i'm try to build with legacy DXVK and VKD3D because my iGPU doesn't support Vulkan 1.3 and just expose 1.2.
In this case i need to build by myself instead of just download the prebuilt from git?

and about script for symlinks? the prebuilt from git doesn't have this, this can be a reason for breaking?

Sorry for the inconvenience

**Comment by Tk-Glitch** [comment]
The easiest way would be to create copies of [updxvk.cfg](https://github.com/Frogging-Family/dxvk-tools/blob/master/updxvk.cfg) and [upvkd3d-proton.cfg](https://github.com/Frogging-Family/dxvk-tools/blob/master/upvkd3d-proton.cfg)  in a `~/.config/frogminer` dir and edit them to target your desired commits. Those files will be used when building dxvk/vkd3d-proton during proton-tkg compilation.

**Comment by Tk-Glitch** [comment]
Closing as answered
