### ISSUE TITLE
Wine Master Proton lsteamclient swap not working with 32-bit games

### ISSUE THREAD

**Issue by cprin21** [Frogging-Family/wine-tkg-git#1113]
On Oblivion and Fallout New Vegas (DX9 games, may hint towards the source of the problem), getting the following error.
```
Application load error 3:0000065432
```
This pops up instead of the game itself launching after the launcher itself works. This is the case for Oblivion and FNV.
This is not the case for other games such as Skyrim AE, a DX11 game. Only for DX9 games it appears.

**Comment by suamor** [comment]
I was curious about this and this page could be helpful: https://appuals.com/fix-application-load-error-30000065432/ 
It looks like an issue related to steam installation.

**Comment by Tk-Glitch** [comment]
It's a 32-bit specific lsteamclient lib issue on mainline based builds. It doesn't affect Valve trees. Will investigate.

**Comment by cprin21** [comment]
Thank you for committing to investigating the problem. Speaking of commits, proton_tkg_9.1.r0.g53c687fd (Wine Master proton) continues to be broken. Likely already knew but thought to give an update that DirectX 9 games still do not run.
