### ISSUE TITLE
Page fault during 64-bit prefix creation/updating on 5.15.2.r2 build

### ISSUE THREAD

**Issue by Kron4ek** [Frogging-Family/wine-tkg-git#112]
Hello,

I get page fault during 64-bit prefix initialization with the 5.15.2r2 build:

    wine: Unhandled page fault on read access to 0000000000000000 at address 00007F2DAA3FDC70 (thread 0040), starting debugger...

Despite the error, 64-bit applications (at least the ones i tested) work fine, so i don't know if it has any negative effects. The error doesn't happen when creating/updating 32-bit prefix (WINEARCH=win32). Previous TkG releases work fine, regular Staging and Vanilla builds also work fine.

Can be reproduced by creating a new prefix or by updating an existing one:

    wineboot -u

Here is a full log if it helps.

[launch.log](https://github.com/Frogging-Family/wine-tkg-git/files/5083767/launch.log)

OS: Arch Linux (also happens on Xubuntu 20.04)

**Comment by Tk-Glitch** [comment]
Mainline 5.15 : Couldn't repro
Staging 5.15 initial release : Couldn't repro
Staging 5.15.2r2 : **Could repro**
Staging 5.15.2r3 : Couldn't repro

Pretty weird results.
Supposedly fixed by https://github.com/wine-staging/wine-staging/commit/28fad42582d0e4c8e4e47d914b9a0f6e83671202 ?

**Comment by Kron4ek** [comment]
> Supposedly fixed by wine-staging/wine-staging@28fad42 ?

Yes, i can't reproduce the issue on 5.15.2r3.
