### ISSUE TITLE
winesync-dkms module not detected, build forcibly prevented

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#1120]
So I'm trying to build wine-tkg-git with winesync enabled, but I get this error: 

```
 ==> ERROR: fatal
 ==> ERROR: Winesync header was not found. Build is forcibly prevented.
 ==> ERROR: Please use linux-tkg build with _winesync="true" or https://aur.archlinux.org/packages/winesync-dkms/
```

Only I have `winesync-dkms` installed, `winesync` is loaded with modprobe and shows up in `lsmod | grep winesync`, and I've reset the udev rules that come with the dkms module install. So everything is done correctly, but the build script isn't seeing that for some reason.

**Comment by Tk-Glitch** [comment]
What about the header package? It's separate yet needed to build wine.

**Comment by Tk-Glitch** [comment]
Make sure you have all the packages there installed: https://aur.archlinux.org/pkgbase/winesync
I tested again on my end and our header check works, so closing.
Feel free to comment in case you're still facing an issue.
