### ISSUE TITLE
childwindow patch needs an update for wine(-staging) 9.1

### ISSUE THREAD

**Issue by plaimbock** [Frogging-Family/wine-tkg-git#1121]
wine 9.1 + wine-staging 9.1 plus wine-tkg HEAD from 20240127 (git rev https://github.com/Frogging-Family/wine-tkg-git/commit/135e11e5a289a9d9875a5672a9a31ee37e2f4374), customization.cfg _LOCAL_PRESET="default-tkg"

HEAD is now at c963c4141a0 Release 9.1.
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 -> cherry picking...
 -> Hotfixing...
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: 
 -> Applying fsync-unix-staging.patch
 -> Applying fsync_futex_waitv.patch
 -> Applying childwindow-proton.patch
 ==> ERROR: Patch application has failed. The error was logged to /builddir/build/BUILD/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
error: Bad exit status from /var/tmp/rpm-tmp.lW4H3n (%prep)

**Comment by plaimbock** [comment]
From prepare.log:

childwindow-proton.patch -- ( Applied child window for vk patch )
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 52 (offset 1 line).
Hunk #2 succeeded at 153 (offset 10 lines).
Hunk #3 succeeded at 300 (offset 10 lines).
Hunk #4 succeeded at 313 with fuzz 2 (offset 10 lines).
Hunk #5 succeeded at 432 (offset 10 lines).
patching file dlls/winemac.drv/vulkan.c
patching file dlls/winevulkan/make_vulkan
Hunk #1 succeeded at 195 (offset -31 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 77 (offset 1 line).
Hunk #2 succeeded at 130 (offset 10 lines).
Hunk #3 succeeded at 296 (offset 10 lines).
Hunk #4 succeeded at 729 (offset 4 lines).
patching file include/wine/vulkan_driver.h
Hunk #2 succeeded at 55 (offset -2 lines).
patching file dlls/winex11.drv/init.c
Hunk #1 succeeded at 243 (offset -1 lines).
patching file dlls/winex11.drv/opengl.c
Hunk #1 succeeded at 1983 (offset 28 lines).
Hunk #2 succeeded at 2004 (offset 28 lines).
Hunk #3 succeeded at 2031 (offset 28 lines).
Hunk #4 succeeded at 3351 with fuzz 2 (offset 30 lines).
Hunk #5 FAILED at 3350.
Hunk #6 FAILED at 3371.
Hunk #7 FAILED at 3384.
3 out of 7 hunks FAILED -- saving rejects to file dlls/winex11.drv/opengl.c.rej
...

[opengl.c.rej.txt](https://github.com/Frogging-Family/wine-tkg-git/files/14072842/opengl.c.rej.txt)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/06cf294b3f30c449d916a8daed6e11878210f22d
