### ISSUE TITLE
ChildWindow Patch for Wine 9.1-Staging

### ISSUE THREAD

**Issue by lunarlettuce** [Frogging-Family/wine-tkg-git#1122]
Hi,

I'm a developer at VinegarHQ, a Wine wrapper for running Roblox on Linux systems. I've used your childwindow.patch (the legacy one in wine-tkg-patches/misc/childwindow/legacy/childwindow.patch) up until wine 8.20. Unfortunately, this patch no longer applies on wine-9.1 staging. Additionally, the newest patches appear to apply to wine proton, which we do not use.

Would it be possible for the childwindow.patch to be updated for wine-9.1 staging?

**Comment by unjaks** [comment]
ong

**Comment by lunarlettuce** [comment]
@Tk-Glitch Thanks for the advice, it appears to work. Cheers
