### ISSUE TITLE
Can't build with wayland driver on Ubuntu 22.04

### ISSUE THREAD

**Issue by rankynbass** [Frogging-Family/wine-tkg-git#1124]
Setting _wayland_driver="true" (or adding --with-wayland to _configure_userargs64) doesn't work when building on Ubuntu 22.04. It works fine in Fedora and Arch (I've successfully built and used wine wayland in both).

Fails with the following error message:
```
configure: error: Wayland 64-bit development files not found, the Wayland driver won't be supported.
This is an error since --with-wayland was requested.
```

libwayland-dev is installed. If there's some other package that needs to be installed, I can't figure what it is.

Building wine-9.0 mainline or later, for reference.

**Comment by lixiaolong2007** [comment]
Although I am using Redhat, I also encountered the same problem by installing wayland level and libwayland - *, but it still shows missing files

**Comment by lixiaolong2007** [comment]
Although I am using Redhat, I also encountered the same problem by installing wayland-devel and libwayland - *, but it still shows missing files

**Comment by lixiaolong2007** [comment]
但事实上它应该是识别到了wayland-devel
![2024-02-04 08-36-15 的屏幕截图](https://github.com/Frogging-Family/wine-tkg-git/assets/93075973/943290d4-17a1-4429-953e-311cbe9d0a94)

**Comment by loopyd** [comment]
Tested on a refresh ``ubuntu:jammy`` image in a docker container, and reporting back that the same thing occurs, even though ``libwayland-*`` is installed.

**Comment by yu-zify** [comment]
Check configure, you need to install xkbcommon and xkbregistry, etc.

**Comment by rankynbass** [comment]
Turned out to be a missing libxkbregistry package. Not sure if it was the libxkbregistry0 or libxkbregistry-dev, so I just installed them both, and it built first try.

**Comment by jackthenewbie** [comment]
I'm using ubuntu:24.04, it was the libxkbregistry-dev package, thanks op for the clue.
```
sudo apt install libxkbregistry-dev
```
