### ISSUE TITLE
Proton Nightly Build (Wine Master) Not Building

### ISSUE THREAD

**Issue by cprin21** [Frogging-Family/wine-tkg-git#1126]
```
-> Applying proton-tkg-staging.patch
 ==> ERROR: Patch application has failed. The error was logged to /__w/wine-tkg-git/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
```

**Comment by Tk-Glitch** [comment]
Please run `git-pull` in your clone to get the latest update. This was fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/3fbd4978a084c5a2ba9225929af1a57804669201

**Comment by cprin21** [comment]
Now the most recent Wine Master Nightly Build crashes Skyrim and Fallout 4, and older ones either do not launch and glitch out Steam, or launch with no soundtrack.
Very off behaviour. None of these issues occur on other strains of Proton.

**Comment by Tk-Glitch** [comment]
There is a known issue with 32-bit steam bridge library being broken on wine 9.x so games relying onto a 32-bit launcher/executable will not run in most cases. Between that and the waylol driver issues it's not the best time for the upstream based builds indeed.
It should all get sorted soon-ish.
Depending on your distro the nighties might have dependencies that are newer than what you have, which could explain the sound issues. Not sure about that one, I'll check if the CI builds broke in some way.

**Comment by cprin21** [comment]
Wine-TKG-Git Wine Master Proton Nightly Builds (Proton nopackage Arch Linux CI) has been failing to build here since Feb 21st.

**Comment by Tk-Glitch** [comment]
Both issues are fixed now. Closing.
