### ISSUE TITLE
The procedure entry point GetPointerDeviceRects could not be located in the dynamic link library USER32.dll

### ISSUE THREAD

**Issue by vivantart** [Frogging-Family/wine-tkg-git#1129]
Hello! This error is related to some missing library or is it a not implemented function?

![Screenshot_20240219_181355](https://github.com/Frogging-Family/wine-tkg-git/assets/109477864/a1ff8105-9835-45bc-adc1-f1f1391ab33d)

Console output:
fsync: up and running.
002c:fixme:winediag:loader_init Wine TkG (staging) 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0120:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0120:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0120:fixme:ntdll:NtQuerySystemInformation (0x00000007,0x141508,0x00000018,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x00000050,0x141508,0x000000a8,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
0120:fixme:ntdll:NtQuerySystemInformation (0x00000021,0x141690,0x00000010,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000002d,0x141690,0x00000020,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000003d,0x1416a8,0x00000a58,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x00000012,0x1416a8,0x00000a58,0x11ece0) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000002a,0x1416c0,0x00000a40,0x11ece0) stub
0120:fixme:ntdll:NtRaiseHardError 50000018 stub

and a clean wineprefix generates only these two lines:
**01cc:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
01cc:fixme:ntdll:NtRaiseHardError 50000018 stub**

but if I override kerberos dll and disable it the first line no longer appears.

I tried a few things like: another wine version, windows version, clean wineprefix, uninstall wine mono and installed dotnet through winetricks, compiled WoW64 wine...

**Comment by Tk-Glitch** [comment]
Kerberos isn't the issue here as you have found.
It seems the function is declared in winuser.h but it might not be implemented. Weird that there's no mention of it in the log though.

**Comment by vivantart** [comment]
> Kerberos isn't the issue here as you have found. It seems the function is declared in winuser.h but it might not be implemented. Weird that there's no mention of it in the log though.

Exactly! I have no clue what the software is trying to find.
Should I report it on WineHQ forum? Can I get a more detailed log?
