### ISSUE TITLE
Patching with wine-staging 9.3 fails

### ISSUE THREAD

**Issue by murl-digital** [Frogging-Family/wine-tkg-git#1130]
Attached is my prepare.log, it seems the x11/vulkan driver patches are blowing up

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/14398418/prepare.log)

**Comment by Tk-Glitch** [comment]
Indeed. I'll be working on fixing those later today.

**Comment by SingleInfiniteLoop** [comment]
This [patch](https://github.com/SingleInfiniteLoop/wine-tkg-git/commit/96e77e0d731653448765c45a419277f9ef76bb2a) might help.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/8098d4cbb9207c900664405ceba5038019e30c0a
