### ISSUE TITLE
Need NTSYNC5 patch rebase for Wine actual git

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1131]
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/14448410/proton-tkg.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/14448414/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/14448415/last_build_config.log)
![Screenshot from 2024-02-29 18-14-08](https://github.com/Frogging-Family/wine-tkg-git/assets/36989404/afac3913-6214-4da6-92ca-b08d6856f3e7)
![Screenshot from 2024-02-29 18-16-05](https://github.com/Frogging-Family/wine-tkg-git/assets/36989404/fc03205f-57ec-48f5-a52e-8355199cec06)

**Comment by Dlanis** [comment]
The patch fixes when I changed this line
`-#define SERVER_PROTOCOL_VERSION 793`
to this
'-#define SERVER_PROTOCOL_VERSION 794'
