### ISSUE TITLE
wine can't launch in some circumstances: Could not create tray window

### ISSUE THREAD

**Issue by murl-digital** [Frogging-Family/wine-tkg-git#1142]
after upgrading to the latest version in the chaotic-aur repo, wine can't open any windows. explorer.exe seems to not be able to launch, and the wayland driver isn't loading correctly

**Comment by Tk-Glitch** [comment]
Do the chaotic-aur builds had wine-wayland driver enabled/working before?

**Comment by murl-digital** [comment]
i think so, i'd have to double check. it is just building aur packages directly

**Comment by murl-digital** [comment]
OK, after the same issue happened after I switched back to wine-staging, I dug around and found it was a combination of 2 things:

1. I didn't have wine's drivers set in the registry (for anyone googling this, the command you want is ``wine reg.exe add HKCU\\Software\\Wine\\Drivers /v Graphics /d x11,wayland``)
2. yabridge, which is what I use wine for mainly, breaks with wine 9.5 ish and up. The fix for now is editing ``yabridge-host.exe``, see [this issue](https://github.com/robbert-vdh/yabridge/issues/320) for more details

Since this isn't an issue with tkg, I'm closing this out
