### ISSUE TITLE
childwindow.patch needs an update for wine(-staging)-9.5 (no wayland)

### ISSUE THREAD

**Issue by plaimbock** [Frogging-Family/wine-tkg-git#1144]
wine 9.5 + wine-staging 9.5 plus wine-tkg HEAD from 20240324 (git rev https://github.com/Frogging-Family/wine-tkg-git/commit/d08b8898f33798bce350ade6150fe0ab3fbe71cf ), customization.cfg _LOCAL_PRESET="default-tkg"

HEAD is now at 7c5b9304a62 Release 9.5.
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 -> cherry picking...
 -> Hotfixing...
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: 
 -> Applying fsync-unix-staging.patch
 -> Applying fsync_futex_waitv.patch
 -> Applying childwindow-proton.patch
 ==> ERROR: Patch application has failed. The error was logged to /builddir/build/BUILD/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit

From prepare.log:

childwindow-proton.patch -- ( Applied child window for vk patch )
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 52 (offset 1 line).
Hunk #2 FAILED at 143.
Hunk #3 succeeded at 233 (offset -55 lines).
Hunk #4 succeeded at 246 with fuzz 2 (offset -55 lines).
Hunk #5 succeeded at 351 (offset -69 lines).
1 out of 5 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winemac.drv/vulkan.c
Hunk #1 succeeded at 426 (offset -165 lines).
patching file dlls/winevulkan/make_vulkan
Hunk #1 succeeded at 196 (offset -30 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 77 (offset 1 line).
Hunk #2 FAILED at 120.
Hunk #3 succeeded at 228 (offset -57 lines).
Hunk #4 succeeded at 483 (offset -241 lines).
1 out of 4 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file include/wine/vulkan_driver.h
Hunk #1 succeeded at 29 (offset 8 lines).
Hunk #2 FAILED at 57.
1 out of 2 hunks FAILED -- saving rejects to file include/wine/vulkan_driver.h.rej
patching file dlls/winex11.drv/init.c
Hunk #1 succeeded at 243 (offset -1 lines).
patching file dlls/winex11.drv/opengl.c
Hunk #1 succeeded at 1980 (offset 25 lines).
Hunk #2 succeeded at 2001 (offset 25 lines).
Hunk #3 succeeded at 2028 (offset 25 lines).
Hunk #4 succeeded at 3348 with fuzz 2 (offset 27 lines).
Hunk #5 succeeded at 3377 (offset 27 lines).
Hunk #6 succeeded at 3398 (offset 27 lines).
Hunk #7 succeeded at 3411 (offset 27 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 347 (offset 14 lines).
Hunk #2 succeeded at 367 (offset 15 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 37 with fuzz 2 (offset 1 line).
Hunk #2 succeeded at 65 (offset 1 line).
Hunk #3 succeeded at 174 (offset -58 lines).
Hunk #4 succeeded at 274 (offset -58 lines).
Hunk #5 succeeded at 350 (offset -58 lines).
Hunk #6 succeeded at 356 (offset -58 lines).
Hunk #7 succeeded at 369 (offset -65 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1860 (offset 124 lines).
Hunk #2 succeeded at 1896 (offset 124 lines).
Hunk #3 succeeded at 2138 (offset 151 lines).
Hunk #4 succeeded at 2615 (offset 149 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 653 (offset 16 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 65 (offset 1 line).
Hunk #2 succeeded at 92 with fuzz 2 (offset -9 lines).
Hunk #3 FAILED at 146.
Hunk #4 succeeded at 278 (offset -58 lines).
Hunk #5 succeeded at 294 (offset -58 lines).
Hunk #6 succeeded at 354 with fuzz 2 (offset -58 lines).
1 out of 6 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winex11.drv/clipboard.c
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 446 with fuzz 2 (offset 20 lines).
Hunk #2 succeeded at 454 (offset 20 lines).
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 50 (offset -2 lines).
Hunk #2 succeeded at 72 (offset -1 lines).
Hunk #3 succeeded at 89 (offset -2 lines).
Hunk #4 succeeded at 668 (offset 69 lines).
Hunk #5 succeeded at 830 (offset 69 lines).
patching file dlls/winex11.drv/xfixes.h
patching file configure.ac
Hunk #1 succeeded at 72 (offset -4 lines).
Hunk #2 succeeded at 1191 with fuzz 1 (offset 6 lines).
Hunk #3 succeeded at 1295 with fuzz 2 (offset -8 lines).
patching file dlls/winex11.drv/init.c
Hunk #2 succeeded at 254 (offset 7 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 296 (offset -61 lines).
Hunk #2 succeeded at 320 (offset -61 lines).
Hunk #3 succeeded at 356 with fuzz 2 (offset -61 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 447 with fuzz 1 (offset 20 lines).
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 51 (offset -2 lines).
Hunk #2 succeeded at 74 (offset -1 lines).
Hunk #3 succeeded at 677 (offset 69 lines).
Hunk #4 succeeded at 703 (offset 69 lines).
Hunk #5 succeeded at 729 (offset 69 lines).
Hunk #6 succeeded at 888 (offset 69 lines).
patching file dlls/winex11.drv/xfixes.h
patching file dlls/winex11.drv/xpresent.h
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 52 (offset 1 line).
Hunk #2 FAILED at 153.
Hunk #3 succeeded at 174 (offset -61 lines).
Hunk #4 succeeded at 229 (offset -61 lines).
Hunk #5 succeeded at 248 (offset -61 lines).
Hunk #6 succeeded at 413 (offset -68 lines).
Hunk #7 succeeded at 435 (offset -68 lines).
1 out of 7 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1915 (offset 124 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 655 (offset 25 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 225 (offset -60 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1484 (offset 114 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 657 (offset 25 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 250 (offset -60 lines).
Hunk #2 succeeded at 492 (offset -67 lines).
Hunk #3 succeeded at 501 with fuzz 1 (offset -71 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1602 with fuzz 2 (offset 127 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 658 (offset 25 lines).
Hunk #2 succeeded at 668 with fuzz 2 (offset 24 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 65 (offset 1 line).
Hunk #2 succeeded at 241 (offset -60 lines).
Hunk #3 succeeded at 263 (offset -60 lines).
Hunk #4 succeeded at 271 (offset -60 lines).
Hunk #5 succeeded at 432 (offset -60 lines).
Hunk #6 succeeded at 444 (offset -56 lines).
Hunk #7 succeeded at 462 (offset -67 lines).
Hunk #8 succeeded at 485 (offset -67 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 67 (offset 1 line).
Hunk #2 succeeded at 242 (offset -60 lines).
Hunk #3 succeeded at 396 (offset -60 lines).
Hunk #4 succeeded at 417 (offset -60 lines).
Hunk #5 succeeded at 442 (offset -60 lines).
Hunk #6 succeeded at 455 (offset -60 lines).
Hunk #7 succeeded at 496 (offset -67 lines).
Hunk #8 succeeded at 549 (offset -72 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 271 (offset -60 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 369 (offset -67 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1608 (offset -141 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1896 (offset -210 lines).

**Comment by gilvbp** [comment]
duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/1143

**Comment by plaimbock** [comment]
Thanks @gilvbp I missed your issue. Closing.
