### ISSUE TITLE
[proton-tkg] no longer builds due to "other process window Vulkan rendering" (`OPWR-proton`) winex11.drv patchset

### ISSUE THREAD

**Issue by Arastais** [Frogging-Family/wine-tkg-git#1145]
Proton-tkg no longer builds due to "other process window Vulkan rendering patchset" (`wine-tkg-git/wine-tkg-patches/misc/childwindow/OPWR-proton.patch`). This seems to have started after wine-staging mirror commit [`5d8ef8d`](https://github.com/wine-staging/wine-staging/commit/5d8ef8d88105f566ccf5aab61be0b8811ad161da) was pushed.

```
-> Applying OPWR-proton.patch
==> ERROR: Patch application has failed. The error was logged to /home/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
```
<details>
<summary><code>prepare.log</code></summary>
<br>
<pre>
OPWR-proton.patch -- ( Applied other process window Vulkan rendering patchset )
patching file dlls/winex11.drv/vulkan.c
Hunk #1 FAILED at 70.
Hunk #2 FAILED at 244.
Hunk #3 FAILED at 413.
Hunk #4 FAILED at 436.
Hunk #5 FAILED at 445.
Hunk #6 FAILED at 532.
6 out of 6 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 65 with fuzz 1 (offset -7 lines).
Hunk #2 FAILED at 316.
Hunk #3 FAILED at 331.
Hunk #4 succeeded at 377 with fuzz 1 (offset 29 lines).
Hunk #5 FAILED at 416.
Hunk #6 FAILED at 423.
Hunk #7 FAILED at 452.
Hunk #8 FAILED at 568.
Hunk #9 FAILED at 598.
7 out of 9 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 2606 (offset -182 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 FAILED at 664.
Hunk #2 succeeded at 932 (offset 28 lines).
1 out of 2 hunks FAILED -- saving rejects to file dlls/winex11.drv/x11drv.h.rej
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 89 with fuzz 1 (offset -3 lines).
Hunk #2 succeeded at 768 (offset 35 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 66 (offset -7 lines).
Hunk #2 succeeded at 114 (offset -122 lines).
Hunk #3 succeeded at 394 (offset 29 lines).
Hunk #4 FAILED at 456.
Hunk #5 FAILED at 474.
Hunk #6 FAILED at 484.
Hunk #7 FAILED at 538.
Hunk #8 FAILED at 568.
Hunk #9 FAILED at 584.
Hunk #10 FAILED at 601.
Hunk #11 FAILED at 646.
8 out of 11 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 27 (offset 4 lines).
Hunk #2 succeeded at 178 with fuzz 1 (offset -408 lines).
Hunk #3 FAILED at 628.
1 out of 3 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej
</pre>
</details>

This can also be seen in the [wine master CI](https://github.com/Frogging-Family/wine-tkg-git/actions/runs/8485731837) going as far back as the last 5 days.

**Comment by Arastais** [comment]
Don't know if it's related, but if I "disable" the `OPWR` patch, I get a new error - `proton-tkg-additions.patch` now fails to apply:
<details>
<summary><code>prepare.log</code></summary>
<br>
<pre>
proton-tkg-additions.patch -- ( Using additional Proton-tkg patches )
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 FAILED at 68.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/x11drv_main.c.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 2761 (offset 146 lines).
Hunk #2 succeeded at 2795 (offset 146 lines).
patching file dlls/win32u/input.c
Hunk #1 succeeded at 2493 (offset 8 lines).
patching file dlls/winex11.drv/event.c
Hunk #1 succeeded at 1091 (offset -38 lines).
Hunk #2 succeeded at 1331 (offset -37 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1296 (offset 36 lines).
Hunk #2 succeeded at 1313 (offset 36 lines).
Hunk #3 succeeded at 1805 (offset 44 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 627 (offset 6 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1397 (offset -84 lines).
Hunk #2 succeeded at 1434 (offset -96 lines).
Hunk #3 succeeded at 1471 with fuzz 2 (offset -108 lines).
Hunk #4 succeeded at 2657 with fuzz 2 (offset -80 lines).
Hunk #5 succeeded at 2688 with fuzz 2 (offset -80 lines).
Hunk #6 succeeded at 2789 (offset -82 lines).
Hunk #7 succeeded at 2806 (offset -82 lines).
Hunk #8 succeeded at 2826 (offset -82 lines).
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1261 (offset -85 lines).
Hunk #2 succeeded at 2821 (offset -129 lines).
patching file dlls/winex11.drv/event.c
Hunk #1 succeeded at 1307 (offset -104 lines).
</pre>
</details>

**Comment by s0mebodyhelpme** [comment]
Same issue here. OPWR patch causes the build to fail.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/02e568d06dc9bd280450c30a0c179d6c4ba930ac
