### ISSUE TITLE
Mingw version on some distros does not pack d3d11to12 required to build dxvk

### ISSUE THREAD

**Issue by alemarostica** [Frogging-Family/wine-tkg-git#1148]
I was trying to build on ubuntu 22.04 which installs mingw v8.0.0, which apparently does not pack d3d11to12.h for some reason

**Comment by mikeserv-git** [comment]
That's d3d11on12.h (not d3d11to12) and it's a wine include, not mingw. You likely need to install the corresponding "devel" package that corresponds with whatever system wine packages you have installed.

**Comment by alemarostica** [comment]
Yes you're right, later I found something was messed up with my wine install. I have absolutely no idea why since the docker container I used for the build was brand new but I simply updated wine and everything worked
