### ISSUE TITLE
rebase childwindow

### ISSUE THREAD

**Issue by apprehensions** [Frogging-Family/wine-tkg-git#1149]
```
# childwindow needs rebasing
if git merge-base --is-ancestor 28873ce8c426f696ceb16e3f5d98d5f5c5ed3b79 HEAD; then
  warning "hotfix: disable fshack stuff depending on childwindow, currently disabled (28873ce+)"
  _childwindow_fix="false"
fi
```
also additionally required for 9.6 staging

**Comment by plaimbock** [comment]
On April 10 I asked the developer and here's what he said: " I'm currently working on upstreaming patches to make it easier to implement, hopefully even getting it upstream. I don't know how much time it'll take, hopefully not too long and I'll make sure a rebased version of it gets public afterwards, if it didn't make it upstream"
