### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by DJZeroAction** [Frogging-Family/wine-tkg-git#1150]
![2024-04-12_12-43](https://github.com/Frogging-Family/wine-tkg-git/assets/36211345/fc6629f5-6462-46b6-a4b5-76e4f6354946)

the build fails (0-default)

all i changed in the config was staging-version "v9.4"

im new to linux so i dont really know how to troubleshoot this, sorry if this is the wrong place to report the bug, i just want to make sure this is actually a bug.

im on arch linux, cloned and ran makepkg -si in the /wine-tkg-git/wine-tkg-git/ folder.

**Comment by Tk-Glitch** [comment]
It's not a issue from us.
Considering the segfault, if you have any CPU or RAM overclock in place, it's the most likely cause. Else it could be a bad RAM stick or some OS corruption.

**Comment by mikeserv-git** [comment]
A good indicator if it's a hardware problem, is that it will likely happen in different spots in a build (not always the same place) if you're corrupting data.

**Comment by Tk-Glitch** [comment]
Closing as we cannot help more on that matter. Hopefully DJZeroAction was able to fix it.
