### ISSUE TITLE
Fails to build Proton

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1170]
OS: Arch Linux.
e1e8369b9cf02e906fc3e069b76a7ee68646de39
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/15283984/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/15283985/prepare.log)

![Screenshot from 2024-05-11 23-31-01](https://github.com/Frogging-Family/wine-tkg-git/assets/36989404/97ce8736-6955-480c-b8bb-67f9a19a82bb)
![Screenshot from 2024-05-11 23-31-56](https://github.com/Frogging-Family/wine-tkg-git/assets/36989404/7ab3882c-4baf-45cd-9482-a432fb217ccb)

**Comment by Nanotwerp** [comment]
This is a duplicate of #1167 . #1171 should be able to fix it.

**Comment by Kerrung** [comment]
Closing it as duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/1167
