### ISSUE TITLE
Getting configure error when building wine-tkg on latest git

### ISSUE THREAD

**Issue by s0mebodyhelpme** [Frogging-Family/wine-tkg-git#1173]
The error appears as below:

![Screenshot](https://github.com/Frogging-Family/wine-tkg-git/assets/163645480/e6aa670c-475b-4352-b16e-5d3670bf5e34)

And the config.log mentioned is here:

[config.log](https://github.com/Frogging-Family/wine-tkg-git/files/15303601/config.log)

In case it's important, this is a fresh install of Arch with the custom kernel from Frogging-Family, too.

**Comment by Nanotwerp** [comment]
Sorry! I caused this issue! You can fix it by downloading [this patch](https://patch-diff.githubusercontent.com/raw/Frogging-Family/wine-tkg-git/pull/1174.patch) from this PR and using `git apply 1174.patch` while in the root of your `wine-tkg-git` directory.

You could also change the flags in your Wine and Proton advanced-customization.cfg and sample-external-config.cfg files from having `-Wno-error=-Wincompatible-pointer-types` in the `_GCC_FLAGS` and` _CROSS_FLAGS ` to `-Wno-error=incompatible-pointer-types`

**Comment by s0mebodyhelpme** [comment]
Thanks! Gonna give the patch a try.

**Comment by s0mebodyhelpme** [comment]
It works!

**Comment by mirh** [comment]
@alesliehughes can you update the *eventfd_synchronization* and *gdi32-rotation* patches to work with gcc 14?

**Comment by alesliehughes** [comment]
I can easily fix the gdi32-rotarion one. The other will take time.
