### ISSUE TITLE
[winewayland.drv][proton-tkg] wayland gets disabled after proton shutting down

### ISSUE THREAD

**Issue by SopaDeMacaco-UmaDelicia** [Frogging-Family/wine-tkg-git#1181]
So I've been using proton from wine master tree (git builds) with native wayland driver and in latest builds after proton shutting down the registry key
`HKEY_CURRENT_USER\Software\Wine\Drivers\Graphics=` gets changed from `x11,wayland` to just `x11` so this prevents me from running game in wayland native mode.

Currently I'm using `proton_tkg_9.7.r5.gc5ff8141` build, which works great, but newer `proton_tkg_9.8.r3.gf76ea979` and `proton_tkg_9.9.r4.g791a70fa` do not work for me and force this registry key for some reason.

**Comment by Tk-Glitch** [comment]
Did you set `PROTON_ENABLE_WAYLAND=1` in your game launch options?

**Comment by SopaDeMacaco-UmaDelicia** [comment]
> Did you set `PROTON_ENABLE_WAYLAND=1` in your game launch options?

Is that a new thing? I've been using wayland-native proton for quite some time without it. I only put `DISPLAY=` in launch options and manually modified registry key. I tried your suggestion now but the registry still keeps being modified and the game can't launch since the display is unset and wayland not available.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
@Tk-Glitch Thanks! New build works like a charm.
![image](https://github.com/Frogging-Family/wine-tkg-git/assets/106288630/7273220f-550e-438d-b403-d512e9e067e2)
