### ISSUE TITLE
proton-win10-default.patch fails on on latest git default-tkg

### ISSUE THREAD

**Issue by s0mebodyhelpme** [Frogging-Family/wine-tkg-git#1182]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/15443434/prepare.log)

**Comment by s0mebodyhelpme** [comment]
Temporary workaround is to set staging version as v9.9.

**Comment by bautistamoll** [comment]
Same issue here

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/3930719f3c671072da93c55378eeff115d548fc6
