### ISSUE TITLE
proton can't build due to failure with building dxvk

### ISSUE THREAD

**Issue by s0mebodyhelpme** [Frogging-Family/wine-tkg-git#1183]
DXVK build fails from dxvk-tools, and it only works outside of proton-tkg by setting an earlier commit. I set mine to the latest release (as of now 2.3.1), and it builds. However, whenever proton-tkg's script is launches any changes made to updxvk.cfg are reverted to whatever is default and the build process is essentially soft-locked into failing when building with the proton-tkg script.

**Comment by s0mebodyhelpme** [comment]
commenting out lines 374-375 of proton-tkg.sh stops the dxvk-tools repo in external-resources from reverting to the defaults. this seems to be a temporary workaround, though.

**Comment by IdrisKalp** [comment]
It is a failure due to GCC 14. Downgrading to GCC 13 ends succesful

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/dxvk-tools/commit/bec16df66b36b2c81389085de944a4e95b72ca45
