### ISSUE TITLE
dxvk patches don't work with latest dxvk-tools commit

### ISSUE THREAD

**Issue by 2bc4** [Frogging-Family/wine-tkg-git#1184]
The patches directory was deleted in Frogging-Family/dxvk-tools@bec16df66b36b2c81389085de944a4e95b72ca45 so proton-tkg.sh just fails when attempting to copy patch files.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/dxvk-tools/commit/27c40cf87560c2ec106136cac313c87748e2aac7
