### ISSUE TITLE
Patch ntsync5-staging-protonify.patch & ntsync5-staging.patch needs rebasing

### ISSUE THREAD

**Issue by h0x32** [Frogging-Family/wine-tkg-git#1187]
Hello, patch ntsync5-staging-protonify.patch is failing, here is [error.log](https://github.com/user-attachments/files/15747440/error.log) output

and here is my [customization.cfg.zip](https://github.com/user-attachments/files/15747447/customization.cfg.zip)

The code for the wine server was modified upstream to add new features such as https://gitlab.winehq.org/wine/wine/-/commit/37e7038c5c314527dc242cdbe5e8a70000fdfe98

and thus the ntsync5 patch needs to be rebased.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/0baab046ffc8cf52114e094ffef10b53e5f5b0a9
