### ISSUE TITLE
failed building proton-tkg

### ISSUE THREAD

**Issue by Galcian79** [Frogging-Family/wine-tkg-git#119]
`makepkg -si` exits with:

`PKGBUILD: line 165: cd: too many arguments, error in prepare ()`

maybe i'm doing something wrong?

my config:
[...]
_nomakepkg_dep_resolution_distro="archlinux"
[...]
_plain_version=""
_use_staging="true"
_staging_version="5.9"
[...]
_community_patches="dxvk linux58-tkg vkd3d-git wine-tkg-git"

**Comment by openglfreak** [comment]
You can't just go and assume that a shell script works properly under a directory with spaces in the name :D
Move the repo somewhere else.

**Comment by Tk-Glitch** [comment]
`_community_patches="dxvk linux58-tkg vkd3d-git wine-tkg-git"`
That's not how community patches are working :frog:
