### ISSUE TITLE
Error in prepare while applying ntsync5-staging.patch

### ISSUE THREAD

**Issue by pppbb** [Frogging-Family/wine-tkg-git#1195]
[prepare.log](https://github.com/user-attachments/files/15845370/prepare.log)

[wine-tkg.cfg.txt](https://github.com/user-attachments/files/15845099/wine-tkg.cfg.txt)

I get error : `patch: **** malformed patch at line 3873:  { 
==> BŁĄD: Patch application has failed. The error was logged to /home/piotr/Pobrane/tmp/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> BŁĄD: Wystąpił błąd w prepare().`

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/d64b87e602f70fd3b413c18dcce3de557e8b9d68

**Comment by LionHeartP** [comment]
> [prepare.log](https://github.com/user-attachments/files/15845872/prepare.log) Unfortunately compilation is still broken for me.

Can I see your `include/config.h.in.rej` ?

**Comment by pppbb** [comment]
`Can I see your include/config.h.in.rej ?`

[config.h.in.rej.txt](https://github.com/user-attachments/files/15854895/config.h.in.rej.txt)

**Comment by pppbb** [comment]
I can confirm that PR #1198 works for me.

**Comment by Tk-Glitch** [comment]
Hopefully resolved for a while with https://github.com/Frogging-Family/wine-tkg-git/commit/3e43387665eebdeaae86c10b748ab92b0839c540
