### ISSUE TITLE
childwindow-proton.patch needs update for wine-9.11

### ISSUE THREAD

**Issue by plaimbock** [Frogging-Family/wine-tkg-git#1196]
=> Applying fsync_futex_waitv.patch
 => Applying childwindow-proton.patch
 ===> ERROR: Patch application has failed. The error was logged to /builddir/build/BUILD/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 => Applying LAA-unix-staging.patch
 => Applying josh-flat-theme.patch

Rémi's  last commit in his vulkan-childwindow branch shows some dpi-related changes:
https://gitlab.winehq.org/rbernon/wine/-/commit/c84db35c12d69b20fc31ca44fffd0ed86c67b0f0

**Comment by Artewar67** [comment]
This commit should fix it: https://github.com/Frogging-Family/wine-tkg-git/pull/1197

**Comment by plaimbock** [comment]
@Artewar67 Thanks for the super fast fix!
