### ISSUE TITLE
error when creating the prefix, then some application can't be installed

### ISSUE THREAD

**Issue by robistic** [Frogging-Family/wine-tkg-git#1210]
Hi,
In Endeavouros, when I run winecfg, in order to create .wine prefixe, I get these errors in the terminal, but previously it used to work:
wine: created the configuration directory '/home/olivier/.wine'
wineserver: using server-side synchronization.
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
002c:fixme:winediag:loader_init Wine TkG (staging) 9.11 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
004c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0054:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0054:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0054:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0054:err:ole:apartment_get_local_server_stream Failed: 0x80004002
004c:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
004c:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
004c:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0054:err:ole:start_rpcss Failed to open RpcSs service
0080:err:ntoskrnl:ServiceMain Failed to load L"C:\\windows\\system32\\win32k.sys"
0080:err:ntoskrnl:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgkrnl.sys"
0080:err:ntoskrnl:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgmms1.sys"
00a0:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
00a0:fixme:file:NtLockFile I/O completion on lock not implemented yet
00a0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00b0:fixme:file:NtLockFile I/O completion on lock not implemented yet
00b0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00b8:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
00b8:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
00b0:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
00b0:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
00a0:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
00a0:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0108:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
0108:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0108:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export

**Comment by mikeserv-git** [comment]
If you need gnutls, install it like this in an Arch based distro like Endeavour

# pacman -S gnutls lib32-gnutls

(note that you would need to have the multilib repo enabled for lib32)

Check your wine-mono version too. Wine 9.11 would need at least Mono 9.1.0

**Comment by robistic** [comment]
Thank you.
now when I launch the program (Kontakt 7), I have this error:
I had to reinstall Endeavouros. And now, impossible to run Kontakt. Installed with Native Access 1. With Wine tkg, here is the error :
wineserver: using server-side synchronization.
002c:fixme:winediag:loader_init Wine TkG (staging) 9.11 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0124:err:module:import_dll Library ODBC32.dll (which is needed by L"C:\\Program Files\\Native Instruments\\Kontakt 7\\Kontakt 7.exe") not found
0124:err:module:loader_init Importing dlls for L"C:\\Program Files\\Native Instruments\\Kontakt 7\\Kontakt 7.exe" failed, status c0000135
