### ISSUE TITLE
Applying ntsync5-mainline.patch failed 

### ISSUE THREAD

**Issue by damachine** [Frogging-Family/wine-tkg-git#1214]
hi. last wine mainline build failed.

 -> cherry picking...
  -> Hotfixing...
  -> Applying ntsync5-mainline.patch
==> FEHLER: Patch application has failed. The error was logged to /home/damachine/.tkg/temp/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by GrabbenD** [comment]
**Workaround**

```ini
_plain_version="wine-9.12"
_use_staging="false"
```

**Comment by damachine** [comment]
hi i think wine-9.12.r0.gb87f35898d2 was the last the patch work on. lasted git mirror commits, it did not work. i use 

`
#### WINE FLAVOUR SETTINGS ####
...

# plain wine commit (short) or version tag if you want to use a specific wine version. Can use e.g. "64d9f30", "wine-3.16" or "wine-4.0"
# !!! Only affects non-staging builds (you want to edit the staging_version below for staging builds) !!!
# Leave empty to use latest master - https://github.com/wine-mirror/wine/commits/master
#_plain_version=""

# use mirror servers (github) for plain wine and staging sources. It is usually much faster than main servers but there might be a little delay before it gets synchronized.
_github_mirrorsrc="true" 

_use_fastsync="false"
_use_ntsync="true"
_use_esync="false"
_use_fsync="false"
_use_staging="false"
.....
`

**Comment by Artewar67** [comment]
I was able to make ntsync5 work on the latest wine. Wait for the rebasing patches

**Comment by damachine** [comment]
thx
