### ISSUE TITLE
Bug with childwindow patch on Wine 9.12

### ISSUE THREAD

**Issue by lunarlattice0** [Frogging-Family/wine-tkg-git#1220]
Hi, 

I've identified a bug with the childwindow patch on Wine 9.12 that causes Roblox Studio to not function correctly:
![image](https://github.com/user-attachments/assets/001770ac-4585-4bb9-8d55-004e94f0daef)
as built [here](https://github.com/vinegarhq/wine-builds/pull/5)

The patch functions correctly on Wine 9.2, and Roblox Studio does not have any graphical issues in that version.

Please advise, thanks

**Comment by km9l** [comment]
> I've identified a bug with the childwindow patch on Wine 9.12 that causes Roblox Studio to not function correctly: ![image](https://private-user-images.githubusercontent.com/18731514/348017655-001770ac-4585-4bb9-8d55-004e94f0daef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTQ1NzQsIm5iZiI6MTcyMTA1NDI3NCwicGF0aCI6Ii8xODczMTUxNC8zNDgwMTc2NTUtMDAxNzcwYWMtNDU4NS00YmI5LThkNTUtMDA0ZTk0ZjBkYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4OGMzMzk0YzRjZmM1ZTAzZmJkYTNkZTlkMzIzNmFlZmU5NmVmMDk5YTMyMTJiYjlkMzUwZTQwMWE4NGQwZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lBG6h-0XJpa_pNVIEPgcC7OByXUoZf6J-IJQSkKH5wQ) as built [here](https://github.com/vinegarhq/wine-builds/pull/5)

to clarify, this happens on roblox studio's vulkan renderer with proprietary nvidia drivers. the d3d11 engine (with or without dxvk) works worse. the person who tested this seems to have no issues with his amd gpu, but that gpu apparently works slow for him.

> The patch functions correctly on Wine 9.2, and Roblox Studio does not have any graphical issues in that version.

not for everyone :sweat_smile:: https://github.com/vinegarhq/vinegar/issues/423

**Comment by Artewar67** [comment]
I tried to make the patch work somehow and used https://gitlab.winehq.org/rbernon/wine and the "wip/vulkan-child-window" branch but I have no luck. I have interestingly much worse artifacts and maybe the new patch will work better for you.
[childwindow-proton-mainline.txt](https://github.com/user-attachments/files/16254359/childwindow-proton-mainline.txt)
[childwindow-proton.txt](https://github.com/user-attachments/files/16254362/childwindow-proton.txt)

### Rename txt to patch!

**Comment by km9l** [comment]
> I tried to make the patch work somehow and used https://gitlab.winehq.org/rbernon/wine and the "wip/vulkan-child-window" branch but I have no luck. I have interestingly much worse artifacts and maybe the new patch will work better for you.

i tested it myself too, and i also had intense flickering. for some reason my friend doesnt have that.
this new patch didnt really change anything

> It would help if you could mention any childwindow issues in this MR

i will do. thanks.

**Comment by km9l** [comment]
> I tried to test it on a plain wine to make sure that it is a problem with the childwindow patch itself and yes it is a childwindow problem. So I left a comment with a description of the issues and a log file.

thanks a lot! btw, you tested it with dxvk which has more instabilities. the same is observable with the roblox vulkan engine though. (you can test that too by changing the renderer from studio settings) wined3d with d3d11 renderer works ok.

also, we have just tested the patch in the new [wayland childwindow MR](https://gitlab.winehq.org/wine/wine/-/merge_requests/6107). my friend is reporting great results besides some menus and a button rendered offscreen (so they have intense flickering). even resizing menus work fine unlike xorg which is cool:

https://github.com/user-attachments/assets/3a15d200-cdb3-45b5-ac74-d1c28f624b0f


https://github.com/user-attachments/assets/d5328705-3236-4ab3-acf9-34fe62d109bb

**Comment by sakx7** [comment]
I'm encountering the same problems. Is there a fix for it?

**Comment by km9l** [comment]
> I'm encountering the same problems. Is there a fix for it?

not yet as far as i know

**Comment by Artewar67** [comment]
@lunarlattice0 @km9l 
Today was in upstream wine was merged childwindow support and I can confirm that it works fully correctly with roblox studio but only with dxvk. Native vulkan has become completely broken for me in general

**Comment by Artewar67** [comment]
@Tk-Glitch I think we can close this issue

**Comment by Tk-Glitch** [comment]
Fixed upstream.
