### ISSUE TITLE
[bug] can't build with _use_ntsync="true"

### ISSUE THREAD

**Issue by OneOfOne** [Frogging-Family/wine-tkg-git#1221]
The build exits with: `ERROR: NTsync conflicts with _use_esync and _use_fsync. Build is forcibly prevented. Please disable them in your .cfg to use ntsync`

```
_use_esync="false"
_use_fsync="false"
_use_fastsync="false"
_use_vkd3dlib="false"
_dxvk_dxgi="true"
_use_ntsync="true"

_wayland_driver="true"
```

**Comment by qsniyg** [comment]
For now, disable `_staging_esync`

**Comment by OneOfOne** [comment]
the same error, it still applies `fsync-unix-staging.patch`

```
_use_esync="false"
_staging_esync="false"
_use_fsync="false"
_staging_fsync="false"
_use_fastsync="false"
_use_vkd3dlib="false"
_dxvk_dxgi="true"
_use_ntsync="true"
```

**Comment by OneOfOne** [comment]
setting _protonify=false doesn't work either, it's staging applying those patches.

**Comment by atamax** [comment]
Build with _use_ntsync="true" went successfully for me, don't forget to do `_fsync_spincounts="false"` inside the advanced-customization.cfg as it failed to build without doing that. Do try to diff against my provided files to check whats different:
[customizationfiles.tar.gz](https://github.com/user-attachments/files/16405321/customizationfiles.tar.gz)

**Comment by OneOfOne** [comment]
Thank you!

It was ` _LOCAL_PRESET="protonified"` that was overriding some of the settings.

With ntsync, battle.net crashes but that's an issue for another day.

**Comment by Artewar67** [comment]
> With ntsync, battle.net crashes but that's an issue for another day.

I can't confirm on my side. Did you build with staging patches?
