### ISSUE TITLE
no-makepkg build fails on Fedora 40 after wine-staging commit d2636c4

### ISSUE THREAD

**Issue by AllenTzul** [Frogging-Family/wine-tkg-git#1233]
Attempts to make a no-makepkg build on Fedora 40 fails after wine-staging commit d2636c4 with the following error:

```
patching file dlls/winex11.drv/bitblt.c
Hunk #1 FAILED at 2263.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/bitblt.c.rej
```
 The last commit that works for me is 06d8038.

**Comment by Artewar67** [comment]
This https://github.com/Frogging-Family/wine-tkg-git/pull/1235 and this https://github.com/Frogging-Family/wine-tkg-git/pull/1234 should fix issue
