### ISSUE TITLE
Wine valve-exp-bleeding builds failure at patching

### ISSUE THREAD

**Issue by IdrisKalp** [Frogging-Family/wine-tkg-git#1238]
Garuda Linux, title explains problem.
Screenshot:
![resim](https://github.com/user-attachments/assets/e82a1212-2cc9-42c3-8aac-325b190f4980)

prepare.log
https://dpaste.org/DnAu8

**Comment by adolfintel** [comment]
Can you try again? It builds absolutely fine here

**Comment by rchris494** [comment]
i get the same thing when trying to build on unbuntu 22.04 the valve-exp-bleeding

Branch 'experimental_9.0' set up to track remote branch 'experimental_9.0' from 'origin'.
HEAD is now at 9e9501cfbbd mmdevapi: Unlock session in create_session_enumerator().
 => Cleaning wine-staging source code tree...
 => Cleaning wine source code tree...
 ==> WARNING: Disabling any known to be broken (or already patched in) community patch on valve proton tree
 => cherry picking...
 => Hotfixing...
 => Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: -W winex11-_NET_ACTIVE_WINDOW -W user32-alttab-focus -W winex11-WM_WINDOWPOSCHANGING -W winex11-MWM_Decorations -W ntdll-Syscall_Emulation -W ntdll-Junction_Points -W server-File_Permissions -W server-Stored_ACLs -W eventfd_synchronization -W d3dx11_43-D3DX11CreateTextureFromMemory -W dbghelp-Debug_Symbols -W ddraw-Device_Caps -W ddraw-GetPickRecords -W Pipelight -W server-PeekMessage -W server-Realtime_Priority -W server-Signal_Thread -W loader-KeyboardLayouts -W msxml3-FreeThreadedXMLHTTP60 -W ntdll-ForceBottomUpAlloc -W ntdll-WRITECOPY -W ntdll-CriticalSection -W ntdll-Exception -W ntdll-Hide_Wine_Exports -W ntdll-Serial_Port_Detection -W server-default_integrity -W user32-rawinput-mouse -W user32-rawinput-mouse-experimental -W user32-recursive-activation -W windows.networking.connectivity-new-dll -W wineboot-ProxySettings -W winex11-UpdateLayeredWindow -W winex11-Vulkan_support -W wintab32-improvements -W xactengine3_7-PrepareWave -W xactengine-initial -W kernel32-CopyFileEx -W shell32-Progress_Dialog -W shell32-ACE_Viewer -W fltmgr.sys-FltBuildDefaultSecurityDescriptor -W inseng-Implementation -W ntdll-RtlQueryPackageIdentity -W packager-DllMain -W wscript-support-d-u-switches -W wininet-Cleanup -W sapi-ISpObjectToken-CreateInstance -W cryptext-CryptExtOpenCER -W shell32-NewMenu_Interface -W wintrust-WTHelperGetProvCertFromChain -W user32-FlashWindowEx -W wined3d-zero-inf-shaders -W kernel32-Debugger -W ntdll-NtDevicePath -W ntdll-HashLinks -W ntdll_reg_flush -W odbc-remove-unixodbc -W winspool.drv-ClosePrinter -W winmm-mciSendCommandA -W winex11-XEMBED -W winex11-CandidateWindowPos -W winex11-Window_Style -W winex11-ime-check-thread-data -W winex11-Fixed-scancodes -W winex11.drv-Query_server_position -W user32-Mouse_Message_Hwnd -W winepulse-PulseAudio_Support -W d3dx9_36-D3DXStubs -W shell32-registry-lookup-app -W ntdll-ext4-case-folder
 ===> ERROR: Patch application has failed. The error was logged to /home/legion/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 => To use the last known good mainline version, please set _plain_version="" in your .cfg
 => To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
 => GE patches...
 => Applying assettocorsa-hud.patch 
 => Applying killer-instinct-winevulkan_fix-80.patch 
 => Applying hotfix-guild_wars_2.patch 
 => ######################################################
 => 
 => Applying your own plain-wine patch /home/legion/wine-tkg-git/wine-tkg-git/de-steamify-90.mypatch
 => 
 => ######################################################

i noticed this in the prepare log

/tmp/wine-tkg/src/wine-staging-git/staging/../patches/gitapply.sh -d /home/legion/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < error: patch failed: dlls/d3dx9_36/d3dx9_private.h:127
error: dlls/d3dx9_36/d3dx9_private.h: patch does not apply
error: patch failed: dlls/d3dx9_36/surface.c:650
error: dlls/d3dx9_36/surface.c: patch does not apply

Failed to apply patch d3dx9_36-DDS/0002-d3dx9_36-Improve-D3DXSaveTextureToFile-to-save-simpl.patch

[prepare.log](https://github.com/user-attachments/files/16576914/prepare.log)

attached is my prepare log.

it still keeps building. i just noticed it when i first started the build

**Comment by IdrisKalp** [comment]
@adolfintel tried many times, it's same.

**Comment by adolfintel** [comment]
@IdrisKalp Looking at my log I can confirm what @rchris494 says, that specific patch (which comes from wine-staging) fails to apply on valve wine bleeding-edge, but the build process continues, it's not a fatal error.

**Comment by adolfintel** [comment]
The patch is not present in valve wine, but it doesn't seem to be anything important, it adds functions for saving DDS textures to file, maybe for screenshots or for debugging?

**Comment by IdrisKalp** [comment]
@adolfintel Problem is build won't continue for me. Patch fails and everything stops.

**Comment by IdrisKalp** [comment]
I did before but to be sure, I renewed customization.cfg but the fail persisted. There is no other change in files. And I set that variable now, fail continues.
