### ISSUE TITLE
Linking d3dx10_43.dll sometimes fails

### ISSUE THREAD

**Issue by Saancreed** [Frogging-Family/wine-tkg-git#124]
Trying to build latest wine-staging fails on my machine with following error:

```
../../tools/winegcc/winegcc -o d3dx10_43.dll --wine-objdir ../.. -b x86_64-w64-mingw32 --lib-suffix=.cross.a \
  -Wl,--wine-builtin -shared ../../../wine-mirror-git/dlls/d3dx10_43/d3dx10_43.spec -mno-cygwin \
  async.cross.o d3dx10_43_main.cross.o version.res ../../dlls/windowscodecs/libwindowscodecs.delay.a \
  ../../dlls/d3d10_1/libd3d10_1.cross.a ../../dlls/d3dcompiler_47/libd3dcompiler.cross.a \
  ../../dlls/dxguid/libdxguid.cross.a ../../dlls/ucrtbase/libucrtbase.cross.a -Wl,-O1,--sort-common,--as-needed \
  -Wl,--file-alignment,4096
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xca0): undefined reference to `GUID_ContainerFormatBmp'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xcb0): undefined reference to `GUID_ContainerFormatJpeg'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xcc0): undefined reference to `GUID_ContainerFormatPng'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xcd0): undefined reference to `GUID_ContainerFormatDds'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xce0): undefined reference to `GUID_ContainerFormatTiff'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xcf0): undefined reference to `GUID_ContainerFormatGif'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata+0xd00): undefined reference to `GUID_ContainerFormatWmp'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: d3dx10_43_main.cross.o:d3dx10_43_main.c:(.rdata$.refptr.IID_IWICDdsDecoder[.refptr.IID_IWICDdsDecoder]+0x0): undefined reference to `IID_IWICDdsDecoder'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make[1]: *** [Makefile:336: d3dx10_43.dll] Error 2
make[1]: Leaving directory '/build/wine-tkg-git/src/wine-tkg-git-64-build/dlls/d3dx10_43'
make: *** [Makefile:9570: dlls/d3dx10_43] Error 2
```

My `wine-tkg.cfg`:
```
_NOINITIALPROMPT="true"
_PKGNAME_OVERRIDE="none"
_use_vkd3dlib="fork"
_plasma_systray_fix="true"
_protonify="true"
_hotfixes_no_confirm="true"
```

Fwiw I'm building the package in a 'clean' (slightly modified) ramfs chroot like this: `makechrootpkg -cr /var/lib/archbuild -D /build/.config/frogminer -I ~/Packages/vkd3d/vkd3d-proton-*.pkg.tar* -I ~/Packages/vkd3d/lib32-vkd3d-proton-*.pkg.tar* -I ~/Packages/dxil-spirv/dxil-spirv-*.pkg.tar* -I ~/Packages/dxil-spirv/lib32-dxil-spirv-*.pkg.tar*`

The issue seems like a race condition; after restarting the build, linking 64–bit DLL succeeded but later linking 32–bit DLL failed with the exact same error.

**Comment by SveSop** [comment]
I had this happen to me too, and afaik i solved that by switching some buildflags. I updated my scripts, so i dont remember what flags i used, but currently i am using:
```
CFLAGS='-O2 -ftree-vectorize'
CROSSCFLAGS='-O2 -ftree-vectorize'
LDFLAGS='-Wl,-O1,--sort-common,--as-needed'
CROSSLDFLAGS='-Wl,-O1,--sort-common,--as-needed'
```
I sometimes add -O3 and -march=native tho, but the generic flags i use is like above.

I did not experience this problem when building lutris 5.7-8 source... but recently when trying to get World of Warcraft PTR to work, it needs a newer wine, and i got this link error from > 5.13. And as you experienced aswell, just doing "make" again completed it seemingly.

Sorry that i could not remember the flags i used before that seemed to have some issues with this.

**Comment by tannisroot** [comment]
I workarounded the issue by getting rid of `-pipe` flag from CROSSCFLAGS and CFLAGS in advanced configuration

**Comment by Tk-Glitch** [comment]
It seems to be a "new feature" of GCC10. If getting rid of the -pipe flag is a confirmed workaround we can do that. On my end it'll happen once in a blue moon, maybe 1/100 compilations or less, so it'll take me a while to verify.

**Comment by SveSop** [comment]
> It seems to be a "new feature" of GCC10. If getting rid of the -pipe flag is a confirmed workaround we can do that. On my end it'll happen once in a blue moon, maybe 1/100 compilations or less, so it'll take me a while to verify.

I did not test this to calculate a average of times it happened, so i cant really tell, but yeah, it does not happen every time.

It seems as `-pipe` is not used for the mingw-w64 part according to the generated Makefile by default tho, so if you had `CROSSCFLAGS=-pipe xxxx` maybe it could be something there?

My configure line (without the --prefix):

`configure CFLAGS='-O2 -march=native -ftree-vectorize' CROSSCFLAGS='-O2 -march=native -ftree-vectorize' LDFLAGS='-march=native -Wl,-O1,--sort-common,--as-needed' CROSSLDFLAGS='-march=native -Wl,-O1,--sort-common,--as-needed' --enable-win64`
```
CFLAGS          = -O2 -march=native -ftree-vectorize -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
CPPFLAGS        = 
CROSSCFLAGS     = -O2 -march=native -ftree-vectorize
CROSSLDFLAGS    = -march=native -Wl,-O1,--sort-common,--as-needed
EXTRACFLAGS     = -Wall -pipe -fcf-protection=none -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op
EXTRACROSSCFLAGS= -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value -Wno-format -Wformat-overflow -Wnonnull -mcx16
MSVCRTFLAGS     =  -fno-builtin -fshort-wchar -mabi=ms
TARGETFLAGS     = -m64
LDDLLFLAGS      = -fPIC -fasynchronous-unwind-tables

LDFLAGS         = -march=native -Wl,-O1,--sort-common,--as-needed
```
Also, i am on ubuntu so i am somewhat stuck with gcc-9.3/gcc-mingw-w64-9.3
```
gcc version 9.3.0 (Ubuntu 9.3.0-11ubuntu0~18.04.1)
gcc version 9.3-posix 20200422 (GCC)
```
Arf.. i have a tendency to NOT save my "old scripts" once i find a problem and fix it.. (should probably just .git my whole drive hehe), but i do think i had `CROSSCFLAGS=-pipe` before updating it for this problem.

@tannisroot If you run configure with your setup, try to compare your Makefile with mine and see if there is any obvious difference?

**Comment by reticulatedpines** [comment]
Removing -pipe fixed this for me, at least for 20 builds.  I was seeing this on 100% of builds if I used all threads.  I have 8C/16T which is relatively high so perhaps that makes it more likely.  Manually using -j4 I would still see it, but less frequently.  -j1 I never saw it, but the build takes over 40 minutes so didn't try very often.

**Comment by tannisroot** [comment]
Should we report this to WineHQ guys maybe?

**Comment by SveSop** [comment]
> Should we report this to WineHQ guys maybe?

Well, as i posted above, i still compile with `-pipe` as this seems to be the default "detected" from wine configure, and it does not seem to fail... however, the mingw-w64 flags are NOT detected with `-pipe`. 

It would be interesting to compare distro perhaps, cos it should "work out of the box" without the need to set any specific flags IMO.
```
cd ~/wine-dirs/wine-build/
../wine-source/configure
make
make install
```
[https://wiki.winehq.org/Building_Wine](https://wiki.winehq.org/Building_Wine)

It could be a distro specific thing? What flags are being set if you run just "configure" without any "CFLAGS" settings on Arch vs. Ubuntu perhaps? Or "insert-distro-here". Are they different?

"Plain" configure with gcc-9.3 + gcc-mingw-w64 for my Ubuntu 18.04 box:
```
CFLAGS          = -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
CROSSCFLAGS     = -g -O2
EXTRACFLAGS     = -Wall -pipe -fcf-protection=none -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf
EXTRACROSSCFLAGS= -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value -Wno-format -Wformat-overflow -Wnonnull -mcx16 -gdwarf-2 -gstrict-dwarf
CROSSLDFLAGS    = 
LDFLAGS         = 
```

**Comment by SveSop** [comment]
The reason i am saying this is that i am 110% certain that if just doing `configure` without any set CFLAGS/CROSSCFLAGS compiles without issue, the wine devs will kick this off as a distro issue - ie. Not-Our-Bug :)

If however the auto-configure flags causes crashes, it would be something to consider posting about - and it would be worth comparing if there is a difference between distros, or gcc/mingw versions perhaps, or if it is a difference between this happening with gcc-10 vs other gcc versions.

`-pipe` is a non-standard flag for mingw (CROSSCFLAGS) and `-ftree-vectorize` is non-standard for both, atleast for my Ubuntu. (I can check the difference for Ubuntu 20.04 if you think its of use).

**Comment by Tk-Glitch** [comment]
Was the issue reproduced since the `-pipe` flag removal? Else I'll close.

**Comment by Saancreed** [comment]
@Tk-Glitch I can consistently build Wine now with that error nowhere in sight, so feel free to close the issue.
