### ISSUE TITLE
NTSYNC5 broken once again on Fedora 40 after wine-staging commit cd2cce2

### ISSUE THREAD

**Issue by AllenTzul** [Frogging-Family/wine-tkg-git#1241]
NTSYNC5 is broken on Fedora 40 after commit cd2cce2 on wine-staging -> `eventfd_synchronization: Fix compile warnings.`

**Comment by Artewar67** [comment]
this should fix: https://github.com/Frogging-Family/wine-tkg-git/pull/1242
