### ISSUE TITLE
compilation error: A failure occurred in prepare().

### ISSUE THREAD

**Issue by Sprusrroot** [Frogging-Family/wine-tkg-git#1243]
There are no errors in the log(
![issue](https://github.com/user-attachments/assets/2d0ac187-b670-4ee1-887a-8dc562ba54cf)
[prepare.log](https://github.com/user-attachments/files/16617104/prepare.log)

**Comment by Artewar67** [comment]
This should fix: https://github.com/Frogging-Family/wine-tkg-git/commit/ecd65dc53a6b62de7a1a7704b8d1912d8d284ae2

**Comment by Sprusrroot** [comment]
Thanks, it helped!
But a new error has appeared: FAILED -- saving rejects to file dlls/winex11.drv/window.c.rej
[prepare.log](https://github.com/user-attachments/files/16622384/prepare.log)
