### ISSUE TITLE
Build fails while trying to apply staging hotfixes

### ISSUE THREAD

**Issue by Nocifer** [Frogging-Family/wine-tkg-git#125]
On latest master I get this error while applying the hotfixes:

`patch: **** Can't open patch file ../Tk-Glitch/wine-tkg-git/wine-tkg-git/valve_proton_fullscreen_hack-staging-938dddf.patch : No such file or directory`

But in the verification stage I get:

`valve_proton_fullscreen_hack-staging-938dddf.patch ... Passed`

and the file does exist in the build directory. So...

Btw I'm on Arch, in case that's relevant somehow.

**Comment by Nocifer** [comment]
I looked into this a bit more and found this in line 1312 of prepare.sh:

```
# Legacy Proton Fullscreen inline patching
	if [ "$_proton_rawinput" = "true" ] && [ "$_proton_fs_hack" = "true" ] && [ "$_use_staging" = "true" ] && ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 938dddf7df920396ac3b30a44768c1582d0c144f HEAD ); then [...]
```

In my case all these conditions are true so the script ends up entering this "Legacy" block, which then produces the error I encountered. Now, I won't presume to have (bothered to acquire) any real understanding of the script's logic, but I'd assume that, unless something has changed upstream in the two weeks since Wine 5.15 and this combination of patches (rawinput + fs_hack + staging) has been demoted to deprecated, me trying to build against the latest Staging sources shouldn't be hitting this roadblock, because the script should be bypassing this section and proceeding to the next one, i.e. the non-legacy "Proton Fullscreen patch" one.

I managed to hack around the error by switching the if flags but I'm sure this is not the best solution, if it can even be considered a solution at all. The good news is that at least the patch in question seems to have been properly applied in its current non-legacy implementation after I messed with the script, so at least this part of the build did not get borked.

**Comment by Nocifer** [comment]
Alright, I found the problem: between 5.15 and 5.16 I moved my build dir to a folder that contains a space in its path, and line 1316 is what breaks the script:

```patch ${_f} >> "$_where"/prepare.log << 'EOM'```

Adding quotes around the variable expansion fixes the issue:

```patch "${_f}" >> "$_where"/prepare.log << 'EOM'```

**Comment by Tk-Glitch** [comment]
Please let me know if there are remaining issues with proton-tkg. Thanks !
