### ISSUE TITLE
Can we not use `steamuser` as our username?

### ISSUE THREAD

**Issue by fxzxmicah** [Frogging-Family/wine-tkg-git#1253]
On the one hand, we have no connection with Steam, and on the other hand, hard coded username deprive users of their choice.
Additionally, this particularity may also bring some issues.

Downstream: https://github.com/bottlesdevs/wine/issues/73

**Comment by Artewar67** [comment]
There is a de-steamify-90 patch for proton that makes it function like normal wine including a normal username instead of the hardcoded `steamuser`

https://github.com/Frogging-Family/wine-tkg-git/blob/c4982f9ee170d505bb81a7654acfd2ca9adedcd6/wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-90.mypatch

**Comment by fxzxmicah** [comment]
Thank you. I just know that proton has made so many changes besides the username.

**Comment by StarTroop** [comment]
I suppose it's already been decided to use the aforementioned patch, but whatever the new username ends up being, could Bottles perhaps create a symlink to have the same data shared between a de-steamified user and the current "steamuser", so we could switch between Proton and other Wine versions without having to fix the user data path?

**Comment by fxzxmicah** [comment]
> I suppose it's already been decided to use the aforementioned patch, but whatever the new username ends up being, could Bottles perhaps create a symlink to have the same data shared between a de-steamified user and the current "steamuser", so we could switch between Proton and other Wine versions without having to fix the user data path?

If you don't use another wine version associated with proton, you can rename the folder yourself. If you want to use it, it's not too complicated to create a symlink yourself.
