### ISSUE TITLE
Can't Build wine-tkg-git with wine-valve-exp-bleeding Tree Patch Application Failed

### ISSUE THREAD

**Issue by tungstenpanda** [Frogging-Family/wine-tkg-git#1258]
Hey, I'm trying to build wine-tkg-git using the wine-valve-exp-bleeding tree, but when I run makepkg -si, it fails during the prepare step. I also tried compiling proton-tkg it fails too but keeps going until it tries to build Proton itself.

[prepare.log](https://dpaste.org/mRnDm#L5)

**Comment by Tk-Glitch** [comment]
Thanks! Will be fixed later today.
