### ISSUE TITLE
esync-unix-mainline.patch fails on mainline

### ISSUE THREAD

**Issue by AlexanderWKoenig** [Frogging-Family/wine-tkg-git#1261]
Building wine-tkg-fsync-git without staging patches fails to apply esync-unix-mainline.patch.
Tried building yesterday and today with the following error:

> cherry picking...
  -> Hotfixing...
  -> Applying esync-unix-mainline.patch
==> FEHLER: Patch application has failed. The error was logged to /mnt/ssd/git/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> FEHLER: Ein Fehler geschah in prepare().

Staging version builds fine thou.
[prepare.log](https://github.com/user-attachments/files/17061326/prepare.log)
[last_build_config.log](https://github.com/user-attachments/files/17061327/last_build_config.log)

**Comment by silverhikari** [comment]
the problem file in the patch is config.h.in
```
patching file include/config.h.in
Hunk #1 FAILED at 699.
Hunk #2 FAILED at 822.
Hunk #3 succeeded at 510 (offset -512 lines).
```

**Comment by AlexanderWKoenig** [comment]
@Tk-Glitch thank you, builds fine now :+1:

**Comment by fiercebrake** [comment]
Greetings!

I am getting a similar problem when trying to build with wine-9.22, any ideas?

`==> WARNING: Hotfix: Fix for high CPU usage with esync/fsync
  -> cherry picking...
  -> Hotfixing...
  -> Applying esync-unix-mainline.patch
==> ERROR: Patch application has failed. The error was logged to /home/fierce_brake/Downloads/linux-tkg/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
`
