### ISSUE TITLE
Can't build wine-staging v9.18 with protonify="true"

### ISSUE THREAD

**Issue by rankynbass** [Frogging-Family/wine-tkg-git#1265]
The build errors out with:
```
ccache gcc -m64 -c -o dlls/ntdll/unix/virtual.o ../wine-git/dlls/ntdll/unix/virtual.c -Idlls/ntdll -I../wine-git/dlls/ntdll \
  -Iinclude -I../wine-git/include -D__WINESRC__ -D_NTSYSTEM_ -D_ACRTIMP= -DWINBASEAPI= \
  -DWINE_UNIX_LIB -I/usr/include/x86_64-linux-gnu -Wall -pipe -fcf-protection=none \
  -fvisibility=hidden -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement \
  -Wempty-body -Wignored-qualifiers -Winit-self -Wlogical-op -Wno-packed-not-aligned -Wpointer-arith \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wno-misleading-indentation -fPIC -fasynchronous-unwind-tables -O2 -ftree-vectorize -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
../wine-git/dlls/ntdll/unix/virtual.c: In function ‘get_prot_str’:
../wine-git/dlls/ntdll/unix/virtual.c:1127:52: error: ‘VPROT_WRITTEN’ undeclared (first use in this function); did you mean ‘VPROT_WRITE’?
 1127 |     buffer[3] = (prot & VPROT_WRITECOPY) ? (prot & VPROT_WRITTEN ? 'w' : 'W')
      |                                                    ^~~~~~~~~~~~~
      |                                                    VPROT_WRITE
../wine-git/dlls/ntdll/unix/virtual.c:1127:52: note: each undeclared identifier is reported only once for each function it appears in
../wine-git/dlls/ntdll/unix/virtual.c: In function ‘try_map_free_area’:
../wine-git/dlls/ntdll/unix/virtual.c:1304:11: warning: unused variable ‘ptr’ [-Wunused-variable]
 1304 |     void *ptr;
      |           ^~~
../wine-git/dlls/ntdll/unix/virtual.c: In function ‘NtProtectVirtualMemory’:
../wine-git/dlls/ntdll/unix/virtual.c:5051:49: error: ‘VPROT_WRITTEN’ undeclared (first use in this function); did you mean ‘VPROT_WRITE’?
 5051 |                 set_page_vprot_bits(base, size, VPROT_WRITTEN, 0);
      |                                                 ^~~~~~~~~~~~~
      |                                                 VPROT_WRITE
make: *** [Makefile:115012: dlls/ntdll/unix/virtual.o] Error 1
```

It appears wine-staging commit [16dce52](https://github.com/wine-staging/wine-staging/commit/16dce521242b3f4a52cd2c8799ce6fe464fac83c) is the culprit.

**Comment by rankynbass** [comment]
Did a sanity check, and dropped the deleted ntdll-WRITECOPY patch files into the wine-tkg-userpatchs folder (renamed to *.mypatch), and it built successfully.

Files were: 
```
0001-ntdll-Trigger-write-watches-before-passing-userdata-.patch
0002-ntdll-Trigger-write-watches-on-the-info-pointer-in-S.patch
0003-ntdll-Install-signal-handlers-a-bit-earlier.patch
0004-ntdll-Properly-handle-PAGE_WRITECOPY-protection.-try.patch
0005-ntdll-Track-if-a-WRITECOPY-page-has-been-modified.patch
0007-ntdll-Report-unmodified-WRITECOPY-pages-as-shared.patch
0008-ntdll-Fallback-to-copy-pages-for-WRITECOPY.patch
0009-kernel32-tests-psapi-tests-Update-tests.patch
```

**Comment by Tk-Glitch** [comment]
@rankynbass Could you elaborate on what's the broken behavior? Thanks!

**Comment by rankynbass** [comment]
Sure. The problem I'm having is with Final Fantasy XIV, specifically when using [XIVLauncher.Core](https://github.com/goatcorp/XIVLauncher.Core).

I provide modified wine builds for the project. I've done builds for many wine-staging builds going back to 8.5 or so, and they've always worked just fine with the launcher to run Final Fantasy XIV. When I merged in the latest changes around the time 9.18 was released, it stopped building as mentioned in the first post. Adding the ntdll-WRITECOPY patches made it build, but FFXIV would not launch properly. It would launch to a black screen; the mouse cursor would change to the FFXIV cursor, but then nothing.

I was able to launch a number of simple games directly with my wine build without any problem. And when I used [my fork](https://github.com/rankynbass/XIVLauncher.Core) of XIVLauncher and disabled DXVK, the game did launch. I tried a number of different dxvk versions, and none of them worked. 9.17 works just fine.

I did test to make sure it wasn't one of our custom patches for XIVLauncher that was causing the issue. I did some clean builds from a freshly cloned version of this repo, and all of them showed the same behavior. I also tried downloading one of the artifacts from the github actions, and again, same problem.

I have come to the conclusion that it's not a problem with the build system or any of your patches, however. I think either it's a problem with wine-staging or XIVLauncher. I tried one of the [Kron4ek](https://github.com/Kron4ek/Wine-Builds) vanilla staging builds and had the same behavior with 9.18, while 9.17 worked just fine.

**Comment by SingleInfiniteLoop** [comment]
I've noticed the repeated message from DXVK too, it happens when I try to resize Overwatch window right after startup, or when launching the Epic Games Launcher because, apparently, it tries to maximize its window right after it has launched. As a workaround, I use `-OpenGl` argument for the Epic Games Launcher.

**Comment by rankynbass** [comment]
> I've noticed the repeated message from DXVK too, it happens when I try to resize Overwatch window right after startup, or when launching the Epic Games Launcher because, apparently, it tries to maximize its window right after it has launched. As a workaround, I use `-OpenGl` argument for the Epic Games Launcher.

Yeah, this is it. FFXIV launches at a config file defined resolution in a window, and then full-screens itself. If I set the resolution in the config file to match my monitor resolution, the game successfully launches. If it's a mismatch, it'll hang. Tested with tkg-staging, tkg-wine without staging, and Kron4ek build with staging. All behave the same way. Definitely a wine bug.
