### ISSUE TITLE
proton-tkg-steamclient-swap.patch application has failed, need rebase.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1275]
Arch Linux. 
[proton-tkg.log](https://github.com/user-attachments/files/17173957/proton-tkg.log)
[last_build_config.log](https://github.com/user-attachments/files/17173958/last_build_config.log)
[prepare.log](https://github.com/user-attachments/files/17173959/prepare.log)

![Screenshot From 2024-09-28 14-47-31](https://github.com/user-attachments/assets/3f1e4ddf-0de4-4fdf-9ee6-20f9158330a5)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/45fd0f78b3b54c23fb073140bf4dbeac7a469540
