### ISSUE TITLE
0034-bcrypt-Stop-compile-error-when-HAVE_GNUTLS_CIPHER_IN.patch fails for valve-exp-bleeding build

### ISSUE THREAD

**Issue by IdrisKalp** [Frogging-Family/wine-tkg-git#1276]
prepare.log

`[1m[34m  ->(B[m[1m Cleaning wine-staging source code tree...(B[m
HEAD şimdi şurada: cab93f47 Release v9.0
[1m[34m  ->(B[m[1m Cleaning wine source code tree...(B[m
HEAD şimdi şurada: f06ad045cab win32u: Correctly fill new foreground window TID in WM_ACTIVATEAPP.

Applying wine-staging patches...
hata: yama başarısız oldu: dlls/ntdll/loader.c:4274
hata: dlls/ntdll/loader.c: yama uygulanamıyor
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0001-windowscodecs-Avoid-implicit-cast-of-interface-point.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0021-d2d1-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0022-d3d11-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0023-d3d8-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0024-d3d9-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0025-ddraw-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0026-dwrite-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0027-msxml3-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0028-oleaut32-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0030-vbscript-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0031-include-Check-element-type-in-CONTAINING_RECORD-and-.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0032-wsdapi-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0033-ntdll-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0034-bcrypt-Stop-compile-error-when-HAVE_GNUTLS_CIPHER_IN.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0035-d3d10-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0036-d2d1-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0037-dxgi-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0038-msctf-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0039-rpcrt4-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Compiler_Warnings/0040-wbemdisp-Avoid-implicit-cast-of-interface-pointer.patch
/media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/gitapply.sh -d /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit < /media/pacman/tkg/wine-tkg-git/wine-tkg-git/src/wine-staging-git/staging/../patches/Staging/0001-ntdll-Print-a-warning-message-specifying-the-wine-st.patch
Failed to apply patch Staging/0001-ntdll-Print-a-warning-message-specifying-the-wine-st.patch`

**Comment by Tk-Glitch** [comment]
Wasn't the GNUTLS patch, but nonetheless, fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/bd376ef055b62257e1d7acf0823b8309331de938
