### ISSUE TITLE
Regression since 9.18 on nVidia cards

### ISSUE THREAD

**Issue by sfjuocekr** [Frogging-Family/wine-tkg-git#1284]
There was a regression that borked DXVK on nVidia cards with WINE versions 9.18 and higher: https://github.com/doitsujin/dxvk/issues/4329

The patch is found here: https://bugs.winehq.org/attachment.cgi?id=77218&action=diff&context=patch&collapsed=&headers=1&format=raw

**Comment by XZVB12** [comment]
Yes, I have referenced this fix in two of my commentaries, anyway.

**Comment by Artewar67** [comment]
this patch have been merged in upstream: https://gitlab.winehq.org/wine/wine/-/merge_requests/6633

**Comment by Tk-Glitch** [comment]
Closing
