### ISSUE TITLE
Add DXGI_FORMAT_R8G8B8A8_UNORM support on d2d_wic_render_target_init

### ISSUE THREAD

**Issue by LightSrc** [Frogging-Family/wine-tkg-git#1285]
Can we also get support for this?
https://github.com/GloriousEggroll/proton-ge-custom/pull/116

That fixes error in alt:V
`[21:45:12][Error] [TextLabel]: Failed to create D2D render target: 88982f80 Unknown error 0x88982F80`

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/6a7196a0acfc3696fce59cd2ad7753cf33131f19
