### ISSUE TITLE
wine-tkg : Fsync Support

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#13]
Hello Frogs,

According to customization.cfg, enable fsync support require Wine 4.7, Wine Staging 4.9 or newer. Badly, I can't build Wine TkG 5.1 because the `fsync-spincounts.patch` doesn't apply. There are may be an another errors but I don't have enough knowledge yet.

Thank you

**Comment by Tk-Glitch** [comment]
Oh yeah that patch will apply only on much newer wine versions. I'll define a lower bound.

**Comment by Tk-Glitch** [comment]
By the way, in case it was unclear, the spincounts patchset is an optional addition to the main fsync patchset and isn't a prerequisite to make use of fsync itself.

**Comment by IroAlexis** [comment]
Okay and If I understand the spincounts patchset is just applied when we build a staging version higher than 8b2fd05

**Comment by Tk-Glitch** [comment]
Indeed 👌
