### ISSUE TITLE
Patch Application has failed

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#131]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5192391/prepare.log)

PS: I wanna say thank you over and over again for your hard work :)

**Comment by Tk-Glitch** [comment]
Should be fixed after https://github.com/Frogging-Family/wine-tkg-git/commit/97c9927813c869e88f0911ce8572785163e43325 & https://github.com/Frogging-Family/wine-tkg-git/commit/1a8998fc53149260be2c2e82b7f4a92ef804da9f

**Comment by ninelore** [comment]
fixed
