### ISSUE TITLE
wine-tkg fails to build wine-9.21 when patching server/named_pipe.c

### ISSUE THREAD

**Issue by silverhikari** [Frogging-Family/wine-tkg-git#1311]
wine-tkg-git version: latest master 29cbd84
wine-version: wine-9.21
preset selected: default-tkg(disabled staging in customization.cfg) via makepkg

issue: wine-tkg fails to build wine-9.21 when patching server/named_pipe.c

from reading the .orig and .reg it seems to be caused by the removal of  `NULL,                                    /* get_esync_fd */` in the original file compared to the patch

named_pipe.c.org:

```
    add_queue,                               /* add_queue */
    remove_queue,                            /* remove_queue */
    default_fd_signaled,                     /* signaled */
    no_satisfied,                            /* satisfied */
    no_signal,                               /* signal */
```

named_pipe.c.rej:

```
     add_queue,                               /* add_queue */
     remove_queue,                            /* remove_queue */
     default_fd_signaled,                     /* signaled */
     NULL,                                    /* get_esync_fd */
+    NULL,                                    /* get_fsync_idx */     
     no_satisfied,                            /* satisfied */
     no_signal,                               /* signal */
```
though that is more of a guess as i don't understand patching to well

**Comment by Kerrung** [comment]
@silverhikari Hi! We need all logs from wine-tkg directory.

**Comment by silverhikari** [comment]
https://paste.ee/p/TbQQZ

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/4583dc43b65f2680d77dfb24ca6395806c404daa
