### ISSUE TITLE
Need rebase

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1318]
[proton-tkg.log](https://github.com/user-attachments/files/17792097/proton-tkg.log)
[last_build_config.log](https://github.com/user-attachments/files/17792099/last_build_config.log)
[prepare.log](https://github.com/user-attachments/files/17792100/prepare.log)
![image](https://github.com/user-attachments/assets/38864e76-0dca-4802-8e23-5e16f7dcabcf)

**Comment by imbovich** [comment]
I have the same problem
