### ISSUE TITLE
proton-tkg: (arch) dependency check is missing one package

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#132]
after a build error i figured out that `python-fonttools` wasnt installed. I think this should be included in the dependdency check o the proton-tkg.sh

**Comment by nutta-git** [comment]
`sudo pacman -S python-fonttools`

**Comment by ninelore** [comment]
> `sudo pacman -S python-fonttools`

What are you trying to tell me with this comment?
My Question is why this isn't included in the automatic dependency resolution.

**Comment by nutta-git** [comment]
I read your issue wrong, sorry. 
Marked the original comment as off-topic
