### ISSUE TITLE
Baldur's Gate 3 have not launching with Proton-tkg anymore.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1322]
I use Arch Linux, btw. All works fine with vanilla Proton Experimental, but with TKG 5a279bff0c796254d1670228581891569b774ece I see only "Running install script" for endless time. And also I have tried to delete prefix at all, but have not changes. And also Steam doesn't give any information in the terminal while launching the game. It seems like some kind of regressions because it had worked fine for me at the past with TKG with the same cfg.
[proton-tkg.log](https://github.com/user-attachments/files/17807241/proton-tkg.log)
[last_build_config.log](https://github.com/user-attachments/files/17807242/last_build_config.log)
[prepare.log](https://github.com/user-attachments/files/17807243/prepare.log)
![image](https://github.com/user-attachments/assets/82e60854-fc88-48b1-8a40-99f36085d3a7)

**Comment by Artewar67** [comment]
Found out it was my mistake. when I rebased the patches I made the error ntsync5-staging.patch

**Comment by Kerrung** [comment]
@Artewar67 I have tested  with 17b6e8af983b6ccda9040460badfd3565ade1a78, but it still have not worked, no changes.

**Comment by Kerrung** [comment]
@Artewar67 now works fine with FSYNC or with NTSYNC too since cadda7ef00fc9db5b90d4cc376a151766421d46a. Thank you!
