### ISSUE TITLE
non-makepkg-build on Fedora 41: ntsync5-staging-protonify.patch fails to apply

### ISSUE THREAD

**Issue by AllenTzul** [Frogging-Family/wine-tkg-git#1323]
Based on staging rebase against **67c1c3c**, ntsync5-staging-protonify.patch fails to apply with the following error:

```
ntsync5-staging-protonify.patch -- ( Using ntsync patchset )
Hunk #24 FAILED at 2418.
1 out of 31 hunks FAILED -- saving rejects to file dlls/ntdll/unix/sync.c.rej
```

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/1e3fa6a2e9ac35d64b428c224305920cab76fb21
