### ISSUE TITLE
Compile stuck on generating default prefix

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#1329]
Tried to compile the latest master with wine master and experimental_90 and it's been stuck on generating default prefix for hours.

Noticed the same issue with the github workflow build too, seems to be timing out

**Comment by damachine** [comment]
hi. i can confirm. stuck on generating default prefix. thx

**Comment by shaumux** [comment]
Resolving this, since it seems to be fixed
