### ISSUE TITLE
fails on hotfix "error: could not revert 3885b32bc8. 

### ISSUE THREAD

**Issue by nasedase** [Frogging-Family/wine-tkg-git#133]
I tried applying the fix here](https://github.com/Frogging-Family/wine-tkg-git/commit/a4e7388240c909f77e5b7d005f1fd33e29674bf0) 
didn't resolve my issue. Here's the terminal output: `./proton-tkg.sh 

 ______              __                      __   __
|   __ \.----.-----.|  |_.-----.-----.______|  |_|  |--.-----.
|    __/|   _|  _  ||   _|  _  |     |______|   _|    <|  _  |
|___|   |__| |_____||____|_____|__|__|      |____|__|__|___  |
                                                       |_____|

Also known as "Some kind of build wrapper for wine-tkg-git"

 -> Non-makepkg build script will be used.

 ->        .---.`               `.---.
 ->     `/syhhhyso-           -osyhhhys/`
 ->    .syNMdhNNhss/``.---.``/sshNNhdMNys.
 ->    +sdMh.`+MNsssssssssssssssNM+`.hMds+
 ->    :syNNdhNNhssssssssssssssshNNhdNNys:
 ->     /ssyhhhysssssssssssssssssyhhhyss/
 ->     .ossssssssssssssssssssssssssssso.
 ->    :sssssssssssssssssssssssssssssssss:
 ->   /sssssssssssssssssssssssssssssssssss/
 ->  :sssssssssssssoosssssssoosssssssssssss:
 ->  osssssssssssssoosssssssoossssssssssssso
 ->  osssssssssssyyyyhhhhhhhyyyyssssssssssso
 ->  /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
 ->   smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
 ->    /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
 ->     `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
 ->        `-+shdNNNNNNNNNNNNNNNdhs+-`
 ->              `.-:///////:-.`
 -> 
 -> #################################################################
 -> 
 -> You can configure your wine build flavour (right now for example)
 -> by editing the proton-tkg.cfg file in the proton-tkg dir,
 -> or by creating a custom config, for example
 -> ~/.config/frogminer/proton-tkg.cfg (path set in config file)
 -> to override some or all of its values.
 -> 
 -> Current path is '/home/eric/PKGBUILDS/wine-tkg-git/wine-tkg-git'
 -> 
 -> If you are rebuilding using the same configuration, you may want
 -> to delete/move previously built package if in the same dir.
 -> 
 -> ###################################TkG##########was##########here
When you are ready, press enter to continue.
 -> Using staging patchset
 -> Using fsync patchset
 -> Using pba patchset
 -> Installing to /home/eric/.steam/root/compatibilitytools.d/proton_tkg
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 -> Changing wine HEAD to the wine-staging base commit...
Note: switching to '0ead40dc9b87ebbd74ad6ebda0182365ab2efde3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0ead40dc9b winemac.drv: Don't fail GPU detection if some IOKit properties are missing.
 -> Hotfixing...
error: could not revert 3885b32bc8... conhost: Update tty output in IOCTL_CONDRV_ACTIVATE.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/eric/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
`

**Comment by Tk-Glitch** [comment]
Should be fixed since https://github.com/Frogging-Family/wine-tkg-git/commit/a0c1e99fd4219afff79712dfc4063aed4b4bce0e
