### ISSUE TITLE
Latest TKG (ESync Fsync Staging) Update Broke Xbox Controller Mappings

### ISSUE THREAD

**Issue by mister-x123** [Frogging-Family/wine-tkg-git#134]
As the title says.
I didn’t know where else to post this.
I have verified it because in Steam/Proton the mappings are normal and proper
and it only happened after the latest update to the package I received today from the Chaotic-AUR repo.
AND also when using the normal wine version (not from Chaotic-AUR repo), the mappings are all normal and same as Lutris 5.7.9 the mappings are all normal.

Please fix

**Comment by IroAlexis** [comment]
Hello can you precise, what is the package you are using on Chaotic AUR ? :thinking:

**Comment by mister-x123** [comment]
wine-tkg-staging-fsync-vkd3d-git
Version: 5.16.r19.g88e6b6c6-298

**Comment by Tk-Glitch** [comment]
And 5.16r18 didn't exhibit the issue?

**Comment by ebiroud** [comment]
Yep, 5.16.r18 works without any issues related to this.

**Comment by Valmar33** [comment]
I'm busy trying to bisect what mainline Wine commit broke this. :|

**Comment by Valmar33** [comment]
I'm getting close ~ a few steps to get...

**Comment by Valmar33** [comment]
This is the first bad commit:

https://github.com/wine-mirror/wine/commit/e9090e1c903578b30118ce9559c1824361abc6da

Last good commit should be:

https://github.com/wine-mirror/wine/commit/ec02224941eedf16b8b043964519f6363b5ce21f

**Comment by Valmar33** [comment]
Bug report:

https://bugs.winehq.org/show_bug.cgi?id=49815

**Comment by Tk-Glitch** [comment]
The offending commit and related changes are now reverted in the hotfixer until it gets fixed upstream

**Comment by mixalis1987** [comment]
Yep xbox controller no longer works. using wine-tkg-staging-fsync-vkd3d-git 5.16.r22 from chaotic-aur. Do we need to do something, or just wait for new release to come out?

**Comment by Tk-Glitch** [comment]
Marking fixed on our end

**Comment by Tk-Glitch** [comment]
@Valmar33 Did the revert actually fix anything?

**Comment by Valmar33** [comment]
Ah ~ yes, it did!

Now that I remember... I did my bisecting with hotfix reverts enabled, so that made the upstream bug report useless...

But, it seems to have fixed the issue with regards to the revert rollercoaster, so that's what matters, I suppose.
