### ISSUE TITLE
5.16.r19 broke the Battle.net app

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#135]
Could be related to #134 

Im working on debug logs atm

But Version used before was r6

**Comment by ninelore** [comment]
[lutrisdebug-20200911-1.txt](https://github.com/Frogging-Family/wine-tkg-git/files/5210099/lutrisdebug-20200911-1.txt)

**Comment by Tk-Glitch** [comment]
Please try again on current head

**Comment by Tk-Glitch** [comment]
![Screenshot_20200912_160953](https://user-images.githubusercontent.com/741977/92997297-8357b080-f512-11ea-8397-46b13415c3ca.png)
Looking fine on my end now

**Comment by ninelore** [comment]
works fine for me nwo too. Whatever it was, thanks anyway ;)

**Comment by Tk-Glitch** [comment]
It was indeed linked to https://github.com/Frogging-Family/wine-tkg-git/issues/134
