### ISSUE TITLE
Fails to Compile Wine64

### ISSUE THREAD

**Issue by DeathTBO** [Frogging-Family/wine-tkg-git#137]
I'm running Fedora 33 and a 5700xt with Mesa drivers. I do have glibc-2.32, as well as all of the dependencies listed here https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies

It runs through all of the hotfixes, and then starts to make. After ~5 seconds it stops and cleans up. Prepare.log last mentions Vulkan.
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5212136/prepare.log)

I captured the output of the configure and make steps:

[Configure.log](https://github.com/Frogging-Family/wine-tkg-git/files/5212142/Configure.log)
[Make.log](https://github.com/Frogging-Family/wine-tkg-git/files/5212143/Make.log)

Any ideas?

**Comment by Tk-Glitch** [comment]
The prepare.log and Configure.log look clean. The vulkan part is outputting expected strings.

I have found the following in your Make.log though:
```
gcc: error: Builders/build/wine-tkg-git/wine-tkg-git/wine-tkg-staging-fsync-vkd3d-git-5.16.r22.gd34ff186/lib64/wine": No such file or directory
make[1]: *** [Makefile:213: main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Which indicates a truncation of the full path (`/home/deathtbo/Game Builders/build/wine-tkg-git/wine-tkg-git/wine-tkg-staging-fsync-vkd3d-git-5.16.r22.gd34ff186/`). It might be an unprotected variable on my end somewhere. Getting rid of that space in your path should fix it for now.

**Comment by DeathTBO** [comment]
Oh shoot, that was an old directory anyway. That fixed it, thanks a bunch!
