### ISSUE TITLE
error: could not revert 947fe11e02... include: Use ioctl access bits for console driver ioctls.

### ISSUE THREAD

**Issue by veganvelociraptor** [Frogging-Family/wine-tkg-git#138]
-> Using staging patchset
 -> Using fsync patchset
 -> Using pba patchset
 -> Installing to /home/vv/.steam/root/compatibilitytools.d/proton_tkg
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 -> Changing wine HEAD to the wine-staging base commit...
Note: switching to '01bacebba418bf6f58a644b1aab41be215bd200a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 01bacebba4 Release 5.17.
 -> Hotfixing...
error: could not revert 947fe11e02... include: Use ioctl access bits for console driver ioctls.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/vv/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

**Comment by adonisd** [comment]
same exact error for me. wine-staging just pushed an update. So am thinking some incompatibility with the script

**Comment by Tk-Glitch** [comment]
The update is almost ready

**Comment by Tk-Glitch** [comment]
Should be fixed with 7a7abb70dea175393c727ed80e65dc1dc6544ae0...2e2d1ad4c821ca63f6eaea7e6dfa6a51d71bac6b

**Comment by adonisd** [comment]
> Should be fixed with [7a7abb7...2e2d1ad](https://github.com/Frogging-Family/wine-tkg-git/compare/7a7abb70dea175393c727ed80e65dc1dc6544ae0...2e2d1ad4c821ca63f6eaea7e6dfa6a51d71bac6b)

yeah working perfectly fine now. Thanks!

**Comment by veganvelociraptor** [comment]
Yep, working. Thanks!
