### ISSUE TITLE
Worse performance with the proton-tkg?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/wine-tkg-git#139]
Hello there,
i've got a problem with the tkg proton fork. With the tkg wine everything works how i would it expect to work. However in every game i play i have performance hits compared to a proton ge fork. For example in the game "The Elder Scrolls IV: Oblivion" or "Gothic 3". In both games i have a smoother experience when using the latest ge custom fork. Currently it's Proton 5.9-GE-ST. But i think as i switched to the wine tkg the experience got smoother without using the proton tkg version. Is this just my imagination or could this be true? And what could be the reason for those performance hits in my games i play with tkg proton? I'm thankful to every respond. If you need some additional information, feel free to require them in this issue thread. Bye :-)

**Comment by flightlessmango** [comment]
I have not noticed a performance hit when using proton-tkg. Use something like MangoHud to remove the human element and verify the potential difference

**Comment by Axilot** [comment]
No, the hits are very noticeable. I have high drops and way less smoother experience. I'm now downloading the recent proton tkg version maybe this version will run better. If not i'll respond with a graphical mongohud log.

**Comment by Axilot** [comment]
Nope cant even record it cause the log cant finish before the game crashes

**Comment by Tk-Glitch** [comment]
The only things that could affect perf negatively here would be either upstream regressions (either in wine or dxvk), Proton's FS hack (which GE's build lacks), or frogged up caches from different dxvk versions being used.

With zero logs, numbers, or information on the machine used it's not really helpful though, so tagging as question for now.

**Comment by Axilot** [comment]
Do i have to install some additional packages for your proton build to work properly?

**Comment by Axilot** [comment]
If i change to your proton build the first thing to happen is wine changing some configurations in the compatdata directory. I also noticed in game mods like "Enderal" (A total conversion of Skyrim) the loading times of all files are much slower. I realised this to happen in some older proton ge builds playing this game. But in the example of Oblivion the game seems to crash within 10-20 seconds. And in this time the overall performance is really bad.

**Comment by Axilot** [comment]
Now some specs to my mashine (it's my old one pretty bad i know but im gonna upgrade when big navi releases^^)

Graphics Card: Nvidia GTX 1050 Ti (Using the dkms-nvidia propietary driver)
CPU: Intel Core i5-7500
RAM: 8GB ddr3 ram
And i have a slow hard disk drive on this setup haha

And i've installed the linux-zen kernel

**Comment by Axilot** [comment]
And how would i create some logs where i can see what kind of issues occure when playing the game and especially the crash at the end?

**Comment by Axilot** [comment]
Okay, after testing the game "The Elder Scrolls V: Skyrim Special Edition" i realised that this game runs pretty well without any noticeable issues. So these crashes seem to be happening in "very old" and with some mods of games. So the proton itself should work fine but not in the games mentioned in my thread. I'll be adding some more logs of the games in the future.

**Comment by Axilot** [comment]
https://flightlessmango.com/games/22315/logs/909

Here is the comparison in Skyrim. This game runs pretty much fine on both proton forks. However i realized that the input lag of my keyboard and my mouse is higher on the tkg version. I can tell that because this game locks the fps at 60 and uses vsync.

**Comment by Axilot** [comment]
Stupid me! Everything fixed, i had some missing packages. I was interupting your time. Proton tkg just works fine :D And it runs much better than ge does.

**Comment by Tk-Glitch** [comment]
Thanks for reporting back, I was still scratching my head about this!
