### ISSUE TITLE
Path of Exile broken

### ISSUE THREAD

**Issue by vedrafal** [Frogging-Family/wine-tkg-git#140]
Hi, 
after the new PoE patch 3.11.2 the game no longer runs. I have tried a couple older builds with the same result. 
The only build that is working atm is this one linked below, I am not sure if that helps at all in finding the problem:

https://github.com/stevenlafl/Proton/releases/tag/proton-5.0-7-alyx-2

**Comment by Tk-Glitch** [comment]
I cannot reproduce your issue on my end. Could you provide a log?
![Screenshot_20200913_202617](https://user-images.githubusercontent.com/741977/93025618-82507d00-f5ff-11ea-984e-b77f19f21806.png)

**Comment by PedroHLC** [comment]
@Tk-Glitch what version is your proton for this screenshot?
Mine is also broken after this 22Gb... Tried with at least three proton versions.

Here's the log with c44db537, clean compatdata: [poe.log](https://github.com/Frogging-Family/wine-tkg-git/files/5215047/poe.log)

**Comment by Tk-Glitch** [comment]
It was actually the 5.17 based release available here. However I have noticed this:
```
00e0:err:steamclient:create_win_interface Don't recognize interface name: SteamUser021
```
I'm not using the steam client (because it's been a huge pile of garbage for years), I'm using the standalone. This error indicates a specific error with steam. Proton's lsteamclent lib, even. Doesn't look like my bug.

**Comment by PedroHLC** [comment]
Ok, linking official issue for following up: https://github.com/ValveSoftware/Proton/issues/58

**Comment by thorsten-passfeld** [comment]
This may be a tiny bit off-topic, but how is the performance with Proton-TKG in Path of Exile compared to the official Proton version that currently works? Is there a noticeable difference?

It's always such a bummer for me that there are so many freezes when there's a lot going on (mostly lots of particles and mobs). I have a 3900X and a 1080Ti with 32GB DDR4 @ 3600 CL16 and I'm using Vulkan with pretty medium to low graphics settings, which would probably not encounter this issue under Windows. I'm just wondering if there's anything we can do to analyse what's happening when it freezes and what causes it. The freezes can also be experienced by Windows users, but usually they have way worse hardware.

**Comment by Tk-Glitch** [comment]
I have not tried Nvidia on the vulkan renderer (though it was very good with DXVK/d3d11 after a bit of caching), but on AMD I have had a pretty flawless experience with my 5700XT/8086K/32GB 4000C16 machine. No freeze, no stutter, mostly staying at or near my 144fps cap with max settings except for GI set to high @ 1440p. I don't know if the last patch has fixed the steam client (it might), but I'd most definitely give the standalone one a try. The steam client has been underperforming and stuttering for years, and updates would take about 20x longer with it. It was also larger by a couple GB's unjustifiably.

**Comment by thorsten-passfeld** [comment]
Actually, you should probably give Steam another try after the latest update. They have completely overhauled how they manage their files, especially addressing the problem you stated about updates via Steam! It's pretty interesting that the experience seems to be much better on AMD. I mean I mostly get 140-147 FPS too, but as soon as many particles are involved, the game has very frequent frame drops from my experience. It was a lot better when they first introduced their Vulkan renderer. I'm also running @ 1440p. I might consider switching over to the standalone client if the experience would somehow be better there. Is it hard to set up correctly? I'd imagine I would need to install it via Lutris.

**Comment by 9ngol** [comment]
> Actually, you should probably give Steam another try after the latest update. They have completely overhauled how they manage their files, especially addressing the problem you stated about updates via Steam! It's pretty interesting that the experience seems to be much better on AMD. I mean I mostly get 140-147 FPS too, but as soon as many particles are involved, the game has very frequent frame drops from my experience. It was a lot better when they first introduced their Vulkan renderer. I'm also running @ 1440p. I might consider switching over to the standalone client if the experience would somehow be better there. Is it hard to set up correctly? I'd imagine I would need to install it via Lutris.
> 
> Edit: Is it possible for you to include the patch that made HL: Alyx work in a (temporary) Proton-TKG version? That patch will be included in default Proton as well soon if I remember correctly from the Proton issue for Path of Exile. [ValveSoftware/Proton#58 (comment)](https://github.com/ValveSoftware/Proton/issues/58#issuecomment-691095466)

standalone works fine. Install is easy just download from there site installer set WINEPREFIX and launch installer with wine. 
Only problem i had with Standalone it didn't launch first because it needs dxvk but i was too lazy to install it so just changed in config file ~/Documents/My Games/Path of Exile/production_Config.ini
renderer_type=Vulkan 
and it launched directly to vulkan.
for my self i just made simple launch sh file 
`#!/bin/bash
cd /opt/POE/drive_c/g/poe/
export WINEPREFIX=/opt/POE/
export WINEFSYNC=1
gamemoderun /opt/wine/wine-tkg-staging-fsync-vkd3d-git-5.16.r11.g7a5a98a1/bin/wine PathOfExile_x64.exe --nologo`

**Comment by vedrafal** [comment]
Sorry guys had a couple of busy days. 
As I can see this is a steam related issue, thank you for your help I will switch over to the standalone client for the time beeing. 

I have been running tkg-proton with PoE with Nvidia on Steam flawlessly. Had some stutters here and there if there are too many effects on the screen with d3d11 after switching to vulkan everything was running smooth in FullHD and even in 1440p. 

Had problems with the normal proton versions and eggrolls mostly stutters and small freezes.

Had to tweak the startup setting a bit: DXVK_USE_PIPECOMPILER=1 ENABLE_VKBASALT=1 WINEF-YNC=1 %command% --waitforpreload --nologo -gc 2 

Running this on an Ryzen 7 1700x  / 16GB/ GTX 1080 .

Had no problems at all till the new patch.

**Comment by Tk-Glitch** [comment]
I have added the parts of PR 3886 that are interesting us here, fixing the issue for the steam client.
