### ISSUE TITLE
Having hard time to find correct fsync and esync patches for recent wines

### ISSUE THREAD

**Issue by arabcian** [Frogging-Family/wine-tkg-git#142]
Hello i tried almost all of the fsync patches in the repo with wine-staging 5.15 but none could be applied. How to find the correct patch and wine version to apply patches?

**Comment by ionenwks** [comment]
From my understanding these can't be used on their own since wine/wine-staging-5.10, same issue as https://github.com/Tk-Glitch/PKGBUILDS/issues/570

**Comment by SveSop** [comment]
Wine-staging has not been able to fix the esync patchset that fsync relies upon yet.
[https://github.com/wine-staging/wine-staging/blob/master/patches/eventfd_synchronization/definition#L9](https://github.com/wine-staging/wine-staging/blob/master/patches/eventfd_synchronization/definition#L9)

The patchnotes for wine-staging also sais this:
[https://www.winehq.org/pipermail/wine-devel/2020-September/173549.html](https://www.winehq.org/pipermail/wine-devel/2020-September/173549.html)

> NOTE: Currently the esync patchset has been disabled until it can be 
> rebased.

So it is somewhat of a "project on hold" even if Tk is trying his best to do hotfix-reverts to enable this :)

**Comment by Tk-Glitch** [comment]
Until Zebediah pushes his proper rebase, the changes required to get esync/fsync back on current wine versions are pretty large (basically reverting the huge PE ntdll refactor, some conflicting server changes and a couple others + backports). The wine/proton-tkg build script offers doing it for you, and it's done that way due to how often and deep it can get destroyed upstream (more or less daily for the past few months). Initially the idea was that it was all very temporary and wouldn't grow too much, but hey, here we are now months later.

**Comment by SveSop** [comment]
> Initially the idea was that it was all very temporary and wouldn't grow too much, but hey, here we are now months later.

Yeah.. I guess there is a balance between hotfix/reverting too much to really be of use too. I mean, you could revert(hotfix) all commits from 5.17 -> 5.7 and call it 5.17, but it would not be that useful in the end. The ntdll PE work that has been done upstream from 5.10'ish -> 5.12 is huge, not to mention lots changes after that (although i guess the ntdll work is mostly done).

I can only imagine how much work it is keeping all builds <-> what hotfix works with what patches (config options) atm for you, so there is no envy there to say the least hehe.

I also see there has not been that much movement on the proton git either (2 months?), but there might be some branches or whatnot i am unaware of tho? The proton-next branch had its last commit jul 15...

**Comment by Tk-Glitch** [comment]
The patches are now rebased and staging is back in staging. Closing.
