### ISSUE TITLE
Doesn't Create A Proton Version in Compatabilitytools.d

### ISSUE THREAD

**Issue by fluffy-coder** [Frogging-Family/wine-tkg-git#148]
This is the error:
```
configure: error: gstreamer-1.0 base plugins 32-bit development files not found, GStreamer won't be supported.
This is an error since --with-gstreamer was requested.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real    6m22.465s
user    66m39.293s
sys     5m40.554s
```

Doesn't get past this point, don't know if it should. I have gstreamer installed. I am on Manjaro 20.1. There is no proton-tkg in compatibilitytools.d.

**Comment by nutta-git** [comment]
I maybe wrong, but you need to install  `gstreamer` `lib32-gstreamer `
but to install `lib32-gstreamer` you need to enable the multilib repos for Manjaro.

**Comment by Tk-Glitch** [comment]
I'd run `makepkg -si` first (in the same folder as `proton-tkg.sh`) to grab all dependencies. Once that's done you can cancel and run `proton-tkg.sh` again.

**Comment by gardotd426** [comment]
@nutta-git Manjaro enables multilib by default.

And TKG is right @fluffy-coder, always run `makepkg -si` (or just `-s` if you don't want to install after building) to make sure you have required dependencies whenever trying to build anything from TKG, it just makes things easier. The PKGBUILD doesn't know to pull in dependencies if you don't pass `-s`

**Comment by Tk-Glitch** [comment]
I'll consider this as fixed. Closing.
