### ISSUE TITLE
Spurious output when applying fsync-staging-no_alloc_handle.patch

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#15]
When the script is applying fsync-staging-no_alloc_handle.patch there is a spurous git am help text after the first hunk is patched.
I'm not sure if the patch was applyied fully or not

  -> Applying fsync-staging-no_alloc_handle.patch
patching file server/fsync.c
Hunk #1 succeeded at 165 (offset 29 lines).
uso: git merge-base [-a | --all] <commit> <commit>...
  oppure: git merge-base [-a | --all] --octopus <commit>...
  oppure: git merge-base --independent <commit>...
  oppure: git merge-base --is-ancestor <commit> <commit>
  oppure: git merge-base --fork-point <riferimento> [<commit>]

    -a, --all             manda in output tutti gli antenati comuni
    --octopus             trova gli antenati per un singolo merge a n vie
    --independent         elenca le revisioni non raggiungibili dalle altre
    --is-ancestor         il primo argomento è antenato dell'altro?
    --fork-point          trova il punto di fork di <commit> dal registro dei riferimenti di <riferimento>

**Comment by llde** [comment]
That was fast. Confirm Fixed

**Comment by Tk-Glitch** [comment]
Great! Thanks :)
