### ISSUE TITLE
Xbox One Controller Bindings Messed Up

### ISSUE THREAD

**Issue by mister-x123** [Frogging-Family/wine-tkg-git#150]
As the title says. Since the 5.17 update the default Xbox One controller bindings are all messed up.
Prior to that, on 5.16 the default bindings were normal.
This issue has apparently been fixed already (https://github.com/Frogging-Family/wine-tkg-git/issues/134) but my bindings are still all messed up.

**Comment by Tk-Glitch** [comment]
Did you accept the hotfixes? The revert is currently bound to them.

**Comment by mister-x123** [comment]
Yeah I did all of them

**Comment by rsvensson** [comment]
I'll also add that I have the same issue, or rather the controller doesn't seem to work at all.
I'm using an 8bitdo SN30 Pro+ in Xinput mode with `proton-tkg 5.18.r11.g19466905-1` from chaotic-aur. The controller is working fine with other versions of Proton and the latest stable Wine-Staging.

I also tried to manually compile the same revision without any success.

**Comment by shaumux** [comment]
I tried the latest official release 5.21 and tried to build my own using docker on a Gentoo system, Xbox controller isn't detected in games.
Tried Witcher 3, and DmC5 to test the controller

**Comment by Tk-Glitch** [comment]
Can you please try again with current head?

**Comment by shaumux** [comment]
Seems to be working again, built `5.21.r4.gcd3ee9b` and `5.21.r7.g7bdc1d6b` works on both
Thanks for the great work

**Comment by Tk-Glitch** [comment]
It should be resolved now, closing.
