### ISSUE TITLE
Fedora 32 compiling fail to aply hotfixes

### ISSUE THREAD

**Issue by tuxtergames** [Frogging-Family/wine-tkg-git#153]
Hi folks,

I've been trying to compile wine-tkg on Fedora 32 a few times and I have the same message everytime, like the image bellow, I've installed all dependencies according wiki page, I a newbie, than please have some patience, tks for all....
![image](https://user-images.githubusercontent.com/26095484/94351433-c5aee080-002e-11eb-958a-f8b15b924b4d.png)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5287408/prepare.log)

I'll left log and terminal output...

[prepare.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/5287409/prepare.tar.gz)
[terminal output.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/5287410/terminal.output.tar.gz)

**Comment by h3o66** [comment]
Can you please check if you have `patch` installed ?
This seems to be missing accoring to the line before the error,

**Comment by tuxtergames** [comment]
> Can you please check if you have `patch` installed ?
> This seems to be missing accoring to the line before the error,

Man you're my hero, miss patch, now I got another error, with 32bit development librarys, I try to install acordind a wiki but got and error iwth all librarys, heres the final output

  display.o expr.o gdbproxy.o info.o memory.o source.o stack.o symbol.o tgt_active.o tgt_minidump.o \
  tgt_module.o types.o winedbg.o dbg.tab.o debug.yy.o winedbg.res -lcomdlg32 -lshell32 -lcomctl32 \
  -luser32 -lgdi32 -ldbghelp -ladvapi32 ../../libs/port/libwine_port.a -ldl \
  -Wl,-delayload,comdlg32.dll -Wl,-delayload,shell32.dll -Wl,-delayload,comctl32.dll \
  -Wl,-delayload,user32.dll -Wl,-delayload,gdi32.dll -Wl,-O1,--sort-common,--as-needed
make[1]: Leaving directory '/home/tuxter/wine-tkg-git/wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/programs/winedbg'
Wine build complete.
 -> Building Wine-32...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... ccache gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether ccache gcc accepts -g... yes
checking for ccache gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether ccache g++ accepts -g... yes
checking for cpp... cpp
checking for ld... ld
checking whether ccache gcc -m32 works... no
configure: error: Cannot build a 32-bit program, you need to install 32-bit development libraries.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real    4m31,737s
user    45m58,054s
sys     5m0,552s

 dom set 27 05:13 tuxter@fedora:wine-tkg-git$

**Comment by h3o66** [comment]
Maybe have a look at this:
https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies
There is a section for fedora.

**Comment by tuxtergames** [comment]
> Maybe have a look at this:
> https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies
> There is a section for fedora.

Hi @h3o66 tks again, I tought if only install 64bit libraries wike-tkg will compile, without problem, after install 32bit library solve here, tks for all, closing topic......
