### ISSUE TITLE
proton-rawinput.patch failed

### ISSUE THREAD

**Issue by hp-pepster** [Frogging-Family/wine-tkg-git#16]
Hi,

thanks for your efforts. Your build fails - at least on my machine - with the latest wine on manjaro:
```console
/tmp/wine-tkg-git/proton-tkg/$ ./proton-tkg.sh
[…]
-> Applying proton-rawinput.patch
[…]
Hunk #4 succeeded at 3386 (offset 3 lines).
Hunk #5 succeeded at 3394 (offset 3 lines).
patching file dlls/user32/rawinput.c
Hunk #1 FAILED at 43.
Hunk #2 FAILED at 138.
Hunk #3 FAILED at 194.
Hunk #4 FAILED at 219.
Hunk #5 succeeded at 438 with fuzz 1 (offset 23 lines).
Hunk #6 succeeded at 523 (offset 21 lines).
4 out of 6 hunks FAILED -- saving rejects to file dlls/user32/rawinput.c.rej
```
[rawinput.c.rej.log](https://github.com/Frogging-Family/wine-tkg-git/files/4464240/rawinput.c.rej.log)

Removing lines 1145-1149 in wine-tkg-scripts/prepare.sh aka don't applying the proton-rawinput.patch solves the problem.

Please tell me if you need my sys-spec or something else.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/9207e49732062fe17c6bec284e72e18ee7ff0e12
