### ISSUE TITLE
MHW: Performance issues after last patch using PROTON_USE_SECCOMP=1 to avoid the pagefault

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [Frogging-Family/wine-tkg-git#160]
As title indicates I'm getting choppy performance in game. It hiccups every second with no reason for doing so, the game barely reaches 60fps eventhough it used to do higher and other applications are unusable. Before this patch other applications got laggy and the mouse was a bit harder to use, but now it's much worse. The mouse input doesn't properly register when the game is active, stuff like twitch that used to be fine now are a huge problem and the X server seems to be taking quite the load. I'm using vkd3d (forked as mentioned before due to crashing behavior) dx12 in game.

**Comment by Tk-Glitch** [comment]
`PROTON_USE_SECCOMP=1` introduces overhead that can - depending on what the game does - lead to such results. Considering you have had issues with dx11 mode with your CPU before I guess it's not really a viable option to try?

**Comment by GoLD-ReaVeR** [comment]
Using dx11 didn't help one iota. And it isn't just the performance decrease, it's also that dx11 is crashprone and causes performance issues such as heavy disk load when someone faints (this is a windows problem) and slow quest loading.

I figured that that setting was the cause of the performance issue, but I was hoping someone could look into this. Otherwise I'll have to yap at CRAPCUM for 2 weeks and they haven't forgotten about last time I did that (and that was Iceborne release).

**Comment by GoLD-ReaVeR** [comment]
https://steamcommunity.com/app/582010/discussions/3/2840039920177165143/ <--- looks like it doesn't pertain to just proton users either.

**Comment by GoLD-ReaVeR** [comment]
https://github.com/ValveSoftware/Proton/issues/175#issuecomment-703114864

This is still weird, because when I disabled d3d12 in game it was performing a lot worse and most of these messages are d3d12 related. I will check again.

**Comment by GoLD-ReaVeR** [comment]
Your version underperforms even with PROTON_LOG disabled. It seems to be showing the same kind of log however. Maybe it has to do with the fullscreen hack as well? I'm going to compile a new version and see if that helps.

**Comment by GoLD-ReaVeR** [comment]
HEAD is now at cce4f36e214 dxgi/tests: Check that the last adapter is always WARP.
 -> Hotfixing...
error: could not revert cb5edb4b12e... server: Remove redundant calls to sock_reselect().
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/reaver/proton_tkg/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="fa9f4a20f5305b7cbcfe3a644d39d4b759f89203" in your .cfg
 -> To use the last known good staging version, please set _staging_version="7145412e0829b4de99704ecdc57adbf75cb800ee" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done


Couldn't compile :'(

**Comment by GoLD-ReaVeR** [comment]
Alright, so I did the same trick I did with the GE build (not having twitch open) and the game ran amicably. There's a few more things to note: once every minute or so there would be a huge fps drop. When I switch away from the window to do other things the system slows down a lot, but if I press esc first that brings up the menu and would allow me to move the mouse out of the game, the performance is much better. Moving the mouse into chromium tabs that have youtube or other media stuff going on also slows down the game quite a bit. This is all with logging disabled. I've set chromium hardware rendering to disabled in every conceivable way possible. But I reckon it still tries to use the video renderer somehow and that that gives a bigger resource conflict than the rest.

**Comment by GoLD-ReaVeR** [comment]
One more thing, and this is also since latest MHW patch: Preprocessing shaders freezes my system.

**Comment by GoLD-ReaVeR** [comment]
I still have to test preprocessing shaders. But the latest nvidia drivers seem to run MHW without any issues. I can have twitch open again and play the game at the same time. Performance isn't where it used to be but isn't as abominable to the point of unplayability.
