### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Leebre** [Frogging-Family/wine-tkg-git#165]
Hi, I am trying to compile wine_tkg on my system (Arch Linux) and it is throwing several errors similar to the following:

```
gcc -m32 -c -o dlls/bcrypt/macos.o ../wine-mirror-git/dlls/bcrypt/macos.c -Idlls/bcrypt \
  -I../wine-mirror-git/dlls/bcrypt -Iinclude -I../wine-mirror-git/include -D__WINESRC__ -D_UCRT \
  -DWINE_UNIX_LIB -D_REENTRANT -fno-PIC -fasynchronous-unwind-tables -Wall -pipe \
  -fcf-protection=none -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement \
  -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes \
  -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -O2 -ftree-vectorize -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
In file included from ../wine-mirror-git/dlls/bcrypt/gnutls.c:1612:
../wine-mirror-git/include/windef.h:116:24: error: unknown type name ‘va_list’
  116 | #  define __ms_va_list va_list
      |                        ^~~~~~~
../wine-mirror-git/include/winbase.h:2073:84: note: in expansion of macro ‘__ms_va_list’
 2073 | WINBASEAPI DWORD       WINAPI FormatMessageA(DWORD,LPCVOID,DWORD,DWORD,LPSTR,DWORD,__ms_va_list*);
      |                                                                                    ^~~~~~~~~~~~
In file included from ../wine-mirror-git/dlls/bcrypt/gnutls.c:1613:
../wine-mirror-git/include/winbase.h:1613:1: note: ‘va_list’ is defined in header ‘<stdarg.h>’; did you forget to ‘#include <stdarg.h>’?
 1612 | #include <poppack.h>
  +++ |+#include <stdarg.h>
 1613 | 
In file included from ../wine-mirror-git/dlls/bcrypt/gnutls.c:1612:
../wine-mirror-git/include/windef.h:116:24: error: unknown type name ‘va_list’
  116 | #  define __ms_va_list va_list
      |                        ^~~~~~~
../wine-mirror-git/include/winbase.h:2074:85: note: in expansion of macro ‘__ms_va_list’
 2074 | WINBASEAPI DWORD       WINAPI FormatMessageW(DWORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,__ms_va_list*);
      |                                                                                     ^~~~~~~~~~~~
../wine-mirror-git/include/windef.h:116:24: note: ‘va_list’ is defined in header ‘<stdarg.h>’; did you forget to ‘#include <stdarg.h>’?
  116 | #  define __ms_va_list va_list
      |                        ^~~~~~~
../wine-mirror-git/include/winbase.h:2074:85: note: in expansion of macro ‘__ms_va_list’
 2074 | WINBASEAPI DWORD       WINAPI FormatMessageW(DWORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,__ms_va_list*);
      |                                                                                     ^~~~~~~~~~~~
../wine-mirror-git/include/windef.h:116:24: error: unknown type name ‘va_list’
  116 | #  define __ms_va_list va_list
      |                        ^~~~~~~
../wine-mirror-git/include/winternl.h:3459:82: note: in expansion of macro ‘__ms_va_list’
 3459 | NTSYSAPI NTSTATUS  WINAPI RtlFormatMessage(LPCWSTR,ULONG,BOOLEAN,BOOLEAN,BOOLEAN,__ms_va_list *,LPWSTR,ULONG,ULONG*);
```

It seems to be looking for a typename 'va_list', which is supposedly in stdarg.h, which doesn't seem to be being included. Does anyone have any idea how I can resolve it?

**Comment by Tk-Glitch** [comment]
I can't reproduce that issue on my end. Could you please give more details about your build's configuration, in case you customized it or are using custom patches on top? Also, did you use `makepkg -si` for building?

**Comment by aeris** [comment]
o/ here !
Seems I hit the same trouble trying to compiling wine-staging/wine on arch.

Wine-staging commit : e2d9f97b
Wine commit : 70d77a439ab

```
gcc -m32 -c -o dlls/comctl32/dpa.o /mnt/workspace/external/lutris-wine/wine/dlls/comctl32/dpa.c -Idlls/comctl32 \
  -I/mnt/workspace/external/lutris-wine/wine/dlls/comctl32 -Iinclude \
  -I/mnt/workspace/external/lutris-wine/wine/include \
  -I/mnt/workspace/external/lutris-wine/wine/include/msvcrt -D__WINESRC__ -D_COMCTL32_ -D_UCRT \
  -D_REENTRANT -fno-PIC -fasynchronous-unwind-tables -fno-builtin -fshort-wchar -Wall -pipe \
  -fcf-protection=none -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement \
  -Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes \
  -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -fno-omit-frame-pointer -march=native -pipe
In file included from /mnt/workspace/external/lutris-wine/wine/dlls/bcrypt/gnutls.c:1871:
/mnt/workspace/external/lutris-wine/wine/include/windef.h:120:24: error: unknown type name 'va_list'
  120 | #  define __ms_va_list va_list
```

**Comment by drizzt** [comment]
I fixed that with a simple userpatch: https://gist.github.com/drizzt/364a915fc5f88b6143b913e7f494950b

**Comment by Tk-Glitch** [comment]
I'm still unable to reproduce that issue on my end. It all builds fine as is. Do you guys have recent mingw-gcc builds installed (and that uses the same GCC base as your main GCC toolchain)?

**Comment by drizzt** [comment]
tredaell@aldebaran ~ ₿ i686-w64-mingw32-gcc --version
i686-w64-mingw32-gcc (GCC) 10.2.1 20200723 (Fedora MinGW 10.2.1-2.fc33)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

tredaell@aldebaran ~ ₿ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

tredaell@aldebaran ~ ₿

**Comment by IDeathByte** [comment]
when i try compile proton-tkg build on manjaro i have this error:

steamclient_main.c:19:10: фатальная ошибка: wine/list.h: Нет такого файла или каталога
   19 | #include "wine/list.h"
      |          ^~~~~~~~~~~~~
компиляция прервана.
winegcc: /usr/bin/ccache failed
make: *** [Makefile:360: steamclient_main.o] Ошибка 2
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/deathbyte/Загрузки/wine-tkg-git/proton-tkg/external-ressources/Proton/build/lsteamclient.win32»
cp: не удалось выполнить stat для 'Proton/build/lsteamclient.win64/lsteamclient.dll.so': Нет такого файла или каталога
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
  -> exit cleanup done

i tried both makepkg and .sh building

**Comment by Hello71** [comment]
the original error is caused by not installing lib32-gnutls, or disabling it. it can be worked around by adding `#include <stdarg.h>` to gnutls.c. this new error is completely unrelated, and is also very annoying to read when printed in russian for no good reason.
