### ISSUE TITLE
API D3D not found with Wine TKG clean prefix.

### ISSUE THREAD

**Issue by iWeaker4you** [Frogging-Family/wine-tkg-git#17]
When I try to install DXVK in a clean installation made with WINE TKG, it doesn't find these files, I already installed the DirectX with Winetricks and it still doesn't work.

Install Wine-Staging to verify, and with a clean prefix if it works without problem.

Terminal result when try to install DXVK on WINE TKG clean prefix: 
/dxgi.dll: File not found in wine prefix/dosdevices/c:/windows/system32
/dxgi.dll: File not found in wine prefix/dosdevices/c:/windows/syswow64
/d3d9.dll: File not found in wine prefix/dosdevices/c:/windows/system32
/d3d9.dll: File not found in wine prefix/dosdevices/c:/windows/syswow64
/d3d10.dll: File not found in wine prefixdosdevices/c:/windows/system32
/d3d10.dll: File not found in wine prefixdosdevices/c:/windows/syswow64
/d3d10_1.dll: File not found in wine prefixsdevices/c:/windows/system32
/d3d10_1.dll: File not found in wine prefixsdevices/c:/windows/syswow64
/d3d10core.dll: File not found in wine prefixevices/c:/windows/system32
/d3d10core.dll: File not found in wine prefixevices/c:/windows/syswow64
/d3d11.dll: File not found in wine prefixdosdevices/c:/windows/system32
/d3d11.dll: File not found in wine prefixdosdevices/c:/windows/syswow64

**Comment by Tk-Glitch** [comment]
Do you have mingw-w64 compiler installed? If yes, did you build it yourself or is it prebuilt, and where does it come from?

**Comment by iWeaker4you** [comment]
@Tk-Glitch I uninstalled it and installed it from the ones in "Release" already compiled, but I still get the error, uninstall it and install Wine-Staging and it works, if I create a Prefix with Wine-Staging, I uninstall it and install Wine- TKG and update the prefix works without problems, it only happens when I create a clean Prefix with Wine-TKG

**Comment by iWeaker4you** [comment]
@Tk-Glitch yes, i have mingw-w64 installed

**Comment by Tk-Glitch** [comment]
At first glance, `winepath` has regressed with https://github.com/wine-mirror/wine/commit/e22bcac706be3afac67f4faac3aca79fd67c3d6f so building without mingw or reverting that change should fix it. I'm experimenting on my end for a workaround in the meantime.
