### ISSUE TITLE
 Patch application has failed

### ISSUE THREAD

**Issue by CygnusTerminal** [Frogging-Family/wine-tkg-git#170]
Hello again, i am trying to compile proton-tkg with 5.8 staging, and applying the "winex11-fs-no_above_state.mypatch", causes this error:
patching file dlls/winex11.drv/window.c
Hunk #1 FAILED at 1078.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/window.c.rej
I don't know what is the cause since this is all the information that prepare.log shows. 
I've also succesfully applied the GNUTLShack patch and the winex11-fs-no_above_state patch.
Distro is Arch Linux with all builds deps fulfilled.

**Comment by CygnusTerminal** [comment]
Interestingly enough, if i remove the fs-no_above_state patch, it builds fine.

**Comment by Tk-Glitch** [comment]
Community patches are always rebased against current head, so for 5.8 you'd likely want to use an earlier version of the patchset for it to apply.
You can try that one: https://raw.githubusercontent.com/Frogging-Family/community-patches/f43839ed2e416aec892c13e22048ab300ff1923f/wine-tkg-git/winex11-fs-no_above_state.mypatch
It's the version before the last.

**Comment by CygnusTerminal** [comment]
> Community patches are always rebased against current head, so for 5.8 you'd likely want to use an earlier version of the patchset for it to apply.
> You can try that one: https://raw.githubusercontent.com/Frogging-Family/community-patches/f43839ed2e416aec892c13e22048ab300ff1923f/wine-tkg-git/winex11-fs-no_above_state.mypatch
> It's the version before the last.

Thanks tk! Gonna try after work, and sorry for bothering, i am still new to all of this

**Comment by Tk-Glitch** [comment]
Hopefully that worked out for your 5.8 based build :) If it did, feel free to close or report as fixed. Thanks!

**Comment by CygnusTerminal** [comment]
> Hopefully that worked out for your 5.8 based build :) If it did, feel free to close or report as fixed. Thanks!

Oh, i always forgot to do so, it worked! Thanks Tk!

**Comment by Tk-Glitch** [comment]
You're welcome :smiley: :+1:
