### ISSUE TITLE
Unable to compile: 'error: could not revert 2d91f7def15... ntdll: Load libwine dynamically.'

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/wine-tkg-git#171]
Ran TkgThingy and updated all the repos, but now I cannot compile due to a hotfix not applying.  I'm assuming this is due to a need for a rebase?

` -> Changing wine HEAD to the wine-staging base commit...
Note: switching to '568e3e8b697a960881c162671a33c28727921797'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 568e3e8b697 ucrtbase: Add [_]strtold[_l].
 -> Hotfixing...

error: could not revert 2d91f7def15... ntdll: Load libwine dynamically.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.`

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5333918/prepare.log)

**Comment by Tk-Glitch** [comment]
Right below the last line you pasted, you should have the last known good commit on my end, which will tell a long story about the potential need for hotfix rebasing.
```
HEAD is now at 568e3e8b697 
```
If the last known good mainline commit is not `568e3e8b697a960881c162671a33c28727921797`, a rebase is needed.
Spoiler: it'll be rebased asap ;)

**Comment by JooJooBee666** [comment]
Ok, great.  And yes, those lines were there.  However, in my experience, the _set _plain_version and _staging_version were ignored.  I tried them today and they worked. :man_shrugging:
