### ISSUE TITLE
[wine-tkg-git] A build failure with commit 61777742b3e1ae15008d3753f8220c5a1907719c

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#176]
A build failure with commit 61777742b3e1ae15008d3753f8220c5a1907719c

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5359668/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5359669/prepare.log)

![Screenshot from 2020-10-10 23-30-34](https://user-images.githubusercontent.com/36989404/95662537-22db8380-0b51-11eb-92b0-d0827b8ff78f.png)

**Comment by rizzini** [comment]
Same here.

**Comment by Tk-Glitch** [comment]
Upstream broke compatibility with vkd3d-proton (library version) recently, and now requires a git version of upstream vkd3d lib. My recommendation right now is to get rid of any vkd3d package you might have currently installed, and build vkd3d-proton as standalone using https://github.com/Frogging-Family/dxvk-tools.
I'll change the vkd3d-git package I'm providing to target upstream vkd3d by default again for the ones who'd want to use it anyway, but using vkd3d-proton standalone will give much better results at this point in time.

**Comment by rizzini** [comment]
vkd3d-proton all the way. Thanks for the reply.

**Comment by Tk-Glitch** [comment]
The vkd3d-git package I offer has been updated since my last message so rebuilding that (or just uninstalling another vkd3d package you might have) is the actual fix for this issue.
If you're still encountering the problem after following the advises in here, feel free to post here with as much detail as possible regarding your current setup. Thanks :)

Marking fixed

**Comment by Kerrung** [comment]
> The vkd3d-git package I offer has been updated since my last message so rebuilding that (or just uninstalling another vkd3d package you might have) is the actual fix for this issue.
> If you're still encountering the problem after following the advises in here, feel free to post here with as much detail as possible regarding your current setup. Thanks :)
> 
> Marking fixed

But I still have the same problem.
https://github.com/Frogging-Family/wine-tkg-git/commit/54d209fc9370492c3daf754e7a7c27ff3edccece

**Comment by Tk-Glitch** [comment]
@Kerrung Remove any vkd3d package installed as mentioned above -> fixed.

**Comment by Kerrung** [comment]
> @Kerrung Remove any vkd3d package installed as mentioned above -> fixed.

Please tell me if I'm doing anything wrong. I removed all vkd3d packages. That is, I now have no packages
vkd3d and lib32-vkd3d from the official Arch Linux repositories, nor the vkd3d-proton and lib32-vkd3d-proton packages compiled from your repository. Am I doing everything right? If this is true, then World of Warcraft no longer sees D3D12 support on my system.

![Screenshot from 2020-10-19 14-16-11](https://user-images.githubusercontent.com/36989404/96426486-b9c1d300-1216-11eb-9fe3-bfdf40791c9f.png)

**Comment by Kerrung** [comment]
If I rebuilding the latest vkd3d-proton, so your wine-tkg-git don't want to build...

**Comment by Tk-Glitch** [comment]
Yes that's normal. You will need to install vkd3d-proton standalone. It's shipped in proton-tkg, but requires manual installation for wine. You can use https://github.com/Frogging-Family/dxvk-tools to build it (`./upvkd3d-proton build`), then you'll need to copy the d3d12.dll files to your prefix (and set d3d12 as native), similarly to DXVK.

**Comment by Kerrung** [comment]
> Yes that's normal. You will need to install vkd3d-proton standalone. It's shipped in proton-tkg, but requires manual installation for wine. You can use https://github.com/Frogging-Family/dxvk-tools to build it (`./upvkd3d-proton build`), then you'll need to copy the d3d12.dll files to your prefix (and set d3d12 as native), similarly to DXVK.

As DXVK have a symlink script, maybe you create your own for your vkd3d version? Because creating symlinks once is more convenient than manually copying files to all Wine prefixes each time after each updates.

**Comment by Tk-Glitch** [comment]
I do agree, and that's on my todos list! That will happen after I'm done with the whole wine/proton-tkg rebasing work :)
