### ISSUE TITLE
Patch errors with new wine releases

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/wine-tkg-git#178]
Is anybody checking the patches + wine after each version release? its not the 1st time the patch fail to apply to a new version of wine. many times i was  unable to apply the patches even after more than a week from a new release. 
at least disable those that are not ready for new versions of wine.

**Comment by Tk-Glitch** [comment]
Please give a list of the patches you have experienced problems with. Most patches are tested but some combinations might break as there are too many possible to test them all. The usual combinations are all tested and working just fine on a given head.

**Comment by Tk-Glitch** [comment]
Also if you're talking about community patches (which affect wine-tkg-git, but are in a different repo), they are what they are and technically unmaintained. I will rebase some of them at times if nobody does, but they are not supported and maintained in the same way included patches are.

**Comment by logan001** [comment]
im talking about these

```
==> WARNING: HALP! We got some hotfixes for your current tree!
Do you want to apply them all with no further prompt?
> Y/n : 
```
i don't know if its community or not. this is were most of the time fails. 
i see that now there is no error

**Comment by Tk-Glitch** [comment]
This is normal and expected. Everyday wine and wine-staging are updated upstream and wine/proton-tkg can/will break for a few hours until I fix it against the latest changes. That's why you're invited to use the last known good commit in case it fails. Depending on your timezone, the amount of work it represents on my end, and my availability, you may end up attempting to compile more often than not when you have very low chances of everything being fixed up already, leading to that feeling. But nope, I'm on it every day :wink:

**Comment by logan001** [comment]
well i thought its expected to break for every new release. the problem is that they sometimes are not fixed for an entire release

**Comment by Tk-Glitch** [comment]
That's untrue. As I explained, they are fixed on a daily basis, and in case I skip a day I get spammed by users. It's expected to break every day, as wine/proton-tkg targets wine-devel and not "releases". You're probably trying to compile on my sleep schedule or something :smile:

**Comment by logan001** [comment]
ok
but i sure was unable to compile 5.18. i've tried a few times (2-4) and always failed. and i think 5.16 was the same. i don't remember. another one i was able to compile it after a week. so i don't know what to say. they failed at that step when try to apply those patches.

**Comment by Tk-Glitch** [comment]
You should have opened an issue and posted your logs at the time. I have uploaded 5.16 and 5.18 releases in a timely manner despite what you say, with accompanying sources generated from the very same script I offer publicly. It might have been an exotic combination of options that's not tested too often, an out of date tree, or some other reason I can't think about.

Please open an issue the next time you face such an issue so we can properly understand what's happening on your end. If it's just the daily delay before I push fixes, you'll know that's normal and it'll get fixed a few hours later, until the next day breakage.

**Comment by logan001** [comment]
ok.
i'll do that next time.
i hope there is no next time :)

**Comment by Tk-Glitch** [comment]
Thank you!
