### ISSUE TITLE
Warframe: No Sound since 5.18+

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#179]
Any 5.17 Build i have Sound is working fine
Any 5.18+ build i made the game is completely silent exept for the launcher

Lutris Debug: 
[warframeSoundError.txt](https://github.com/Frogging-Family/wine-tkg-git/files/5370101/warframeSoundError.txt)

**Comment by ninelore** [comment]
Expected it to be upstream

**Comment by Tk-Glitch** [comment]
Breakage happened after those:
https://github.com/wine-mirror/wine/commit/6314a75006d1cfb86c1fb3da71be037fe646437c
https://github.com/wine-mirror/wine/commit/d8ae98d4216b85b3da342ef71b28674996e5c9d5
https://github.com/wine-mirror/wine/commit/530c79fba272219e9ed7bc1ebf309fe7163ac8ee
https://github.com/wine-mirror/wine/commit/370a538e54bc7d2b97c8f845f702adfc51902862

Reverting them fixes it. I'll check if that can be reverted on master and staging cleanly, and if needed, make a custom patch until this is fixed upstream.

**Comment by Tk-Glitch** [comment]
[xact-revert-179.myrevert.txt](https://github.com/Frogging-Family/wine-tkg-git/files/5374661/xact-revert-179.myrevert.txt)
Here's a revert patch (drop it in your `wine-tkg-git/wine-tkg-git/wine-tkg-userpatches/`) that seem to apply up to the last known good commit. Not sure if it'll compile with it just yet but it's time for sleep for me, so I'll fix the hotfixer against master and check that out tomorrow.
