### ISSUE TITLE
Patch application has failed

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#180]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5377417/prepare.log)

As always thanks for your hard work

**Comment by netbospl** [comment]
In customization.cfg set
_staging_version="v5.19"
and it will go.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/bd2fd3543d4afbb078b0f6a6cb3d47ee01eb9657
