### ISSUE TITLE
983e112579 doesnt build 

### ISSUE THREAD

**Issue by kkartaltepe** [Frogging-Family/wine-tkg-git#183]
This 983e112579 commit introduces proton-steam-bits-de679af4.patch in the hotfixer but does not include it.

Side question is master expected to build on every commit?

**Comment by Tk-Glitch** [comment]
Thank you for your report!

**Comment by Tk-Glitch** [comment]
> Side question is master expected to build on every commit?

Master of wine-tkg-git is at least expected to build on every final patch of the daily patch wave, which will often just work with every patch of the patchwave. You typically never want to use something else than master for wine-tkg-git, and only define the wine version you desire in your .cfg. If you find a breaking point on legacy wine versions (while using master), it's worth opening a ticket for.
