### ISSUE TITLE
[NOT A BUG] Just a small clarification about dxvk & vkd3d

### ISSUE THREAD

**Issue by Nocifer** [Frogging-Family/wine-tkg-git#184]
Just to make sure I'm doing this properly (because lately some stuff have been rapidly changing regarding dxvk & vkd3d), if I want a non-proton wine prefix with both dxvk and vkd3d-proton support, I'd do the following:

- Build wine with _use_vkd3dlib="false" (default) and _dxvk_dxgi="false" (non-default)
- Build dxvk with the dxvk_config.dll patch enabled (default if I'm using your provided scripts) and vkd3d-proton
- Copy d3d9.dll, d3d10core.dll, d3d11.dll, d3d12.dll and dxvk_config.dll to my wine prefix (and set them to native as needed), but not dxgi.dll, since the functionality is built-in in wine's own dxgi.dll

And then stuff should Just Work™ with both DX11 and DX12 in the same prefix (barring any bugs and limitations in vkd3d itself)?

**Comment by Tk-Glitch** [comment]
Looks all good to me indeed :)
For some rare games, using DXVK's dxgi might be needed. I think Borderlands 3 is one of them, possibly the only one.

**Comment by Nocifer** [comment]
Great to hear that! As for dxgi, I'm aware about that limitation (you also mention it in the config file), fortunately I don't really care for Borderlands 3 so all's well :)
