### ISSUE TITLE
proton-steam-bits-de679af4.patch: No such file or directory

### ISSUE THREAD

**Issue by Sukid** [Frogging-Family/wine-tkg-git#186]
Just trying to compile proton-tkg using staging 5.9 and this happens as it's applying patches:
./non-makepkg-build.sh: line 170: /media/data01/TKGlitch/PKGBUILDS/wine-tkg-git/wine-tkg-git/proton-steam-bits-de679af4.patch: No such file or directory

prepare.log doesn't give much more info than that. It just shows everything going normally then stopping there.

**Comment by Tk-Glitch** [comment]
This issue was fixed earlier today on master. Pulling latest changes should get you back on track.

**Comment by Sukid** [comment]
ah, yeah all good now!
