### ISSUE TITLE
FSync Staging Unix Patch

### ISSUE THREAD

**Issue by Aeirex** [Frogging-Family/wine-tkg-git#188]
Error when applying patch.
[sync-unix-staging.log](https://github.com/Frogging-Family/wine-tkg-git/files/5397182/sync-unix-staging.log)

**Comment by ninelore** [comment]
Same as #187

**Comment by Aeirex** [comment]
@ninelore FSync is not much better than ESync, honestly better to just  disable it for now.

**Comment by Valmar33** [comment]
Wine Staging commit `ed56966feb49eaee62356df5970c886344bc2ec5` works just fine.

The latest Wine Staging commit breaks it.

**Comment by Valmar33** [comment]
@Aeirex 

Maybe it just doesn't do much for you. Have you tested your claim on everyone's hardware configurations? No?

**Comment by Aeirex** [comment]
@Valmar33 Well the performance is less than 1%. I've done tests as have many other Linux users. https://flightlessmango.com/benchmarks/doom_eternal_vsync

**Comment by Valmar33** [comment]
Isn't Doom Eternal already significantly optimized? It's also Vulkan-based.

So, I wouldn't take that benchmark as evidence for your claim.

Besides, I only have your claim that many other Linux users have done tests.

**Comment by Aeirex** [comment]
Well okay it's fine, I will use the commit and use FSync. I mean some games so good like Guild Wars 2 with my tests, but I wasn't sure if it was 1-2 FPS honestly. But every FPS counts.

**Comment by Aeirex** [comment]
This is no longer a bug.
