### ISSUE TITLE
dlls/ntdll/server.c is Gone (Breaks Staging-Shared-Memory-Default Patch)

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#189]
I've been struggling to find where the commit was that deleted this file, I can't find it for the life of me. 

If I drop back to Staging commit 6d726da3ba0130385e352be0c534399d5c7eb29d, the patch succeeds, but the build fails later (after actual compilation starts) and I can't find where it breaks, I think it breaks before  the scrollback limit of my terminal (I just see a bunch of entering and leaving directories with `make` and then it just says "time for 64-bit wine" stuff and it exits). 

Is this something we no longer need? I've always used it (except for with Origin games)

**Comment by fleggie** [comment]
Got the same error I think. Using wine console outputs that ntdll is missing. But I am not quite sure what I am doing here. New to all that stuff.

**Comment by gardotd426** [comment]
Yeah the file existed up until a few days ago, some commit deleted it but I can't find which. I'm just building without it for now.

If you want to use the benefits of the patch without the patch just use the `STAGING_SHARED_MEMORY=1` environment variable.

**Comment by fleggie** [comment]
Thanks I'm already using that environment variable. But after building wine my applications won't open up. Guess I'm doing something wrong.

**Comment by SveSop** [comment]
Perhaps not what you are asking for, but upstream wine removed server.c in this commit:
[https://github.com/wine-mirror/wine/commit/4e5811637ad027d01cc5033f76b03e6e8cfdd287#diff-e11e0e91ac4630a9ba8ed0078e67c868dcaad3549d0d56d54d22019f243c1c5f](https://github.com/wine-mirror/wine/commit/4e5811637ad027d01cc5033f76b03e6e8cfdd287#diff-e11e0e91ac4630a9ba8ed0078e67c868dcaad3549d0d56d54d22019f243c1c5f)

**Comment by gardotd426** [comment]
Well what's weird is that I've always used this patch and I've built a ton of times since August 25th.

**Comment by Tk-Glitch** [comment]
The hotfixer path, used by default in -tkg until yesterday basically, restored it. That patch (I totally forgot about tbh) will need to be updated on my end.

**Comment by gardotd426** [comment]
Ah, that makes so much more sense lol, I was starting to go crazy wondering what was going on. Cool, no worries.

**Comment by Tk-Glitch** [comment]
Actually, `server-Shared_Memory` is currently disabled in staging and hasn't been rebased at all just yet :frog: Looks like it'll take more than me updating the patch. I'll forcefully disable that option for the time being.

**Comment by gardotd426** [comment]
lol alrighty, nbd

**Comment by Tk-Glitch** [comment]
The patchset is still disabled in staging, so we are still disallowing that option. But yeah we could consider this as not an issue anymore. The feature is simply gone.
