### ISSUE TITLE
unable to use fsync wine-tkg last

### ISSUE THREAD

**Issue by tuxtergames** [Frogging-Family/wine-tkg-git#192]
Customization file not change, set by default, not working running trought terminal or lutris.

![image](https://user-images.githubusercontent.com/26095484/96377992-81ab8900-115f-11eb-8cb9-fbf1582fb8b6.png)

![image](https://user-images.githubusercontent.com/26095484/96377914-28435a00-115f-11eb-87c4-e300aeefd99e.png)

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5398058/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5398059/prepare.log)

**Comment by fleggie** [comment]
What is the terminal output when launching `lutris -d` ? Did you replaced something in your /opt/ (/opt/ is for Debian don't know what you are running) If the output of `lutris -d` is fsync is up if you apply "Enable anyway..." I think you are good to go.

Something like this when you start the application:

`Initial process has started with pid 31265
Game is considered started.
gamemodeauto: 
fsync: up and running.
`

**Comment by tuxtergames** [comment]
> What is the terminal output when launching `lutris -d` ? Did you replaced something in your /opt/ (/opt/ is for Debian don't know what you are running) If the output of `lutris -d` is fsync is up if you apply "Enable anyway..." I think you are good to go.
> 
> Something like this when you start the application:
> 
> `Initial process has started with pid 31265`
> `Game is considered started. `
> `gamemodeauto: `
> `fsync: up and running.`

tks @fleggie ignoring lutris alert of don't support looks like thats running anyway, closing....

![image](https://user-images.githubusercontent.com/26095484/96387165-7a43aa00-1176-11eb-9ccc-a2c511cfe6a3.png)
