### ISSUE TITLE
Warframe steam/Proton-tkg version

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#193]
Is it intended that the Patch for the broken sound doesnt apply to proton and only to wine-tkg?
(Warframe has both a steam and a non-steam client)

**Comment by ninelore** [comment]
In the meantime i copypasted the `.myrevert` from wine over to proton-userpatches

**Comment by Tk-Glitch** [comment]
As long as you are accepting hotfixes, it should be applied to your Proton builds just as well. It definitely is on my end as I'm using Proton-tkg exclusively as a user. Could you please post your `prepare.log` and `last_build_config.log` ?

**Comment by ninelore** [comment]
Was to tired yesterday to dig into it, but now i can confirm that the patch applied and there were no build errors. But the Sound does not work in proton for some reason. Works fine in the non-steam version with a wine-tkg with almost same settings and same commit.

There some other minor issues with the proton version too, like the launcher has minor graphic glitches and the FPS seems to be noticably worse.

It would be nice to be able to play the STeam version cus it has some exclusive apperances

**Comment by ninelore** [comment]
The Sound Problem worked itself out after a rebuild but the freezes got worse

**Comment by Tk-Glitch** [comment]
`There some other minor issues with the proton version too, like the launcher has minor graphic glitches`
I can't reproduce this (and never experienced anything similar).

`random 0.5sec freezes and the general FPS seems to be noticably worse.`
Sounds like shader compilation for the 0.5s freezes. For the framerate being worse, I can't reproduce it either.

**Comment by ninelore** [comment]
I've skipped the shader pre-caching / turned it off because it takes 30-60min for me to compile the shaders at that speed that it gives me. Ill try to let them pre-cache now and see whats happening

**Comment by ninelore** [comment]
[Example of the Launcher Glitches](https://youtu.be/QrTNsjZ69NE)

**Comment by Tk-Glitch** [comment]
> Still hanging issues when entering a new part of the map

Definitely shader compilation then. There's no fix for that. Just play the game on the same driver version for a while and it'll smooth itself out. For that game (along with a few others), steam's shader pre-caching is worthless.

Regarding the launcher, I'm not experiencing that on plasma+intel gpu. However, if another window covers the launcher, it'll need a refresh before the part of the launcher that was covered shows again. That's a wine issue and I'm pretty sure it's been there for a long while now.

**Comment by ninelore** [comment]
Is it possible that i can blame Nvidia? x)

Still weird that the non-steam version works smooth af

**Comment by Tk-Glitch** [comment]
I'm not experiencing such an issue on both AMD and Intel GPUs while using the steam version (and having the shader precaching disabled at all times). I have had to populate my cache initially of course, but it's been smooth ever since outside of the unavoidable minor itches for a couple minutes after a driver update.
I have never experienced a perf issue when I was using a geforce 980Ti a year back or so, so unless there's been a regression with nvidia drivers (which is possible) I wouldn't immediately blame nvidia. I have access to a laptop with a geforce 1050Ti, I'll give the game a try on it.

**Comment by Tk-Glitch** [comment]
After testing recently on multiple machines, the game works as usual and as expected taking DXVK's shader compilation into account. Rbernon's PR for DXVK (https://github.com/doitsujin/dxvk/pull/1582) helps with recompilation times after driver update on a hot DXVK state cache. The asynchronous pipeline compiler hack patchset also can help but is possibly dangerous for your account so I can't recommend it.
Nothing technically wrong with the state of the game right now, so let's close.
