### ISSUE TITLE
How do i learn all of this so i understand how i would do something like this on my own?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/wine-tkg-git#195]

**Comment by Tk-Glitch** [comment]
You'll want to learn shell scripting (which is used for almost all our automation), python (used in Proton) and C (for most Wine patches), as well as using git. Then of course you'll need some experience with Linux and various distros to understand packaging and dependencies systems, among other subtleties you might need along the way.

**Comment by Axilot** [comment]
C is a language i mainly program in. And in git i got the main understanding of how all of this works.

**Comment by Axilot** [comment]
But why are those .patch files? And what are they? Is this a feature of the "normal" wine that allows you to modify some things within a .patch file?

**Comment by Tk-Glitch** [comment]
The `.patch` extension is fully optional. This isn't a wine feature, those are just git diffs.

**Comment by Axilot** [comment]
Ah okay. When did you started diving into all of this?

**Comment by Tk-Glitch** [comment]
Specifically for wine and related, 3 years. For scripting and kernel work, it's been 12 years or so (I feel so old saying that :sweat_smile: ).

**Comment by Axilot** [comment]
XD

**Comment by Axilot** [comment]
Do you have any address where i can text you without spamming your issue threads?
