### ISSUE TITLE
Impossible to build new version 

### ISSUE THREAD

**Issue by Bojahdok** [Frogging-Family/wine-tkg-git#196]
Hi,
I'm on Arch and when I'm trying to build the new version of proton-tkg and wine-tkg with `makepkg -si` it stops and I get that error : `Note: switching to '6373792eec0f122295723cae77b0115e6c96c3e4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6373792eec0 Release 5.20.
 -> Hotfixing...
error: could not revert c9e1b789d28... conhost: Clear out_size in IOCTL_CONDRV_READ_CONSOLE implementation.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/johnny/Git/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="fa9f4a20f5305b7cbcfe3a644d39d4b759f89203" in your .cfg
 -> To use the last known good staging version, please set _staging_version="7145412e0829b4de99704ecdc57adbf75cb800ee" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

And there is what's in the prepare.log : `Note: switching to '6373792eec0f122295723cae77b0115e6c96c3e4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6373792eec0 Release 5.20.
 -> Hotfixing...
error: could not revert c9e1b789d28... conhost: Clear out_size in IOCTL_CONDRV_READ_CONSOLE implementation.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
 ==> ERROR: Patch application has failed. The error was logged to /home/johnny/Git/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="fa9f4a20f5305b7cbcfe3a644d39d4b759f89203" in your .cfg
 -> To use the last known good staging version, please set _staging_version="7145412e0829b4de99704ecdc57adbf75cb800ee" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done
`
I don't know if it's me doing something wrong (it probably is) or something else, I'm really a beginner with github so don't hesitate to tell me if my post isn't at the right place or something.

**Comment by rboxeur** [comment]
For the time being -- keeping fingers crossed that our main maintainer Frenchy guy is safe/available -- you can downgrade to wine-staging 5.20 + a few mores patches that let patch wine
Here is my own advanced configuration for  the moment http://techer.pascal.free.fr/download/wine-tkg-external-config-5.20.cfg
Using it, I was able to generate a fresh wine sources. It automacillay generated wine sources and stops the process to build wine Main reason is that I am not on Arch but Xubuntu.
To build wine I usually use script provided by https://github.com/Kron4ek/Wine-Builds
But since you are on Arch you can modify my own script to let the process go ahead and build wine for you.
I hope the main repository to be up-to-date like everybody

**Comment by Tk-Glitch** [comment]
The master branch builds fine. You seem to be using an older version. I have just pushed a sync commit for the PKGBUILDS repo in case you're using that (which is likely the case considering the old behavior you're experiencing).

**Comment by SigiDijkstra** [comment]
Hey I am having same issues, trying to build fresh for the first time, and it failed twice already.. Building in clean chroot ends up the same - cannot build the package, here's the last lines of the prepare.log that seem to lead to build errors:

```
Applying /build/wine-tkg-staging-fsync-git/src/wine-staging-git/patches/widl-winrt-support/0001-include-Add-windows.media.speechsynthesis.idl-draft.patch
Applying /build/wine-tkg-staging-fsync-git/src/wine-staging-git/patches/widl-winrt-support/0002-widl-Restrict-some-keywords-to-WinRT-mode-only.patch
error: patch failed: tools/widl/parser.l:317
error: tools/widl/parser.l: patch does not apply
ERROR: Failed to apply patch, aborting!
```

**Comment by Bojahdok** [comment]
I'm really a beginner using git, which is the correct way to update the branch ? 
I'm currently using the script named "TkgThingy" located in the "PKGBUILDS" branch.

**Comment by Tk-Glitch** [comment]
Wine-staging is borked upstream at the moment. I'll try to offer a workaround until this is resolved.
