### ISSUE TITLE
Building proton-tkg with makechrootpkg fails at pkgver()

### ISSUE THREAD

**Issue by kattjevfel** [Frogging-Family/wine-tkg-git#197]
Due to my system packages being completely wrecked otherwise, I must compile wine & proton in a chroot, I was able to compile wine-tkg just fine (wine-tkg-staging-fsync-git-5.20.r3.g534f6ae3-303-x86_64.pkg.tar.zst), but trying the same for proton-tkg just gives me:
```
==> Retrieving sources...
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
==> Starting prepare()...
==> Starting pkgver()...
==> ERROR: A failure occurred in pkgver().
    Aborting...
  -> exit cleanup done
==> ERROR: Build failed, check /var/lib/archbuild/multilib-x86_64/katt/build
```
With no further logs to be seen anywhere. I'd rather not have to spin up a full VM just to build this :/

**Comment by Thaodan** [comment]
Try to use set -x in pkgver()

**Comment by kattjevfel** [comment]
No change, and I must agree with the commend there... `# overcomplicated BS`

**Comment by Thaodan** [comment]
You should add it to the top of the function to debug it better. It doesn't fix anything.
It only helps fixing it.

**Comment by kattjevfel** [comment]
That's exactly what I did, but it didn't change the output whatsoever.

**Comment by kattjevfel** [comment]
yooo thanks tkg! compiled and works great
