### ISSUE TITLE
Fullscreen hack stopped working in proton

### ISSUE THREAD

**Issue by xDShot** [Frogging-Family/wine-tkg-git#199]
It now changes desktop resolution

**Comment by Tk-Glitch** [comment]
The FS hack hasn't yet been ported over. I wanted this to be done for 5.20 release, but time constraints prevented me from doing so. It's pending. You can use `_plain_version="de679af4"` for mainline or `_staging_version="80498dd4"` for staging in your .cfg to get the FS hack back in the meantime.

**Comment by gulafaran** [comment]
any changes to this? ive hold back building wine since 5.17

**Comment by Valmar33** [comment]
It's a big patchset to have to rebase. It's on TkG's to-do list.

**Comment by aufkrawall** [comment]
It seems `_proton_fs_hack="true"` isn't fully ignored though when building recent wine-staging git? It breaks Gallium Nine in Oblivion, there is only a tiny downscaled window snippet in the top left corner in an otherwise black fullscreen window.

**Comment by aufkrawall** [comment]
Please forgive the nagging, but is there a rough ETA?
With KDE Plasma, compositor suspend notification still works when using borderless, though unlike fullscreen with fullscreen hack, it doesn't auto-resume compositing when alt + tabbing (which would be a cool feature for borderless btw. but not idea how realistic this idea is).

**Comment by aufkrawall** [comment]
One important thing I forgot to mention: Without fullscreen hack, many games initiate a mode switch for me (despite not actually changing resolution or refresh rate) when starting or alt + tabbing, which results in a very painful DP -> DVI adapter re-initialization (whole display blinking in different colors for several seconds, and that every time). This isn't the case on native Windows, so imho Wine doesn't fully meet ideal behavior here without fullscreen hack.
Also, when clamping to `_staging_version="80498dd4"`, futex2 isn't available. :(

**Comment by aufkrawall** [comment]
Great, thanks!

Minor nit: Build recently fails with `_proton_mf_hacks="true"`.

**Comment by Tk-Glitch** [comment]
That setting is deprecated on staging so I'll move it to legacy and disallow it on staging. Thanks.
