### ISSUE TITLE
Mortal Kombat 11 -  Kharon's Ship performance

### ISSUE THREAD

**Issue by nvaert1986** [Frogging-Family/wine-tkg-git#201]
Hello all,

First of all thank you for making a proton / wine release, that supports Mortal Kombat 11, as it's one of my favourite games :-) It's appreciated.

I've been playing Mortal Kombat 11 on Linux for a month of 2 - 3 now and noticed the overall FPS performance even seems to be slightly better than it used to be for me on Microsoft Windows, but noticed something unusual:

Whenever I'm playing on the Kharon's Ship stage, performance takes a nosedive. Sometimes the match is playable, but when performing a fatality (especially with Sub-Zero) the performance completely drops to 1 - 2 fps. It'll take about 5 - 7  minutes to complete the fatality (fatality in slow motion... :D). It doesn't always happen, but it happens on the regular The game hasn't crashed on me this far when this happened (only crashes rarely when loading in story mode), but just considered it weird as I never had performance issues in Microsoft Windows on this stage.

Has anybody else encountered this issue? Is this a known issue and is there a known workaround for it (as I couldn't find any)? Is this stage known to be very performance demanding?

I'm running on gentoo-sources-5.8.16 with the fsync patch applied. I've tried toggling fsync on and off, but when turning it off the performance is way worse (then the match isn't even playable on this stage). I'm using a MSI / NVIDIA Geforce GTX 1070 with nvidia-drivers-455.28 on a KDE desktop.

P.S.: For those who have a barely playable experience in The Krypt: Applying the fsync patch to the kernel enhances the performance significantly / resolves the slow / choppy / crashes issue.

Keep up the great work! :-)

**Comment by Tk-Glitch** [comment]
This is pretty interesting and might be a DXVK "issue". Fsync can improve CPU performance quite substantially depending on the game, and your results seem to indicate that the game is pretty demanding on the CPU front. I'm not familiar with the game running on Linux, but there is another unreal engine based fighting game with large performance drops on some stages: Tekken 7. In the case of Tekken 7, I think it's due to some very bad tesselation practices.

If not already done I'd open an issue over there: https://github.com/doitsujin/dxvk/issues with as much detail as possible (respecting the layout) to be helpful.

**Comment by nvaert1986** [comment]
> This is pretty interesting and might be a DXVK "issue". Fsync can improve CPU performance quite substantially depending on the game, and your results seem to indicate that the game is pretty demanding on the CPU front. I'm not familiar with the game running on Linux, but there is another unreal engine based fighting game with large performance drops on some stages: Tekken 7. In the case of Tekken 7, I think it's due to some very bad tesselation practices.
> 
> If not already done I'd open an issue over there: https://github.com/doitsujin/dxvk/issues with as much detail as possible (respecting the layout) to be helpful.

Thank you for your reply. A content shader caching update on Steam about 3 days ago actually resolved the issue for me, but now after the 17-11-2020 update the game refuses to launch completely. It shows it's about to launch and just crashes back to the desktop. This game is a real PITA to get to work properly under Linux unfortunately :(

**Comment by Tk-Glitch** [comment]
So Steam can actually ship broken shader caches? One more reason for me to keep pre-caching disabled forever :frog:
Sad that they broke the game with an update. It was already a huge pain to get it kinda working in the first place.. I'm closing this. Feel free to open another issue regarding the game not launching if you feel like it.

**Comment by Tk-Glitch** [comment]
@nvaert1986 You can find the links you asked about on the bottom of the readme of https://github.com/Tk-Glitch/PKGBUILDS :frog:
