### ISSUE TITLE
mtga-staging patch can't be applied 

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#202]
mtga-staging.patch can't be applied anymore failing with this log

mtga-staging.patch -- ( Applied MTGA crashfix )
patching file dlls/ntdll/thread.c
Hunk #1 FAILED at 787.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/thread.c.rej
patching file server/thread.c
Hunk #1 succeeded at 1966 (offset 107 lines).
patching file dlls/ntdll/thread.c
Hunk #1 FAILED at 807.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/thread.c.rej
patching file include/wine/server_protocol.h
Hunk #1 succeeded at 2448 (offset -452 lines).
Hunk #2 succeeded at 2464 (offset -452 lines).
patching file server/protocol.def
Hunk #1 succeeded at 1857 (offset -300 lines).
Hunk #2 succeeded at 1869 (offset -300 lines).
patching file server/request.h
Hunk #1 succeeded at 1279 (offset -205 lines).
patching file server/thread.c
Hunk #1 succeeded at 141 (offset 5 lines).
Hunk #2 succeeded at 149 with fuzz 2 (offset 5 lines).
Hunk #3 succeeded at 285 (offset 18 lines).
Hunk #4 succeeded at 407 (offset 30 lines).
Hunk #5 succeeded at 1694 (offset 75 lines).
Hunk #6 succeeded at 1877 (offset 75 lines).
Hunk #7 succeeded at 1885 (offset 75 lines).
patching file server/trace.c
Hunk #1 succeeded at 2426 (offset -249 lines).
patching file dlls/ntdll/thread.c
Hunk #1 FAILED at 778.
Hunk #2 FAILED at 793.
Hunk #3 FAILED at 813.
3 out of 3 hunks FAILED -- saving rejects to file dlls/ntdll/thread.c.rej

**Comment by jarrard** [comment]
Might pay to look at the failed lines and see if their still needed or require slight changes to be compatible. Its just basic script code.
