### ISSUE TITLE
How can I build wine-tkg with your vkd3d-proton?

### ISSUE THREAD

**Issue by SigiDijkstra** [Frogging-Family/wine-tkg-git#203]
Hi, I am trying to build your wine-tkg (thanks for your great work btw!) with your standalone vkd3d-proton but I am failing miserably.. I was trying to search thru various boards, reddit etc, but everywhere the answer is to use lutris.. While I think it is a good tool, I'd want to be able to build/patch it manually without using lutris.. Is it even possible? If so, any RTFM how to? Thanks a lot in advance!

**Comment by Tk-Glitch** [comment]
Hello!
Well, it's basically the same as installing DXVK.
Manual way:
```
https://github.com/Frogging-Family/dxvk-tools.git
cd dxvk-tools
./upvkd3d-proton build
```
This will give you a d3d12.dll file for both 32 and 64-bit archs. You'll then need to drop your x86 d3d12.dll in your prefixe's `drive_c/windows/syswow64/` dir, and your x64 one in `drive_c/windows/system32/`. Then you'll need to set d3d12 as `native,builtin` in the libraries tab of winecfg.

There's an install script in vkd3d-proton's repo but I couldn't get it to work on my end.

**Comment by SigiDijkstra** [comment]
Thanks a lot for quick reply, much appreciated! I did try to do it like you said, but winecfg did not pick it up not sure why.. Gonna try one more time in a clean prefix, maybe dxvk installation (thou used --without-dxgi) messed things up.. One more thing, do you think symlinking (so that my dummy self won't forget to copy) the binaries from latest to the correct folders be a good idea? Similar to how dxvk can do it?

**Comment by Tk-Glitch** [comment]
What do you mean by `winecfg did not pick it up`? It's not supposed to show up, you have to type `d3d12` to add it.
Symlinking works just fine :slightly_smiling_face:

**Comment by SigiDijkstra** [comment]
I meant that it did not work :) But making a completely new prefix  _and_ installing wow into it worked like a charm! :) Again thanks a lot for your help and great work on wine and other tools! Gonna close this now.

**Comment by Tk-Glitch** [comment]
Weird, but I'm glad you got it fixed!
