### ISSUE TITLE
ARK: Survival Evolved = Loading Failure

### ISSUE THREAD

**Issue by jarrard** [Frogging-Family/wine-tkg-git#206]
For a while now ARK Survival Evolved doesn't properly load with TKG releases but works fine with Proton-GE, basically it attempts to load to main menu but only has the loading text at bottom and cursor, and music, eventually if ctd without error.

This is on a NVIDIA 1080TI Pop!_OS System but I wouldn't be surprised if the issue is universal regardless of distro or hardware. Again proton-ge works just fine with this game.

**Comment by Tk-Glitch** [comment]
![Screenshot_20201109_182337](https://user-images.githubusercontent.com/741977/98574845-b9b66f80-22b8-11eb-93ce-ac69e2f6535e.png)
I can't reproduce the issue on my end. It *did* lock up on a white screen with text at the bottom, but eventually switched to the main menu soon after. This was on a 5.21r0 based build.

**Comment by jarrard** [comment]
Ok I will retest this sometime.

**Comment by jarrard** [comment]
Unfortunately it still loads to a black screen with only cursor and the loading screen text at very bottom. 
After about 3minutes or so the game silently crashes.

**Comment by jarrard** [comment]
I have recently change to a amdgpu 6800XT and the problem persists, just with this game. 

The game loads a blank window without loading animation, but has the eventual loading tip messages show up below.   

I also just installed Proton-TKG 5-22

**Comment by jarrard** [comment]
Well look at that, disabling the WMV files in /ARK/ShooterGame/Content/Movies/ folder fixes the issue!

Seems proton-tkg has a few issues with WMV files, maybe I got to manually install mf stuff for some reason.

**Comment by jarrard** [comment]
I'll close this now as it seems running mf-install may fix the issue, or if someone else gets it they can just remove the vid files.
