### ISSUE TITLE
ESync broke mountmgr

### ISSUE THREAD

**Issue by VolkMilit** [Frogging-Family/wine-tkg-git#207]
After wine update `5.19 (gb49e8743)` to `5.21 (ge2d9f97b)` mountmgr just stop working on my setup. Symptoms are constant spamming:

> fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 50
> fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 50

And winecfg can't connect to Mount Manager, installers (e.g. GoG installer) doesn't display anything on directory select. If you disable esync\fsync using env variables, it works.

It seems like this bug appears on `5.19 (gbe9c9681)` and newest wine-staging versions.

What I tried so far:
- Install wine-tkg-staging-*-git from chaotic-aur
- Install newest Proton
- Install wine-staging from Arch repository
- Change kernel version
- Build wine-tkg myself
- Create new prefix

Also, my system is `Artix Linux`, updated yesterday.

Oddly, with `WINEDEBUG=+all` it works (slowly, ofc, but works). Some race condition in ESync?

Sorry if this is wrong place to report this issue, I don't know if I need to report this to winehq, since this problem also occurs on plain wine-staging?

**How to reproduce:**
- Create new wine prefix
- Wait wineserver to die
- Launch winecfg (issue not occurs)
- Close winecfg, wait to wineserver to die
- Launch winecfg again (issue occurs)

After that issue will occurs every time.

**Comment by Tk-Glitch** [comment]
![Screenshot_20201108_191101](https://user-images.githubusercontent.com/741977/98475765-2b79b500-21f6-11eb-98a4-0e4279bf4611.png)

Sadly I cannot reproduce your issue on my machine. It might be configuration-related. I remember a couple years ago about a similar issue with esync when my external SSD was plugged in. It reported two identical device IDs and esync choked on it. The issue should indeed be reported to winehq (if not already done), but I'll ping zf (the author of the esync patchset) about it nonetheless.

**Comment by IroAlexis** [comment]
This error are very similar to what I had found lately. Can you check this https://bugs.winehq.org/show_bug.cgi?id=50046 ? Does this match in your problem ? If yes, esync is not related with this, it is present too Wine

**Comment by zfigura** [comment]
To clarify, this happens on plain wine-staging, with no extra patches applied?

If you can, please file a bug on bugs.winehq.org, and attach a log with WINEDEBUG=+esync,+sync,+server,+seh,+pid,+timestamp.

**Comment by VolkMilit** [comment]
@IroAlexis, I create a prefix with `wineboot -u`, and wineserver works normally. Not sure is this related to this issue.

@zfigura, yes, I checked all wine-staging versions from 5.19 to 5.21. All have same issues (at least versions from Arch repos). Staging 5.18 works normally. I will report this bug to winehq soon.

**Comment by VolkMilit** [comment]
After some research it seems the problem was on my end. I don't think this issue will appears on "normal" configurations. 
To fix this, I added: `127.0.0.1 Volk_PC` in `/etc/hosts` (file was empty) and everything works now.

Thanks zfigura for help.
