### ISSUE TITLE
[proton-tkg] ERROR: Patch application has failed

### ISSUE THREAD

**Issue by sonic2kk** [Frogging-Family/wine-tkg-git#209]
When trying to build Proton-tkg both with `./proton-tkg.sh` and `makepkg -si` I get the following error directly after the `Applying proton-steam-bits.patch` part of the process: `ERROR: Patch application has failed. The error was logged to /very/cool/path/prepare.log for your convenience`. I couldn't find the patch the line was referring to so I can't confirm if removing it would solve the problem (nor can I say whether or not it's a good idea haha). I've attached the `prepare.log` file below.

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5531952/prepare.log)

I've seen several of these issues on this repo at different points in time but unfortunately I'm running into it as well.

Thanks!

**Comment by Tk-Glitch** [comment]
It's bound to happen again and again :smile: That's the price to pay for targeting upstream :frog:
