### ISSUE TITLE
Gamepad (DS4 v2 Bluetooth not working in wine-tkg-staging-fsync-git-5.21

### ISSUE THREAD

**Issue by radmedres** [Frogging-Family/wine-tkg-git#211]
Game pad (DS4 V2 Bluetooth) not working in wine-tkg-staging-fsync-git-5.21.r0.ge2d9f97b-305-x86_64
Going back to the previous installed wine-tkg-staging-fsync-git-5.19.r1.gb49e8743-300-x86_64 fixes this.

I only use the wine built-in functionality through wine control. DS4 responds is registered in this GUI but not when running Games or Cemu.

**Comment by soredake** [comment]
Same happened to me, ds4 v2 bluetooth too.

**Comment by Tk-Glitch** [comment]
Any better since yesterday's changes?

**Comment by soredake** [comment]
Gamepad works now, yes, thanks!

**Comment by Tk-Glitch** [comment]
:tada:

**Comment by radmedres** [comment]
Yes, the gamepad works again with the new build. Thx!
