### ISSUE TITLE
Proton-TkG 3886.myprotonpatch fails

### ISSUE THREAD

**Issue by ronoverdrive** [Frogging-Family/wine-tkg-git#212]
`Your branch is up to date with 'origin/proton_5.0'.
######################################################

Applying your own proton patch /home/ronoverdrive/TKG/wine-tkg-git/proton-tkg/src/proton-tkg-userpatches/3886.myprotonpatch

######################################################
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamClient_SteamClient021.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamClient_SteamClient021.h
The next patch would create the file lsteamclient/cppISteamUser_SteamUser021.cpp,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file lsteamclient/cppISteamUser_SteamUser021.h,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamapplist.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamapps.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamappticket.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamclient.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamcontroller.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamfriends.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamgamecoordinator.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamgameserver.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamgameserverstats.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamhtmlsurface.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamhttp.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteaminput.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteaminventory.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteammasterserverupdater.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteammatchmaking.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteammusic.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteammusicremote.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamnetworking.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamnetworkingsockets.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamnetworkingutils.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamparentalsettings.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamps3overlayrenderer.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamremoteplay.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamremotestorage.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamscreenshots.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamugc.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamuser.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamuserstats.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamutils.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamvideo.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/matchmakingtypes.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steam_api.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steam_api_common.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steam_api_flat.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steam_api_internal.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steam_gameserver.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamclientpublic.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamdatagram_tickets.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamencryptedappticket.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamhttpenums.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamnetworkingtypes.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamps3params.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamtypes.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamuniverse.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/winISteamClient.c
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/winISteamUser.c
Hunk #1 succeeded at 302 with fuzz 2 (offset 287 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors.h
Hunk #1 succeeded at 1 with fuzz 2.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors_table.dat
Hunk #1 succeeded at 1 with fuzz 2.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamTV_STEAMTV_INTERFACE_V001.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamTV_STEAMTV_INTERFACE_V001.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/gen_wrapper.py
Hunk #1 FAILED at 15.
Hunk #2 succeeded at 114 (offset 3 lines).
1 out of 2 hunks FAILED -- saving rejects to file lsteamclient/gen_wrapper.py.rej
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steam_defs.h
Hunk #1 FAILED at 96.
Hunk #2 succeeded at 161 (offset 3 lines).
Hunk #3 succeeded at 230 (offset 3 lines).
1 out of 3 hunks FAILED -- saving rejects to file lsteamclient/steam_defs.h.rej
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamclient_private.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamtv.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/steamtypes.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/winISteamTV.c
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file vrclient_x64/vrclient_x64/vrclient_private.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors_table.dat
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamNetworkingSocketsSerialized_SteamNetworkingSocketsSerialized004.cpp
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/cppISteamNetworkingSocketsSerialized_SteamNetworkingSocketsSerialized004.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/steamworks_sdk_149_scaffold/isteamnetworkingsocketsserialized.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/winISteamNetworkingSocketsSerialized.c
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors.h
(Stripping trailing CRs from patch; use --binary to disable.)
patching file lsteamclient/win_constructors_table.dat
`

**Comment by Tk-Glitch** [comment]
Any reason for using the 5.0 branch instead of 5.13?
It seems there was an update to the 5.0 branch in the meantime, deprecating the patchset. I'll get rid of it.

**Comment by ronoverdrive** [comment]
Honestly was re-using a separate configuration that I've been using for a while. Didn't realize I missed setting it of 5.13. Will fix that.
