### ISSUE TITLE
mistake at applying patches

### ISSUE THREAD

**Issue by chain2k** [Frogging-Family/wine-tkg-git#213]
HI, yesterday I've build wine-tkg-git without any problems. Today I've desided to try another options and can't build even the same config. And default config too. "Patch application has failed. "
Prepare.log in attachment 
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5540850/prepare.log)

**Comment by openglfreak** [comment]
Could we pleas stop getting this same issue report like every month?
Just wait for the next update or go back to the previous staging commit.

**Comment by AbsurdlySuspicious** [comment]
Last compatible commit is https://github.com/wine-staging/wine-staging/commit/41c7c741d7636af377874024e80a32e59c10e17a
