### ISSUE TITLE
Source Filmmaker Fails to launch with Proton-TKG 5.21, launches with Lutris 5.7 and Proton-GE 5.8

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/wine-tkg-git#217]
- System: Arch Linux
- Kernel: 5.9.9-95-tkg-cfs
- GPU: Radeon RX 580 with Mesa-tkg-git 21.0.0_devel.131228.fdfe4a4d307-1
- Log: [steam-1840.log](https://gist.github.com/HurricanePootis/92db8d50f79534cfa10947e07dfb2910)
- User_settings.py: [user_settings.py](https://gist.github.com/HurricanePootis/62571632be50ffbf3e5a556f8eeeed3a)

From my understanding, a newer version of DXVK in Proton-tkg 5.21 fixes an issue with memory, which is an issue in SFM when rendering volumetric lighting. Lutris 5.7 and Proton-GE 5.8 both are able to lunch the game, and produce normal renders, except for the volumetric problem. I have found no one else talking about this online, so I have decided to file a bug report :].

**Comment by Tk-Glitch** [comment]
I grabbed proton-tkg 5.8.0 release (https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.8.r0.g7d92cd31) for a try and it works there as well, so this looks like an upstream regression. I'll try to bisect.

**Comment by Tk-Glitch** [comment]
It actually works up to 5.19 then breaks on 5.20+. I have deprecated the ntdll refactor hotfixer path with 5.20, so unless that's a funny coincidence, it tends to solidify the upstream regression assumption.

**Comment by HurricanePootis** [comment]
Thanks for the info, Tk-glitch.
