### ISSUE TITLE
Can't use release version of DXVK because both dxvk-x.y.z and dxvk-tools exists

### ISSUE THREAD

**Issue by HugLifeTiZ** [Frogging-Family/wine-tkg-git#219]
Trying to build DXVK from git is failing for me on Xubuntu 20.04. So I tried to just use the release version, but I get an error from mv. So I stuck an `ls` in there, and...

```
#######################################################

 Downloading latest DXVK release from github for you...

#######################################################

dxvk-1.7.2	     PKGBUILD			   proton-tkg-profiles
dxvk-tools	     Proton			   proton-tkg.sh
external-ressources  proton_dist_tmp		   proton_tkg_token
gecko		     proton_template		   proton-tkg-userpatches
liberation-fonts     proton_tkg_5.22.r2.g0ae73155  README.md
mono		     proton-tkg.cfg		   vkd3d-proton
mv: target '/home/tiz/src/wine-tkg-git/proton-tkg/dxvk' is not a directory
```

Looks like the existence of both dxvk-tools and dxvk-1.7.2 in the directory is what causes the error.

Changing the problematic line to `mv "$_nowhere"/dxvk-*.* "$_nowhere"/dxvk` so that it doesn't catch dxvk-tools fixes it for me.

**Comment by Tk-Glitch** [comment]
Thanks!

Sidenote: DXVK now requires MingGW 8.0.0, which Ubuntu doesn't offer yet afaik. You can use https://github.com/Frogging-Family/mostlyportable-gcc as a temporary solution.
