### ISSUE TITLE
Proton fails to launch any game after final commit on 22/11/2020

### ISSUE THREAD

**Issue by kruesephiikz** [Frogging-Family/wine-tkg-git#220]
Line 512 of the main proton script contains `                "mfplay": "n" #disable built-in mfplay`

It is missing a comma, and therefore fails to continue on the next line referencing dotnetfx35.exe. Adding the comma back to it, `                "mfplay": "n", #disable built-in mfplay` fixes the issue.

**Comment by Tk-Glitch** [comment]
Thanks. As a side note, you will most likely want to drop `_proton_mf_hacks="true"` in your config for the best experience on latest versions.
