### ISSUE TITLE
configure: error: X 64-bit development files not found.

### ISSUE THREAD

**Issue by nipnipj** [Frogging-Family/wine-tkg-git#221]
I'm following this steps (https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git), but an error appeared. What do I do solve the following error?
```
checking for X... no
configure: error: X 64-bit development files not found. Wine will be built
without X support, which probably isn't what you want. You will need
to install 64-bit development packages of Xlib at the very least.
Use the --without-x option if you really want this.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

```

**Comment by nutta-git** [comment]
looks like you need to install `libx11-dev` 
https://ubuntu.pkgs.org/20.04/ubuntu-updates-main-amd64/libx11-dev_1.6.9-2ubuntu1.1_amd64.deb.html

**Comment by Tk-Glitch** [comment]
If you're using a debian based distro or fedora, set it in your `customization.cfg` file to help resolve dependencies:
```
# Set to the distro of your choice to attempt dependency resolution. Valid options are "debuntu" (for debian, ubuntu and similar), "fedora" or "archlinux".
_nomakepkg_dep_resolution_distro=""
```

**Comment by Tk-Glitch** [comment]
Closing.

Feel free to reopen if needed.
