### ISSUE TITLE
Assassin's Creed Valhalla crash on splash screen

### ISSUE THREAD

**Issue by LordDaveTheKind** [Frogging-Family/wine-tkg-git#227]
Hello,
I tried a few times today to run Assassin's Creed Valhalla (via Lutris and Ubisoft connect) with proton-tkg-5.22.r11.g47fea9ff. Here below the available build options:
(  TkG Staging Esync Vkd3d DXVK-Compatible )

The outcome is always the same: it throws an unhandled exception and crashes at the same splash screen (debug log here: https://pastebin.com/PiC1Z1Bi). It does not get to generate any line for the vkd3d-proton log.

Does anyone have any clue on what I can additionally check and/or fix? Do you need any specific info? 

kernel release is 5.8.7
Hw is NVidia GTX 1080 Ti (driver version 455.45.01).

Cheers,
Dave

**Comment by screwylightbulb** [comment]
Try compiling vkd3d-proton from source and then copying the 64 bit d3d12.dll directly into the directory where the game's exe is. Weird, I know, but this is how it managed to work here.

**Comment by LordDaveTheKind** [comment]
> Try compiling vkd3d-proton from source and then copying the 64 bit d3d12.dll directly into the directory where the game's exe is. Weird, I know, but this is how it managed to work here.

Tried also this way. Same result.

**Comment by LordDaveTheKind** [comment]
Hello,
Never mind. I made it run and successfully performed the in-game benchmark. 
The secret was to create an empty prefix, different than the Ubisoft Connect one.

Here below my additional setup:
 - Proton-TKG 6.0rc1.rc3.gfce121fc
 - dxvk commit 0b4e16. file d3d11.dll copied in the executable directory;
 - vkd3d-proton commit cf4fbe47. file d3d11.dll copied in the executable directory;
 - A clean Wine prefix;
 - Esync disabled;
 - Fsync disabled.

here the result: https://i.postimg.cc/rFGDSCCB/Screenshot-2020-12-07-23-33-33.png

Please let me know if you would like me to check anything specific about it. I will close this issue in the meantime.

Kind regards,
Dave

**Comment by screwylightbulb** [comment]
@LordDaveTheKind That performance wobble seems in line with what we experienced here while wine was logging. Can yuo try making sure all logging is suppressed? Like:
WINEDEBUG=-all WINEESYNC=1 VKD3D_DEBUG=none VKD3D_SHADER_DEBUG=none WINEPREFIX=bla etc.

Also this reminds me, looking at your post. I think it's fine to have esync on, even preferable.
