### ISSUE TITLE
Futex2 enabled builds?

### ISSUE THREAD

**Issue by holzi91** [Frogging-Family/wine-tkg-git#229]
Any chance for a build with the newer futex2 based fsync patch set?  Both Kernel and Proton need to be patched though. At least I guess so. Unfortunately there isn't much documentation on it.

Here are the links for collabora's gitlab repositories:

[Kernel](https://gitlab.collabora.com/tonyk/linux/-/tree/futex2-stable)

[Proton](https://gitlab.collabora.com/tonyk/wine/-/tree/proton_5.13)

**Comment by Tk-Glitch** [comment]
Added support through community patches with https://github.com/Frogging-Family/community-patches/commit/d33552342619e4e3b6d28c7347034e0eb53ae1fa
