### ISSUE TITLE
Elder Scrolls Online does not launch with proton-tkg 5.22.r2.g0ae73155

### ISSUE THREAD

**Issue by txtsd** [Frogging-Family/wine-tkg-git#230]
After hitting Play on the launcher, it creates a task in the taskbar and captures the mouse, but nothing is visible on the screen. Desktop and windows are still visible though.

Works fine with proton 5.13-2

**Comment by txtsd** [comment]
Fails with a different error on proton-tkg 6.0rc1.r0.gd7b71f0b
![2020-12-09-154541_1200x800_scrot](https://user-images.githubusercontent.com/768728/101616688-b3412200-3a35-11eb-9eb0-db3c0dbdbbf5.png)

**Comment by Tk-Glitch** [comment]
The issue should now be fixed on 6.0rc2.
