### ISSUE TITLE
Yakuza: Like a Dragon (1235140) does not recognise controllers

### ISSUE THREAD

**Issue by sonic2kk** [Frogging-Family/wine-tkg-git#231]
As of 6.0-RC-1, *Yakuza: Like a Dragon* does not recognise controllers. In Steam, it does not even show the controller configuration being loaded. When trying to enter inputs, nothing happens. Button prompts do not change from keyboard/mouse to controller, it is as if there is no controller connected at all. Proton-tkg 5.22 and below recognised controllers, and indeed Proton 5.13 recognises controllers. Proton-GE also works.

I tested some other games and they seem to recognise controllers fine with 6.0-RC-1, so far I haven't found any other games affected by this issue. The other Yakuza games, namely _Yakuza Kiwami 2_ which uses a similar engine, do not have any controller issues.

**Note**: Controllers for this game are incorrectly mapped due to a general game bug, so this isn't _too_ big of an issue as the game is unplayable with a controller at this moment in time. The point of this issue is to report that the controller isn't recognised at all.

**Comment by Tk-Glitch** [comment]
It *might* need `_gamepad_additions="true"` (which is not enabled by default in -tkg due to some other issues with different games). That patchset is part of both upstream proton and GE builds.

**Comment by sonic2kk** [comment]
Perhaps I enabled it wrong, but that didn't seem to work. I set the flag in `proton-tkg/proton-tkg.cfg`. And for clarity's sake for anyone reading this in the future, this source build was built against Wine 6.0-rc2 as opposed to rc1.

**Comment by sonic2kk** [comment]
Just updating to say the issue is still present in 6.0-rc3.

**Comment by sonic2kk** [comment]
To update: As of today's latest Proton Experimental build, controllers in *Yakuza: Like a Dragon* function correctly.

**Comment by Tk-Glitch** [comment]
Apparently it breaks steering wheels in other games as a result. The fun never ends :frog: 
Importing the change for yakuza behind a toggle sounds like the best idea.

**Comment by HurricanePootis** [comment]
> To update: As of today's latest Proton Experimental build, controllers in _Yakuza: Like a Dragon_ function correctly.

Did you build it with the game pad additions enabled, or not? I am having issues with controller detection in 6.0rc6 (nothing changed in build configs) on Yakuza 0.

**Comment by Tk-Glitch** [comment]
It might not be fixed (I don't have the game to check), so I'll reopen if the patch wasn't enough. Please let me know how it goes.

**Comment by sonic2kk** [comment]
I have both *Yakuza: Like a Dragon* and *Yakuza 0*, and a Steam Controller, so I'll make a fresh build of tkg later today and see how it goes.

**Comment by HurricanePootis** [comment]
I just tried Yakuza 0 with a fresh build of proton-tkg, and my steam control didn't work with normal Steam UI, nor Steam Big Mode.

Even though this issue is for Yakuza: Like a Dragon, I would imagine both games use the same input system.

**Comment by sonic2kk** [comment]
A bit late but I tried the latest release of Proton-tkg with *Yakuza: Like a Dragon*. Mirroring Proton Experimental builds, controllers are mapped mostly correctly, however with my Steam Controller the triggers are not recognised. However the initial issue of controllers not being recognised is solved. The issue with triggers is going to need to be fixed with further gamepad patches but that not the concern of this ticket, though I wanted to point it out all the same.
