### ISSUE TITLE
Patch application has failed. Fedora 33

### ISSUE THREAD

**Issue by tuxtergames** [Frogging-Family/wine-tkg-git#232]
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 310019789f7 dbghelp: Use WINELOADER environment variable from debuggee process in get_wine_loader_name.
 ==> WARNING: Hotfix: Revert bd27af97 to fix many game launchers displaying empty windows (StarCitizen, EGS, Riot Client, Minecraft Dungeons etc.)
 -> Hotfixing...
 -> Applying use_clock_monotonic.patch
 -> Applying childwindow.patch
 -> Applying steam.patch
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches...
 ==> ERROR: Patch application has failed. The error was logged to /home/tuxter/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="" in your .cfg
 -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5675359/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5675360/prepare.log)

**Comment by Tk-Glitch** [comment]
You are missing the autoconf make dependency (at the very least, as far as the log goes).

**Comment by tuxtergames** [comment]
> You are missing the autoconf make dependency (at the very least, as far as the log goes).

tks for replay, solved
