### ISSUE TITLE
Patch for vkQueueWaitIdle

### ISSUE THREAD

**Issue by rodrigorc** [Frogging-Family/wine-tkg-git#233]
Hi!
I noticed that you added my patch that includes a call to `vkQueueWaitIdle()` in ca7a68c, but then reverted it in 1cc5491d  citing "performance penalties".

I didn't notice such a penalty in the programs I use. Could you add details about this so that I can try and improve it?

I think this patch is mostly useful for GUI apps, not for games. In particular I find it essential for Autodesk Fusion 360. Without it, the UI is always one frame behind the program status. For games, maybe it is unnoticeable.

Anyway, I think that part of the problem may be that we are calling `vkQueueWaitIdle()` from inside a critical section. Maybe moving the call to just after `pvkQueuePresentKHR()` would be much more performant. Maybe you could test that?

Thanks!

**Comment by Tk-Glitch** [comment]
Hi!

The test case was the Cemu emulator. I got a user report complaining about frame pacing issues and much lower average framerates with the patch applied (only tested on Zelda: Breath of the Wild). I could reproduce it on a weak Intel iGPU with mesa/ANV.
I can definitely test your suggestion.

Thank you!

**Comment by rodrigorc** [comment]
I've just tried Cemu, with a less demanding game, and I see no diference with this patch or without it.
Maybe my Cemu installation is a bit old, and I'm using a Nvidia... but BotW in an emulation with an Intel GPU? I wouldn't expect it to work at all!

Reviewing my own patch, if you have the time, there is this other version I would like to test, the call is where it was, but the critical section is temporarily exited:
```
@@ -638,7 +640,10 @@ static VkResult X11DRV_vkQueuePresentKHR(VkQueue queue, const VkPresentInfoKHR *
             escape.code = X11DRV_FLUSH_GL_DRAWABLE;
             escape.gl_drawable = x11_surface->window;
             escape.flush = TRUE;
+            LeaveCriticalSection(&context_section);
+            pvkQueueWaitIdle(queue);
             ExtEscape(x11_surface->child_window_dc, X11DRV_ESCAPE, sizeof(escape), (LPSTR)&escape, 0, NULL);
+            EnterCriticalSection(&context_section);
         }
     }
     LeaveCriticalSection(&context_section);
```
Also it would be nice to know the value of `present_info->swapchainCount`. I've traced it and I never saw it different from 1 in any app or game. Maybe it it is >1 there are some extra optimizations worth doing.

**Comment by rodrigorc** [comment]
This patch does not apply anymore to the latest Wine. That, and the performance issues of before, makes it useless, so I'm closing this. Thanks anyway!
