### ISSUE TITLE
Patch application has failed

### ISSUE THREAD

**Issue by ReburonMaxus98** [Frogging-Family/wine-tkg-git#235]
Everytime i try to compile the wine-tkg using the [non-makepkg-build.sh](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/non-makepkg-build.sh) script it ends up with :

-> Applying proton-tkg-staging.patch
 ==> ERROR: Patch application has failed. The error was logged to /home/Bread/Desktop/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

in the prepare log only thing i found that could indicate what failed are these three lines:

patching file dlls/winegstreamer/gstdemux.c
Hunk #3 FAILED at 1051.
1 out of 3 hunks FAILED -- saving rejects to file dlls/winegstreamer/gstdemux.c.rej

here are the error logs and my customizaton file if it helps (i had to changethe customization extension to txt cause github doesnt let me upload it as cfg file)

[customization.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/5676878/customization.cfg.txt)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/5676879/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5676880/prepare.log)

i tried to download the whole repo again as it was reccomended in one of issues but with no avail also tried running it more times before redownlloading the repo and that didnt worked neither sadly and im not sure what i did wrong

**Comment by Hyper-KVM** [comment]
Can confirm, having the same exact issue.

**Comment by Tk-Glitch** [comment]
I was sleeping when the patch wave dropped. Fix incoming.
