### ISSUE TITLE
wine-tkg-git: Issues with makechrootpkg, jack/jack2

### ISSUE THREAD

**Issue by krathalan** [Frogging-Family/wine-tkg-git#237]
This issue is for wine-tkg-git, not proton-tkg.

If I try to use `makechrootpkg` with a clean chroot, I get the following error when installing dependencies before the build:

```
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...
:: jack2 and jack are in conflict. Remove jack? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: jack2 and jack are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
```

Specifying `jack2` in the `depends=()` array in the PKGBUILD fixes this issue and allows me to build wine-tkg-git.

**Comment by Thaodan** [comment]
Whats missing to fix this? This also affects plain Arch Linux, I'm not sure how this is distribution related.

**Comment by Tk-Glitch** [comment]
The issue is due to cross-dependency. Jack or Jack2 are no explicit dependency for wine. It seems to be a conflict somewhere possibly with the `ffmpeg` package which depends on the `jack` package explicitly, followed by another package which depends on `jack2` explicitly. I am not sure yet what depends on jack2 explicitly but that would need to be fixed there instead of on our side.

**Comment by ViNi-Arco** [comment]
Good afternoon, people..

The reason for that is, with **lib32-gst-plugins-good 1.18.1**, the dependency on [lib32-jack](https://github.com/archlinux/svntogit-community/commit/874c77eff0e29e7af589b8c4da8fa42b2f8db52a#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422L12-R12) has been added.
And Etienne's script has [lib32-gst-plugins-good](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/PKGBUILD#L114) as a build dependency, with this he informs the replacement of **lib32-jack** with **lib32-jack2**.

this during the build. then you can remove **lib32-jack2** and install **lib32-jack** again if you want it.
