### ISSUE TITLE
Rocket League: DS4 Controller input doesn't work

### ISSUE THREAD

**Issue by kescherCode** [Frogging-Family/wine-tkg-git#239]
This issue does not occur with official Proton 5.13-4, hence I'm submitting it here.

The game launches fine, however, it will not detect natively my DualShock 4 controller connected via Bluetooth, nor will it detect Steam Input's config, when enabled. Proton 5.13-4 will have Rocket League detect both just fine.

The issue has been tested with a fresh compile of both 9d2caf40a29cbe3833ba199c24f548a93f865fe5 and 59ef6e38e26f46991f1b07fad44f41053fb58f15.

**Comment by Tk-Glitch** [comment]
The DS4 is such a pita. Possibly same reason as https://github.com/Frogging-Family/wine-tkg-git/issues/231. The proposed solution is worth a shot.

**Comment by kescherCode** [comment]
The proposed solution does not change anything.

**Comment by kescherCode** [comment]
995402483cfdc53627c048ef3705d17b197dab92 fixes this issue. Closing.
