### ISSUE TITLE
Patch valve_proton_fullscreen_hack-staging

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#24]
Hello frogs,

The valve_proton_fullscreen_hack-staging patch doesn't apply : [log](https://github.com/Frogging-Family/wine-tkg-git/files/4527832/crash_wine-tkg.log)

Thanks for all

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/902b2ca07faf7576486a5db795f7060dadf7821d
