### ISSUE TITLE
CreateWindow Application tried to create a window, but no driver could be loaded.

### ISSUE THREAD

**Issue by nitish159** [Frogging-Family/wine-tkg-git#242]
While trying to run any app using wine or even winecfg, I get the following error:
```
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow The explorer process failed to start.

```
I tried the latest wine-tkg release `wine-tkg-staging-fsync-git-6.0rc2.r0.gc646dc92-311-x86_64`

I use an Arch system with `5.10.1-102-tkg-upds` kernel and using nvidia-dkms drivers if that helps

**Comment by nitish159** [comment]
Works with 6.0-rc3, closing

**Comment by Tcll** [comment]
what exactly is the fix for this error??

I get this error on every wine version from 6.0 to 9.0-staging-tkg with many games
but 5.6.5-tkg works perfectly fine (black screen from lacking visual support but they all run)

whatever the fix was for this might help me track down my issue.

**Comment by Tcll** [comment]
update, after swapping back to my nvidia card and reinstalling my nvidia drivers, everything works fine now (no change to my runners)

I can now say for a fact there was definitely some conflict going on where something in `/usr/lib/`...

whatever change you guys made regarding something in `/usr/lib/`for detecting the primary GPU between 5.7 and 6.0, I think you broke something :P

(same applies to proton as well)

**Comment by Tcll** [comment]
well so much for my last post, 6.0+ just randomly decided it was going to stop working for me again for no reason at all while 5.7 and below still work just fine :P

I'm completely stumped

whatever you guys broke between 5.7 and 6.0, I hope you figure it out :)
