### ISSUE TITLE
build automation with CI?

### ISSUE THREAD

**Issue by paulcarroty** [Frogging-Family/wine-tkg-git#243]
Github Actions & ~~Gitlab CI~~ provides a huge free credit theoretically enough for several distributions. Any plans to implement this?

**Comment by Tk-Glitch** [comment]
Yes. Most of it is ready for Github Actions. I need to polish it a bit and fix file uploading, but it's *slowly* coming.

**Comment by robigan** [comment]
So it's been 6mo but I want to do the same for the RoL community, has there been any update yet?

**Comment by paulcarroty** [comment]
Nope, nobody cares.

**Comment by Tk-Glitch** [comment]
I should take some time to finish this. Let's move it up in the priority list.
