### ISSUE TITLE
Monster Hunter: World (582010): ERR21: NVAPI error fffffffb

### ISSUE THREAD

**Issue by shumvgolove** [Frogging-Family/wine-tkg-git#246]
- System: Arch Linux
- Linux 5.10.2
- GPU: AMD RX590
- Mesa 20.3.1
- Logs: [steam-582010.log](https://github.com/Frogging-Family/wine-tkg-git/files/5742454/steam-582010.log)

MH:W crashes with `ERR21: NVAPI error fffffffb` before launching to main menu. `proton-5.0-10` works fine.

![image](https://user-images.githubusercontent.com/37271604/103142678-51acd300-4718-11eb-85fd-92ba9418fcfe.png)

**Comment by Tk-Glitch** [comment]
Simply disabling nvapi should fix it.

**Comment by shumvgolove** [comment]
Thanks for the hint!

**Comment by AllenyRED** [comment]
> 簡單地禁用 nvapi 應該修復它。

thanks it's work

**Comment by AllenyRED** [comment]
> Simply disabling nvapi should fix it.

thanks it's work
