### ISSUE TITLE
What is the difference between wine-tkg-git and wine-tkg?

### ISSUE THREAD

**Issue by Joe23232** [Frogging-Family/wine-tkg-git#250]
Hi, I am seeing two different repositories, wine is `wine-tkg-git` (which is this repo) and [`wine-tkg`](https://github.com/Tk-Glitch/wine-tkg).

I wanted to know what is the difference between the two repos and which one should I use?

**Comment by rboxeur** [comment]
Let's assume the KISS principle, Keep It Simple and Smart 
wine-tkg-git maintains code from

- wine git repository
- staging git repository
- and a huge set of patches from a lot of contributors (proton, mf (mfplat.dll...), patches for games and so on

wine-tkg-git aims at letting you merging all of this as you wish instead on using the usual packages from your own Linux distribution..

Example: wine + staging + proton patches + patches for particular games

All of theses are maintained using only shell scripts. That's the power of our favorite frog.

Somehow in the main process, then the wine sources have to be built. Then you get new wine sources. 
the "wine-tkg" you were pointing to on your message are supposed to be the new wine sources and they are supposed to be refreshed for every new wine-tkg build
Here the main maintainer forgot to synchronize them with the wine sources he got on his own PC with the remote repository "wine-tkg"

To reply to your question then yes you are supposed to use the repo here.

**Comment by Joe23232** [comment]
I see, thanks mate :)

**Comment by rboxeur** [comment]
You are welcome. **If you are on Arch the following information are useless.**

**I am sharing all these information hoping it can be helpful. Kron4ek did the most important job. I just re-use his work here**

My goal is just to share all knowledge I learnt from the 3 past months

To share more information. You don't have to be on Arch to use wine-tkg-git
I am on Xubuntu 20.04 and Kron4ek writes and maintain scripts and wine builds for Linux users based on wine-tkg-git too

His repo is https://github.com/Kron4ek/Wine-Builds 

Kron4ek does it by setting up 2 chroots based on Ubuntu 18.04. (named create_ubuntu_chroots.sh in his repo)
- a 64-bit chroot
- a 32-bit chroot
This Ubuntu version offers supports for both 64-bit and 32-bit chroots. That's the latest version supporting both 32/64-bit chroot
This is almost the same idea that it is shared on Wine wiki for WoW64 (Windows on Windows) that you can find here https://wiki.winehq.org/Building_Wine#Shared_WoW64

Assuming that your wine sources were generated by wine-tkg-git then once these chroots are up then he uses the second script (named "build_wine.sh") to build his own wine builds. I used Kron4ek's wine builds for more than one year and it works like a charm. One day I took decision to write my own scripts based on his scripts.

Based on Kron4ek's scripts, I slighty modified his modified scripts for my own purposes.
Thus it implies to understand how wine-tkg-git works.
The real needs are
1. Understand how wine-tkg-git works
2.  Let wine-tkg-git generate new wine sources
3. Prevent wine-tkg-git from building wine

Let's assume  you did this
cd 
git clone https://github.com/Frogging-Family/community-patches.git
git clone https://github.com/Frogging-Family/wine-tkg-git.git my_wine-tkg-git_cloned
cd my_wine-tkg-git_cloned

For set 1 above, I will recommend to have a look on the sample configuration file sample-external-config.cfg
cp my_wine-tkg-git_cloned/wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg ${USER}/wine-tkg-external-6.0-rc4.cfg
Then edit this file 
my_wine-tkg-git_cloned/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg 
to modify this line
_EXT_CONFIG_PATH=/home/<YOUR_USERNAME>/wine-tkg-config/wine-tkg-external-6.0-rc4.cfg

**To let wine-tkg-git generate new wine sources for 6.0 RC4  without building wine them then you can have a look on my own config file  here** 
http://techer.pascal.free.fr/download/wine/scripts/wine-tkg-external-6.0-rc4.cfg
**Keep it mind that it was used for Debian/Ubuntu not arch.**

Once your configuration file is ready then just do
cd my_wine-tkg-git_cloned/wine-tkg-git
./non-makepkg-build.sh
That shoudl take a while

After that there are the 2 chroots

git clone https://github.com/Kron4ek/Wine-Builds.git

It is almost safe to launch the first scrip create_ubuntu_chroots.sht.  I just recommend to modify this line in the script
export MAINDIR=/opt/chroots
to point to another path based on a device with enough free space.
then you can launch it
./create_ubuntu_chroots.sh
Ok now you will have both
1. from wine-tkg-git: your new wine sources properly patched
2. from Kron4ek: your new chroots
Then all you need now is to work on his second script. build_wine.sh
I wrote my own script based on this script if it can help you

http://techer.pascal.free.fr/download/wine/scripts/build_all-wine-6.0rc4.r0.g350eb136-staging-tkg-amd64.sh

**Comment by Joe23232** [comment]
Thanks mate for the information but yeah I am on Arch 👍 

By the way does `wine-tkg-git` by default come with patches without me having to do anything other than building it right from source?

**Comment by rboxeur** [comment]
Let's say that 85% are inside the repository
but I recommed to do it this way at this level-folders

cd
# Repo from community
git clone https://github.com/Frogging-Family/community-patches.git
# Repo from wine-tkg-git
git clone https://github.com/Frogging-Family/wine-tkg-git.git my_wine-tkg-git_cloned

"community" is required if you want to add more patches for exqmple inside your configuration files

community_patches="amdags.mypatch winex11-fs-no_above_state-nofshack.mypatch"

**Comment by rboxeur** [comment]
The two repositories have to be at the same level-folder
example here at the same leve-folder for your $HOME
cd $HOME
git clone  https://github.com/Frogging-Family/community-patches.git
git clone https://github.com/Frogging-Family/wine-tkg-git.git my_wine-tkg-git_cloned

**Comment by Joe23232** [comment]
I see, thanks mate but one thing I don't get

> community_patches="amdags.mypatch winex11-fs-no_above_state-nofshack.mypatch"

Where do I add this line exactly?

**Comment by rboxeur** [comment]
Proton patches are already inside wine-tkg

Just have a look on this sample 

http://techer.pascal.free.fr/download/wine/scripts/wine-tkg-external-6.0-rc4.cfg

bottom of file above 

Quoted from my first reply -- just copied/pasted below

Let's assume you did this
cd
git clone https://github.com/Frogging-Family/community-patches.git
git clone https://github.com/Frogging-Family/wine-tkg-git.git my_wine-tkg-git_cloned
cd my_wine-tkg-git_cloned

I will recommend to have a look on the sample configuration file sample-external-config.cfg
cp my_wine-tkg-git_cloned/wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg ${USER}/wine-tkg-external-6.0-rc4.cfg
Then edit this file
my_wine-tkg-git_cloned/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg
to modify this line
_EXT_CONFIG_PATH=/home/<YOUR_USERNAME>/wine-tkg-external-6.0-rc4.cfg

**To let wine-tkg-git generate new wine sources for 6.0 RC4 without building wine them then you can have a look on my own config file here**
http://techer.pascal.free.fr/download/wine/scripts/wine-tkg-external-6.0-rc4.cfg
**Keep it mind that it was used for Debian/Ubuntu not arch Modify it to cover your needs**

**Comment by rboxeur** [comment]
In a nutshell
1. Edit the file wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg to point to a configuration file
_EXT_CONFIG_PATH=/home/<YOUR_USERNAME/some_configuration.cfg
2. Modify the file some_configuration.cfg. You can have a sample configuration at wine-tkg-profiles/sample-external-config.cfg. 
3. When ready launch the process

cd wine-tkg-git
./non-makepkg-build.sh

Good luck :)

**Comment by Joe23232** [comment]
Thanks mate =D

**Comment by Tk-Glitch** [comment]
Closing :)
