### ISSUE TITLE
Unable to install it on Arch-based systems

### ISSUE THREAD

**Issue by Joe23232** [Frogging-Family/wine-tkg-git#252]
I ran this command

```makepkg -si```

after I did `cd` inside the `git clone`d directory and it failed

Error message: ```==> ERROR: PKGBUILD does not exist.```

Any idea how to fix this?

**Comment by Valmar33** [comment]
Assuming you want to install wine-tkg... you would want to `cd` into `wine-tkg-git/wine-tkg-git`. `PKGBUILD` resides there.

**Comment by Joe23232** [comment]
I see, my mistake, thanks :)

**Comment by kescherCode** [comment]
(this issue can be closed)
