### ISSUE TITLE
Add _staging_userargs option to proton-tkg advanced-customization.cfg

### ISSUE THREAD

**Issue by Valmar33** [Frogging-Family/wine-tkg-git#256]
https://www.phoronix.com/scan.php?page=news_item&px=Wine-Staging-6.0-RC5

https://bugs.winehq.org/show_bug.cgi?id=50292

ntdll-NtAlertThreadByThreadId patchset is causing performance hits in various games. Personally, I've noticed it causing odd random freezing in The Witcher 3.

**Comment by smo0z** [comment]
It can be disabled in ../wine-tkg-profiles/advanced-customization.cfg with _staging_userargs="-W ntdll-NtAlertThreadByThreadId"
But i don't know if the same is possible with proton-tkg. there is no such variable and i didn't test if it gets used if i just paste it in its config.

Another game where this patchset causes freezes is FFXIV.

**Comment by Valmar33** [comment]
I see! Didn't see `_staging_userargs` in `proton-tkg/proton-tkg-profiles/advanced-customization.cfg`, so I somehow assumed mistakenly that there was no such option...

Hmmmmmm...

**Comment by AdelKS** [comment]
I think TKG will patch it out till it gets figured out soon. Thanks for the `advanced-customization.cfg` tip @smo0z ! I only use it to test wild compiler flag and activate `nvidia-hate` :sunglasses:
