### ISSUE TITLE
issue when downloading world of warcraft

### ISSUE THREAD

**Issue by upsetgamer** [Frogging-Family/wine-tkg-git#257]
I am having an issue when downloading wow through lutris. I downloaded wine and it's dependencies, also got the lutris and battlenet dependencies. Yet when I try to download, I can only get so far into the download before this string of text appears.

Running /home/upsetgamer/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/wine /home/upsetgamer/.cache/lutris/installer/world-of-warcraft/setup/Battle.net-Setup-enUS.exe
Initial process has started with pid 23320
Start monitoring process.
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 6.0-rc1 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0024:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0108:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0108:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STU
0124:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0124:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0124:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0124:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0124:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_IGNORE_OFFLINE: STUB
0138:fixme:ver:GetCurrentPackageId (013FFEF0 00000000): stub
012c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="[http://www.blizzard.com/404](http://www.blizzard.com/404)">here</a>.</h2>

Initial process has exited (return code: 0)
0190:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0124FEF4
0188:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0224:err:ole:com_get_class_object apartment not initialised
0224:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0069FEAC
0230:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0230:fixme:wbemprox:client_security_SetBlanket 62EA0768, 00A75B48, 10, 0, (null), 3, 3, 00000000, 0x00000000
0230:fixme:wbemprox:client_security_Release 62EA0768
0230:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0230:fixme:wbemprox:enum_class_object_Next timeout not supported
0240:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0232FEF8
0230:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0230:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0230:fixme:wbemprox:client_security_SetBlanket 62EA0768, 00AB40F0, 10, 0, (null), 3, 3, 00000000, 0x00000000
0230:fixme:wbemprox:client_security_Release 62EA0768
0284:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
0284:fixme:toolhelp:Heap32ListFirst : stub
0244:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
0244:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
0244:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
0244:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)

**Comment by Tk-Glitch** [comment]
> 012c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

This is typically covered by the `samba` package on Archlinux. Probably not the main issue though.
Your issue looks similar to what others have experienced on 6.0rc1. There has been quite a few regressions in 6.0rc1 and most of them are now resolved in the 6.0 release version.

**Comment by Tk-Glitch** [comment]
Considering this as fixed. Please reopen if it's still happening on current versions.
