### ISSUE TITLE
Proton-tkg: can't even attempt to use staging on latest Wine git

### ISSUE THREAD

**Issue by Iron-Overheat** [Frogging-Family/wine-tkg-git#265]
Expected behavior: Script attempts and (I would guess, probably) fails to apply Staging patches on top of latest Wine git non-release (commit 00401d2 as of writing this)

Actual behavior: Script automatically switches HEAD to commit Wine Staging is based on, ignoring any preference for latest Wine git when not matching the base for Wine Staging

I think users should have the choice to use wine combinations that are potentially broken just out of user choice even if a warning is required.

This is using proton-tkg, unsure about the behavior on wine-tkg
P.S.: Not a programmer

**Comment by Tk-Glitch** [comment]
This should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/ca8e12114c8c02b5e20ef59a9eb7f3bf6dd31dee

Similar to https://github.com/Frogging-Family/wine-tkg-git/issues/266
