### ISSUE TITLE
proton-winevulkan-nofshack patching failed

### ISSUE THREAD

**Issue by qwert0p** [Frogging-Family/wine-tkg-git#273]
I tried to compile last wine-tkg-git with osu profile(without profile i have same issue), this issue should be fixed on the ca8e12114c8c02b5e20ef59a9eb7f3bf6dd31dee but no, [last prepare.log part](https://pastebin.com/3AfYVGdK) and a [console output](https://pastebin.com/Cp9NU7mf) 
Maybe i did something wrong, but anyway.

**Comment by bachstudies2020** [comment]
Same here...

**Comment by Tk-Glitch** [comment]
This was fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/a3748826bb3d1696faf2585b7bf662ac6f1fa7d8
Make sure you have latest changes pulled in.
