### ISSUE TITLE
Gallium Nine Not Enabling Even When Set On

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/wine-tkg-git#275]
Whenever I render in SFM, DXVK usually produces 100% normal results, unless I am doing something with volumetric lighting (crashes SFM). I noticed that proton-tkg has the option to enable Gallium Nine, with the `PROTON_USE_CUSTOMD3D9` in the `user_settings.py` file. However, even when set, and with the package `wine-nine` installed, DXVK is used. A new DXVK cache is generated next to the binary, and with `DXVK_HUD` set to full, I see everything.

I am using linux510-tkg-cfs `5.10.10-115`, with proton-tkg-version `6.0.r0.g2414b1da-1`, and Wine-Nine version `0.7-1`
[Steam Hardware Information](https://gist.github.com/HurricanePootis/471b993e36a98037da2af4cdcd08d5c5)
[User Settings](https://gist.github.com/HurricanePootis/1d523150bc77c5741fd28b7abef24841)

**Comment by Tk-Glitch** [comment]
To make use of that feature in proton-tkg, you need to install gallium nine standalone (through the winetricks integration for example). The wine-nine package is completely useless in this case.

**Comment by HurricanePootis** [comment]
Alright, thanks for clearing it up for me.
