### ISSUE TITLE
proton-tkg-staging.patch fails to apply with _clock_monotonic=false

### ISSUE THREAD

**Issue by openglfreak** [Frogging-Family/wine-tkg-git#277]
The "ntdll: Use clock_gettime64 if supported." commit needs to be split.

**Comment by Tk-Glitch** [comment]
We could actually move it to the clock monotonic patchset I suppose

**Comment by openglfreak** [comment]
Wait now nobody with _clock_monotonic=false gets the commit

**Comment by Tk-Glitch** [comment]
I thought it was obvious :frog:
The better question would be why you wouldn't want to enable the clock monotonic patchset :frog:

**Comment by openglfreak** [comment]
I'm sure CLOCK_MONOTONIC_RAW is used for a reason by default, and it has been [implemented in vdso](https://bugzilla.kernel.org/show_bug.cgi?id=198961) for quite a while now (since kernel 5.3).
Idk why it would still be slower than CLOCK_MONOTONIC, it probably isn't, so I always keep _clock_monotonic disabled.
