### ISSUE TITLE
PSA: Building wine-staging 5.20 and older fails

### ISSUE THREAD

**Issue by Tk-Glitch** [Frogging-Family/wine-tkg-git#281]
It looks like there is an issue on legacy staging trees.. So far it seems to point to an autotools update breaking things. I have not yet been able to track down the breaking point, but 5.20 and older is failing to build. This is not a wine-tkg issue, this happens on stock staging.

**Comment by ViNi-Arco** [comment]
Everything indicates that it is the new versions of Autoconf.

I tried to compile Wine 5.7 and it fails with this [exact problems](https://github.com/wine-mirror/wine/commit/d7645b67c350f7179a1eba749ec4524c74948d86) that the Wine team fixed for versions 5.21 and above

**Comment by Tk-Glitch** [comment]
I'll add the patch selectively for older versions tomorrow.
