### ISSUE TITLE
fsync-unix-staging.patch failing to apply.

### ISSUE THREAD

**Issue by Spoons** [Frogging-Family/wine-tkg-git#284]
Thanks for sharing your froggy builds. 

The fsync-unix-staging patch is throwing up a hunk failure. I've attached the prepare log.
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5929856/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/a0d6adb39fc9662fd1ced91e49542f58711e58e2
