### ISSUE TITLE
Proton-tkg: Patch Application has failed

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#286]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5978770/prepare.log)

As always: Thanks alot for you great work!

**Comment by Tk-Glitch** [comment]
Your proton-tkg/wine-tkg-git tree doesn't seem to be up to date. That issue was resolved days ago :frog:

**Comment by ninelore** [comment]
lol mb sry

**Comment by Tk-Glitch** [comment]
Happens to the best of us!
