### ISSUE TITLE
League of Legends broken

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#29]
Hi Frogs,

Wine Version : 
* wine-tkg-git-5.6.1.r2.g4861c47f work (but another computer that use the backend WineD3D)
* wine-tkg-git-5.6.1.r14.g77d29cbe ([last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4535495/last_build_config.log)) don't work
* wine-tkg-git-5.7.r0.g2ad422ff don't work

For me, when the select champ is over, I can't get into the game and the client is completly freeze. The command `WINEPREFIX=/path/to/prefix/ /path/to/wineserver -k` has no effect. Indeed, the process `wineserver` doesn't exist (crash probably) and I need restart my computer for kill all Wine process.
Without `WINEDEBUG=-all`, I have this errors in the terminal :
```
01bd:err:ntdll:RtlpWaitForCriticalSection section 0x7bd6d220 "../../../wine-mirror-git/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 01bd, blocked by 01c5, retrying (60 sec)
01c9:err:ntdll:RtlpWaitForCriticalSection section 0x7bd6d220 "../../../wine-mirror-git/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 01c9, blocked by 01c5, retrying (60 sec)
0087:err:ntdll:RtlpWaitForCriticalSection section 0x7bd6c9c0 "../../../wine-mirror-git/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0087, blocked by 0086, retrying (60 sec)
```

Edit : https://bugs.winehq.org/show_bug.cgi?id=49011

**Comment by IroAlexis** [comment]
I just took a look at the bugzilla. There seem to be almost similar problems to mine. Should I close the issue or not?

**Comment by IroAlexis** [comment]
With the last commit (this nigth), leagueoflolfix.patch doesn't apply. Here is the [errors](https://github.com/Frogging-Family/wine-tkg-git/files/4542210/crash_wine-tkg.log)

**Comment by Tk-Glitch** [comment]
Yeah, quite a few patches to fix tonight. Working on it.

**Comment by IroAlexis** [comment]
Nice with the commit [06d30b7](https://github.com/Frogging-Family/wine-tkg-git/commit/06d30b7b49573e1761b566a98ee0c8eae15cafa3), it is fixed !!

Thanks for your job :D
