### ISSUE TITLE
Add a patch for FL Studio 20.08

### ISSUE THREAD

**Issue by kajlando** [Frogging-Family/wine-tkg-git#291]
So there's a patch for FL Studio 20.08 because it doesn't work and WINE is in a "code freeze" state so they haven't included it yet..
It would be rad if you could add it!
https://bugs.winehq.org/show_bug.cgi?id=50362
Please and thank you : )
https://bugs.winehq.org/attachment.cgi?id=68970&action=edit

**Comment by kajlando** [comment]
There's even a custom build of wine that makes it work but it's 6.0 r2 and in this version backspace closes some windows which isn't the case on newer versions.
https://drive.google.com/file/d/1WO9IFdREbhPDNshf__aoUZRpSWXBVxvq/view

**Comment by kajlando** [comment]
Any change to add this patch to 6.4?
https://bugs.winehq.org/attachment.cgi?id=69604&action=edit

**Comment by kajlando** [comment]
Unfortunately this bug still happens even with this fix. I guess it's not your fault. Thanks for your time anyway!

**Comment by kajlando** [comment]
Oh I used prebuilt build. I'll try to build it myself!

**Comment by kajlando** [comment]
So I build it with makepkg -si but I'm not an advanced user so I don't really know how to apply the patch. 
_Is it not possible to merge it into prebuilt build?_  There's already an old version of wine with this patch built-in.

**Comment by redgloboli** [comment]
create a file  ~/.config/frogminer/wine-tkg.cfg

put the following  line in that file: 

_community_patches="Add-SORT_DIGITSAS-UMBERS-flag-to-CompareStringsEx.mypatch"

compile again.

**Comment by kajlando** [comment]
Okay wasn't that hard...
Though I still wonder why this isn't enabled by default (?).
