### ISSUE TITLE
Request for permission to publish compiled versions for Debian

### ISSUE THREAD

**Issue by ObscureXwing** [Frogging-Family/wine-tkg-git#293]
3 days passed, I wrote on email tkg@froggi.es but there was no answer, I ask you not to be angry with me because I leave it in issues, I am not strong on licensing issues, and I do not want to accidentally violate anyone's copyright, in the message that I sent on email was the following content:

Hi, my name is Simon, I am actively interested in the development of Linux, I would like to ask you a few questions if it does not make it difficult for you to answer them, and if you have time to answer me, I am grateful in advance for the time devoted to me! I have my own YouTube channel, my main language is Russian, on this channel I also lead in Russian, but soon I want to add English subtitles to expand the reach of the audience.. And recently one of the subscribers asked me a question, "how can I play windows games on Debian," and for a month now I have been actively studying the means by which I could make the installation of Wine with support for F-Sync, Futex2, patches used in Proton, as simple as on Arch Linux, but for Debian users! And I happened to stumble upon your tools for build, wine-tkg-git and linux-tkg for kernels, but I found no mention of any license to use or distribute the compiled versions as result obtained with your tools! On this I would like to start by asking my basic question, can I use your build tools to regularly publish on my GitHub repository compiled versions of kernels and Wine necessary to support the latest Windows games for Debian? So that people do not have to compile again every time, but can download the compiled version and script for installation using my repository on the GitHub? In doing so, certainly I could in the Readme.MD file indicate links to your tools and indicate nicknames and/or contacts to contact people who have contributed greatly to the creation of these tools, and if you do not allow me to do this, I will not try to do it in dishonest ways, I understand everything and I do not want enmity and misunderstandings, I am a simple person who wants to help other people, and therefore I ask a similar question, Thank you so much for your time reading my message!

Respectfully, Simon (ObscureXwing)

**Comment by Tk-Glitch** [comment]
Replied by email :)
