### ISSUE TITLE
GuildWars 2 can't login

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/wine-tkg-git#294]
For some strange reason after updating wine from 6.0 stg to 6.3 stg, guildwars 2 can't login. it can update the game but it just can't login. i've tried another version from lutris and its working fine. it seems that on ubuntu works too (not sure if it v 6.3).
i didn't modified anything in customization.cfg. 
i've tried diablo 3 and it seems there is no problem there.

**Comment by faiden** [comment]
Same proplem
I got it working with: wine-tkg-staging-fsync-git 6.2.r0.g3b5ea332-320
I tried compiling git and unable to login.
Unmodified customization.cfg.
Linux 5.11.2-zen1-1-zen

**Comment by Tk-Glitch** [comment]
Weirdly I have no issue logging in on my end on current HEAD. It failed once and never after. I'm still running kernel 5.10 but I have high doubts it's related.

**Comment by logan001** [comment]
i've just rebuild (wine-6.3.r16.ga11594e1) it and still same problem
i'm on 5.11.4-133-tkg-pds

**Comment by faiden** [comment]
Rebuild myself (wine-tkg-staging-fsync-git-6.3.r16.ga11594e1-322).
It could download and install the patch but not login.

Vent back to wine-tkg-staging-fsync-git 6.2.r0.g3b5ea332-320 and can login without a problem.

**Comment by Tk-Glitch** [comment]
There probably a regression here. After retesting, it actually fails until I enter a wrong password. I'll then get the normal error about wrong password/login, and I can login just fine after that.

**Comment by Tk-Glitch** [comment]
Or maybe not. It seems to be random at this point. It just looks like it'll eventually succeed after multiple tries.

**Comment by rrrakyah** [comment]
I had this issue over the past couple days and somehow managed to fix it today, with wine-6.3.r18.g3790a70 atleast

I dont know what exactly it was that managed to make it work, but I did the following:
-Deleted my whole prefix and created a new one
-Reinstalled GW2 with the the actual installer .exe from the official site, not the Lutris script
-The installer, once it asks you for a login, failed to be able to reach it
-Installed DXVK into the prefix and also ran 'sudo setcap cap_net_raw+epi /usr/bin/wine-preloader'
-Set the prefix to run under a Virtual Desktop, though that probably didnt change anything
-Pointed Wine to run the actual launcher now, not the installer
-Now can login just fine and downloads fine

If I dont forget, Ill try to report back later if/how it runs

**Comment by logan001** [comment]
ok i've tried the 6.3 staging on mint and it has the same problem. so its not a problem of tkg version but with wine itself
