### ISSUE TITLE
Can't build on Linux Mint 20.1

### ISSUE THREAD

**Issue by mozo78** [Frogging-Family/wine-tkg-git#296]
Hello,
After I install the dependencies needed, the script doesn't complain for missing packages, it compiles the source normally but when it finishes without any errors, there's no Wine build anywhere. Can you help me please? Thank you :)

**Comment by Tk-Glitch** [comment]
If it indeed built fine, you'll find your build in the `non-makepkg-builds` folder, in the same dir as the build script.

**Comment by mozo78** [comment]
Yes I know but there's no `non-makepkg-builds` folder at all.
Thank you for your reply :)

**Comment by Tk-Glitch** [comment]
Then it didn't build successfully. What's the tail of the terminal output?

**Comment by mozo78** [comment]
I'll restart for I use Arch as a main OS and Mint is for tests only and I will write you back when it's done.

**Comment by dreamhunt** [comment]
Here's a some portion of the tail input:
https://pastebin.com/3yDhhxMb

**Comment by Tk-Glitch** [comment]
Looks like you're missing the `libxi-dev` dependency.

**Comment by dreamhunt** [comment]
Thank you :)
I installed libxi-dev and libxi-dev:i386 but now it gives this error:

make: *** [Makefile:14767: dlls/bcrypt/gnutls.o] Error 1
make: *** Waiting for unfinished jobs....
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real	2m26,948s
user	33m36,439s
sys	2m21,536s

 -> Compilation time for 32-bit wine: 

real	0m9,452s
user	0m28,605s
sys	0m3,073s
I installed gnutls-bin and gnutls-bin:i386 to no avail.

**Comment by mozo78** [comment]
I'm sorry, it seeme on Mint I'm logged in with a different account and I didn't noticed it. Here I am with the OP's account :)

**Comment by Tk-Glitch** [comment]
Can you please add a longer log containing the actual error like you did earlier? Thanks!

**Comment by mozo78** [comment]
Here you are:
https://pastebin.com/dLaV2RCe

**Comment by Tk-Glitch** [comment]
We have a community patch for that one: https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/wine-fix-gcc10.mypatch
No idea why it only affects *some* machines.

**Comment by mozo78** [comment]
Thank you :)
How can I apply it?

**Comment by Tk-Glitch** [comment]
Set `_community_patches="wine-fix-gcc10.mypatch"` in `customization.cfg` (or your own external config if you're using one).

**Comment by mozo78** [comment]
Unfortunately there's still no folder with a build:
https://pastebin.com/S5iTeFB3

**Comment by Tk-Glitch** [comment]
Have you seen any prompt regarding the patch? It doesn't look like it's been applied.

**Comment by Tk-Glitch** [comment]
The string *should* be enough. Alternatively, you can grab the patch file and drop in inside the `wine-tkg-userpatches` dir next the build script.

**Comment by mozo78** [comment]
When I manually added the patch to wine-tkg-userpatches, now it asks me if I want to apply it but when I choose to apply it, it gaves an error:

```
/home/mozo/wine-tkg-git/wine-tkg-git/wine-fix-gcc10.mypatch
Do you want to install it/them? - Be careful with that ;)
> N/y : y
 -> ######################################################
 -> 
 -> Applying your own plain-wine patch /home/mozo/wine-tkg-git/wine-tkg-git/wine-fix-gcc10.mypatch
 -> 
 -> ######################################################
patch: **** malformed patch at line 17: */

 ==> ERROR: Patch application has failed. The error was logged to /home/mozo/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```
Here's the prepare.log content:
https://pastebin.com/RehvZ0dq

**Comment by Tk-Glitch** [comment]
Yet the patch is fine. I just tested it. Did you edit it or something?

**Comment by mozo78** [comment]
No, I just copied the patch code, created a file with wine-fix-gcc10.mypatch name, pasted the copied code and placed in `/wine-tkg-git/wine-tkg-git/wine-tkg-userpatches`

**Comment by mozo78** [comment]
I copied the code again and now the patch has been applied. Now the script is building. I'll tell you wat happens when it finish.

**Comment by mozo78** [comment]
Yes! Finally there's a build! Thank you very much!!!

**Comment by Tk-Glitch** [comment]
You're welcome!
