### ISSUE TITLE
Question regarding FastSync2

### ISSUE THREAD

**Issue by rboxeur** [Frogging-Family/wine-tkg-git#298]
Salut/Hello

Tout d'abord merci pour votre travail/Thanks for all your contributions to Wine Community

Something is not clear regarding wine-fastsync2
In your repository it is written
commit 06b2afe144d499284f7dd954711aebee81b819a1
Author: Tk-Glitch <ti3nou@gmail.com>
Date:   Sat Mar 13 23:49:52 2021 +0100

    Add a patch for wine fastsync, an experiemental replacement for esync/fsync.
    
    Requires a patched kernel (see linux511-tkg)
    
    https://repo.or.cz/wine/zf.git/shortlog/refs/heads/fastsync2

There is no patch found in the subfolder linux511-tkg https://github.com/Frogging-Family/community-patches/tree/master/linux511-tkg 

If we really need a patch for Linux then where can we find it?

I was able to build it with fastsync2 support added following specifications -- based on your recommendations taken from notes in 'git log'

use_fastsync="true
_use_esync="false"
_use_fsync="false"
_use_staging="false"

Then once build 
WINE_DISABLE_FAST_SYNC=0
I tested a game . My game wokrs. I got almost the same FPS. but I am not pretty sure if I missed something if we need to patch a Linux Kernel? Do we need a new particular patch.

Can you please clarify?

Regards.

**Comment by Tk-Glitch** [comment]
The kernel patch is not in community patches, it's part of the patches offered by linux-tkg as is. Here you go: https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/5.11/0007-v5.11-winesync.patch

**Comment by rboxeur** [comment]
Merci Master ;)
You can fermer le ticket.
Cocorico ;)
