### ISSUE TITLE
Guild Wars 2 launcher unable to login with 6.4

### ISSUE THREAD

**Issue by txtsd** [Frogging-Family/wine-tkg-git#299]
Could be affected by old versions too.

It works fine with lutris' wine 5.7-11 build.

EDIT: Let me know if you need a log.

**Comment by Berobad** [comment]
https://bugs.winehq.org/show_bug.cgi?id=50738

**Comment by txtsd** [comment]
Thanks. Didn't realize it was an upstream bug.

**Comment by Tk-Glitch** [comment]
The bug has been fixed upstream. Closing.
