### ISSUE TITLE
Doom Eternal fails to quit

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#306]
After quitting doom eternal, steam still shows it as running although I'm on the desktop
Force quitting with steam actually kills wineserver

**Comment by Tk-Glitch** [comment]
Yeah there's an issue with proton's steam helper on recent wine. It only affects *some* games, and it seems pretty random, depending on the game. The fix will most likely land along with the 6.x based Valve proton repo update.

In the meantime and if force quitting is problematic, bypassing the helper by disabling it works around the issue but some games/DRMs with heavy checks might refuse to work (not sure if Doom Eternal is one of them).

You can disable steam helper by setting `_proton_use_steamhelper="false"` (default is "true") in `proton-tkg/proton-tkg-profiles/advanced-customization.cfg` or in your external config.

**Comment by shaumux** [comment]
Is it a compile-time option only? Is it possible to disable it at runtime by adding any ENV variables?

**Comment by Tk-Glitch** [comment]
No, but you can do some manual edits to disable it without a recompilation.
See https://github.com/Frogging-Family/wine-tkg-git/blob/master/proton-tkg/proton_template/steam.exe.patch

Basically you want to revert the patch. So you can either reverse-apply it directly to your build's `proton` script (`$HOME/.steam/root/compatibilitytools.d/proton_tkg_*/proton`) with `patch -Np1 -R "patchname"` or make the changes by hand in a text editor. Green lines need to be replaced with the red ones, and the additional line at the beginning should be removed.
