### ISSUE TITLE
Nova Ragnarok crashing when speaking with some npcs.

### ISSUE THREAD

**Issue by ltsdw** [Frogging-Family/wine-tkg-git#307]
Steps to reproduce:

1 - creating a new character (or log in with an existing one)
2 - log with the char
3 - type '@go mh' in the chat (this will sent you to monster hunter place to start the quest) / (also is possible to reproduce this on another places, but this one is easier)
4 - enter the first building after being warped (a 'cut scene' will start, with dialogs and 'cutins' (images of the npcs that you are talking to), also is here that the crash happens

heres is a [log.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6201212/log.txt).

I was trying debug to solve it myself but my wine-fu isn't that good.

Something that got my attention was these lines:
```
0024:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
0024:warn:file:NtCreateFile L"\\??\\C:\\Games\\NovaRO\\dbghelp.dll" not found (c0000034)
0024:warn:menu:grab_menu_ptr invalid menu handle=00000002
0024:warn:menu:MENU_SetMenu hMenu 00000002 is not a menu handle
0024:warn:dialog:DIALOG_CreateControls32 control L"Button" L"Copy" creation failed
```
And the fact that sometimes if WINEDEBUG=warn+all is set, (maybe) the game doesn't crash (maybe an race condition is happening?). I thought about changing `grab_menu_ptr` and `MENU_SetMenu` to ignore invalid handles, but those are just warnings right? Maybe they aren't the cause of the crash.

Any thoughts?

**Comment by Tk-Glitch** [comment]
Was this fixed?

**Comment by ltsdw** [comment]
I do think so, [51518](https://bugs.winehq.org/show_bug.cgi?id=51518), I'm unable to reproduce it on new versions of wine.
