### ISSUE TITLE
Latest build 6.4-r11 fails to launch anything but builds ok

### ISSUE THREAD

**Issue by mixalis1987** [Frogging-Family/wine-tkg-git#308]
Built the packages twice and all looks fine, however when launching the prefix, it gets built but its wrong. Missing program files folders and the windows folder has system32 and syswow64 but they are empty folders.

wine starting winecfg in terminal i get this;
`wineserver: using server-side synchronization.
002c:err:seh:segv_handler_early Got unexpected trap 14 during process initialization
0024:err:environ:run_wineboot failed to start wineboot c00000e5
0024:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 6.4 is a testing version containing experimental patches.
0024:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0034:err:seh:segv_handler_early Got unexpected trap 14 during process initialization
003c:err:seh:segv_handler_early Got unexpected trap 14 during process initialization
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100`

I don't think it's an issue on my end as the build i did last week was ok. No errors in the building proccess.
Any ideas? 

Using Manjaro

**Comment by mixalis1987** [comment]
The problem is when compiling with staging. With staging disabled the package builds and works to creat a proper prefix. Not sure if the problem is here or at winehq

**Comment by IDeathByte** [comment]
same problem.

**Comment by mixalis1987** [comment]
> same problem.

For now use another version of staging in the customization.cfg file. I think the problem is with staging master. I'm testing some builds out. I've currently built 6.4-r8 and I'm going up until it breaks, so I know what commit breaks it.

**Comment by mixalis1987** [comment]
It's wine-staging master the problem. Just tested.

**Comment by Iglu47** [comment]
this is probably the same bug as on main Wine https://bugs.winehq.org/show_bug.cgi?id=50858
reverts should help
```
    git revert --no-commit 47fed8f5bc89344af054b70c2d3a7bea02b2113c
    git revert --no-commit 34884bf5d071418e3c25e521236361e62e308025
    git revert --no-commit 28fe84da45bea7de56539b50eac8ebcec54342de
```

**Comment by Tk-Glitch** [comment]
The problem has been resolved upstream. Closing.
