### ISSUE TITLE
proton-tkg.sh fails on Ubuntu 20.10 at vkd3d-proton

### ISSUE THREAD

**Issue by enveeed** [Frogging-Family/wine-tkg-git#309]
Hi!

I tried the non-makepkg script to build proton-tkg and on my system it does not complete successfully. It seems like `glslangValidator` does not recognize the quiet option, but I am not sure if this is the cause. The tail of the log is as follows:

```
[...]
vkd3d-proton 2.2

  Subprojects
    dxil-spirv: YES

Found ninja-1.10.0 at /usr/bin/ninja
[59/109] Generating 'libs/vkd3d/libvkd3d-proton.a.p/cs_clear_uav_buffer_float.h'.
FAILED: libs/vkd3d/libvkd3d-proton.a.p/cs_clear_uav_buffer_float.h 
/usr/bin/glslangValidator --quiet -V --vn cs_clear_uav_buffer_float ../../libs/vkd3d/shaders/cs_clear_uav_buffer_float.comp -o libs/vkd3d/libvkd3d-proton.a.p/cs_clear_uav_buffer_float.h
/usr/bin/glslangValidator: Error: --quiet: unrecognized command-line option (use -h for usage)
[64/109] Compiling C object libs/vkd3d-shader/libvkd3d-shader.a.p/spirv.c.obj
ninja: build stopped: subcommand failed.
```

This happens right after it's done with dxil-spirv, not sure if this is an issue with tkg or vkd3d-protons build setup but I thought reporting it here might be a good start.

**Comment by DadSchoorse** [comment]
ubuntu's glslang is just too ancient, either remove `--quiet` or update glslang.

**Comment by enveeed** [comment]
Replacing the binary with the newest one fixed it, thanks!
