### ISSUE TITLE
Protonify is causing issues in winegstreamer

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#315]
I don't know why but using protonify=true is causing massive issues with TES4 Oblivion, where the game hang after the intro video (sometimes it hang with a black screen, sometimes on the loading screen) with a lot of gstreamer assertion or a loader lockup on winegstreamer.dll
`
(wine:733739): GLib-GObject-WARNING **: 20:22:07.461: cannot register existing type 'GstObject'

(wine:733739): GLib-CRITICAL **: 20:22:07.461: g_once_init_leave: assertion 'result != 0' failed

(wine:733739): GLib-GObject-CRITICAL **: 20:22:07.461: g_type_register_static: assertion 'parent_type > 0' failed

(wine:733739): GLib-GObject-WARNING **: 20:22:07.461: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(wine:733739): GLib-CRITICAL **: 20:22:07.461: g_once_init_leave: assertion 'result != 0' failed

(wine:733739): GLib-GObject-CRITICAL **: 20:22:07.461: g_type_register_static: assertion 'parent_type > 0' failed

(wine:733739): GLib-CRITICAL **: 20:22:07.461: g_once_init_leave: assertion 'result != 0' failed

(wine:733739): GLib-GObject-CRITICAL **: 20:22:07.461: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(wine:733739): GStreamer-CRITICAL **: 20:22:07.461: gst_object_ref_sink: assertion 'object != NULL' failed

(wine:733739): GStreamer-CRITICAL **: 20:22:07.461: gst_object_ref: assertion 'object != NULL' failed

(wine:733739): GStreamer-CRITICAL **: 20:22:07.461: gst_allocator_register: assertion 'allocator != NULL' failed

(wine:733739): GStreamer-CRITICAL **: 20:22:07.461: gst_object_ref: assertion 'object != NULL' failed

(wine:733739): GLib-GObject-CRITICAL **: 20:22:07.461: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
`
This doesn't happen with  wine-tkg compiled without the patch or with normal wine/ wine-staging

**Comment by Tk-Glitch** [comment]
Please try against the current HEAD. I have removed the only winegstreamer related patch from the protonify patchsets and while I didn't try Oblivion before, I have verified that it works fine after.

**Comment by llde** [comment]
Fixed thanks
