### ISSUE TITLE
No Japanese Input with fcitx-mocz on winte-tkg

### ISSUE THREAD

**Issue by sangoku116** [Frogging-Family/wine-tkg-git#316]
When using wine tkg compared to standard wine, it is impossible to change the keyboard layout with fcitx. I am pressing my keybind to turn on hiragana input as I do in wine and it still romaji/roman characters. I also am unable to switch to my French Canadian input. 

Distribution: Endeavour OS(Arch)
Kernel: 5.11.11-lqx1-1-lqx
Wine-tkg version: 6.5.r1.g2e42e7d9

**Comment by Tk-Glitch** [comment]
This might be fixed now since a couple cleanups on the protonify patchset. Please test against master.

**Comment by Nocifer** [comment]
There was also up until this morning an issue with (probably, but not 100% confirmed) Qt5 itself not accepting IME input, which was (apparently, again not 100% confirmed this specific package was responsible) resolved with qt5-base updating to 5.15.2+kde+r171-3.

If you build Wine from master as Tk-Glitch suggested and you still have issues, check to see what version of qt5-base you have installed on your system (I don't know how often EndeavourOS updates its repos, so you could still be on the previous version).

**Comment by sangoku116** [comment]
Building from master did fix it! EndeavourOS is just an extra repo alongside arch repos for certain tools, but it is basically arch. It generated a new issue though in Final Fantasy XIV I can no longer move the camera with holding right click and moving the mouse using the arrows works fine

**Comment by Tk-Glitch** [comment]
> Building from master did fix it! EndeavourOS is just an extra repo alongside arch repos for certain tools, but it is basically arch. It generated a new issue though in Final Fantasy XIV I can no longer move the camera with holding right click and moving the mouse using the arrows works fine

That one was an issue upstream with the new rawinput patchset update. It should be fixed as of https://github.com/wine-staging/wine-staging/commit/a886228fbcefe7b8de06d2dd7182272df6cc3c36.

**Comment by sangoku116** [comment]
> > Building from master did fix it! EndeavourOS is just an extra repo alongside arch repos for certain tools, but it is basically arch. It generated a new issue though in Final Fantasy XIV I can no longer move the camera with holding right click and moving the mouse using the arrows works fine
> 
> That one was an issue upstream with the new rawinput patchset update. It should be fixed as of [wine-staging/wine-staging@a886228](https://github.com/wine-staging/wine-staging/commit/a886228fbcefe7b8de06d2dd7182272df6cc3c36).

Thank you, closing the issue as fcitx now works when cloning from master.
