### ISSUE TITLE
proton-sdl-joy.patch fails applying when building proton-tkg

### ISSUE THREAD

**Issue by Kiwii** [Frogging-Family/wine-tkg-git#317]
Freshly cloned repo, no `~/.config/frogminer/proton-tkg.cfg`,  
building fails both with `makepkg -si` and `./proton-tkg.sh` on up-to-date Arch.

Output from makepkg run:

[termnial output](https://gist.github.com/Kiwii/944a81a59ee1d81a5c47cc4abc165cbb)

[prepare.log](https://gist.github.com/Kiwii/e4e8c9b1dca8b02f5af9034c5febd498)

**Comment by Tk-Glitch** [comment]
Multiple patches from the patchset got upstreamed over night. Fix incoming.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/077380bfa030d9681e36fee55021923d99fa8835
