### ISSUE TITLE
Media Foundation no longer installing on wine-tkg-git 6.5 release

### ISSUE THREAD

**Issue by mixalis1987** [Frogging-Family/wine-tkg-git#318]
Last night I tried to install MF on a game and at the end of the MF install I got this:

> wineserver: using server-side synchronization.
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> reg: The operation completed successfully
> Application could not be started, or no application associated with the specifie
> d file.
> ShellExecuteEx failed: File not found.

Everyone that has installed MF before should know we do not get the "Application could not be started and the file not found error"
I tested on current prefix with a game and in an empty new prefix. Problem persists.

Using the wine-tkg 6.4 MF, it installs normally and works.
We can then upgrade to 6.5 and MF will still be installed and used normally.

Please also test in your own time and comment on your experience.

Also building from master and still cannot install MF.

**Comment by Tk-Glitch** [comment]
Some upstream change broke it and the installer would need to be fixed. However, most games shouldn't need that anymore. For which game is it?

**Comment by mixalis1987** [comment]
> Some upstream change broke it and the installer would need to be fixed. However, most games shouldn't need that anymore. For which game is it?

It was for the Crash Bandicoot 4 Its About Time game. But it's happens for empty new prefixes also. Without that MF i was just getting black screen until skipping that point.

**Comment by iWeaker4you** [comment]
Yes,  also its happening to me with FF Type 0 HD , saddly :c

**Comment by mixalis1987** [comment]
Modify the script at the end and change "wine start regedit.exe" to "wine regedit.exe" then MF will install again.

**Comment by runboy93** [comment]
Any idea is this fixed on Wine 6.6, atleast changelog has many entries about fixes against 6.5

**Comment by mixalis1987** [comment]
I think it has. Not tested myself but I think it mentioned in the change log that 6.5 was not using "start" that why I think "wine start regedit.exe" was not working. And they apparently sorted that out. Give it a go and post.

**Comment by Tk-Glitch** [comment]
No feedback, so I'll consider this as fixed. Closing :frog:
