### ISSUE TITLE
Cant compile wine-tkg now

### ISSUE THREAD

**Issue by mixalis1987** [Frogging-Family/wine-tkg-git#321]
Trying to build wine-tkg and now I see this in terminal:

>  Applying use_clock_monotonic.patch
  -> Applying childwindow.patch
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches...
  -> Applying mk11.patch
  -> Applying fsync-unix-staging.patch
  -> Applying fsync_futex2.patch
  -> Applying LAA-unix-staging.patch
==> ERROR: Patch application has failed. The error was logged to /home/michael/Downloads/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

This is the[ prepare.log](https://drive.google.com/file/d/1t-I8I5ouqZrJ-gYrFStgA2GqsjuqAvb-/view?usp=sharing) file if it helps. 

I also used a new VM to test but no change.

**Comment by ukbeast** [comment]
`LAA-unix-staging.patch` needs to be updated to work with source.

LAA-unix-staging.patch -- ( Applied large address aware override support )
patching file dlls/kernel32/heap.c
patching file dlls/ntdll/ntdll.spec
Hunk #1 succeeded at 1620 with fuzz 1 (offset 3 lines).
patching file dlls/ntdll/unix/server.c
Hunk #1 FAILED at 1471.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/unix/server.c.rej

**Comment by Tk-Glitch** [comment]
Forgot to close this. Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/d25bb2d482da74943906b29c5ed8391d67593b57
