### ISSUE TITLE
Unable to launch Fallout 76 after upgrading to proton 6.5

### ISSUE THREAD

**Issue by kittycat9878** [Frogging-Family/wine-tkg-git#325]
I have since tried downgrading back to 6.4 to no avail, it will only launch either using proton experimental in steam or using glorious eggrolls proton 6.4, it may be something super simple but I can't seem to figure it out. 
https://del.dog/steamlog.txt
the link above is the log I grabbed running it through the terminal
My distro is Arch and I am using the 5.11.11 pds kernel.
Edit: I should also add that I'm using the wine 6.5 build and I have tried downgrading to 6.4 again to no avail

**Comment by XaeroVincent** [comment]
Try deleting the game prefix folder:

<Steam-folder>/steamapps/compatdata/1151340

Then generate a new one in Steam with Proton-TKG 6.5 set to be used by the game.

**Comment by kittycat9878** [comment]
So that sorta worked. It gets me further than before now I actually see a wine window open but then it immediately closes 

> Starting app 1151340
>>> Adding process 15141 for game ID 1151340
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15142 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15143 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
esync: up and running.
>>> Adding process 15149 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15150 for game ID 1151340
>>> Adding process 15153 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15155 for game ID 1151340
>>> Adding process 15158 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15166 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15172 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15184 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15194 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15204 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 15206 for game ID 1151340
Game update: AppID 1151340 "", ProcID 15206, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 15206): SteamUtils009 / Utils
Setting breakpad minidump AppID = 1151340
RecordSteamInterfaceCreation (PID 15206): SteamUser019 / User
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198218686687 [API loaded no]
RecordSteamInterfaceCreation (PID 15206): SteamUser019 / User
RecordSteamInterfaceCreation (PID 15206): SteamFriends015 / Friends
RecordSteamInterfaceCreation (PID 15206): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 15206): SteamMatchMaking009 / Matchmaking
RecordSteamInterfaceCreation (PID 15206): SteamMatchMakingServers002 / MatchmakingServers
RecordSteamInterfaceCreation (PID 15206): STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
RecordSteamInterfaceCreation (PID 15206): STEAMAPPS_INTERFACE_VERSION008 / Apps
RecordSteamInterfaceCreation (PID 15206): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 15206): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
RecordSteamInterfaceCreation (PID 15206): STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
RecordSteamInterfaceCreation (PID 15206): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 15206): SteamController006 / Controller
RecordSteamInterfaceCreation (PID 15206): STEAMUGC_INTERFACE_VERSION010 / UGC
RecordSteamInterfaceCreation (PID 15206): STEAMAPPLIST_INTERFACE_VERSION001 / AppList
RecordSteamInterfaceCreation (PID 15206): STEAMMUSIC_INTERFACE_VERSION001 / Music
RecordSteamInterfaceCreation (PID 15206): STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
RecordSteamInterfaceCreation (PID 15206): STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
RecordSteamInterfaceCreation (PID 15206): STEAMINVENTORY_INTERFACE_V002 / Inventory
RecordSteamInterfaceCreation (PID 15206): STEAMVIDEO_INTERFACE_V002 / Video
RecordSteamInterfaceCreation (PID 15206): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15209 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15210 for game ID 1151340
Game update: AppID 1151340 "", ProcID 15209, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 15209): SteamUtils009 / Utils
Setting breakpad minidump AppID = 1151340
RecordSteamInterfaceCreation (PID 15209): SteamUser020 / User
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198218686687 [API loaded 
no]
wine: Unhandled page fault on read access to 0000000000000000 at address 00000001429D6079 (thread 0108), starting debugger...
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 15398 for game ID 1151340
Can't attach process 0104: error 5

**Comment by Tk-Glitch** [comment]
What about 6.6?

**Comment by kittycat9878** [comment]
> What about 6.6?
I'm assuming that I'll have to build it myself since there isn't one on the releases page?

**Comment by kittycat9878** [comment]
BInit - Unable to initialize Vulkan!
Installing breakpad exception handler for appid(steam)/version(1618256785)
roaming config store loaded successfully - 2959 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 8ms
[0413/153502.817365:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0413/153502.873032:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0413/153502.951794:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1618256785)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/kitty/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 3.20 seconds
[0413/153503.257345:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0413/153503.259769:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0413/153503.263345:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
BuildCompleteAppOverviewChange: 195
RegisterForAppOverview 1: 10ms
RegisterForAppOverview 2: 10ms
[1151340]Non-Steam Controller Configs Enabled: 1
Installing breakpad exception handler for appid(steam)/version(1618256785)
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
esync: up and running.
esync: up and running.
esync: up and running.
Installing breakpad exception handler for appid(steam)/version(1618256785)
esync: up and running.
Installing breakpad exception handler for appid(steam)/version(1618256785)
esync: up and running.
esync: up and running.
esync: up and running.
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1151340, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1151340, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 1151340: 0
Game update: AppID 1151340 "", ProcID 403462, IP 0.0.0.0:0
Starting app 1151340
>>> Adding process 403462 for game ID 1151340
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1151340, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403466 for game ID 1151340
esync: up and running.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 403487 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403563 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403567 for game ID 1151340
>>> Adding process 403568 for game ID 1151340
>>> Adding process 403570 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403747 for game ID 1151340
>>> Adding process 403748 for game ID 1151340
esync: up and running.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403749 for game ID 1151340
>>> Adding process 403752 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403754 for game ID 1151340
>>> Adding process 403757 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403765 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403771 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403802 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403814 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 403824 for game ID 1151340
>>> Adding process 403826 for game ID 1151340
Game update: AppID 1151340 "", ProcID 403826, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 403826): SteamUtils009 / Utils
Setting breakpad minidump AppID = 1151340
RecordSteamInterfaceCreation (PID 403826): SteamUser019 / User
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198218686687 [API loaded no]
RecordSteamInterfaceCreation (PID 403826): SteamUser019 / User
RecordSteamInterfaceCreation (PID 403826): SteamFriends015 / Friends
RecordSteamInterfaceCreation (PID 403826): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 403826): SteamMatchMaking009 / Matchmaking
RecordSteamInterfaceCreation (PID 403826): SteamMatchMakingServers002 / MatchmakingServers
RecordSteamInterfaceCreation (PID 403826): STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
RecordSteamInterfaceCreation (PID 403826): STEAMAPPS_INTERFACE_VERSION008 / Apps
RecordSteamInterfaceCreation (PID 403826): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 403826): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
RecordSteamInterfaceCreation (PID 403826): STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
RecordSteamInterfaceCreation (PID 403826): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 403826): SteamController006 / Controller
RecordSteamInterfaceCreation (PID 403826): STEAMUGC_INTERFACE_VERSION010 / UGC
RecordSteamInterfaceCreation (PID 403826): STEAMAPPLIST_INTERFACE_VERSION001 / AppList
RecordSteamInterfaceCreation (PID 403826): STEAMMUSIC_INTERFACE_VERSION001 / Music
RecordSteamInterfaceCreation (PID 403826): STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
RecordSteamInterfaceCreation (PID 403826): STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
RecordSteamInterfaceCreation (PID 403826): STEAMINVENTORY_INTERFACE_V002 / Inventory
RecordSteamInterfaceCreation (PID 403826): STEAMVIDEO_INTERFACE_V002 / Video
RecordSteamInterfaceCreation (PID 403826): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403829 for game ID 1151340
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 403830 for game ID 1151340
Game update: AppID 1151340 "", ProcID 403829, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 403829): SteamUtils009 / Utils
Setting breakpad minidump AppID = 1151340
RecordSteamInterfaceCreation (PID 403829): SteamUser020 / User
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198218686687 [API loaded no]
wine: Unhandled page fault on read access to 0000000000000000 at address 00000001429D6079 (thread 015c), starting debugger...
ERROR: ld.so: object '/home/kitty/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Can't attach process 0158: error 5
>>> Adding process 404042 for game ID 1151340
pid 403750 != 403749, skipping destruction (fork without exec?)
Game removed: AppID 1151340 "", ProcID 403829 
Game 1151340 created interface SteamUser020 / User
Game 1151340 created interface SteamUtils009 / Utils
Game 1151340 method call count for IClientUtils::RecordSteamInterfaceCreation : 2
Game 1151340 method call count for IClientUtils::GetAppID : 3
Game 1151340 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam
Exiting app 1151340 

I get the same thing with proton 6.6 also for some reason earlier today I was able to get the glorious eggrolls 6.5 build to work but it's not as performant as tkg builds so I tried 6.5tkg and it didn't work I have honestly no idea what is going on with all of this. I've never had issues like this before.

**Comment by XaeroVincent** [comment]
It says "BInit - Unable to initialize Vulkan!". Could that be a problem here?

What does "ls /usr/share/vulkan/icd.d/" show?

Also 'vulkaninfo' ?

Do you have 'steam-native' installed? If you do, try uninstalling that and use just 'steam-runtime'.

**Comment by kittycat9878** [comment]
> It says "BInit - Unable to initialize Vulkan!". Could that be a problem here?
> 
> What does "ls /usr/share/vulkan/icd.d/" show?
> 
> Also 'vulkaninfo' ?
> 
> Do you have 'steam-native' installed? If you do, try uninstalling that and use just 'steam-runtime'.

![image](https://user-images.githubusercontent.com/81938309/114891048-2c2ffc00-9dd1-11eb-885e-16400d31ff25.png)
vulkaninfo is an unknown command apparently

**Comment by kittycat9878** [comment]
so turns out I'm just stupid for some reason I had amdvlk installed alongside radv uninstalled amdvlk and it runs now, however now I can't build from source for some reason lol
