### ISSUE TITLE
Add GTA V Online patch.

### ISSUE THREAD

**Issue by kajlando** [Frogging-Family/wine-tkg-git#328]
So currently GTA V Online redirects to solo session only. Patch has been added to Proton-6.5-GE-2 that fixes it could you add it in 6.6?

**Comment by Tk-Glitch** [comment]
The issue is with the origin downloads fix patch. If you include it into your build, it breaks GTA V Online. Just don't add it to your build and GTA V Online will work as intended.

**Comment by Tk-Glitch** [comment]
Actually I won't include the patch for the 6.6 based Proton release, since Proton doesn't need working Origin downloads (steam downloads the games, bypassing Origin). So that will be fixed on the next "release".
I'll keep the patch enabled for the wine releases though, hoping for a fix upstream at some point.

**Comment by kajlando** [comment]
I just wanna play normal Online on your default Wine build because I need it to use in Lutris :(

**Comment by theRealCarneiro** [comment]
What is the name of the patch i have to disable? I removed the one in the hotfix directory but gta online doesnt seem to work

**Comment by kajlando** [comment]
I wonder too.. Currently the only way to play Online properly is through GE.

**Comment by kajlando** [comment]
How I can compile WIne-tkg without that patch?

**Comment by kajlando** [comment]
_origin_3078f10d_fix="false" should work I'll see.

**Comment by kajlando** [comment]
I'd be eager to compile wine-tkg myself to use with GTA V Online.
@Tk-Glitch please, could you tell us which patch/es we have to disable?
Is it origin_3078f10d_fix.mypatch?

**Comment by kajlando** [comment]
I'd be eager to compile wine-tkg myself to use with GTA V Online.
@Tk-Glitch please, could you write which patch/es we have to disable?

**Comment by kajlando** [comment]
6.7 fixed it but I still have a problem with my mouse in a borderless window.
