### ISSUE TITLE
Can't compile latest wine

### ISSUE THREAD

**Issue by qwert0p** [Frogging-Family/wine-tkg-git#329]
While using latest git commit, can't compile wine because LAA-unix-staging.patch don't applying, [prepare.log](https://pastebin.com/8iUSn42y)

**Comment by Tk-Glitch** [comment]
That one was fixed 5 days ago or so :thinking: . What's the md5sum of your `LAA-unix-staging.patch`?

**Comment by qwert0p** [comment]
Oh, yeah, it's fixed already, i updated repository with git checkout, but it isn't fully updated, now i cloned repository and all works, sorry for the false report).
