### ISSUE TITLE
_proton_mf_hacks broken on latest (380f519)

### ISSUE THREAD

**Issue by t14462** [Frogging-Family/wine-tkg-git#330]
Some dll cant be compiled with it. Sorry, I loose my log

**Comment by rboxeur** [comment]
I am not sure if you met this issue but I met this one assuming your copy of wine-tkg was refreshed before trying to compile

.....ld ....dll/mfreadwrite/......undefined reference to 'heap_alloc_zero'

To fix it then once the wine-tkg sources were generated before compiling then 

vim  dlls/mfreadwrite/reader.c

Add the following line ''include "wine/heap.h" -- see below

#include "wine/debug.h"
#include "wine/list.h"
+#include "wine/heap.h"
#include "mf_private.h"

Then you should be able to build Wine.
