### ISSUE TITLE
No working cursor with latest build

### ISSUE THREAD

**Issue by shumvgolove** [Frogging-Family/wine-tkg-git#332]
- OS: Arch Linux, everything's up to date
- Linux 5.11.12
- GPU: AMD RX590
- Mesa 21.0.2
- Proton-tkg: https://github.com/Frogging-Family/wine-tkg-git/commit/380f51915726e6a7a75ee0a22344a2e8e33ae458

Every game running with latest `proton-tkg` has no working in-game cursor: it's just stays in the middle of the screen (or moving, but can not do left/middle/right click), although cursor in Steam overlay works fine. Tried with `GTFO`, `Monster Hunter: World` and `Cruelty Squad`, to name a few.

**Comment by Tk-Glitch** [comment]
This is an upstream issue with wine staging. It'll hopefully get fixed soon.

**Comment by Tk-Glitch** [comment]
Should be fixed now

**Comment by SveSop** [comment]
Ah.. this explains breakage on World of Warcraft and mouselook with 6.6
Guess i will see if i can get staging patched and test then :) Thanks :)

**Comment by shumvgolove** [comment]
`proton-tkg-git 6.6.r3.ga886228f-1`: same.

**Comment by shumvgolove** [comment]
Actually, no. Everything works fine. Thanks.
