### ISSUE TITLE
Patch/Fix  to re-allow  proton_mf_hack="true" for Wine 6.6 and over

### ISSUE THREAD

**Issue by rboxeur** [Frogging-Family/wine-tkg-git#333]
While waiting for a real fix for  proton_mf_hack=true please find below a fix to re-allow this support
root@david-Alienware-17-R4:/opt/montage# diff -Napur a/dlls/mfreadwrite/reader.c b/dlls/mfreadwrite/reader.c

> --- a/dlls/mfreadwrite/reader.c	2021-04-13 11:35:49.873076971 +0200
> +++ b/dlls/mfreadwrite/reader.c	2021-04-13 11:12:55.633217904 +0200
> @@ -39,7 +39,7 @@
>  
>  #include "wine/debug.h"
>  #include "wine/list.h"
> -
> +#include "wine/heap.h"
>  #include "mf_private.h"
>  
>  WINE_DEFAULT_DEBUG_CHANNEL(mfplat);
> 

Hope it helps.
Regards

**Comment by Tk-Glitch** [comment]
There won't be a "real fix" for that patchset. It's deprecated and useless so there shouldn't be any reason to use it anymore. If it fixes anything for you, please describe the issue and the change in behavior with the patch, along with your distro and currently installed gstreamer/gstreamer-dev package(s).

**Comment by rboxeur** [comment]
I didn't know that it became useless. Thanks for letting me know.
You can close this ticket
Regards.
