### ISSUE TITLE
6.6 cant launch /unix/path/to/exe

### ISSUE THREAD

**Issue by t14462** [Frogging-Family/wine-tkg-git#335]
Also, double-click doesnt work

**Comment by IroAlexis** [comment]
If you use Wine Staging (which is probably the case), you must compile it from the commit [a886228](https://github.com/wine-staging/wine-staging/commit/a886228fbcefe7b8de06d2dd7182272df6cc3c36)

**Comment by t14462** [comment]
@IroAlexis It's not related to mouse. It's about opening exe-s from desktop by double click.

Problem is in recognizing /unix/path/to/exe

**Comment by ukbeast** [comment]
Right click and open with wine didn't work for me on Gnome 40 on Archlinux.
But you can cd to the root of the .exe and do wine  something.exe

**Comment by t14462** [comment]
Sorry. Double-click on exes from desktop works fine

**Comment by SveSop** [comment]
I wonder if this is related to the "start" bug?
[https://bugs.winehq.org/show_bug.cgi?id=50867](https://bugs.winehq.org/show_bug.cgi?id=50867)
This should be fixed upstream in 6.7, since it is the first commit > 6.6
