### ISSUE TITLE
Regression related to launching d3d12 games using wine tkg with latest changes

### ISSUE THREAD

**Issue by xorpix** [Frogging-Family/wine-tkg-git#336]
So after i upgraded wine-tkg to the latest version with fresh commits all my games which use d3d12 have stopped launching. For example, Kingdom Hearts HD 1.5 + 2.5 ReMIX was launching fine and working. But after the update it gives me the next output in console:
```Initial process has started with pid 161462
Start monitoring process.
Initial process has exited (return code: 0)
field __ImageBase in <Module> should have RVA data, but hasn't
field __ImageBase in <Module> should have RVA data, but hasn't
252:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.2.0.
252:info:vkd3d_instance_init: vkd3d-proton - build: 5f312d416d5c45d0.
free(): invalid size
Monitored process exited.
All monitored processes have exited.
Exit with returncode 0
```
And eventually it crashes and stops laucnhing. I've downgraded to the older build and games work fine again.
Cyberpunk 2077 gives the same output with this version and laucnhes successfully with older one.

**Comment by Tk-Glitch** [comment]
Fix coming soon :tm:

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/211341c5ebb427c6aad555dc7bdb228308b939e9

**Comment by xorpix** [comment]
Yep, games run successfully again. Thank You!
