### ISSUE TITLE
Can't use custom patches

### ISSUE THREAD

**Issue by NastySpaghetti** [Frogging-Family/wine-tkg-git#34]
Hello, so I wanted to include a custom patch, but it didn't work.
This error 
![image](https://user-images.githubusercontent.com/32963491/81322158-d5d01e80-9093-11ea-8919-d0502257309a.png)

> ln: failed to create symbolic link '/home/lucille/Downloads/TKG/wine-tkg-git/wine-tkg-git/bz20338.mypatch': File exists

Here's the makepkg output:
https://pastebin.com/vnS2AjKV

Here's the tree of wine-tkg-git
https://pastebin.com/NzQxhEqN

Here's the customization.cfg
https://pastebin.com/DGpqD48g

Here you go.
Thanks.

**Comment by Tk-Glitch** [comment]
You need to either put your patche(s) in `~/Downloads/TKG/wine-tkg-git/wine-tkg-git/wine-tkg-userpatches/` (and remove it from the community patches array in your cfg), or put it in `~/Downloads/TKG/community-patches/wine-tkg-git/` and have it in the community patches array in your cfg.

In both cases, the patch needs to **not** be in `~/Downloads/TKG/wine-tkg-git/wine-tkg-git/` (PKGBUILD's dir).

That should clear things up :)

**Comment by NastySpaghetti** [comment]
I didn't think i would get an answer that fast.
Okay, so by only removing "bz20338.mypatch" from the array in customization.cfg, it seems to get detected. Thank you

It would maybe be a great idea to clarify the readme in 'wine-tkg-git/wine-tkg-git/wine-tkg-userpatches/'  a bit to distinguish the procedures between the two methods.

Have a great day.

**Comment by Tk-Glitch** [comment]
Indeed. Readme improvements are planned, I'm not happy with their current state either :D

Thank you, have a great day as well.
