### ISSUE TITLE
Controllers not working 

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#340]
Built a new build yesterday night **proton_tkg_6.6.r8.g20303a53** and tkg commit id **d496882** but the controller is not working with this build, if i go back to a previous build **proton_tkg_6.5.r6.g733a420d** it does work.
Game I was using was Tomb Raider

**Comment by redgloboli** [comment]
it worked here after i set 

_sdl_joy_support="false"

in proton-tkg.cfg

you can try that till it's fixed.

**Comment by Tk-Glitch** [comment]
I'm working on fixing the sdl_joy patchset since upstream changes broke it. In the meantime, it's disabled in the hotfixer as a workaround.

https://github.com/Frogging-Family/wine-tkg-git/commit/9b7149bff618170347fe39502c6b8bee64b88f68

**Comment by Tk-Glitch** [comment]
This should be fixed since we're using staging's impl currently.
