### ISSUE TITLE
DCS World - 6.6.r15 not detecting selected windows version

### ISSUE THREAD

**Issue by HellToupee1** [Frogging-Family/wine-tkg-git#343]
DCS world no longer recognising windows version selected in winecfg tried with windows 10 and win 8.1.

Error:
![image](https://user-images.githubusercontent.com/22861691/115802718-849b7500-a433-11eb-84cd-47ed5d30c57f.png)

Previously was using 6.6.r6.g425f75f8 which if i roll back to works.

**Comment by nutta-git** [comment]
@HellToupee1 
Can you provide more information? Are you using wine-tkg or proton-tkg? Can you provide for logs either? Can you list your  computer spec? 

For proton and using Steam, you can get logs with` PROTON_LOG=1 %command%` in the Steam "Launch Options"

**Comment by HellToupee1** [comment]
Hi, was using wine-tkg with the standalone version of DCS with wine-tkg, this affects only the updater tool DCS_update.exe game it self runs fine.

Attached logs of both earlier version without problem and current version with problem

Specs are 
Arch with 5.12.0-150-tkg-cfs
amd 3700x
nvidia 1080ti
32gb ram

Log files 

[lastgood.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6398756/lastgood.txt)
[problemlogfile.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6398762/problemlogfile.txt)

**Comment by HellToupee1** [comment]
Actually now trying 6.7 vanilla packages it has problem also so probably upsteam bug.

**Comment by HellToupee1** [comment]
https://bugs.winehq.org/show_bug.cgi?id=51080

**Comment by Tk-Glitch** [comment]
Fixed upstream
