### ISSUE TITLE
Can't compile Proton-tkg e9e315 during DXVK compiling.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#344]
Can't compile Proton-tkg e9e315acc2b2596c440a5cce76fee81cb6b0385c during DXVK compiling.
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6362665/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6362666/prepare.log)
![Screenshot from 2021-04-23 08-58-36](https://user-images.githubusercontent.com/36989404/115816825-0af38f00-a413-11eb-8ec4-d113bcbd8205.png)

**Comment by Kerrung** [comment]
By the way, compilation of plane standalone DXVK is full OK.

**Comment by Tk-Glitch** [comment]
This is not dxvk, it's a post-compilation script for wine. Installing the pefile python module package will fix it.

**Comment by Kerrung** [comment]
> This is not dxvk, it's a post-compilation script for wine. Installing the pefile python module package will fix it.

So, maybe you should add python-pefile package to "makedepends" PKGBUILD section ?

**Comment by Tk-Glitch** [comment]
Yes that's planned :)

**Comment by Tk-Glitch** [comment]
Yes that's planned :)
