### ISSUE TITLE
LAA-unix-staging.patch fails to apply.

### ISSUE THREAD

**Issue by niobium93** [Frogging-Family/wine-tkg-git#346]
> LAA-unix-staging.patch -- ( Applied large address aware override support )
patching file dlls/kernel32/heap.c
Hunk #2 FAILED at 546.
1 out of 3 hunks FAILED -- saving rejects to file dlls/kernel32/heap.c.rej
patching file dlls/ntdll/ntdll.spec
Hunk #1 succeeded at 1620 with fuzz 1 (offset 3 lines).
patching file dlls/ntdll/unix/server.c
Hunk #1 succeeded at 1683 (offset 212 lines).
patching file dlls/ntdll/unix/unix_private.h
Hunk #1 succeeded at 537 with fuzz 2 (offset 67 lines).
patching file dlls/ntdll/unix/virtual.c
Hunk #1 succeeded at 3786 (offset 366 lines).

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/55aa662c67757b5ea44c5d7ed8ffd1365d8aa7fe
