### ISSUE TITLE
proton-tkg-staging.patch fails to apply.

### ISSUE THREAD

**Issue by niobium93** [Frogging-Family/wine-tkg-git#347]
proton-tkg-staging.patch -- ( Using Steam-specific Proton-tkg patches (staging) 2/3 )
patching file dlls/ws2_32/socket.c
Hunk #1 succeeded at 3278 (offset -54 lines).
patching file dlls/wined3d/adapter_gl.c
Hunk #1 succeeded at 1037 with fuzz 2 (offset 28 lines).
patching file server/main.c
Hunk #1 succeeded at 43 (offset 1 line).
patching file dlls/ntdll/unix/thread.c
Hunk #1 succeeded at 58 with fuzz 2 (offset 15 lines).
Hunk #2 succeeded at 361 (offset 14 lines).
Hunk #3 succeeded at 392 (offset 13 lines).
patching file dlls/dwrite/font.c
Hunk #1 succeeded at 952 (offset 212 lines).
patching file dlls/msctf/msctf.c
Hunk #4 succeeded at 554 with fuzz 1 (offset -2 lines).
Hunk #5 succeeded at 614 (offset -2 lines).
patching file dlls/msctf/msctf_internal.h
Hunk #1 succeeded at 36 with fuzz 2 (offset 1 line).
patching file dlls/msctf/threadmgr.c
Hunk #8 succeeded at 1400 (offset 8 lines).
Hunk #9 succeeded at 1416 (offset 8 lines).
Hunk #10 succeeded at 1432 (offset 8 lines).
patching file programs/dxdiag/main.c
patching file programs/dxdiag/output.c
Hunk #1 succeeded at 149 (offset -20 lines).
Hunk #2 succeeded at 211 (offset -20 lines).
patching file dlls/ntdll/heap.c
Hunk #1 succeeded at 111 (offset -7 lines).
Hunk #2 succeeded at 781 (offset -18 lines).
Hunk #3 succeeded at 1785 (offset -28 lines).
Hunk #4 succeeded at 1939 with fuzz 2 (offset -28 lines).
patching file tools/makedep.c
Hunk #1 succeeded at 3348 with fuzz 1 (offset 103 lines).
patching file dlls/dxgi/adapter.c
Hunk #1 succeeded at 165 with fuzz 1 (offset 4 lines).
patching file dlls/dsound/dsound.c
Hunk #2 succeeded at 136 (offset -1 lines).
Hunk #3 succeeded at 1128 (offset 2 lines).
patching file dlls/dsound/dsound_private.h
Hunk #1 succeeded at 209 (offset 7 lines).
patching file dlls/dsound/primary.c
Hunk #2 succeeded at 110 (offset -1 lines).
Hunk #3 succeeded at 196 (offset -1 lines).
patching file dlls/dwmapi/dwmapi_main.c
Hunk #1 succeeded at 197 (offset -8 lines).
patching file dlls/dwmapi/Makefile.in
Hunk #1 succeeded at 1 with fuzz 2.
patching file dlls/dwmapi/dwmapi_main.c
Hunk #1 succeeded at 209 (offset -8 lines).
patching file dlls/xaudio2_7/xaudio_dll.c
Hunk #1 succeeded at 81 (offset -1 lines).
Hunk #2 succeeded at 1305 (offset -2 lines).
Hunk #3 succeeded at 1710 (offset -2 lines).
Hunk #4 succeeded at 1786 (offset -2 lines).
Hunk #5 succeeded at 1807 (offset -2 lines).
Hunk #6 succeeded at 1819 (offset -2 lines).
patching file dlls/xaudio2_7/xaudio_private.h
patching file dlls/bcrypt/gnutls.c
Hunk #1 succeeded at 342 with fuzz 2 (offset 75 lines).
patching file dlls/winex11.drv/mouse.c
Hunk #1 succeeded at 1664 (offset 39 lines).
patching file programs/winebrowser/main.c
patching file dlls/winepulse.drv/mmdevdrv.c
Hunk #1 succeeded at 701 with fuzz 1 (offset 130 lines).
patching file dlls/xaudio2_7/xaudio_dll.c
Hunk #2 succeeded at 1976 (offset 27 lines).
patching file dlls/dxgi/adapter.c
Hunk #1 succeeded at 204 (offset 4 lines).
patching file dlls/kernelbase/sync.c
Hunk #1 succeeded at 1067 (offset 107 lines).
Hunk #2 succeeded at 1089 (offset 107 lines).
patching file dlls/ntdll/unix/file.c
Hunk #1 succeeded at 3601 (offset 8 lines).
patching file dlls/ntdll/unix/virtual.c
Hunk #1 succeeded at 3823 (offset 398 lines).
patching file dlls/d3d10core/d3d10core_main.c
Hunk #1 succeeded at 29 with fuzz 2.
patching file dlls/dxgi/dxgi_main.c
patching file dlls/kernelbase/file.c
Hunk #1 succeeded at 44 (offset 3 lines).
Hunk #2 succeeded at 718 with fuzz 1 (offset 284 lines).
Hunk #3 succeeded at 888 (offset 360 lines).
Hunk #4 succeeded at 906 (offset 360 lines).
patching file dlls/kernelbase/file.c
Hunk #1 succeeded at 731 (offset 284 lines).
patching file dlls/wbemprox/builtin.c
Hunk #1 succeeded at 1257 (offset 76 lines).
Hunk #2 succeeded at 1303 (offset 76 lines).
Hunk #3 succeeded at 1383 (offset 76 lines).
Hunk #4 succeeded at 1544 (offset 76 lines).
Hunk #5 succeeded at 1581 (offset 76 lines).
Hunk #6 succeeded at 1609 (offset 76 lines).
Hunk #7 succeeded at 2748 (offset 96 lines).
Hunk #8 succeeded at 3568 (offset 93 lines).
Hunk #9 succeeded at 3834 (offset 94 lines).
Hunk #10 succeeded at 4046 (offset 91 lines).
patching file dlls/ws2_32/socket.c
Hunk #1 succeeded at 6344 (offset -139 lines).
Hunk #2 succeeded at 6616 (offset -125 lines).
patching file dlls/user32/hook.c
Hunk #1 succeeded at 379 (offset -3 lines).
Hunk #2 succeeded at 393 (offset -3 lines).
patching file server/queue.c
Hunk #1 succeeded at 1717 (offset 76 lines).
patching file configure
Hunk #1 succeeded at 1834 (offset 68 lines).
Hunk #2 succeeded at 24423 (offset 2843 lines).
patching file configure.ac
Hunk #1 succeeded at 4033 (offset 36 lines).
patching file programs/dotnetfx35/Makefile.in
patching file programs/dotnetfx35/main.c
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 75 (offset -1 lines).
patching file programs/winecfg/x11drvdlg.c
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 70 with fuzz 1 (offset -1 lines).
patching file dlls/winex11.drv/event.c
Hunk #1 succeeded at 1424 (offset 82 lines).
patching file dlls/winex11.drv/event.c
Hunk #1 succeeded at 443 (offset 10 lines).
patching file dlls/winex11.drv/x11drv.h
Hunk #1 succeeded at 410 (offset -2 lines).
patching file dlls/winex11.drv/x11drv_main.c
Hunk #2 succeeded at 751 (offset 12 lines).
patching file dlls/kernelbase/file.c
Hunk #1 succeeded at 757 (offset 16 lines).
patching file dlls/vulkan-1/Makefile.in
patching file dlls/ntdll/unix/signal_x86_64.c
Hunk #1 succeeded at 2427 (offset 59 lines).
Hunk #2 succeeded at 2541 (offset 59 lines).
patching file configure
Hunk #1 succeeded at 1126 (offset 24 lines).
Hunk #2 succeeded at 1407 (offset 41 lines).
Hunk #3 succeeded at 23414 (offset 2964 lines).
Hunk #4 succeeded at 23775 (offset 2982 lines).
patching file configure.ac
Hunk #1 succeeded at 3022 (offset 8 lines).
Hunk #2 succeeded at 3383 (offset 26 lines).
patching file dlls/api-ms-win-gaming-tcui-l1-1-0/Makefile.in
patching file dlls/api-ms-win-gaming-tcui-l1-1-0/api-ms-win-gaming-tcui-l1-1-0.spec
patching file dlls/gamingtcui/Makefile.in
patching file dlls/gamingtcui/gamingtcui.spec
patching file dlls/gamingtcui/gamingtcui_main.c
patching file dlls/ntdll/ntdll.spec
patching file dlls/ntdll/tests/om.c
Hunk #2 succeeded at 2565 (offset 15 lines).
Hunk #3 succeeded at 2641 (offset 15 lines).
Hunk #4 succeeded at 2659 (offset 15 lines).
patching file dlls/ntdll/unix/process.c
Hunk #1 succeeded at 1537 (offset -222 lines).
patching file include/wine/server_protocol.h
Hunk #1 succeeded at 5504 (offset -85 lines).
Hunk #2 succeeded at 5804 (offset -89 lines).
Hunk #3 succeeded at 6092 (offset -93 lines).
Hunk #4 succeeded at 6378 (offset -97 lines).
patching file server/process.c
Hunk #1 succeeded at 1717 (offset -65 lines).
patching file server/protocol.def
Hunk #1 succeeded at 3826 (offset -54 lines).
patching file server/request.h
Hunk #1 succeeded at 399 (offset -4 lines).
Hunk #2 succeeded at 686 (offset -8 lines).
Hunk #3 succeeded at 2275 (offset -38 lines).
patching file server/trace.c
Hunk #1 succeeded at 4532 with fuzz 1 (offset -54 lines).
Hunk #2 succeeded at 4826 (offset -58 lines).
Hunk #3 succeeded at 5108 (offset -64 lines).
Hunk #4 succeeded at 5394 (offset -66 lines).
patching file dlls/ntdll/ntdll.spec
patching file dlls/ntdll/tests/om.c
Hunk #2 succeeded at 2591 (offset 15 lines).
Hunk #3 succeeded at 2671 (offset 15 lines).
Hunk #4 succeeded at 2690 (offset 15 lines).
patching file dlls/ntdll/unix/thread.c
Hunk #1 succeeded at 1410 (offset -52 lines).
patching file include/wine/server_protocol.h
Hunk #1 succeeded at 5522 (offset -85 lines).
Hunk #2 succeeded at 5823 (offset -89 lines).
Hunk #3 succeeded at 6112 (offset -93 lines).
Hunk #4 succeeded at 6399 (offset -97 lines).
patching file server/protocol.def
Hunk #1 succeeded at 3837 (offset -54 lines).
patching file server/request.h
Hunk #1 succeeded at 400 (offset -4 lines).
Hunk #2 succeeded at 688 (offset -8 lines).
Hunk #3 succeeded at 2284 with fuzz 2 (offset -38 lines).
patching file server/thread.c
Hunk #1 succeeded at 2022 (offset -152 lines).
patching file server/trace.c
Hunk #1 succeeded at 4545 with fuzz 1 (offset -54 lines).
Hunk #2 succeeded at 4841 (offset -58 lines).
Hunk #3 succeeded at 5124 with fuzz 2 (offset -64 lines).
Hunk #4 succeeded at 5411 (offset -66 lines).
patching file loader/wine.inf.in
Hunk #1 succeeded at 69 (offset 2 lines).
Hunk #2 succeeded at 98 (offset 2 lines).
Hunk #3 succeeded at 126 (offset 1 line).
Hunk #4 succeeded at 147 with fuzz 1 (offset 2 lines).
Hunk #6 succeeded at 1390 (offset 256 lines).
patching file dlls/api-ms-win-appmodel-runtime-l1-1-1/api-ms-win-appmodel-runtime-l1-1-1.spec
patching file dlls/ext-ms-win-kernel32-package-l1-1-1/ext-ms-win-kernel32-package-l1-1-1.spec
patching file dlls/kernel32/kernel32.spec
patching file dlls/kernel32/tests/version.c
patching file dlls/kernelbase/kernelbase.spec
patching file dlls/kernelbase/version.c
patching file include/appmodel.h
patching file dlls/api-ms-win-appmodel-runtime-l1-1-1/api-ms-win-appmodel-runtime-l1-1-1.spec
patching file dlls/ext-ms-win-kernel32-package-l1-1-1/ext-ms-win-kernel32-package-l1-1-1.spec
patching file dlls/kernel32/kernel32.spec
Hunk #1 succeeded at 1153 (offset 1 line).
patching file dlls/kernel32/tests/version.c
patching file dlls/kernelbase/kernelbase.spec
patching file dlls/kernelbase/version.c
patching file include/appmodel.h
patching file dlls/api-ms-win-appmodel-runtime-l1-1-1/api-ms-win-appmodel-runtime-l1-1-1.spec
patching file dlls/ext-ms-win-kernel32-package-l1-1-1/ext-ms-win-kernel32-package-l1-1-1.spec
patching file dlls/kernel32/kernel32.spec
patching file dlls/kernel32/tests/version.c
patching file dlls/kernelbase/kernelbase.spec
patching file dlls/kernelbase/version.c
patching file include/appmodel.h
patching file dlls/api-ms-win-core-processthreads-l1-1-3/api-ms-win-core-processthreads-l1-1-3.spec
patching file dlls/kernel32/kernel32.spec
patching file dlls/kernelbase/kernelbase.spec
patching file dlls/kernelbase/memory.c
Hunk #1 succeeded at 1168 (offset -2 lines).
patching file dlls/ntdll/unix/esync.c
patching file dlls/dxgi/factory.c
patching file dlls/dxgi/swapchain.c
patching file dlls/dxgi/Makefile.in
patching file dlls/mscoree/metahost.c
Hunk #1 succeeded at 1770 (offset 28 lines).
patching file dlls/mscoree/config.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/mscoree/config.c.rej
patching file dlls/kernel32/heap.c
Hunk #2 FAILED at 562.
Hunk #3 FAILED at 573.
2 out of 4 hunks FAILED -- saving rejects to file dlls/kernel32/heap.c.rej
patching file dlls/kernel32/tests/heap.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file dlls/kernel32/tests/heap.c.rej

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/550655e70a1b8c93b59c0a74eb53155d0ae9a31f
