### ISSUE TITLE
The Forest crashes with proton-tkg

### ISSUE THREAD

**Issue by FLGX06** [Frogging-Family/wine-tkg-git#35]
The Forest doesn't launch anymore with proton-tkg, works with normal proton. I can't get even into the Unity game launcher. Doesn't work without DXVK either.

Last line before closing the crash window: 1149
[steam-242760.log](https://github.com/Frogging-Family/wine-tkg-git/files/4598040/steam-242760.log)

**Comment by PhantomX** [comment]
Could be wine [bug#49109](https://bugs.winehq.org/show_bug.cgi?id=49109). Some Unity games are running again after reverting [78e9b02cebf4b107aba69aa9a845ab661a7daf10](https://source.winehq.org/git/wine.git/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10).

**Comment by Ashraaf** [comment]
Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:

```
patching file dlls/wbemprox/builtin.c
Hunk #1 FAILED at 50.
Hunk #2 succeeded at 824 (offset 3 lines).
Hunk #3 succeeded at 864 (offset 3 lines).
Hunk #4 succeeded at 899 (offset 3 lines).
Hunk #5 succeeded at 1086 (offset 3 lines).
Hunk #6 succeeded at 1126 (offset 3 lines).
Hunk #7 succeeded at 1172 (offset 3 lines).
Hunk #8 succeeded at 1211 (offset 3 lines).
Hunk #9 succeeded at 1219 (offset 3 lines).
Hunk #10 succeeded at 1285 (offset 3 lines).
Hunk #11 succeeded at 1312 (offset 3 lines).
Hunk #12 succeeded at 1332 (offset 3 lines).
Hunk #13 succeeded at 1458 (offset 3 lines).
Hunk #14 succeeded at 1491 (offset 3 lines).
Hunk #15 succeeded at 1519 (offset 3 lines).
Hunk #16 succeeded at 1759 (offset 3 lines).
Hunk #17 succeeded at 1815 (offset 3 lines).
Hunk #18 succeeded at 1828 (offset 3 lines).
Hunk #19 succeeded at 1886 (offset 3 lines).
Hunk #20 succeeded at 1971 (offset 3 lines).
Hunk #21 succeeded at 2016 (offset 3 lines).
Hunk #22 succeeded at 2093 (offset 3 lines).
Hunk #23 succeeded at 2119 (offset 3 lines).
Hunk #24 succeeded at 2161 (offset 3 lines).
Hunk #25 succeeded at 2176 (offset 3 lines).
Hunk #26 succeeded at 2247 (offset 3 lines).
Hunk #27 succeeded at 2282 (offset 3 lines).
Hunk #28 succeeded at 2328 (offset 3 lines).
Hunk #29 succeeded at 2342 (offset 3 lines).
Hunk #30 succeeded at 2402 (offset 3 lines).
Hunk #31 succeeded at 2435 (offset 3 lines).
Hunk #32 succeeded at 2460 (offset 3 lines).
Hunk #33 succeeded at 2476 (offset 3 lines).
Hunk #34 succeeded at 2488 (offset 3 lines).
Hunk #35 succeeded at 2562 (offset 3 lines).
Hunk #36 succeeded at 2605 (offset 3 lines).
Hunk #37 succeeded at 2637 (offset 3 lines).
Hunk #38 succeeded at 2645 (offset 3 lines).
Hunk #39 succeeded at 2810 (offset 3 lines).
Hunk #40 succeeded at 2901 (offset 3 lines).
Hunk #41 succeeded at 2911 (offset 3 lines).
Hunk #42 succeeded at 2972 (offset 3 lines).
Hunk #43 succeeded at 2998 (offset 3 lines).
Hunk #44 succeeded at 3030 (offset 3 lines).
Hunk #45 succeeded at 3057 (offset 3 lines).
Hunk #46 FAILED at 3157.
Hunk #47 FAILED at 3193.
Hunk #48 succeeded at 3219 (offset -27 lines).
Hunk #49 succeeded at 3238 (offset -27 lines).
Hunk #50 succeeded at 3275 (offset -27 lines).
Hunk #51 succeeded at 3286 (offset -27 lines).
Hunk #52 succeeded at 3311 (offset -27 lines).
Hunk #53 succeeded at 3328 (offset -27 lines).
Hunk #54 succeeded at 3353 (offset -27 lines).
Hunk #55 succeeded at 3413 (offset -27 lines).
Hunk #56 succeeded at 3426 (offset -27 lines).
Hunk #57 succeeded at 3448 (offset -27 lines).
Hunk #58 succeeded at 3468 (offset -27 lines).
Hunk #59 succeeded at 3480 (offset -27 lines).
Hunk #60 succeeded at 3499 (offset -27 lines).
Hunk #61 succeeded at 3689 (offset -27 lines).
Hunk #62 succeeded at 3764 (offset -27 lines).
Hunk #63 succeeded at 3835 (offset -27 lines).
Hunk #64 succeeded at 3854 (offset -27 lines).
Hunk #65 succeeded at 3873 (offset -27 lines).
Hunk #66 FAILED at 3947.
Hunk #67 succeeded at 3932 (offset -26 lines).
Hunk #68 succeeded at 3959 (offset -26 lines).
4 out of 68 hunks FAILED -- saving rejects to file dlls/wbemprox/builtin.c.rej
patching file dlls/wbemprox/class.c
patching file dlls/wbemprox/process.c
patching file dlls/wbemprox/qualifier.c
patching file dlls/wbemprox/query.c
patching file dlls/wbemprox/reg.c
patching file dlls/wbemprox/security.c
patching file dlls/wbemprox/service.c
patching file dlls/wbemprox/services.c
patching file dlls/wbemprox/table.c
patching file dlls/wbemprox/wbemlocator.c
patching file dlls/wbemprox/wbemprox_private.h
==> ERROR: A failure occurred in prepare().
```

**Comment by Tk-Glitch** [comment]
Yeah commit(s?) were pushed since that will prevent a clean revert. I'll try to offer a patch to test this later today if still needed.

**Comment by Ashraaf** [comment]
Right now im compiling last version of wine staging before this problematic commit merged, 
which is 029c249e789fd8b05d8c1eeda48deb8810bbb751, but guy1524_mfplat_WIP.mypatch cannot be applied on this staging version. Ill report back if my unity game work fine after this.

**Comment by Ashraaf** [comment]
And yes, my game(Cities Sklines) is running fine on wine staging 029c249e789fd8b05d8c1eeda48deb8810bbb751, now time to find the older version that can merge with guy1524_mfplat_WIP.mypatch, or wait until the fix from upstream arrive.

**Comment by PhantomX** [comment]
> Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:
`
Here, revert them in this order:
https://github.com/wine-mirror/wine/commit/8b6c86eb824d1f529dab7bbbbd09907f41c182d3.patch
https://github.com/wine-mirror/wine/commit/550d96b0bf0928ac4dc573f49d2ec2e0c0444fc5.patch
https://github.com/wine-mirror/wine/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10.patch

**Comment by FLGX06** [comment]
> > Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:
> 
> Here, revert them in this order:
> https://github.com/wine-mirror/wine/commit/8b6c86eb824d1f529dab7bbbbd09907f41c182d3.patch
> https://github.com/wine-mirror/wine/commit/550d96b0bf0928ac4dc573f49d2ec2e0c0444fc5.patch
> https://github.com/wine-mirror/wine/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10.patch

Still does not revert for me when I put it in wine-tkg-userpatches, and yes it applies in the correct order.

**Comment by Ashraaf** [comment]
> > > Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:
> > 
> > 
> > Here, revert them in this order:
> > https://github.com/wine-mirror/wine/commit/8b6c86eb824d1f529dab7bbbbd09907f41c182d3.patch
> > https://github.com/wine-mirror/wine/commit/550d96b0bf0928ac4dc573f49d2ec2e0c0444fc5.patch
> > https://github.com/wine-mirror/wine/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10.patch
> 
> Still does not revert for me when I put it in wine-tkg-userpatches, and yes it applies in the correct order.

Weird., I managed to revert by giving them name by 1.myrevert 2.myrevert 3.myrevert, compiling latest wine staging right now

**Comment by Ashraaf** [comment]
> > Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:
> 
> Here, revert them in this order:
> https://github.com/wine-mirror/wine/commit/8b6c86eb824d1f529dab7bbbbd09907f41c182d3.patch
> https://github.com/wine-mirror/wine/commit/550d96b0bf0928ac4dc573f49d2ec2e0c0444fc5.patch
> https://github.com/wine-mirror/wine/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10.patch

Thank you.

**Comment by FLGX06** [comment]
> > > > Hello, can someone kindly share the revert patch?, i tried creating it, named it to unity.myrevert and put it in wine-tkg-userpatches, but it failed to apply. Here the log:
> > > 
> > > 
> > > Here, revert them in this order:
> > > https://github.com/wine-mirror/wine/commit/8b6c86eb824d1f529dab7bbbbd09907f41c182d3.patch
> > > https://github.com/wine-mirror/wine/commit/550d96b0bf0928ac4dc573f49d2ec2e0c0444fc5.patch
> > > https://github.com/wine-mirror/wine/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10.patch
> > 
> > 
> > Still does not revert for me when I put it in wine-tkg-userpatches, and yes it applies in the correct order.
> 
> Weird., I managed to revert by giving them name by 1.myrevert 2.myrevert 3.myrevert, compiling latest wine staging right now

Actually it works, but not for proton-tkg.

``` -> ######################################################
 -> 
 -> Reverting your own plain-wine patch /home/flgx/TKG/wine-tkg-git/wine-tkg-git/003-revert.myrevert
 -> 
 -> ######################################################
(Stripping trailing CRs from patch; use --binary to disable.)
patching file dlls/wbemprox/builtin.c
Hunk #1 FAILED at 50.
Hunk #2 succeeded at 823 (offset 2 lines).
Hunk #3 FAILED at 861.
Hunk #4 succeeded at 898 (offset 2 lines).
Hunk #5 succeeded at 1085 (offset 2 lines).
Hunk #6 succeeded at 1125 (offset 2 lines).
Hunk #7 succeeded at 1171 (offset 2 lines).
Hunk #8 succeeded at 1210 (offset 2 lines).
Hunk #9 succeeded at 1218 (offset 2 lines).
Hunk #10 succeeded at 1284 (offset 2 lines).
Hunk #11 succeeded at 1311 (offset 2 lines).
Hunk #12 succeeded at 1331 (offset 2 lines).
Hunk #13 succeeded at 1457 (offset 2 lines).
Hunk #14 succeeded at 1490 (offset 2 lines).
Hunk #15 succeeded at 1518 (offset 2 lines).
Hunk #16 succeeded at 1758 (offset 2 lines).
Hunk #17 succeeded at 1814 (offset 2 lines).
Hunk #18 succeeded at 1827 (offset 2 lines).
Hunk #19 succeeded at 1885 (offset 2 lines).
Hunk #20 succeeded at 1970 (offset 2 lines).
Hunk #21 succeeded at 2015 (offset 2 lines).
Hunk #22 succeeded at 2092 (offset 2 lines).
Hunk #23 succeeded at 2118 (offset 2 lines).
Hunk #24 succeeded at 2160 (offset 2 lines).
Hunk #25 succeeded at 2175 (offset 2 lines).
Hunk #26 succeeded at 2246 (offset 2 lines).
Hunk #27 succeeded at 2281 (offset 2 lines).
Hunk #28 succeeded at 2327 (offset 2 lines).
Hunk #29 succeeded at 2341 (offset 2 lines).
Hunk #30 succeeded at 2401 (offset 2 lines).
Hunk #31 succeeded at 2434 (offset 2 lines).
Hunk #32 succeeded at 2459 (offset 2 lines).
Hunk #33 succeeded at 2475 (offset 2 lines).
Hunk #34 succeeded at 2487 (offset 2 lines).
Hunk #35 succeeded at 2561 (offset 2 lines).
Hunk #36 succeeded at 2604 (offset 2 lines).
Hunk #37 succeeded at 2636 (offset 2 lines).
Hunk #38 succeeded at 2644 (offset 2 lines).
Hunk #39 succeeded at 2809 (offset 2 lines).
Hunk #40 succeeded at 2900 (offset 2 lines).
Hunk #41 FAILED at 2908.
Hunk #42 succeeded at 2971 (offset 2 lines).
Hunk #43 succeeded at 2997 (offset 2 lines).
Hunk #44 succeeded at 3029 (offset 2 lines).
Hunk #45 succeeded at 3056 (offset 2 lines).
Hunk #46 succeeded at 3159 (offset 2 lines).
Hunk #47 succeeded at 3204 (offset 2 lines).
Hunk #48 succeeded at 3258 (offset 2 lines).
Hunk #49 succeeded at 3277 (offset 2 lines).
Hunk #50 succeeded at 3314 (offset 2 lines).
Hunk #51 succeeded at 3325 (offset 2 lines).
Hunk #52 succeeded at 3350 (offset 2 lines).
Hunk #53 succeeded at 3367 (offset 2 lines).
Hunk #54 succeeded at 3392 (offset 2 lines).
Hunk #55 succeeded at 3452 (offset 2 lines).
Hunk #56 succeeded at 3465 (offset 2 lines).
Hunk #57 succeeded at 3487 (offset 2 lines).
Hunk #58 succeeded at 3507 (offset 2 lines).
Hunk #59 succeeded at 3519 (offset 2 lines).
Hunk #60 succeeded at 3538 (offset 2 lines).
Hunk #61 succeeded at 3728 (offset 2 lines).
Hunk #62 succeeded at 3803 (offset 2 lines).
Hunk #63 succeeded at 3874 (offset 2 lines).
Hunk #64 succeeded at 3893 (offset 2 lines).
Hunk #65 succeeded at 3912 (offset 2 lines).
Hunk #66 succeeded at 3959 (offset 2 lines).
Hunk #67 succeeded at 3970 (offset 2 lines).
Hunk #68 succeeded at 3997 (offset 2 lines).
3 out of 68 hunks FAILED -- saving rejects to file dlls/wbemprox/builtin.c.rej```

**Comment by Tk-Glitch** [comment]
Disabling the mk11 fix will fix that one (`_mk11_fix="false"`).

**Comment by FLGX06** [comment]
> _mk11_fix="false"

Yep that fixed it, thanks! Building proton now and will try if The Forest works with proton-tkg again.

**Comment by FLGX06** [comment]
> Could be wine [bug#49109](https://bugs.winehq.org/show_bug.cgi?id=49109). Some Unity games are running again after reverting [78e9b02cebf4b107aba69aa9a845ab661a7daf10](https://source.winehq.org/git/wine.git/commit/78e9b02cebf4b107aba69aa9a845ab661a7daf10).

Right, after reverting that commit, The Forest works again. (tested with 5.8.r0.g7d92cd31 and the commit reverted, previously used 5.7.r18.g813de5d6)
Thanks everyone btw, and I guess @Tk-Glitch will make a config variable or something else to revert it so Unity games work again.
