### ISSUE TITLE
Age of Pirates: Captain Blood

### ISSUE THREAD

**Issue by rejedai** [Frogging-Family/wine-tkg-git#351]
I ran into two problems with this game.
1. The game runs on wine from proton_tkg_6.7.r0.gdeed76f3, but does not run on wine-tkg-staging-fsync-git-6.7.r0.gdeed76f3-326.
2. Background music and videos do not work in the game.

Problem solved:
- The game won't launch without PhysX installed. And only with the legacy version, the game will not start, so a more recent one is required. On amd video cards, need to install legacy before the new version.

[captainBlood.log](https://github.com/Frogging-Family/wine-tkg-git/files/6403644/captainBlood.log)

[Link](https://drive.google.com/file/d/1QShyriSrUWVYHm8WUEAqsld5aq5gzqA4) to the game. The game was not released due to issues with the captain's rights. Nevertheless, there is a physical testkit version for x360, and a build for pc appeared on the net a few days ago.

**Comment by Tk-Glitch** [comment]
The usual culprit in such cases is nvapi. Proton-tkg comes with nvapi and nvapi64 disabled since many games will break with it enabled (which is staging's default). Running your app/game with `WINEDLLOVERRIDES=nvapi=d; nvapi64=d` might be all that's needed.

**Comment by rejedai** [comment]
Does not help. I tried the same on another computer, with an AMD video card and Proton-GE 6.1. The sound has partially appeared, but disappears over time, for example, the sound of the attack is present the first few times, then it disappears.

I switched to Proton-GE 6.1 because there is a built-in Media Foundation, and the newer do not work on my pc.

New log. I used game id persona 4 golden, for protonfixes.
[game.log.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/6485534/game.tar.gz)

**Comment by Tk-Glitch** [comment]
I was able to test the game myself. You can get correct audio with native xact (`winetricks /q xact`). And indeed you need physx installed, even if disabling nvapi (`winetricks /q physx`). I have also installed d3dx9 with winetricks since the game uses d3dx9_41, but I'm not sure if that's actually needed.

**Comment by Tk-Glitch** [comment]
Closing since native xact works.

**Comment by rejedai** [comment]
Unfortunately, pre-rendered videos won't play, but thanks a lot for that.

**Comment by Tk-Glitch** [comment]
Yeah I noticed. It's not mfplat related, it's quartz and friends. It's usually extremely problematic if it doesn't work ootb. You can try installing native quartz, wmp9, one of the codec packs offered in winetricks.. I'll try things on my end and post here in case I can get them to work.

**Comment by Tk-Glitch** [comment]
Yeah it's not too big a problem, thankfully. The problem seems to point to `wmvcore.dll` still. I'll try to see what gstreamer has to say about it.
