### ISSUE TITLE
winevulkan_Use_standard_CRT_memory_allocators4.myearlyrevert fail to apply

### ISSUE THREAD

**Issue by Fox2Code** [Frogging-Family/wine-tkg-git#352]
The patch is failing, I found commits related to the issue on the official wine git repository.

Probably caused by these two commits:
[`winevulkan: Don't use wine_ prefix on PE side.`](https://source.winehq.org/git/wine.git/commit/007a4bc9b0f788f91125b692ea12ce23adf1eb21)
[`winevulkan: Use wine_ prefix for Unix thunks.`](https://source.winehq.org/git/wine.git/commit/0fce8076f2d4bb9b484218d94dc17209879d5caa)

My logs: [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6404399/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/3dfe58b705448f89ddf0db182fab28050a7869d7 & https://github.com/Frogging-Family/wine-tkg-git/commit/b3995c62aad497f55fc9f5ddb9ad6de9024a8920
