### ISSUE TITLE
After the recent update of Proton-tkg all my games stopped running for me, crashing on startup.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#356]
OS: Arch Linux
GPU: Radeon with Mesa-git (RADV)
LLVM 12.0.0
Proton-tkg: b60f1081e4d33fa86c1c5d5a5808fff30d41bd87
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6413944/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6413947/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6413948/prepare.log)
[steam.log](https://github.com/Frogging-Family/wine-tkg-git/files/6413959/steam.log)

I tried to launch two Windows games, since these are the only games I currently have installed on Steam. The first game I tried to launch was Skyrim SE. The second game was Heroes of Might and Magic 5. Skyrim SE just crashes at the start, HMM5 completely freezes at the start until the introductory cinematic appears.
However, it is important to note two things:
1) Before this problem appeared, I had played many hours of these games using Proton-tkg;
2) These games continue to run using the official vanilla Valve's Proton Experimental.
3) The official vanilla Valve's Proton Experimental for some unknown reason does not work on GNOME Wayland (works only on X11), while before this problem I played many hours of these games using Proton-tkg on GNOME Wayland (XWayland), so I would like Proton-tkg started working again.

**Comment by Tk-Glitch** [comment]
Here's the issue:
```
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Bad EXE format for C:\windows\system32\steam.exe.
```
This is an upstream issue, which seems to be pretty random. I have a few things pending but you might want to try a non-makepkg build first. Those (makepkg ones) are known to be problematic.

`3. The official vanilla Valve's Proton Experimental for some unknown reason does not work on GNOME Wayland`

The reason is well known, actually. It's due to https://github.com/ValveSoftware/wine/commit/a30e9f3f9395056df2a5527acb37305613e45079

**Comment by Kerrung** [comment]
So what should I do to fix these problems?

**Comment by Tk-Glitch** [comment]
Was this unclear:
`you might want to try a non-makepkg `

Anyway, I have pushed a workaround which is very annoying and will break some games (the ones explicitly checking for steam.exe): https://github.com/Frogging-Family/wine-tkg-git/commit/b0852ba44bd7d63d98b5ea19ac734a1b8588a99d

The best thing to do, however, would be to use an older staging commit id that used to work for you until a fix is found.

**Comment by Kerrung** [comment]
Do you know from what exactly Wine Staging commit this problem started?

**Comment by Valmar33** [comment]
This is a problem began in mainline Wine, I think? :eyes:

**Comment by Kerrung** [comment]
> This is a problem began in mainline Wine, I think?

I'm actually just trying to figure out what to write here:

_staging_version="..."

**Comment by Tk-Glitch** [comment]
Yeah it's not staging-related. I guess r1 is safe: `552dc36846adaa70e2265a64bce6b622304d3be3`

**Comment by Kerrung** [comment]
> Yeah it's not staging-related. I guess r1 is safe: `552dc36846adaa70e2265a64bce6b622304d3be3`

I compiled Proton-tkg using _staging_version = "552dc36846adaa70e2265a64bce6b622304d3be3" and this is what I found as a result of this:

1) Skyrim SE still does not start, giving exactly the same error:
[steam.log](https://github.com/Frogging-Family/wine-tkg-git/files/6419946/steam.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6419950/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6419953/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6419954/prepare.log)

2) I found another Proton-tkg bug, which is that Proton-tkg is marked as the newest Wine Staging commit anyway, although in fact it is actually one of the previous commits, in this case the one which I indicated.

**Comment by Kerrung** [comment]
By the way, Skyrim SE STRICTLY REQUIRES steamhelper, does not start with _proton_use_steamhelper="false". But now Skyrim SE won't start even with _proton_use_steamhelper="true", even if I'm using the old Wine commit https://github.com/wine-staging/wine-staging/commit/552dc36846adaa70e2265a64bce6b622304d3be3 with it.
Is it possible to make steamhelper work for previous Wine commits that are not yet affected by this new issue?

**Comment by Tk-Glitch** [comment]
You're still using a makepkg build which, as explained before, is not recommended.

> I found another Proton-tkg bug, which is that Proton-tkg is marked as the newest Wine Staging commit anyway, although in fact it is actually one of the previous commits, in this case the one which I indicated.

I'll need a bit more details about this, since your logs are clean. Makepkg builds are all kind of frogged so that sounds like a makepkg-only issue, which I'm not too interested in.

> Is it possible to make steamhelper work for previous Wine commits that are not yet affected by this new issue?

It is already the case. Keep in mind I am not affected by that issue at all on my end and everything works just fine (I have even added the `_new_lib_paths_override` variable to enforce using the steamhelper even on supposedly affected trees, so I can keep using my stuff as usual since everything *works* here). It only affects *some* machines. Since I'm not using makepkg builds at all, your issues might be solved by just moving to a regular build.

**Comment by iWeaker4you** [comment]
Hi @Tk-Glitch  
Do you think this commit will solve this problem with TKG?
https://github.com/GloriousEggroll/proton-ge-custom/commit/63db596d03ca29f28b210ff1ec5b9d959231b1fe

**Comment by Tk-Glitch** [comment]
> Hi @Tk-Glitch
> Do you think this commit will solve this problem with TKG?
> [GloriousEggroll/proton-ge-custom@63db596](https://github.com/GloriousEggroll/proton-ge-custom/commit/63db596d03ca29f28b210ff1ec5b9d959231b1fe)

**Comment by Tk-Glitch** [comment]
Whoops. Missclick. No it won't fix the issue.

**Comment by Kerrung** [comment]
Full fixed now, all works again with makepkg compiled! Thank you so much!
