### ISSUE TITLE
Replace Vulkan child window support with patch for newer attempt?

### ISSUE THREAD

**Issue by aufkrawall** [Frogging-Family/wine-tkg-git#358]
Hello,
Rémi Bernon provided a new patch for child window support that is also included in Proton Experimental:
https://bugs.winehq.org/show_bug.cgi?id=45277#c63
This patch seems to allow more apps to work than currently with `_childwindow_fix="true"`. E.g. 3DCenter Filter Tester doesn't work in wine-tkg with DXVK, whereas it does in Proton Exp. Would it be possible to use that patch instead?

Thanks!

**Comment by llde** [comment]
as of now the current childwindow.patch doesn't apply cleanly:
childwindow.patch -- ( Applied child window for vk patch )
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 32 with fuzz 2 (offset -1 lines).
Hunk #2 succeeded at 55 (offset -1 lines).
Hunk #3 succeeded at 63 with fuzz 2 (offset -1 lines).
Hunk #4 succeeded at 142 (offset 4 lines).
Hunk #5 FAILED at 256.
Hunk #6 FAILED at 281.
Hunk #7 succeeded at 314 (offset 10 lines).
Hunk #8 succeeded at 407 (offset 13 lines).
Hunk #9 succeeded at 646 (offset 79 lines).
2 out of 9 hunks FAILED -- saving rejects to file dlls/winex11.drv/vulkan.c.rej

**Comment by Tk-Glitch** [comment]
The current version of the fs hack patchset contains the newer patch already. The legacy/standalone patch needs to be updated though, indeed.

**Comment by aufkrawall** [comment]
It still fails with staging c814617e2c3226243278a228f80305ba26c52c7f:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x480003f
  Serial number of failed request:  119
  Current serial number in output stream:  119
```
```

#### PROTON PATCHES ####

# Bypass compositor in fullscreen modes - Typically reduces stuttering and improves performance - https://github.com/ValveSoftware/wine/commit/141ba5cf73029029a5a0bd2cdcfd5f9f9ab7ee7b
_FS_bypass_compositor="true"

# Proton Fullscreen patch - Requires 3.16+ for staging and 5.0+ for mainline - Allows resolution changes for fullscreen games without changing desktop resolution
# You can optionally use nearest neighbour upscaling with the WINE_FULLSCREEN_INTEGER_SCALING envvar
_proton_fs_hack="true"

# Proton compatible rawinput patchset - Only effective when _proton_fs_hack is set to "true" - Requires a tree containing 6d7828e8df68178ca662bc618f7598254afcfbe1 (4.20+)
_proton_rawinput="true"

# Enforce mscvrt Dlls to native then builtin - from Proton
_msvcrt_nativebuiltin="true"

# Set the default wine version to win10 (instead of win7) - Necessary to enable d3d12 (for use with vkd3d) in some games
_win10_default="true"

# Other misc proton patches and hacks - Notably contains fixes for some native vk games (such as Doom Eternal) as well as Rockstar launcher
# Also enables some winevulkan performance optimizations - https://github.com/Joshua-Ashton/proton-wine/tree/winevulkan-opt (fs hack) - https://github.com/Joshua-Ashton/wine/commits/winevulkan-opt-mainline (no fs hack)
_protonify="true"
```
and both `_childwindow_fix="false"` and `_childwindow_fix="true"`

**Comment by Tk-Glitch** [comment]
This looks like the XWayland issue.. Are you using Wayland?

**Comment by aufkrawall** [comment]
Plasma Xorg.

**Comment by Szwendacz99** [comment]
i have exactly same problem

**Comment by Tk-Glitch** [comment]
Added with https://github.com/Frogging-Family/wine-tkg-git/commit/37d2f4058e91179b854d2f05ae173e878aa66e50
It needed a rebase so hopefully it's not already broken :frog:
Keep in mind you'll have to disable fs hack to use it.

**Comment by aufkrawall** [comment]
For some reason it still fails to start also with disabled fshack. :(

**Comment by aufkrawall** [comment]
It works for me now with at least 6.14. :)

Though I've built without fullscreen hack, as it regressed and causes Heroes of the Storm not to start (planning to create a ticket for this).

**Comment by Tk-Glitch** [comment]
The "regression" seems to hit 6.13 as well for HotS, so meh.

**Comment by aufkrawall** [comment]
Funny thing is that FSH even makes winecfg.exe stop working correctly, it always crashes when applying new DLL override settings. Indeed this has been broken much longer than since just 6.13.

**Comment by Tk-Glitch** [comment]
My winecfg is fine, and the game simply doesn't work on my end, with or without fshack.

**Comment by aufkrawall** [comment]
There was some dependency (probably on the Linux system, not in the Wine prefix) which I tended to forget to install for this game, just can't recall it. :(

The winecfg issue is really weird (and that you can't repro too :( ), but it's definitely 100% reproducible here. I can switch DLLs from native to builtin as many times as I want in a row without FSH. When I build an otherwise identical protonified Wine build with FSH, it instantly crashes.

**Comment by Tk-Glitch** [comment]
I nuked my prefix (which was a couple years old at this point) and HotS works perfectly fine with the fshack on my end. Still no winecfg error either.

:shrug:

**Comment by aufkrawall** [comment]
I also tried with a clean prefix: I changed vcruntime140 to native, pressed apply (worked). Then I changed it to builtin, pressed apply and it crashed. :frog: 
No custom userpatches etc., just all `#### PROTON PATCHES ####` set to true with 6.14 staging and latest clone of your repo.

**Comment by aufkrawall** [comment]
At long last, I can report that the crash issue with fullscreen hack is gone (likely due to recent commits). =)
