### ISSUE TITLE
valve_proton_fullscreen_hack-staging.patch fails due to upstream changes

### ISSUE THREAD

**Issue by Fox2Code** [Frogging-Family/wine-tkg-git#360]
Commit that broke the patch:
[`winex11.drv: Handle Vulkan surface creation with NULL hwnd.`](https://source.winehq.org/git/wine.git/commit/011fabb2c43d13402ea18b6ea7be3669b5e6c7a8)

Rejects: [vulkan.c.rej.gz](https://github.com/Frogging-Family/wine-tkg-git/files/6422420/vulkan.c.rej.gz) (There are no other rejects)

Console:
![ProtonFSHaxError](https://user-images.githubusercontent.com/42963271/117035606-cb774d80-ad04-11eb-8ef0-85d1314a806e.png)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/06792b3c41392438c4bec3063336e54bff1e417b

**Comment by ObserverOfTime** [comment]
Now the revert patch fails with this: [vulkan.h.rej.gz](https://github.com/Frogging-Family/wine-tkg-git/files/6426243/vulkan.h.rej.gz)
