### ISSUE TITLE
Forza Horizon 4 Crash

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#365]
I tried to run Forza Horizon 4 with 6.8, steam tries to start it but crashes before anything happens.

I did get a proton log
[steam-1293830.log](https://github.com/Frogging-Family/wine-tkg-git/files/6452297/steam-1293830.log)

I'm on mesa git with LLVM-12 AMD 6700xt
Kernel 5.12.2
Distro: Gentoo 

I can launch with Proton-6.8-GE1

Does FH4 require any system libraries specifically?

**Comment by Tk-Glitch** [comment]
It needs native vcrun 2017 or 2019 if I remember well. It's supposedly getting installed on first run, but due to an upstream change we have to choose between games never exiting in steam or initial dependencies installation getting randomly skipped.

See https://github.com/Frogging-Family/wine-tkg-git/commit/f30fd95a14e6813b09de24e89ce848290199da7a
You can try running the game once with `PROTON_ALT_START=1 %command%`, then you should be able to remove it.
The game works fine (outside of known issues) on my end on a 6.8 build.

**Comment by Tk-Glitch** [comment]
Also, you might want to add `amdags-proton.mypatch` to your community patches array if not already done. The game does some calls to amd_ags.

**Comment by shaumux** [comment]
I tried doing both and no luck, I thought missing system library since proton-tkg doesn't use steam runtime
But as a final try, I tried the 6.8-r0 precompiled from here and it works.

Now I'm guessing it's either my compile config or vkd3d-proton

[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6466931/proton-tkg.cfg.txt)
Here's the config I used to compile 6.8.r4.g234a9fe7 today to test.

Is the vkd3d-proton used in the official release master or a version?

**Comment by Tk-Glitch** [comment]
You have used `"amdags.mypatch"` but you'll want `"amdags-proton.mypatch"` as it contains specific changes for FH4.

> Is the vkd3d-proton used in the official release master or a version?

If you mean my 6.8 based release, it was master at the date of release. If you mean valve proton 6.3, it's usually the current latest release version, unless there is a known bug needing a cherry pick. I have played the game on a build from yesterday (6.8.r3) fine, and I doubt it got broken with r4.

**Comment by shaumux** [comment]
With some more testing, I found a very weird behavior, If the prefix is created with your official release FH4 works after installing vcrun-2019 but if I try to use the prefix with a self-compiled version post 6.8 it doesn't run and switiching back to your official release stops working too

I'm thinking there's some issue in the version i'm compiling on how it's handling prefixes

**Comment by Tk-Glitch** [comment]
[proton-tkg.cfg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6515684/proton-tkg.cfg.log)

I have attached my own cfg file (rename to `proton-tkg.cfg` and drop in `$HOME/.config/frogminer/`) for you to try. FH4 works with it. Also, as a side note, I have noticed that the game doesn't run with Wayland.
