### ISSUE TITLE
Pixelated image with fullscreen hack enabled

### ISSUE THREAD

**Issue by Kron4ek** [Frogging-Family/wine-tkg-git#367]
When fullscreen hack is enabled and in-game fullscreen resolution is lower than native screen resolution, the image becomes pixelated (sharpened?). Proton 6.3 doesn't have this issue.

**Proton 6.3-3**:

![proton1](https://user-images.githubusercontent.com/13851877/117971258-161b4a00-b343-11eb-80f8-51307a09f075.jpg)
![proton2](https://user-images.githubusercontent.com/13851877/117971261-174c7700-b343-11eb-978d-cf36b6299bcc.jpg)

**Wine-TkG 6.8**:
![tkg2](https://user-images.githubusercontent.com/13851877/117971266-187da400-b343-11eb-9a72-1ad5170f2d93.jpg)
![tkg](https://user-images.githubusercontent.com/13851877/117971263-17e50d80-b343-11eb-89fa-4d0c4f07f801.jpg)

My native screen resolution is 1680x1050, and the in-game resolution is 1280x800.

I don't know if this reproducible in all games, but at least The Witcher 3 is affected.

**Comment by Sterophonick** [comment]
Just compiled Wine with the FShack and tested with Poker Night 2 and it also has this same effect, :/ Hoping for a fix soon,
![Screenshot_34](https://user-images.githubusercontent.com/34801996/118324118-d9745d80-b4be-11eb-876e-26c570d8d1af.png)

**Comment by Tk-Glitch** [comment]
It feels like an upstream change broke the linear filter. I'll try to bisect.

**Comment by Kron4ek** [comment]
By the way, this issue is not reproducible with WineD3D, so it seems to only affect Vulkan.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/c23fa838165ccbc22bd205319baff910b3844ff4

**Comment by Sterophonick** [comment]
Hey, thanks, Glitch!
