### ISSUE TITLE
Can't compile Proton-tkg 59e9449e: steam.exe.so not found

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#368]
Proton-tkg commit: 59e9449efd37317fece7d11c79a298dd7ab25020
OS: Arch Linux
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6468610/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6468612/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6468613/prepare.log)
![Screenshot from 2021-05-13 00-12-37](https://user-images.githubusercontent.com/36989404/118031952-8b594000-b380-11eb-8e8a-ecbcca6babdb.png)

**Comment by Tk-Glitch** [comment]
Don't use the experimental branch and you'll be fine. I'll prevent the use of experimental branches by default for people tempted to use it :frog:

**Comment by Tk-Glitch** [comment]
"Fixed" with https://github.com/Frogging-Family/wine-tkg-git/commit/6e5c6c594549700f65b4ebdb08589b1cb72e0525 :frog:
