### ISSUE TITLE
Since the lastest Proton update (makepkg version) all my games stop working because permissions reason.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#370]
OS: Arch Linux
Proton-tkg commit: 173ada9c6f71324325b3fff8d2649b7d4b0d4c5c
[steam.log](https://github.com/Frogging-Family/wine-tkg-git/files/6481126/steam.log)
PermissionError: [Errno 13] Permission denied: '/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/files/steampipe_fixups_mtime'

But I myself found the reason and the solution. 

$ sudo touch '/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/files/steampipe_fixups_mtime'
$ sudo chown my-user-name:users '/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/files/steampipe_fixups_mtime'

The reason was that, since this update, Steam tries to create the file '/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/files/steampipe_fixups_mtime' when launching games, but since it is, of course, launched as a regular user, therefore, it does not have permissions to create any files in directories owned by root, so after a failed attempt to create this file, it stops trying to start the game at all. To work around this problem, I myself created an empty file that Steam tried to create, and then transferred the ownership of this file to the regular user on whose behalf Steam was launched. As a result, after that Steam, on the next attempt to start games, wrote some numbers to this file, after which it normally started the game as usual. Maybe it makes sense to add some script to Proton-tkg that does something like this?
![Screenshot from 2021-05-15 02-07-24](https://user-images.githubusercontent.com/36989404/118331677-571d8500-b522-11eb-9b67-e363c36db744.png)

**Comment by CartoonFan** [comment]
I just ran into this too, so thanks for the the fix, @Kerrung. You might want to change 'sudo tourch' to 'sudo touch', however.

Unfortunately, I ran into another problem after applying your fix: Proton seems to be unable to find the c drive.

Console output when trying to launch PC Building Simulator on a clean prefix:

```console
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_BigPicture, AppID 413090
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/jeremiah/.local/share/Steam/steamapps/workshop/content/241100/1557881022/956347096063773104_legacy.bin
Launching appid 621060
Loaded Config for Local Selection Path for App ID 621060, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
Failed to open digital audio driver Couldn't open OAL device.
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to BPMHybridOverlay10ftShutdown with ""
Loaded Config for Local Selection Path for App ID 621060, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
Slow image load - /home/jeremiah/.local/share/Steam/tenfoot/resource/images/library/play_action_modal_mask.png (dimensions 1920x1080, took 23 msec)
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1224, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/pfx//dosdevices/c:'
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1224, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/pfx//dosdevices/c:'
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 621060
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 621060
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 621060, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 621060, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 621060 "", ProcID 893218, IP 0.0.0.0:0
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1224, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/621060/pfx//dosdevices/c:'
Starting app 621060
Loaded Config for Local Selection Path for App ID 621060, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
>>> Adding process 893218 for game ID 621060
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 893219 for game ID 621060
GameAction [AppID 621060, ActionID 3] : LaunchApp changed task to Completed with ""
Game removed: AppID 621060 "", ProcID 893218 
Uploaded AppInterfaceStats to Steam
Exiting app 621060
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Selection Path for App ID 413080, Controller 0: /home/jeremiah/.local/share/Steam/steamapps/workshop/content/241100/922638163/818937737353552570_legacy.bin
```

**Comment by Kerrung** [comment]
> Proton seems to be unable to find the c drive.

@CartoonFan I think Proton seems to be unable to find the c drive because you havn't it, so Proton created it. But I see an another problem in your log: Failed to open digital audio driver. Couldn't open OpenAL device. Are you sure that you have installed openal and lib32-openal packages and speaker or headphones are connected?

**Comment by CartoonFan** [comment]
If you can believe it, both openal and lib32-openal are installed. I tried installing the git versions, too, but no change. Basically, all it seems to affect is the audio in Big Picture mode. It's been a problem since my recent install of Arch, but I've ran this particular game before with sound, so I don't think that it's the same problem (although it's very annoying). I've been using Pipewire, if that helps.

On the issue of the c drive, the folder is there, but it's basically empty. Deleting it and restarting just makes another almost-empty prefix, so I think it's Proton doing (or not doing) something. Here's what the directory looks like:
```console
$ ls -lv compatdata/621060/pfx
total 0
drwxr-xr-x 2 jeremiah jeremiah 0 May 15 03:52 drive_c
```

**Comment by Kerrung** [comment]
> If you can believe it, both openal and lib32-openal are installed. I tried installing the git versions, too, but no change. Basically, all it seems to affect is the audio in Big Picture mode. It's been a problem since my recent install of Arch, but I've ran this particular game before with sound, so I don't think that it's the same problem (although it's very annoying). I've been using Pipewire, if that helps.
> 
> On the issue of the c drive, the folder is there, but it's basically empty. Deleting it and restarting just makes another almost-empty prefix, so I think it's Proton doing (or not doing) something. Here's what the directory looks like:
> ```console
> $ ls -lv compatdata/621060/pfx
> total 0
> drwxr-xr-x 2 jeremiah jeremiah 0 May 15 03:52 drive_c
> ```

Can you create any file in compatdata/621060/pfx not using sudo or root?

**Comment by Tk-Glitch** [comment]
Makepkg builds annoyances 🐸 . Could someone please tell me why they were necessary again? I don't see a point in them tbh. I'll fix that later today with yet another makepkg-only hack.

**Comment by CartoonFan** [comment]
Thanks, @Tk-Glitch!

**Comment by CartoonFan** [comment]
Hey, @Tk-Glitch! Sorry to bug you again, but I did a little more digging into my problem. It seems that Proton is unable to to make complete prefixes, no matter how many times I run the game. However, if, for example, I run protontricks after unsuccessfully launching the game once, protontricks is able to fill out the near-empty prefix, and Steam plays the game just fine afterwards. Am I doing something weird or is this worthy of a separate issue?
