### ISSUE TITLE
Gameforge client white screen

### ISSUE THREAD

**Issue by jona-1993** [Frogging-Family/wine-tkg-git#372]
Hi,

I have an issue with the last wine-tkg version. (After wine 5.11..) I have a white screen with the gameforge launcher.
I can see the splashscreen before however.

My logs:

https://pastebin.com/L5t0n0ut

My customization.cfg:

https://pastebin.com/ei8h7ivU

Have a nice day !

**Comment by Tk-Glitch** [comment]
https://bugs.winehq.org/show_bug.cgi?id=49736

**Comment by kajlamo** [comment]
Try the current version(s), it should work.

**Comment by jona-1993** [comment]
Yes, it works with old versions. Not with 5.11+. I tested with 6.17 and same issue.. 
It looks like a libcef crash.

**Comment by kajlamo** [comment]
![Untitle](https://user-images.githubusercontent.com/86540370/133704591-0bf328cb-a0c5-4167-9562-142608ff9ca7.png)

**Comment by jona-1993** [comment]
Interesting. I will test that this evening ;)

**Comment by Tk-Glitch** [comment]
It might need a fresh prefix

**Comment by jona-1993** [comment]
No, same issue with lutris installer. I created a fresh prefix.
With 6.14 (lutris default): I have a white screen.
With 6.17: I have a page fault.

Log for 6.17:
https://pastebin.com/GbEHLSha

My spec:
Manjaro KDE
Linux 5.14.0-195-tkg-cacule
AMD Ryzen 5950x
Nvidia RTX 3080 Ti

**Comment by kajlamo** [comment]
I don't know if this will help but it worked for me:
1) Download from here with Lutris:
	https://lutris.net/games/gameforge-client/
	Install in a new folder
2) Change Wine version to 6.17 tkg

**Comment by jona-1993** [comment]
Yes, I did that.. I deleted the old prefix before. It's strange..

**Comment by jona-1993** [comment]
I found the issue, it was STAGING_WRITECOPY = 1.
I used that as global configuration in lutris and it crashed cef.
The solution is STAGING_WRITECOPY = 0 ;)

**Comment by Tk-Glitch** [comment]
Oh yeah, this option leads to various issues indeed.
