### ISSUE TITLE
Tokyo Xanadu eX+ hangs and then crashes with builtin qasf

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#373]
Hey there, @Tk-Glitch! I'm back with another bug from the Wine-breaking Tokyo Xanadu eX+. This time, very similarly to https://github.com/Frogging-Family/wine-tkg-git/issues/5, the game hangs for a bit, then crashes with this message:
![20210515-030628](https://user-images.githubusercontent.com/29664894/118356548-a9fb3a80-b52a-11eb-92af-3cc4bdc6ee0a.png)

The crash happens with mainline and wine-TkG. The mainline wine version is wine-6.8.r139.gce72f9b4263 ( TkG Plain ), and the output is here, if it's useful:
[tokyo_xanadu_clean.log.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6485526/tokyo_xanadu_clean.log.zip)

Once again, thanks for your hard work.

**Comment by Tk-Glitch** [comment]
Interesting game, as usual :frog:

**Comment by CartoonFan** [comment]
I know, right? Anyway, I guess that means it's off to WineHQ Bugzilla...

**Comment by CartoonFan** [comment]
So, apparently they declared it as a duplicate of [Wine bug 25329](https://bugs.winehq.org/show_bug.cgi?id=25329), so it might not be fixed for...a while. But here's hoping it's fixed soon!

**Comment by BillFleming** [comment]
From what I remember that game ran fine on standard proton, but that was a while ago.

**Comment by CartoonFan** [comment]
Yeah, for a while, I didn't see any crashes. I just noticed it happening with qasf around Wine-TkG 6.8 or so, so I think it's a recent change.

**Comment by Tk-Glitch** [comment]
> So, apparently they declared it as a duplicate of [Wine bug 25329](https://bugs.winehq.org/show_bug.cgi?id=25329), so it might not be fixed for...a while. But here's hoping it's fixed soon!

Oof. Let's keep our fingers crossed.

**Comment by CartoonFan** [comment]
All right, progress! As of staging https://github.com/wine-staging/wine-staging/commit/7e42d0ac1af37f7c9b852e213ee2ac8086d8906e, the game now works with DXVK! There's a different crash from the original bug, but so far only with WineD3D. Still no videos, but that's a little expected at this point. I uploaded the winedebug log, in case anyone's curious. Thanks, everyone!
[tokyo_xanadu_g161d61481f5.log](https://github.com/Frogging-Family/wine-tkg-git/files/7561361/tokyo_xanadu_g161d61481f5.log)

I guess it's not really the same issue anymore, so I'll close #373.
