### ISSUE TITLE
Error while building proton-tkg on fedora34

### ISSUE THREAD

**Issue by bimokn97** [Frogging-Family/wine-tkg-git#379]
im forgot the log, but the error contain ``glslangValidator' not found``, the simply i can run it again by installing 

- mingw32-gcc-c++
- mingw64-gcc-c++
- glslang

i cant pull request on this git, but somebody can fix it by adding that two prerequisites build on fedora, Thanks

**Comment by bimokn97** [comment]
also can add : 

- mingw32-winpthreads-static
- mingw64-winpthreads-static

Or maybe on fedora needs install with --recommends option

**Comment by Tk-Glitch** [comment]
glslangValidator is usually part of the glslang package (no idea about Fedora specifically). It might be in a separate package like some dev package.

**Comment by Tk-Glitch** [comment]
Ok I can confirm: https://fedora.pkgs.org/33/fedora-x86_64/glslang-11.0.0-1.20200803.git5743eed.fc33.x86_64.rpm.html

`dnf install glslang`

**Comment by bimokn97** [comment]
yeah, Thanks dude, you can wrote that script on prerequired install, so it can be automatically install before compile.

**Comment by Tk-Glitch** [comment]
Thanks for confirming !
