### ISSUE TITLE
valve_proton_fullscreen_hack-staging.patch cannot be applied to wine 6.9

### ISSUE THREAD

**Issue by jpalczewski** [Frogging-Family/wine-tkg-git#380]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6528019/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6528020/last_build_config.log)
[proton-tkg.cfg from frogminer directory](https://github.com/Frogging-Family/wine-tkg-git/files/6528028/proton-tkg.log)

**Comment by ThisNekoGuy** [comment]
I also have this issue, and I disabled the fullscreen hack but now it stops with a different issue:
```
-> Applying dxvk_config_dxgi_support.patch
-> ## Applying reverting hotfix for plain-wine: revert_steamclient_breaker11.myrevert
 ==> ERROR: Patch application has failed.
```
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6528831/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/87ffd1d3695fe7d2abff7524229d78034e1667af
