### ISSUE TITLE
Non-Staging 32-bit Build Error (Arch)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#381]
Attempting to do a build non-Staging build results in a 32-bit build error:

```
Wine build complete.
 -> Building Wine-32...
configure: WARNING: unrecognized options: --with-xattr
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... ccache gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether ccache gcc accepts -g... yes
checking for ccache gcc option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether ccache g++ accepts -g... yes
checking for ccache g++ option to enable C++11 features... none needed
checking for cpp... cpp
checking for ld... ld
checking whether ccache gcc -m32 works... no
configure: error: Cannot build a 32-bit program, you need to install 32-bit development libraries.
```

**Comment by Tk-Glitch** [comment]
Did you enable multilib? If you did, this error usually means that your compiler is broken. This is not a wine-tkg issue.

**Comment by ThisNekoGuy** [comment]
I do have multilib enabled; could it be because I updated GCC?

**Comment by Tk-Glitch** [comment]
Possibly.

**Comment by ThisNekoGuy** [comment]
I've tried downgrading, clearing the cache, and re-upgrading (also recompiling while downgraded) but it refuses to compile with the same error everytime... :v
Got no idea how to fix this

**Comment by Tk-Glitch** [comment]
Please send your `wine-tkg-git/wine-tkg-git/src/wine*-32-build/config.log` file over.

**Comment by ThisNekoGuy** [comment]
The folder doesn't exist:

![no_folder](https://user-images.githubusercontent.com/28468662/119414835-e1fb3e00-bcdf-11eb-97ab-1daf16924fa0.png)

**Comment by Tk-Glitch** [comment]
I thought you were building regular wine. For proton it'll be the `proton_dist-32-build` dir.

**Comment by ThisNekoGuy** [comment]
Sorry, I meant to be more clear about that; I'm trying to build proton but I just kept getting this error both non-staging and staging
[config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6535308/config.log)

**Comment by ThisNekoGuy** [comment]
Also, `gcc -v` claims it's 10.2.0 but the package is listed as 11.1.0-1
![gcc](https://user-images.githubusercontent.com/28468662/119415786-dc065c80-bce1-11eb-9626-0856299156ce.png)

**Comment by Tk-Glitch** [comment]
Okay I'm seeing anomalies.

You have `/opt/cuda/bin/` in your path, leading to
```
COLLECT_GCC=/opt/cuda/bin/gcc
```
While
```
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
```

There seems to be a mismatch since this shouldn't happen:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
```

**Comment by ThisNekoGuy** [comment]
I see

So, do I have have to fix a path or...?
![cuda](https://user-images.githubusercontent.com/28468662/119418249-17eff080-bce7-11eb-9771-45bd638252e8.png)

**Comment by ThisNekoGuy** [comment]
Because I've had this set in my path for a long time, it's weird that this problem is only just now ocurring for me.

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch I had removed it from my path entirely but it still thinks it's there even after reboots

**Comment by Tk-Glitch** [comment]
Alternatively you can set the compiler path manually in wine/proton-tkg .cfg files (by default `wine-tkg-git/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg` for wine, and `wine-tkg-git/proton-tkg/proton-tkg-profiles/advanced-customization.cfg` for proton). If you're using an external config file (in `$HOME/.config/frogminer/` by default) you can of course use that instead.

```
# Custom compiler root dirs - Leave empty to use system compilers
# Example: CUSTOM_MINGW_PATH="/home/frog/PKGBUILDS/mostlyportable-gcc/mingw-mostlyportable-9.2.0"
# Example: CUSTOM_GCC_PATH="/home/frog/PKGBUILDS/mostlyportable-gcc/gcc-mostlyportable-9.2.0"
CUSTOM_MINGW_PATH=""
CUSTOM_GCC_PATH=""
```

**Comment by ThisNekoGuy** [comment]
I actually tried this (by putting `/usr/bin/gcc` as a custom path in the external config) , thinking it might work too, but it still resulted with the same error :/

**Comment by ThisNekoGuy** [comment]
However, it still fails except it's near the end this time:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/ccache failed
make: *** [Makefile:394: lsteamclient.dll.so] Error 2
make: Leaving directory '/home/neko-san/wine-tkg-git/proton-tkg/external-ressources/Proton/build/lsteamclient.win32'
'Proton/build/lsteamclient.win64/lsteamclient.dll.so' -> 'proton_dist_tmp/lib64/wine/x86_64-unix/lsteamclient.dll.so'
cp: cannot stat 'Proton/build/lsteamclient.win32/lsteamclient.dll.so': No such file or directory
neko-san@ARCH ~/w/proton-tkg (master)> 
```

**Comment by Tk-Glitch** [comment]
Try with just `CUSTOM_GCC_PATH="/usr"`.

**Comment by ThisNekoGuy** [comment]
That worked! Thanks :+1:
