### ISSUE TITLE
Application could not be started, or no application associated with the specified file. ShellExecuteEx failed: Bad EXE format for C:\windows\system32\steam.exe.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#383]
After today's Proton-tkg update all my games stopped work at all again for old error message and maybe old reason of this periodical happens regression.

Proton-tkg commit: 3a035bcc9104d5ee8336f75d0daf74dd8e337566
OS: Arch Linux
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6535027/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6535028/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6535029/prepare.log)
[steam-log.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6535030/steam-log.txt)

**Comment by Tk-Glitch** [comment]
Return of the fun error I can't reproduce. I love it.

**Comment by Tk-Glitch** [comment]
Oops, didn't mean to close this :frog:

**Comment by Kerrung** [comment]
Everything worked fine with commit 87ffd1d3695fe7d2abff7524229d78034e1667af

**Comment by Kerrung** [comment]
> Everything worked fine with commit [87ffd1d](https://github.com/Frogging-Family/wine-tkg-git/commit/87ffd1d3695fe7d2abff7524229d78034e1667af)

I just compiled with commit 87ffd1d3695fe7d2abff7524229d78034e1667af, but it didn't help in any way to get Skyrim SE up and running. It seems that the last time I successfully launched this game with the commit ff071e4b361896733fa9e84901ac1646cf03557e, but then the Wine Staging commit was different, more precisely, it was https://github.com/wine-staging/wine-staging/commit / f308782dadd2231f1e287e676aeb95e5a1e28e29
So I ask you to forgive me for the somewhat inaccurate information that I precisely updated for you.

**Comment by Tk-Glitch** [comment]
Just installed Skyrim SE with a fresh 6.9r1 build. It ran just fine. Your issue is elsewhere. I'd try nuking the prefix.
![Screenshot_20210525_003532](https://user-images.githubusercontent.com/741977/119415086-2d6a1800-bcf1-11eb-852d-b30c06b1c063.png)

**Comment by Kerrung** [comment]
Everything worked fine since fixes from commit https://github.com/Frogging-Family/wine-tkg-git/commit/24490eb75a23a8c4e1956b2b3dfd672c2891ce8a and nuking the prefix. Thank you so much!

But it turned out that the game will not start so easily after nuking the prefix, because it contains an some .ini file without which the game refuses to start and asks to reinstall it, and even checking for the integrity of the files does not help fix this. I fixed this by copying all the contents of the old prefix to the fresh one, but without replacing the files (skip all), because I don't know exactly what the name of this file is and where exactly it is located.
