### ISSUE TITLE
Compilation of Proton-tkg fails: "cp: cannot stat 'Proton/build/steam.win32/steam.exe.so': No such file or directory"

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#384]
Proton-tkg commit 87f3e8d1d77f212991274046ffb95e05869ea068
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6538292/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6538293/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6538282/proton-tkg.log)
![Screenshot from 2021-05-25 14-51-41](https://user-images.githubusercontent.com/36989404/119477846-c425eb80-bd68-11eb-828d-4a66bf864b60.png)

**Comment by Tk-Glitch** [comment]
It's because of https://github.com/wine-mirror/wine/commit/4e8fcc41ca42f7e047e4a5cb708a75447a753143
A fix will be pushed soon.

**Comment by jaromero** [comment]
This just happened to me on master. Almost the same, error, except that the line reported is different:

```
/home/ar/Development/wine-tkg-git/proton-tkg/Proton/build/steam.win32/steam.cpp:672: undefined reference to `__wine_make_process_system'
```
