### ISSUE TITLE
Proton-tkg build failing on patch application.

### ISSUE THREAD

**Issue by kruesephiikz** [Frogging-Family/wine-tkg-git#385]
-> Applying dxvk_config_dxgi_support.patch
 -> ## Applying reverting hotfix for plain-wine: revert_steamclient_breaker12.myrevert
 ==> ERROR: Patch application has failed. The error was logged to /home/kruesephiikz/frogging/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
==> ERROR: A failure occurred in build().
   Aborting...
 -> exit cleanup done

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6544901/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6544903/last_build_config.log)

Sorry TKG, it broke again.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/91156bb18173a180dc03e6619ad63eef7470651c
