### ISSUE TITLE
Since the latest Proton-tkg uptades Skyrim SE don't work anymore (regressions again).

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#387]
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6556957/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6556958/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6556959/prepare.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6556970/proton-tkg.zip)
[proton-tkg-profiles.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6556973/proton-tkg-profiles.zip)
[steam-skyrimse.log](https://github.com/Frogging-Family/wine-tkg-git/files/6557124/steam-skyrimse.log)
OS Arch Linux;
A makepkg version of Proton-tkg, commit: f2524822b24777515d075fbc70cd2197c33fc2c2

I see several new regressions I have never seen before. After I installed the new version of Proton-tkg, when I press the "Play" button to start Skyrim SE, I write a window with a message about preparing to launch the game, but the problem is that I see this window indefinitely, but then the game launcher never starts. Then I close this window, then try again to launch the game launcher, but again I see endless preparation for launching the game. It is likely that at this time there is an unsuccessful attempt to execute the wineboot -u command to update the prefix after updating the Wine version, which simply hangs. Then I close the game preparation window again and press the blue button on Steam to force the game to stop, but then I find the "wine", "wineboot", "wineserver" and other Wine processes still running in the GNOME system monitor. Then I end these processes manually. And after that I try to launch the game launcher again, but this time it starts. Then I press the Play button on it, but instead of launching the game, I see an error window, but the game never starts:
![Screenshot from 2021-05-28 03-30-27](https://user-images.githubusercontent.com/36989404/119905256-4f6bd080-bf65-11eb-9b59-a96879031abc.png)

Then I downgrade to the previously saved package proton-tkg-git-6.9.r3.g69765f43-1-x86_64.pkg.tar.zst, after which there is still an endless preparation for starting the game, but after killing Wine processes manually, the game starts up and normally works without problems. About the fact that the regression of the infinitely long preparation for the launch of the game appeared only a few days ago.

**Comment by Tk-Glitch** [comment]
Note:
I'm seeing this in logs: `err:dialog:EndDialog got invalid window handle (0000000000000000); buggy app !?`

**Comment by Kerrung** [comment]
> Note:
> I'm seeing this in logs: `err:dialog:EndDialog got invalid window handle (0000000000000000); buggy app !?`

And what does that mean? All these problems did not exist a few days ago, until the recent updates.

**Comment by Kerrung** [comment]
I just retested with the https://github.com/Frogging-Family/wine-tkg-git/commit/1de59a429ceb8bf9de35618ceed3ea4ca4578206 commit. Now all works fine! Thank you so much!
