### ISSUE TITLE
Prefixes updates (wineboot -u) hangs after each Protom-tkg versions update.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#393]
https://github.com/Frogging-Family/wine-tkg-git/commit/1de59a429ceb8bf9de35618ceed3ea4ca4578206 commit made it possible to start Skyrim SE again, thank you for that. But to run it after compiling and updating to the new version of Proton-tkg, after clicking on the "Play" button in Steam, I have to kill all Wine processes, because they hang, and after that, on the second try, Skyrim SE starts and works fine. And if I do not kill the processes "wine", "wineboot", "wineserver" and other Wine processes, then I will be forced to see a window with the inscription "Preparing to launch Skyrim SE" for an infinite amount of time, until I kill all Wine processes. I have already described this problem in #387. I thought it was already solved by 1de59a429ceb8bf9de35618ceed3ea4ca4578206 commit, until today I compiled with makepkg a new version of Proton-tkg b040f91cefb2d00c6dd7ee65c7ab6501e525b736 including new Wine upstream updates and during updating the prefix ("Preparing to launch Skyrim SE" Steam window) after updating the Proton-tkg version, Wine processes hung again. I draw your attention to the fact that this only happens once after each update of Proton-tkg, as this automatically triggers the update of the prefix with wineboot -u. That is, such hungs occur only each during prefix updates.

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6564979/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6564980/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6564981/proton-tkg.log)

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue on my end. Please attach a steam log. Also, please try a regular build (**NOT** built with makepkg).

**Comment by Kerrung** [comment]
> I cannot reproduce the issue on my end. Please attach a steam log. Also, please try a regular build (**NOT** built with makepkg).

I believe I should test with the newest commit, but I can't do that until you fix #394.

**Comment by Tk-Glitch** [comment]
You can, since #394 only affects the makepkg builds, which I asked you **NOT** to use :frog:

**Comment by Kerrung** [comment]
I just retested with 5561f021266c3e55eaef77f23a32caa33efee28b, with a fresh prefix creating from scratch. And so it still hangs, Skyrim SE game launcher now became ignoring Russian language locale that I selected, and then when I press the "Play" button on the game launcher, it's instantly crashes every times, so the game never launch. It I restore the old early saved prefix, Russian language locale works fine.

**Comment by Kerrung** [comment]
[steam-skyrimse-fresh-pfx-creation.log](https://github.com/Frogging-Family/wine-tkg-git/files/6565488/steam-skyrimse-fresh-pfx-creation.log)
[steam-skyrimse-after-fresh-pfx-creation-2.log](https://github.com/Frogging-Family/wine-tkg-git/files/6565487/steam-skyrimse-after-fresh-pfx-creation-2.log)

**Comment by gardotd426** [comment]
Same issue here. After I kill the wine processes it says `EXE wrong format C:/windows/system32/steam.exe` but otherwise my logs look like @Kerrung's. And starting today, proton_tkg won't even build, it hangs on "Generating default prefix."

**Comment by gardotd426** [comment]
I just left it for like 4 hours and when I came back the Wineprefix update window was still up saying "the prefix at /home/matt/dev/wine-tkg-test/proton_tkg_6.9.r8.g9efac47e/files/share/default_pfx is being updated, please wait..." but the actual `./proton-tkg.sh` command just exited at some point with no error, and obviously the "build" never got installed. 

```
Using prebuilt mfplay

Applying new_lib_paths.patch
patching file proton
Hunk #2 succeeded at 153 (offset 2 lines).
Hunk #3 succeeded at 327 (offset 22 lines).
Hunk #4 succeeded at 724 (offset 180 lines).
Hunk #5 succeeded at 809 with fuzz 2 (offset 180 lines).

Fixing PE files...

Generating default prefix...
```

That's literally it, then the command ends. And the wineprefix update window is still up even as I type this. And again this was on a completely fresh git clone with no modifications to the config files.

**Comment by Kerrung** [comment]
>Generating default prefix...

@gardotd426 during it try this command:
$ pkill -f ".exe";pkill -f "wine*"

**Comment by Kerrung** [comment]
I just retested with ff3fba419a1638e15b8fc46fbfe92bdba423a9d4. I completely deleted the prefix. Then, when I restarted Steam, it started downloading my savegames of SkyrimSE from the cloud, and it did so even before the new prefix was created. Then, when he finished downloading them, I pressed start the game, which triggered the creation of a new prefix. I waited 1.5 hours for this process of creating a new prefix to end, but unfortunately it never ended. It is noteworthy here that for the first time I saw two "wine" processes running simultaneously in the GNOME system monitor for a long time, after a while not a single one was left, but the window for creating a new prefix remained on the screen until I forcibly killed all Wine professors with the command $ pkill -f ".exe"; pkill -f "wine *":
![Screenshot from 2021-05-31 12-17-51](https://user-images.githubusercontent.com/36989404/120158535-ac89af80-c20d-11eb-8263-e104072dfcd3.png)
After that, I tried to start SkyrimSE again and this time it started without problems, and now, unlike the previous Proton-tkg commit, the game normally takes into account the my native Russian language I selected, that is, this problem is solved, but the game did not see the presence of my savegames, despite the fact that they are definitely there. It's good that, just in case, I made a backup copy of the prefix along with my savegames, because restoring the old copy of the prefix causes the game to see my savegames again.

**Comment by Tk-Glitch** [comment]
I'd really like to understand what's going on as I can't reproduce it at all on my end. I have tried deleting dxvk_config.dll from the dxvk dir and from the default pfx but it'll fail differently. Deleting it from the game's prefix will just lead to it getting copied back when launching the game, so I have not the slightest idea of why this happens.
The log seems to indicate that it's trying to copy stuff *from* the game's prefix instead of copying stuff *to* the game's prefix. So weird.

The error itself is found in steam logs from https://github.com/Frogging-Family/wine-tkg-git/issues/393#issuecomment-850918893:
```
Proton: Upgrading prefix from None to 6.9-8 (/home/user/.local/share/Steam/steamapps/compatdata/489830/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1216, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 976, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 718, in setup_prefix
    try_copy(g_proton.dxvk_dir + "x32/" + f + ".dll",
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 81, in try_copy
    shutil.copy(src, dst)
  File "/usr/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/windows/system32/dxvk_config.dll'
```

I have changed the paths for dxvk since, so a current steam log would be cool to have.

> unlike the previous Proton-tkg commit, the game normally takes into account the my native Russian language I selected

I haven't touched anything about this, neither before nor after. The issue was likely a side effect of a broken prefix due to that stalling prefix creation step.

Does it happen with any version? For example, have you tried using `_staging_version="v6.8"`, and if so, does this prefix creation issue persists?

**Comment by Kerrung** [comment]
Retested with ff3fba419a1638e15b8fc46fbfe92bdba423a9d4 specially for creating [steam-skyrimse-fresh-pfx-creation.log](https://github.com/Frogging-Family/wine-tkg-git/files/6570707/steam-skyrimse-fresh-pfx-creation.log)
I completely removed the prefix again, then waited for about a few more hours while a new prefix was created and my Skyrimse's savegames were downloaded from the Steam cloud. Then, when savegames had completely finished downloading and I got tired of waiting for the frozen prefix creation (wineboot), I killed the wineboot process, which caused the game launcher to start immediately after I did it. Then I started the game without any problems, but the game does not see the presence of my Skyrimse's savegames, without shaking the fact that I made sure that they were downloaded exactly.

**Comment by Tk-Glitch** [comment]
Apparently there's an issue with `gst-editing-services` package and prefix creation. If you have that package installed, please try uninstalling it. If it works, then I guess we'll be forced to ship the whole gstreamer block or none of it to fix the issue.

**Comment by Kerrung** [comment]
> Apparently there's an issue with `gst-editing-services` package and prefix creation. If you have that package installed, please try uninstalling it. If it works, then I guess we'll be forced to ship the whole gstreamer block or none of it to fix the issue.

I did have the "gst-editing-services" package installed, but only because it is a required dependency for the "rygel" package, which is part of the "gnome" package group, that is, I installed it a long time ago when I installed gnome, but this problem of creating a prefix first appeared to me about last week or a little earlier.
Now, at your request, I tried to remove the "gst-editing-services" package, which of course led to the removal of the "rygel" package due to the fact that these packages are related dependencies. After that, I again completely removed SkyrimSE's prefix and clicked the "Play SkyrimSE" button on Steam to recreate the prefix. All this led to the fact that this time the prefix was created quickly and without problems and the game started normally. But SkyrimSE still does not see the presence of my savegames, despite the fact that they definitely exist, because Steam downloaded their clouds during the creation of the prefix and I see that they are in the directory for SkyrimSE's savegames inside the prefix, in user's Documents. By the way, why is the user's Documents directory actually located inside the prefix, instead of being a symlink to the real user's Documents folder? As far as I know, vanilla Wine by default uses symlinks to these user directories for this.

**Comment by Tk-Glitch** [comment]
> By the way, why is the user's Documents directory actually located inside the prefix, instead of being a symlink to the real user's Documents folder? As far as I know, vanilla Wine by default uses symlinks to these user directories for this.

Proton doesn't, see https://github.com/ValveSoftware/wine/commit/eb1e88119d8b634cc5a99eae96ac7715e362e5b6

The save issue may or may not be related to an upstream change in the last patchwave: https://github.com/wine-mirror/wine/commit/4111801ab317529c3e24c39a6a97e7043438231a

**Comment by Kerrung** [comment]
> The save issue may or may not be related to an upstream change in the last patchwave: [wine-mirror/wine@4111801](https://github.com/wine-mirror/wine/commit/4111801ab317529c3e24c39a6a97e7043438231a)

How can I check this? Or maybe how can I revert this Wine's commit to test this? Or is it somehow possible to adjust to the new "winvista + AppData paths" standards so that SkyrimSE can see my savegames?

**Comment by Tk-Glitch** [comment]
Basically you just have to move the skyrim prefix you just have to move `489830/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/` to `489830/pfx/drive_c/users/steamuser/Documents/My Games/Skyrim Special Edition/` and you should see your saves ingame.

**Comment by gardotd426** [comment]
Yeah, I can also confirm removing the gst package (and rygel as well since
it requires gst-editing-services) prefixes get created right away as they
always did.

**Comment by Kerrung** [comment]
> Basically, in your skyrim prefix you just have to move `489830/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/` to `489830/pfx/drive_c/users/steamuser/Documents/My Games/Skyrim Special Edition/` and you should see your saves ingame.

If so, then this means that Steam itself, by default, when creating a new prefix from scratch, downloads SkyrimSE's savegames to the wrong directory. And if this is the case, then what are the possible ways to fix it so that Steam starts downloading savegames to the correct directory by default?

**Comment by Tk-Glitch** [comment]
Indeed.
I have added a hack so My Documents gets symlinked to Documents with https://github.com/Frogging-Family/wine-tkg-git/commit/6f3a7814040aa0aaf232e75edd9e630341aaee4d
This preserves compatibility with older/other proton builds as well as existing saves. Hopefully no game will need more exotic paths covered.

**Comment by Kerrung** [comment]
> Indeed.
> I have added a hack so My Documents gets symlinked to Documents with [6f3a781](https://github.com/Frogging-Family/wine-tkg-git/commit/6f3a7814040aa0aaf232e75edd9e630341aaee4d)
> This preserves compatibility with older/other proton builds as well as existing saves. Hopefully no game will need more exotic paths covered.

Thank you! Now I'm going to do makepkg https://github.com/Frogging-Family/wine-tkg-git/commit/6f3a7814040aa0aaf232e75edd9e630341aaee4d to test all the new changes!

And a one more question: Do you have any plans to find a solution for those who have "rygel" package installed, as it is included in the standard GNOME package group and as well gst-editing-services since
it requires it as hard dependency?

**Comment by Tk-Glitch** [comment]
Yes I'd like to find a solution. It took days to find the culprit since I couldn't reproduce it on my end (using plasma and i3, so no dependency on GNOME packages) thanks to @openglfreak who also faced it recently.

See https://github.com/Frogging-Family/wine-tkg-git/issues/396

**Comment by Kerrung** [comment]
I retested with https://github.com/Frogging-Family/wine-tkg-git/commit/6f3a7814040aa0aaf232e75edd9e630341aaee4d and now a prefix was created from scratch without any problems and SkyrimSE have see my savegames. Thank you!

**Comment by Tk-Glitch** [comment]
Great :+1: What a rollercoaster ! :frog:

**Comment by Kerrung** [comment]
But, of course, this is only if the gst-editing-services package is not installed. Therefore, the main problem of this issue has not yet been resolved, therefore, in my opinion, it would be premature to close it for now.

**Comment by Tk-Glitch** [comment]
Keeping this one open would mean having a duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/396
That's why I closed.
