### ISSUE TITLE
Can't compile Proton-tkg with 4e3faff88fce41b3d454a2d9848a9ae50c6131e2

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#394]
4e3faff88fce41b3d454a2d9848a9ae50c6131e2 makepkg version.
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6565394/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6565395/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6565396/proton-tkg.log)
![Screenshot from 2021-05-30 03-27-44](https://user-images.githubusercontent.com/36989404/120086228-735f1b80-c0f7-11eb-81ae-7f548621e153.png)

**Comment by ptr1337** [comment]
repull or delete your directory, fresh pull + if external config rebase it also to newest changes
should work then

**Comment by Kerrung** [comment]
> repull or delete your directory, fresh pull + if external config rebase it also to newest changes
> should work then

Thanks for the advice, but every time I compile a new Persia, I delete everything except the configuration files and source code, so as not to download it again every time.

**Comment by ptr1337** [comment]
> > repull or delete your directory, fresh pull + if external config rebase it also to newest changes
> > should work then
> 
> Thanks for the advice, but every time before I compile a new version, I delete everything except the configuration files and source code, so as not to download it again every time.

He will fix it in some time.

**Comment by Kerrung** [comment]
It's fixed now.
