### ISSUE TITLE
[Unhandled pNext chain conversion] Is it ok?

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#40]
OS: Arch Linux;
Wine-tkg-git commit: https://github.com/Frogging-Family/wine-tkg-git/commit/ee5e71e16916573bb3324310d313ce3f9619ed66
Log file: [last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4638309/last_build_config.log)
![Screenshot from 2020-05-16 16-59-26](https://user-images.githubusercontent.com/36989404/82119336-06e8d700-9797-11ea-9b6f-f93f0f994cca.png)

**Comment by Tk-Glitch** [comment]
Yes those are normal and can be ignored.

**Comment by Kerrung** [comment]
> Yes those are normal and can be ignored.

But what it means?

**Comment by Tk-Glitch** [comment]
It means we are running Wine's `make_vulkan` script, and some things aren't fully handled. You couldn't see the output before I made the call explicit in `prepare.sh` but this is nothing new.
