### ISSUE TITLE
assettocorsa_hud_perf related bug is marked as fixed in wine upstream

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#402]
Is this patch still needed? Bug https://bugs.winehq.org/show_bug.cgi?id=46955 marked the issue as fixed with the "dwrite: Do not require fontface object for HasCharacter()." commit.

Considenring that the customization.cfg has a "Create all kind of issues since b7b1ad0 (5.9 devel), so be careful with that." warning, it may be better to just remove it altogheter.

**Comment by Tk-Glitch** [comment]
The revert patch still offers the best performance. Proton 6.3 implements it as a game-only fix through steam id check (which we are also using in proton-tkg, bypassing the aforementioned issues), but we can't do that on a regular wine build, so it's left at user discretion there.

**Comment by Tk-Glitch** [comment]
Closing since the question was answered imo :)
