### ISSUE TITLE
"ECDH is not supported" in Steep with Proton's bcrypt patches applied

### ISSUE THREAD

**Issue by tannisroot** [Frogging-Family/wine-tkg-git#404]
When I have the Proton Bcrypt patchset option enabled, Steep, a Uplay title, can't connect to its servers due to missing ECDH support in bcrypt:
```
065c:fixme:bcrypt:BCryptCreateHash ignoring object buffer
065c:fixme:bcrypt:key_secret_agreement ECDH is not supported.
0658:fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
0658:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
065c:fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
065c:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
065c:fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
065c:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
```
I am not sure what's wrong with that patchset, but enabling Staging's bcrypt patchset instead allows the game to connect to its servers just fine.
Version tested - wine-tkg-6.10, stock settings, but I also have the issue with the 6.9.

**Comment by tannisroot** [comment]
Oh, I looked at the patchset and it just doesn't implement ECDH whatsoever.
Well, the issue is still valid and I think it would be helpful to keep it open in case someone else encounters this conflict, and until it's resolved somehow.

**Comment by rizzini** [comment]
I"m having this exact same issue now trying to play UNO, which also uses Uplay.

**Comment by rizzini** [comment]
I'm having the same issue playing a Ubisoft game(UNO). I tested with the latest wine-tkg-git and I'm still getting the same bcrypt messages.
