### ISSUE TITLE
Can't compile Proton-tkg with wine_wayland_driver.mypatch

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#409]
Arch Linux
Proton-tkg makepkg ac8c36503d9fc77e2e0fc5b0f55a0b159d5dfc34
https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/wine_wayland_driver.mypatch
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6633811/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6633812/prepare.log)
![Screenshot from 2021-06-11 00-06-23](https://user-images.githubusercontent.com/36989404/121582826-eac27280-ca48-11eb-97eb-c06527c2beea.png)

**Comment by Tk-Glitch** [comment]
Make sure you have the required dependencies installed:
```
note that building with
Wayland requires wayland-client, wayland-egl and xkbcommon development
files to be present on the system
```

That being said, judging by your screenshot, it has nothing to do with the patchset, and looks more like an issue downloading mono or gecko.

**Comment by shumvgolove** [comment]
Compiles successfully on my end.

**Comment by Kerrung** [comment]
![Screenshot from 2021-06-12 13-36-52](https://user-images.githubusercontent.com/36989404/121770561-61638b00-cb83-11eb-9eca-029952efa2e5.png)
