### ISSUE TITLE
Getting hit by bug #49007

### ISSUE THREAD

**Issue by OneOfOne** [Frogging-Family/wine-tkg-git#41]
The patch from https://bugs.winehq.org/show_bug.cgi?id=49007#c11 doesn't revert cleanly atm and WoW won't start with 5.8x.

**Comment by Tk-Glitch** [comment]
I'm offering a specific revert patch as hotfix for -tkg so you don't have to: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/hotfixes/fd7992972b252ed262d33ef604e9e1235d2108c5-6.myrevert

You'll get prompted about applying it or not at build time.

I can't get bnet launcher to install the game lately so I can't test WoW at all. Anyway that's an upstream bug that's getting worse every day and we'll eventually hit a dead end where we can't have partial reverts working anymore. It would be nice to see this fixed soon considering the huge number of games affected..

**Comment by OneOfOne** [comment]
@Tk-Glitch that revert sadly doesn't fix it :-/

**Comment by openglfreak** [comment]
@OneOfOne @Tk-Glitch Here: https://gist.github.com/openglfreak/537f542262d3fa294ac4f784337e6e51

**Comment by OneOfOne** [comment]
@openglfreak sadly that didn't work either, wow's initial window doesn't render at all.

**Comment by Tk-Glitch** [comment]
openglfreak's patch effectively results in the same code, so yeah no reason for a change in behavior. With all the breakage since 5.6 it's probably best to stay on 5.5 for WoW/blizzard stuff until things are getting better.
