### ISSUE TITLE
Upstream  commit 308a5e7 break 32bit applications

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#413]
https://bugs.winehq.org/show_bug.cgi?id=51262

A patch is in the list but still not committed:
https://source.winehq.org/patches/data/207642

**Comment by Tk-Glitch** [comment]
Thanks! Added the fix with https://github.com/Frogging-Family/wine-tkg-git/commit/68190c3dfab48e360d6833b894cd340cdf556e31
