### ISSUE TITLE
_build_gstreamer Broken

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#415]
While trying to build proton-tkg yesterday, I kept getting this maddening error once the wine compilation was finished, when the rest of the proton stuff starts:

```
Cloning into 'gst-orc'...
/usr/lib/git-core/git-remote-https: /home/matt/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/git-core/git-remote-https)
HEAD is now at bb11c51 update wine
error: pathspec '9901a96' did not match any file(s) known to git
```

I traced it at least in part to proton_templates/gstreamer, as well as maybe the move from `external-ressources` to `external-resources`.  

Obviously I do have `/home/matt/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4` (plus my own system `/usr/lib/libcurl.so.4`. 

I've been able to reproduce this in 3 different `git clone`s, and if I disable building gstreamer w/ `_gstreamer="false"`, it builds normally.

Anyway, I was also getting some additional errors on some runs resembling something like `cd: gst/ No such file or directory` or whatever, and I've seen some stuff in `proton-tkg.sh` and `proton_template/gstreamer` that seem wonky, like how in `proton_template/gstreamer` it says to clone the repos into `$_nowhere/Proton`, even though `$_nowhere` is `$PWD` meaning `proton-tkg`, and it also sets `PKG_CONFIG_PATH` as `"$proton_tkg_path/gst/lib64/pkgconfig"`, but nothing's getting cloned there. I mean I see where you're symlinking the contents of `external-resources` to `$_nowhere`, but idk it seems like sometimes it's not working. But that very well may have nothing to do with this issue.

**Comment by gardotd426** [comment]
I saw the "create gst directory before running _gstreamer" or whatever commit, so I thought you might have independently found and fixed the bug, but sure enough it still fails with the same error.

**Comment by gardotd426** [comment]
So, something's wrong with the steam runtime or something like that. 

I ran `mv ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4 ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.bak && ln -s /usr/lib/libcurl.so.4 ~/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4`, and the build completed. 

So, then to confirm, instead of just moving back ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4.bak to it's original place, I *recreated* the symlink by running `ln -s ~/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0 ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4`, since the original libcurl.so.4 file there was a symlink to that libcurl.so.4.2.0 file. 

And sure enough, this time it worked again. So somehow, the symlink didn't get updated, even though when I ran `file ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4.bak`, I got: `/home/matt/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4.bak: symbolic link to /home/matt/nvme/steamroot/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0`

So the symbolic link wasn't broken, and just creating a new one to the same file fixed the issue, so what the hell does that mean? It doesn't make any sense. 

Anyway, I'm guessing other people will run into this issue, so that's the solution, just remove the symlink file `~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4` and recreate it with `ln -s ~/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0 ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4`, and it will fix the issue. 

I'll go ahead and close this, but Etienne let me know your thoughts on whether you think I should report this to Valve or whether you think it's just something got frogged up the last time Steam updated and forced a rebuild of pins or something.

**Comment by AccidentalCalzone** [comment]
I suppose it's back?

```
[13/14] Installing files.
Installing ext/libav/libgstlibav.so to /home/user/git/wine-tkg-git/proton-tkg/src/gst/lib64/gstreamer-1.0
######
mingw-w64 gcc found
######
Cloning into 'liberation-fonts'...
remote: Enumerating objects: 2009, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 2009 (delta 83), reused 71 (delta 44), pack-reused 1890
Receiving objects: 100% (2009/2009), 52.92 MiB | 6.83 MiB/s, done.
Resolving deltas: 100% (1361/1361), done.
HEAD is now at 9510ebd Merge pull request #1 from vishalvijayraghavan/master
patching file src/LiberationMono-Regular.sfd
fontforge -script scripts/fontexport.pe -ttf src/LiberationMono-Regular.sfd src/LiberationMono-Bold.sfd src/LiberationMono-Italic.sfd src/LiberationMono-BoldItalic.sfd src/LiberationSans-Regular.sfd src/LiberationSans-Bold.sfd src/LiberationSans-Italic.sfd src/LiberationSans-BoldItalic.sfd src/LiberationSerif-Regular.sfd src/LiberationSerif-Bold.sfd src/LiberationSerif-Italic.sfd src/LiberationSerif-BoldItalic.sfd
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-01-30 09:56 UTC-ML-D-GDK3.
Generating ttf from src/LiberationMono-Regular.sfd
Generating ttf from src/LiberationMono-Bold.sfd
Generating ttf from src/LiberationMono-Italic.sfd
Generating ttf from src/LiberationMono-BoldItalic.sfd
Generating ttf from src/LiberationSans-Regular.sfd
Generating ttf from src/LiberationSans-Bold.sfd
Generating ttf from src/LiberationSans-Italic.sfd
Generating ttf from src/LiberationSans-BoldItalic.sfd
Generating ttf from src/LiberationSerif-Regular.sfd
Generating ttf from src/LiberationSerif-Bold.sfd
Generating ttf from src/LiberationSerif-Italic.sfd
Generating ttf from src/LiberationSerif-BoldItalic.sfd
python3 scripts/setisFixedPitch-fonttools.py src/LiberationMono-*.ttf
src/LiberationMono-BoldItalic.ttf
isFixedPitch is now:  1
src/LiberationMono-BoldItalic-fixed.ttf saved.
src/LiberationMono-Bold.ttf
isFixedPitch is now:  1
src/LiberationMono-Bold-fixed.ttf saved.
src/LiberationMono-Italic.ttf
isFixedPitch is now:  1
src/LiberationMono-Italic-fixed.ttf saved.
src/LiberationMono-Regular.ttf
isFixedPitch is now:  1
src/LiberationMono-Regular-fixed.ttf saved.
mv  src/LiberationMono-Regular-fixed.ttf  src/LiberationMono-Regular.ttf
mv  src/LiberationMono-Italic-fixed.ttf  src/LiberationMono-Italic.ttf
mv  src/LiberationMono-Bold-fixed.ttf  src/LiberationMono-Bold.ttf
mv  src/LiberationMono-BoldItalic-fixed.ttf  src/LiberationMono-BoldItalic.ttf
mkdir -p liberation-fonts-ttf-2.00.3
mv src/LiberationMono-Regular.ttf src/LiberationMono-Bold.ttf src/LiberationMono-Italic.ttf src/LiberationMono-BoldItalic.ttf src/LiberationSans-Regular.ttf src/LiberationSans-Bold.ttf src/LiberationSans-Italic.ttf src/LiberationSans-BoldItalic.ttf src/LiberationSerif-Regular.ttf src/LiberationSerif-Bold.ttf src/LiberationSerif-Italic.ttf src/LiberationSerif-BoldItalic.ttf liberation-fonts-ttf-2.00.3
'liberation-fonts-ttf-2.00.3/LiberationSans-Regular.ttf' -> '/home/user/git/wine-tkg-git/proton-tkg/src/proton_template/share/fonts/LiberationSans-Regular.ttf'
'liberation-fonts-ttf-2.00.3/LiberationSans-Bold.ttf' -> '/home/user/git/wine-tkg-git/proton-tkg/src/proton_template/share/fonts/LiberationSans-Bold.ttf'
'liberation-fonts-ttf-2.00.3/LiberationSerif-Regular.ttf' -> '/home/user/git/wine-tkg-git/proton-tkg/src/proton_template/share/fonts/LiberationSerif-Regular.ttf'
'liberation-fonts-ttf-2.00.3/LiberationMono-Regular.ttf' -> '/home/user/git/wine-tkg-git/proton-tkg/src/proton_template/share/fonts/LiberationMono-Regular.ttf'
fatal: destination path 'Proton' already exists and is not an empty directory.
HEAD is now at c9bdc51 Hotfixer: Looks like Nioh 2 and Borderlands 3 don't need this patch anymore (The Witcher 3 was fixed already). Let's drop the patch on de89ce1+
Skipping repository ./gst-plugins-base
Skipping repository ./gst-libav
Skipping repository ./gst-plugins-good
Skipping repository ./gstreamer
Skipping repository ./gst-plugins-ugly
Skipping repository ./gst-orc
Skipping repository ./gst-plugins-bad
Skipping repository ./ffmpeg
Removing ./build
Already up to date.
error: pathspec 'proton_6.3' did not match any file(s) known to git
```

**Comment by Tk-Glitch** [comment]
That one is different, and doesn't make sense to me just yet (and I can't reproduce it of course).

**Comment by Tk-Glitch** [comment]
Ok, found it. Fix incoming.
