### ISSUE TITLE
protonify_stg_syscall_emu-002.mystagingpatch can't apply succesfully

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#418]
Applying hotfix protonify_stg_syscall_emu-002.mystagingpatch
patching file patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 47.
Hunk #4 FAILED at 162.
Hunk #5 FAILED at 170.
Hunk #6 FAILED at 182.
5 out of 6 hunks FAILED -- saving rejects to file patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch.rej

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/1e2ca1a404e7bd83ef349f7c5ab5cd77af20ed07

**Comment by llde** [comment]
@Tk-Glitch isn't it better to avoid to include in the patchset configure and config.h.in changes?
The patch is still on the staging repo.
