### ISSUE TITLE
proton-tkg-staging.patch can't apply socket.c changes

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#419]
proton-tkg-staging.patch -- ( Using Steam-specific Proton-tkg patches (staging) 2/3 )
patching file dlls/ws2_32/socket.c
Hunk #1 FAILED at 3332.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ws2_32/socket.c.rej

The other parts of the patch apply correctly

**Comment by llde** [comment]
Commit that broke the patchset:

commit 5c009c17b3a212c3f5b0034c465077c0c593daae
Author: Zebediah Figura <z.figura12@gmail.com>
Date:   Tue Jun 15 23:13:32 2021 -0500

    ws2_32: Reimplement bind() and getsockname() on top of IOCTL_AFD_BIND and IOCTL_AFD_GETSOCKNAME respectively.
    
    Signed-off-by: Zebediah Figura <z.figura12@gmail.com>
    Signed-off-by: Alexandre Julliard <julliard@winehq.org>

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/e07de828e56693345e229e0013a1fe47680be8ef
