### ISSUE TITLE
Proton-tkg Cannot wget wine-gecko-2.47.2-x86_64.tar.xz on artix linux (arch)

### ISSUE THREAD

**Issue by bimokn97** [Frogging-Family/wine-tkg-git#421]
im on artix linux (arch based), i have a problem when build proton tkg
the code is on proton-tkg.sh line 768
and i try to runing manual `wget https://dl.winehq.org/wine/wine-gecko/2.47.2/wine-gecko-2.47.2-x86_64.tar.xz `
and also get error

> --2021-06-19 08:36:51--  https://dl.winehq.org/wine/wine-gecko/2.47.2/wine-gecko-2.47.2-x86_64.tar.xz
>Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
>Resolving dl.winehq.org (dl.winehq.org)... 199.232.82.217
>Connecting to dl.winehq.org (dl.winehq.org)|199.232.82.217|:443... connected.
>ERROR: The certificate of ‘dl.winehq.org’ is not trusted.

**Comment by redgloboli** [comment]
Hi,

here i have no problem with the cert.

There must be something wrong on your system.

It should work with wget --no-check-certificate https://dl.winehq.org/wine/wine-gecko/2.47.2/wine-gecko-2.47.2-x86_64.tar.xz though.

**Comment by bimokn97** [comment]
It work using `wget --no-check-certificate https://dl.winehq.org/wine/wine-gecko/2.47.2/# wine-gecko-2.47.2-x86_64.tar.xz` Thanks, i need to fix my system now
