### ISSUE TITLE
some games failing to launch

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#422]
Some of the games are failing to launch anymore with the builds from newer sources.
The games I tried which failed were Master Chief Collection and Dirt 5.
Doom Eternal launches without any issues

Log from MCC
[steam-976730.log](https://github.com/Frogging-Family/wine-tkg-git/files/6681078/steam-976730.log)

**Comment by baekhoed** [comment]
I'm having problems with Path of Exile aswell. It was working till friday, when I had to reinstall my system and rebuild proton-tkg as a consequence.

**Comment by shaumux** [comment]
Comparing both logs, seems it can't execute steam.exe
This seems to be common on both the logs
`ShellExecuteEx failed: Bad EXE format for C:\windows\system32\steam.exe.` and 
`ShellExecuteEx falhou: Formato EXE impróprio para C:\windows\system32\steam.exe.`

**Comment by shaumux** [comment]
Tested with the latest prebuilt 6.11.r3 same problem with heavy rain too

**Comment by Tk-Glitch** [comment]
Could you guys try to simply delete the `steam.exe` file in `$HOME/.steam/root/compatibilitytools.d/proton_tkg_*/files/lib/wine/i386-windows/`dir?

Before the whole path changes upstream, we used to not have that fake file in place and it worked fine. During the painful transition, we needed it at some point, but it seems to be back to its prior behavior now, working fine without it on my end. If that fixes it for you as well, I'll gladly get rid of that file.

**Comment by Tk-Glitch** [comment]
So, I have disabled that fake steam.exe with the commit above. Please try against that change and let me know how it goes.

**Comment by bear-bulloff** [comment]
> Итак, я отключил эту подделку steam.exe с фиксацией выше. Пожалуйста, попробуйте против этого изменения и дайте мне знать, как оно проходит.

Tested with proton-tkg 6.11 r4. I don't see this file on my computer. I attach the log and a screenshot.
[steam-288160.log](https://github.com/Frogging-Family/wine-tkg-git/files/6721324/steam-288160.log)
![Screenshot_115](https://user-images.githubusercontent.com/59369672/123539463-960a4180-d742-11eb-8ec1-c5b0b137fe5f.png)
![Screenshot_i386-windows_1](https://user-images.githubusercontent.com/59369672/123539473-9e627c80-d742-11eb-8b63-92d8d3968d28.png)

**Comment by shaumux** [comment]
I tried with 6.11.r5 and have some inter5esting results

So If I try to use the older prefix I get the same result across the games not working before with the same error in the logs, after I deleted the game prefix and started with a fresh prefix it works with 6.11.r5, sorry couldn't try the updated r4

If you would like some differential logs I can use your prebuilt r3 and the new r5 on some games, if that's of any help to you
I'll leave this open for now to see if @baekhoed can replicate my findings if they would like to.

**Comment by Tk-Glitch** [comment]
So it got somewhat fixed with that commit, I assume?
