### ISSUE TITLE
Just a short question about wine_wayland_driver.mypatch 

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#423]
If I launch Steam using XWayland, then Steam games are also launched on Proton on XWayland or on Proton using the native Wayland driver for Wine during Steam still using XWayland?

**Comment by Tk-Glitch** [comment]
I'd say the latter as long as the winewayland driver is part of the build.

**Comment by Kerrung** [comment]
Thank you!
