### ISSUE TITLE
New Proton-tkg Prefixes Don't Download/Sync Save Files Properly

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#428]
I noticed this with SC6 and Biomutant:
If I had a prefix from a mainline Proton version (such as 6.3), removing the prefix to generate a new one for Proton-tkg and starting the game doesn't sync the save files from the Steam cloud.

**Comment by Tk-Glitch** [comment]
Oh yeah I can see how if a game's save doesn't restore the My Documents dir. Wine has changed some paths and while we have a hack to work around it when the dir exists, if it doesn't it won't. I'll add another check so the dir exists for sure even on new prefixes.
