### ISSUE TITLE
Error applying on a patch

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#43]
Hello,

As mentioned in the title, a patch (eventfd_synchronization ntdll) don't apply.
Here is the logs [patch_error.log](https://github.com/Frogging-Family/wine-tkg-git/files/4656041/patch_error.log)

Big thanks

**Comment by xavatar** [comment]
Hello,

Same error.

Ty

**Comment by Tk-Glitch** [comment]
Current staging HEAD is frogged. I have reported the issue and pushed a temporary hotfix: https://github.com/Frogging-Family/wine-tkg-git/commit/26e7d37262f52d4d715ccc64f4aceb4b8c73a4ae

**Comment by IroAlexis** [comment]
Hello,

With the last commit, an other patch (use_clock_monotonic-2) don't apply... Not many errors so here's the log :
```
  -> Applying use_clock_monotonic.patch
patching file dlls/ntdll/time.c
Hunk #1 succeeded at 119 (offset 5 lines).
patching file server/request.c
Hunk #1 succeeded at 536 with fuzz 2 (offset 10 lines).
  -> Applying use_clock_monotonic-2.patch
patching file dlls/kernel32/time.c
Hunk #1 FAILED at 82.
1 out of 1 hunk FAILED -- saving rejects to file dlls/kernel32/time.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```

Thanks @Tk-Glitch for your work

**Comment by Tk-Glitch** [comment]
As my grandma used to say: https://github.com/Frogging-Family/wine-tkg-git/commit/fc3d5a5a2c082f3d4859bb97aa554927069328c2
I'm lying, she never said that 🐸
