### ISSUE TITLE
Starting Jedi Fallen Order in Steam Automatically Fails

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#431]
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6713548/proton-tkg.cfg.zip)

I attempted to run Star Wars Jedi Fallen Order with `Proton-tkg 6.11.r4.g0dd44a25` and found that it doesn't launch Origin (or seem to attempt to?) at all.
(Bought on Steam; not running Origin's client as a separate application)

**Comment by shaumux** [comment]
Can you add the proton log too, seems to be similar to #422

**Comment by ThisNekoGuy** [comment]
@shaumux Sorry I didn't mention: it didn't even produce a log either

**Comment by shaumux** [comment]
@ThisNekoGuy DId you start it with PROTON_LOG=1 ?

**Comment by ThisNekoGuy** [comment]
@shaumux Yes, that's why I said it didn't drop a log

**Comment by Tk-Glitch** [comment]
> @shaumux Sorry I didn't mention: it didn't even produce a log either
> 
> It produced a prefix but no log

If there's no wine log, there's a steam log. However, prefix creation is logged on my end so that's kinda weird. Unless you're using a debian based OS, you should be able to run steam from a terminal, and see logs from there. What we're after is a python error.

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch Here ye go:
[steam.log](https://github.com/Frogging-Family/wine-tkg-git/files/6720322/steam.log)

**Comment by ThisNekoGuy** [comment]
Should that still fix the problem?
I mean, if Origin doesn't install even if there is the directory

**Comment by Tk-Glitch** [comment]
`ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
This doesn't look too great. The `${LIB}` variable isn't getting expanded, which seems to be something you have added manually.

For some weird reason, I have better luck with running steam through a terminal to get launchers like Origin installed. Works fine on my end on 6.11.r4 (tested with titanfall 2).

**Comment by ThisNekoGuy** [comment]
> ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
This doesn't look too great. The ${LIB} variable isn't getting expanded, which seems to be something you have added manually.

[This is just a package that replaces GTK app borders with QT ones](https://aur.archlinux.org/packages/gtk3-nocsd-git/), so I don't know how that could affect this?

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch Can you reproduce it with this package?
