### ISSUE TITLE
Can't login "Ubisoft Connect" with wine-tkg-git and new network hotfix. (Endless login)

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#432]
wine-tkg-git commit: 891d5362ea2dd394cb9cfdd76c7e5608990c0886
[cant_login_ubisoft_connect.log](https://github.com/Frogging-Family/wine-tkg-git/files/6717146/cant_login_ubisoft_connect.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6717149/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6717151/prepare.log)

This moment lasts endless, the loading indicator in the lower right corner does not stop rotating, that is, this window does not hangs, but the login does not go further.
![Screenshot from 2021-06-25 20-16-41](https://user-images.githubusercontent.com/36989404/123446424-4f0d3680-d5f2-11eb-98f9-c10d3ed725aa.png)

**Comment by Tk-Glitch** [comment]
It also seemingly breaks origin. I'll add a note. This is somewhat expected considering it's reverting a single bit out of multiple patches. I'll try to revert the whole series, which should fix it.

**Comment by binarydepth** [comment]
off topic: cool bg

**Comment by Kerrung** [comment]
> off topic: cool bg

You can download it here if you want: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/63ae2adb-98d7-47f9-8df6-3f569ed8ba46/d979ppg-aac967f3-68f4-454e-ab2c-bb23468ea028.png/v1/fill/w_1192,h_670,q_70,strp/arch_hero_wallpaper_by_rahremix_d979ppg-pre.jpg
