### ISSUE TITLE
Dishonored Doesn't Start but Does with 6.10-GE-1

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#434]
[steam-205100.log](https://github.com/Frogging-Family/wine-tkg-git/files/6720827/steam-205100.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6713548/proton-tkg.cfg.zip)

Not sure why but the game refuses to launch with `Proton-tkg 6.11.r5.g1c9c21dc`; I tested using [the same launch options](https://github.com/FeralInteractive/gamemode) for both versions. (gamemoderun %command%)

It also threw this error window:
![image](https://user-images.githubusercontent.com/28468662/123534043-94705780-d709-11eb-9af4-48a0f1571caa.png)

**Comment by Tk-Glitch** [comment]
It seems to be an upstream regression of some sort. I just tested the game on 6.11.r9 and it works fine:
![Screenshot_20210701_145058](https://user-images.githubusercontent.com/741977/124127349-ea335f80-da7b-11eb-8960-c84cb1278ec1.png)

**Comment by Tk-Glitch** [comment]
Still working fine on 6.16. Let's close.
