### ISSUE TITLE
Diablo 2 and Diablo 2 LoD installers don't work

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [Frogging-Family/wine-tkg-git#439]
I'm probably making some basic mistake, but when I try to run these installers (downloaded from blizzard) the installers seem to think the game is already installed and when I try to play/uninstall it just seems to restart the installer. The wine version is from a few days ago.

**Comment by Tk-Glitch** [comment]
We have a few interesting regression on current master, and 6.12 is overall in a pretty bad shape for gaming. It *might* be worth trying with 6.11 or even 6.10.

**Comment by GoLD-ReaVeR** [comment]
I can wait. But do you have any idea when they are fixing these regressions?

**Comment by aufkrawall** [comment]
Every version after 6.8 has been useless to me and it had been bad before with versions after 5.20. I think we're at a point where regular git-master builds have got pointless for most cases due to regression hell. They need to fundamentally change something upstream (more automated regression tests?), otherwise I'm not hopeful.

(sorry for the rant)

**Comment by Fox2Code** [comment]
Wine is changing a lot of core components, I think they want to focus on making sure the implementation is correct, and I think they will fix the regressions before the next release of Wine (Wine 7.0), wine version that don't have a 0 in Y (for X.Y.Z) are development versions.

As last time wine stopped at Wine 5.22, and Wine 4.21 the time before that,I think it's a fair assessment that they will focus on features for now, and would focus only on fixing regression when near the Wine 7.0 release (somewhere near Wine 6.21/6.22).

**Comment by Tk-Glitch** [comment]
Just tested on 6.16, using the installer from Blizz in a fresh prefix. No issue encountered.
![Screenshot_20210828_171010](https://user-images.githubusercontent.com/741977/131222519-0fead293-c92d-4b7a-8745-6c0559e1fa68.png)

**Comment by Tk-Glitch** [comment]
Followed by LoD. Still no issue.
![Screenshot_20210828_171938](https://user-images.githubusercontent.com/741977/131222712-3eeca73b-9e84-406e-8fce-723a2558ef72.png)

I'll consider the issue fixed.
