### ISSUE TITLE
Can't seem to get vkd3d to work in Monster Hunter World

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [Frogging-Family/wine-tkg-git#44]
Well, here I am!!!

For some reason I need to uncomment this line to use d3d12 at all:
```
    #Use Wine DXGI instead of DXVK's. This is needed to make use of VKD3D when DXVK is enabled. It will prevent the use of DXVK's DXGI functions.
#    "PROTON_USE_WINE_DXGI": "1",
```

Eventhough the default compilation settings should have this enabled by default. Enabling this however gives me ERR14: Graphics API not implemented when launching Monster Hunter World.

NVAPI is disabled because it's annoying at several levels. No other settings have been modified that pertain to graphics. The vkd3d installed is the one @Tk-Glitch recommended me.

Attached log is with PROTON_USE_WINE_DXGI enabled.
[steam-582010.log](https://github.com/Frogging-Family/wine-tkg-git/files/4659371/steam-582010.log)

**Comment by Tk-Glitch** [comment]
Hi again! :)
Thanks for answering my request.

I am seeing a couple weird warnings and since I have made some changes regarding your specific issue recently I'll give you a few things to try:
 - If your build is a couple days old, set `_use_vkd3d="fork"` in your .cfg and try rebuilding against current changes. The few edits I have made since your last report might have been enough.
 - Make sure you're running the game with `VKD3D_FEATURE_LEVEL=12_0 %command%` as launch parameter.
 - If you're not currently using a self-built DXVK, it's worth a try considering your `PROTON_USE_WINE_DXGI` issue. See https://github.com/Frogging-Family/dxvk-tools#exporting-dxvk-dlls-for-proton-tkg (you'll need to set `_use_dxvk="prebuilt"` in your .cfg).
- If you're using current stable nvidia driver release, you might want to give the latest vulkan dev driver a shot. See https://github.com/Frogging-Family/nvidia-all

That about it from me right now. Time for sleep 🐸

**Comment by GoLD-ReaVeR** [comment]
```
make: Entering directory '/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/Proton/build/steam.win32'
wineg++ -m32 -c -fpermissive -Wno-attributes -O2 -g  -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/include/wine/windows/ -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/include/ -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/Proton/build/lsteamclient.win32/steamworks_sdk_142/   -o jsoncpp.o jsoncpp.cpp
wineg++ -m32 -c -fpermissive -Wno-attributes -O2 -g  -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/include/wine/windows/ -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/include/ -I/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/Proton/build/lsteamclient.win32/steamworks_sdk_142/   -o steam.o steam.cpp
wineg++ -m32 -mwindows -o steam.exe  jsoncpp.o steam.o    -L/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/lib/ -L/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/proton_dist_tmp/lib/wine/ -L/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/src/Proton/steam_helper -lsteam_api -lole32    
make: Leaving directory '/home/reaver/proton_tkg/wine-tkg-git/proton-tkg/Proton/build/steam.win32'
'Proton/build/steam.win32/steam.exe.so' -> 'proton_dist_tmp/lib/wine/steam.exe.so'
'Proton/build/steam.win32/libsteam_api.so' -> 'proton_dist_tmp/lib/libsteam_api.so'
rm: cannot remove 'dxvk/x64/d3d10.dll': No such file or directory
rm: cannot remove 'dxvk/x64/d3d10_1.dll': No such file or directory
rm: cannot remove 'dxvk/x32/d3d10.dll': No such file or directory
rm: cannot remove 'dxvk/x32/d3d10_1.dll': No such file or directory
cp: cannot stat 'dxvk/x64/*': No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
```
I got this trying to rebuild. Did I make a mistake somewhere?

**Comment by Tk-Glitch** [comment]
Something broke upstream with the last patch wave. I have pushed a hotfix for it https://github.com/Frogging-Family/wine-tkg-git/commit/297cf1626e605d72d2256de131ddaab68f6d7d1e until resolved. That *should* fix that `Failed to create process` issue.

**Comment by GoLD-ReaVeR** [comment]
Thanks for that, the d3d12 renderer is working quite well now. I've had no crashes thus far. There is a problem with the Z-prepass rendering and I don't know if that is isolated to Linux or not. The prepass seems to be giving out wrong Z values to the wrong render, causing black artifacts across the screen and perhaps some other offset issues with light sources. Besides that, the renderer seems to be really stable and fast, thanks a lot!

**Comment by Tk-Glitch** [comment]
You're welcome. I'm glad it's solved! :) Regarding your rendering, this *might* be related: https://github.com/HansKristian-Work/vkd3d/commit/b3be23c066eb51c109c47cd7af0bcf3a0a997c15

**Comment by GoLD-ReaVeR** [comment]
I did a latest on the vkd3d build and it fixed it. So it's probably that patch yeah. Again, thanks! The game has run stable for over 12 hours and shown none of the issues that the d3d11 renderer had. There's only this last glitch with the volumetric fog when it's not set to highest. But I'm now able to run the game at max details at 60fps which is a MAJOR improvement.

**Comment by Tk-Glitch** [comment]
Regarding fog, you might want to try the "adaptive" (I think that's how it's called) setting. I remember having good results with it on my Nv GPU.

**Comment by GoLD-ReaVeR** [comment]
Adaptive means it picks the setting dynamically rather than fixed. When it goes lower than highest I get artifacts at the edges of the screen. So I just need to either disable it or keep it on highest. Highest runs fine :P

**Comment by Tk-Glitch** [comment]
That was my initial assumption, but it seems to be a bit more complex than that. I had graphical anomalies with anything else than highest settings (as you said), yet using adaptive - and even when the fog res was clearly lower than highest - fixed it all. It was a very welcomed perf boost on my aging 980Ti vs max setting. That was a while ago though.

**Comment by Tk-Glitch** [comment]
Anyway, issue is solved. Closing!
