### ISSUE TITLE
Can't compile the latest wine-tkg-git with the latest Wine Staging master since a7ae28048004efe9eac8908763a7799b6a05fdb2

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#440]
Can't compile the latest wine-tkg-git with the latest Wine Staging master since https://github.com/wine-staging/wine-staging/commit/a7ae28048004efe9eac8908763a7799b6a05fdb2
Works fine with https://github.com/wine-staging/wine-staging/commit/8988a92beef14a16d8e1af895f2e8df36ce364a2
I tried with cdc194ab1d4e65979ac45c8632b687c46f4ade99 and https://github.com/wine-staging/wine-staging/commit/163f74fe61851ff57264437073805dd5e7afe2bd, but have a compilation crash. 
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6760372/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6760373/prepare.log)
![Screenshot from 2021-07-04 22-59-23](https://user-images.githubusercontent.com/36989404/124395363-2c2f0080-dd1d-11eb-8e9e-61992360936e.png)

**Comment by Fox2Code** [comment]
By doing a fast `grep -r _get_fd_type wine-tkg-git/` i found 2 lines that were interesting:
```
wine-tkg-git/wine-tkg-git/src/wine-mirror-git/dlls/ws2_32/socket.c:                _get_fd_type(fds[j].fd) == SOCK_DGRAM)
wine-tkg-git/wine-tkg-git/src/wine-mirror-git/0001-01-reverts.patch:+                _get_fd_type(fds[j].fd) == SOCK_DGRAM)
```
nothing else contained "_get_fd_type" as a whole word.

But a lot of thing were like `dir_get_fd_type`, `console_get_fd_type`, `device_file_get_fd_type`, `file_get_fd_type`, `mailslot_get_fd_type`, `mail_writer_get_fd_type`, `mailslot_device_file_get_fd_type`, `pipe_end_get_fd_type`, `named_pipe_device_file_get_fd_type`, `serial_get_fd_type`, `mapping_get_fd_type`, `sock_get_fd_type`

Changing `_get_fd_type` to `sock_get_fd_type` seems to be the right idea, but I haven't tested it yet.

**Comment by Fox2Code** [comment]
This commit https://github.com/Frogging-Family/wine-tkg-git/commit/b0b8dcc8fcfa7e4a320c81577e1b317f6a35bbe8 make wine-tkg revert this commit:
[`ws2_32: Reimplement select() on top of IOCTL_AFD_POLL.`](https://source.winehq.org/git/wine.git/commitdiff/414b31bc0bbbfe005e90a1946a649082dc303c55)

I think Zebediah Figura is slowly pushing [it's network changes](https://repo.or.cz/wine/zf.git/shortlog/refs/heads/sock4) to the main wine version.

**Comment by Fox2Code** [comment]
found the commit that nuked `_get_fd_type` from wine code base!
[`ws2_32: Use ws_protocol_info() in getsockopt(SO_LINGER).`](https://source.winehq.org/git/wine.git/commitdiff/1ccab719ee6e87b7399876d4d5b30eb889c49e32)

**Comment by openglfreak** [comment]
@Fox2Code I already sent a fixed up version to TkG, he just hasn't added it yet

**Comment by openglfreak** [comment]
@Kerrung @Fox2Code I already sent a fixed up version to TkG, he just hasn't added it yet

**Comment by Fox2Code** [comment]
I was about to make a pull request that reverted 
`ws2_32: Use ws_protocol_info() in getsockopt(SO_LINGER).` when reverting 
`ws2_32: Reimplement select() on top of IOCTL_AFD_POLL.`, I am posting what I found at the same time I test
Right now I am compiling wine to see if reverting both commits work, (Build hasn't finished yet)
