### ISSUE TITLE
wineboot.exe loop with Dotnet (Proton)

### ISSUE THREAD

**Issue by veganvelociraptor** [Frogging-Family/wine-tkg-git#449]
I've had this issue for some time with 6.11 and 6.12.

When trying to start a Proton game in Steam which has dotnet installed, wineboot.exe processes starts spawning an infinite number of times, until eventually the computer runs out of memory and crashes.

This doesn't occur with any of the Steam-included Proton versions, nor Proton-GE-6.12.

Some Examples:
Borderlands TPS
Borderlands 2
Borderlands 3
Age of Wonders: Planetfall
Yakuza 0

It's not specific to the game, but rather if dotnet is installed or not. I cannot even use protontricks --gui when dotnet is installed without triggering the spawn loop.

**Comment by Tk-Glitch** [comment]
I have never faced this. Weird.

**Comment by veganvelociraptor** [comment]
I'll try a completely cloned base build of proton-tkg-git and see if it works.

**Comment by veganvelociraptor** [comment]
Yep, it still happens. And I can reproduce it easily by install dotnet47 using Protontricks.
Any installation with dotnet47 installed: wineboot.exe spawn loop until system crashes due to out of memory
Without dotnet47: works as intended

**Comment by Tk-Glitch** [comment]
Seems to be fixed. Closing.
