### ISSUE TITLE
unable to build staging 5.6

### ISSUE THREAD

**Issue by cj360** [Frogging-Family/wine-tkg-git#45]
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4659499/last_build_config.log)
[config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4659500/config.log)

Looks like options for gcc in the pkgbuild are invalid?

**Comment by Tk-Glitch** [comment]
No, it seems to be an issue with GCC10 based MinGW. Disabling MinGW or using GCC9.3 based MinGW fixes it.

**Comment by Tk-Glitch** [comment]
Also, it's a compilation error, not a config/configure one, so your logs don't show anything useful.

**Comment by cj360** [comment]
Oops. Did build mostlyportable-gcc and mingw with 9.3 and using those wine build successfully.

**Comment by Tk-Glitch** [comment]
Great :) The GCC10 transition hasn't been the smoothest ride 🐸
