### ISSUE TITLE
Patching Error

### ISSUE THREAD

**Issue by TheTrashPenguin** [Frogging-Family/wine-tkg-git#452]
Hello There. While building wine-tkg-git on fedora 34 inside a toolbox I get this error.
 ```
 -> Hotfixing...
 -> ## Applying hotfix for wine-staging: protonify_stg_syscall_emu-003.mystagingpatch
/home/mark/Devel/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer: line 787: patch: command not found
```
Any Help?

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6801267/prepare.log)

**Comment by Tk-Glitch** [comment]
You'll need to install the `patch` package.

`dnf install patch`

**Comment by TheTrashPenguin** [comment]
Huh. It worked. Apologies for the inconveniences. Turns out patch is an actual command.

**Comment by Tk-Glitch** [comment]
It was supposedly installed with `_nomakepkg_dep_resolution_distro="fedora"` at some point, as a dependency for another package. I suppose the dependency was dropped and I should add the package to the dependency list.
