### ISSUE TITLE
Couldn't install libavcodec58, libswresample3, etc. Packages.

### ISSUE THREAD

**Issue by regedittor** [Frogging-Family/wine-tkg-git#453]
When `non-makepkg-build.sh` tries to install 64 bits dependencies for Debian-based distros, this happens.
```
E: Unable to locate package libavcodec58
E: Unable to locate package libswresample3
E: Unable to locate package libavutil56
E: Unable to locate package libvkd3d-dev
E: Unable to locate package glslang-dev
E: Unable to locate package glslang-tools
```

OS: Elementary OS 5.1.7 Hera (Ubuntu 18.04.4 LTS Based)

**Comment by Tk-Glitch** [comment]
18.04 is 3+ years old at this point, the result is pretty much expected.
You *might* be able to get things to build by removing those unmet dependencies from the deps list (https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-scripts/deps), albeit with missing functionality.

**Comment by regedittor** [comment]
> 18.04 is 3+ years old at this point, the result is pretty much expected.
> You _might_ be able to get things to build by removing those unmet dependencies from the deps list (https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-scripts/deps), albeit with missing functionality.

Thank you, I had another issue apart from this one but when I removed those dependencies it also fixed.

**Comment by Tk-Glitch** [comment]
> > 18.04 is 3+ years old at this point, the result is pretty much expected.
> > You _might_ be able to get things to build by removing those unmet dependencies from the deps list (https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-scripts/deps), albeit with missing functionality.
> 
> Thank you, I had another issue apart from this one but when I removed those dependencies it also fixed.

Great news :) Have fun!
