### ISSUE TITLE
Can't compile wine-tkg-git

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#460]
Arch Linux
6baea97044ff9957100d10140f3fd7b7c374b1b6
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6870375/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6870376/prepare.log)
![Screenshot from 2021-07-23 22-38-49](https://user-images.githubusercontent.com/36989404/126820899-d1190ca5-5a2e-42c5-9c71-56332f253aa2.png)

**Comment by Tk-Glitch** [comment]
The latest winewayland driver patchset isn't compatible with current wine HEAD. You'll have to use an older tree if you want to use that patchset.

Not my bug, closing.

**Comment by Kerrung** [comment]
https://gitlab.collabora.com/alf/wine/-/commits/wayland
There is an updated winewayland version here, but I haven't checked if it compiles with current wine HEAD.

**Comment by Tk-Glitch** [comment]
I have updated the community patch with the latest current version, but it doesn't compile with current HEAD
