### ISSUE TITLE
Rockstar Games Launcher fails to sync cloud saves

### ISSUE THREAD

**Issue by CodingKoopa** [Frogging-Family/wine-tkg-git#461]
I can't get RGL to successfully update my game save data.

With the latest version of proton-tkg built with makepkg (Git commit 6baea97044ff9957100d10140f3fd7b7c374b1b6, package version `6.13.r3.gb57bf86e-1`), I am able to install the game dependencies in a new prefix just fine, and, the first time the game launches, the save data is *downloaded* just fine, without issue. Single player gameplay appears to function normally.

Issues occur for me in the following cases, though:
- Launching the game any time after the first prompts for a save data conflict - this has always been an issue for me. What's different about this is that **I'm unable to resolve the conflict** - regardless of whether I select the local data or cloud data to prefer.
- Exiting the game has the same issue.
- While playing GTA Online, the game is unable to save at all.

The RGS launcher says "Error syncing Cloud saves." Video demonstration:

https://user-images.githubusercontent.com/13039555/126855986-baf3a1a8-bf71-4d86-a048-45cbae28e3b7.mp4

Log file:

[steam-271590.log](https://github.com/Frogging-Family/wine-tkg-git/files/6871844/steam-271590.log)

There are a couple of different messages used in GTA Online.
- Immediately after completing a mission (this can happen on Windows): ![image](https://user-images.githubusercontent.com/13039555/126847197-d50c8df5-4b64-4c30-b346-97b0c762594c.png)
- In the overworld after this failure (this may happen on Windows, but doesn't persist for so long):
![image](https://user-images.githubusercontent.com/13039555/126847230-abbfad60-e622-4804-b5a2-e26f3da513ee.png) ![image](https://user-images.githubusercontent.com/13039555/126847232-d0708ba2-c657-477d-8ba5-5386892cf261.png)

---

Configurations I've tested:
- proton-tkg makepkg with [this](https://gitlab.com/CodingKoopa/comet-observatory/-/blob/master/config/tkg/proton-tkg.cfg) configuration, with the following variants of [this](https://github.com/Frogging-Family/wine-tkg-git/blob/6baea97044ff9957100d10140f3fd7b7c374b1b6/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer#L595-L617) hotfix:
  - Upstream code
  - openglfreak's patch
- [Proton 6.3-5](https://github.com/ValveSoftware/Proton/releases/tag/proton-6.3-5) I wasn't able to create a working prefix with, as it hung on DXSETUP.exe for over an hour.

**Comment by benjamin-poncet** [comment]
I have not done as much troubleshooting yet but I can confirm this is an issue I also experience.

**Comment by Tk-Glitch** [comment]
This is a known upstream issue right now: https://bugs.winehq.org/show_bug.cgi?id=51439

**Comment by Tk-Glitch** [comment]
https://source.winehq.org/patches/data/210168

**Comment by satyrnsstuff** [comment]
The patch got merged upstream, now we wait for 6.14...

**Comment by Tk-Glitch** [comment]
wine-tkg always targets master by default, so yeah, fixed. Closing!

**Comment by CodingKoopa** [comment]
Works for me! Cheers.
