### ISSUE TITLE
mkgpkg build error with preperation caused by protonify_stg_syscall_emu.mystagingpatch

### ISSUE THREAD

**Issue by silverhikari** [Frogging-Family/wine-tkg-git#465]
when building wine-tkg-git using pkgbuild it will error out caused by the protonify_stg_syscall_emu.mystagingpatch hotfix
this is the error log
https://paste.ee/p/Wzo5y

**Comment by Tk-Glitch** [comment]
Your tree is deprecated. It's at least a month and a half old as we're now shipping multiple versions of that patchset that were rebased against upstream.
https://github.com/Frogging-Family/wine-tkg-git/commit/c28c65c402813411be3c053cb35a9e17dc468811

Run `git pull` in your wine-tkg-git clone if you didn't make local changes, or reclone a fresh copy of the repo.

See https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git#download-the-source-

**Comment by Tk-Glitch** [comment]
Closing
