### ISSUE TITLE
Danganronpa Another Episode: Ultra Despair Girls hangs after launcher; Works fine with Proton 6.3

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#467]
Hey, all! I just wanted to mention that Danganronpa Another Episode: Ultra Despair Girls hangs after launching from the launcher with Proton-tkg 6.13.r5.g9da0fe04. The program seems to work fine with Proton 6.3. Let me know if you need any other information. Thanks!

Proton-tkg 6.14 log available here:
[steam-555950.log](https://github.com/Frogging-Family/wine-tkg-git/files/6927130/steam-555950.log)

**Comment by nutta-git** [comment]
Can you provide a Proton Log

Set Launch Options setting in the game's Properties dialog in the Steam client: `PROTON_LOG=1 %command%`

**Comment by CartoonFan** [comment]
Can do! I've updated the main post with the Proton log.

**Comment by CartoonFan** [comment]
Just tested it with under 6.19.GE.2-1 and the game seems to work.
[steam-555950.log](https://github.com/Frogging-Family/wine-tkg-git/files/7376620/steam-555950.log)

**Comment by CartoonFan** [comment]
Seems to be working with proton-tkg now as of 3110c8bba2a9e7788349a135b3c2dba19d1ceb77! Great work, everyone!

Closing #467.
