### ISSUE TITLE
[Suggestion] Build and link statically with libvkd3d

### ISSUE THREAD

**Issue by drizzt** [Frogging-Family/wine-tkg-git#47]
Hi,
since it's difficult (on other distros?) to have forked libvkd3d installed (and if you do that system wine can stop working) I suggest to build a selectable version of libvkd3d and link it statically with wine (or to install it, as shared library, in _prefix)

**Comment by Tk-Glitch** [comment]
Hello drizzt,

Yes, that's a planned feature (not limited to vkd3d also). I've been slow at this due to time constraints and well, life 🐸 But it'll be available eventually!

**Comment by Tk-Glitch** [comment]
Since vkd3d-proton can now be built as standalone both with proton-tkg and dxvk-tools, I'm closing this. Patched up gstreamer or/and FAudio would come in handy going forward.
