### ISSUE TITLE
makepkg fails at prepare when building from latest git

### ISSUE THREAD

**Issue by silverhikari** [Frogging-Family/wine-tkg-git#470]
i have gotten the latest git pull, i am using the makepkg build as i am on manjaro. i do not have ccache enabled, i have run makepkg with the -si options. i have no clue why it will not build?
complete build log
https://paste.ee/p/dlLAs

**Comment by Tk-Glitch** [comment]
Upstream changes from least night have broken one of our patches and I'll need to rebase to make it work again. It'll be done asap.
