### ISSUE TITLE
[Wine-tkg Build] Witcher 3 (GOG Version) Recieves No Controller Inputs

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#475]
[wine-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6934745/wine-tkg.cfg.zip)

For some reason, the GOG version of the Witcher 3 didn't receive any controller inputs with the `wine-tkg-staging-fsync-git-6.14.r2.g00985bf3` version I compiled (I was running the game in Lutris) both with and without the SDL controller patch enabled (Not sure if this is related to https://github.com/Frogging-Family/wine-tkg-git/issues/424 )

**Comment by Tk-Glitch** [comment]
I only have the steam version, which works fine with all my controllers. That being said, there's been quite a few changes regarding controller support upstream, so this might be worth trying again with 6.16.

**Comment by IroAlexis** [comment]
I have GOG version and it works perfectly in my side with 6.16 :frog:

**Comment by ThisNekoGuy** [comment]
I'll try it again with 6.16 when I have a moment soon; thanks

**Comment by ThisNekoGuy** [comment]
Meant to get bavk about this way sooner but it was fixed with 6.16; thanks
