### ISSUE TITLE
Failing to build on pop os 21.04

### ISSUE THREAD

**Issue by hellisabove** [Frogging-Family/wine-tkg-git#476]
When trying to build, it stops saying I have broken packages. "Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev:i386 : Depends: linux-libc-dev:i386 but it is not going to be installed". If I try to install linux-libc-dev:i386 manually, it requires to uninstall build-devel and pop-shell

**Comment by Tk-Glitch** [comment]
Pop os is not able to build wine properly. See https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies

No way around it except building in a VM or container, unless you're up for switching to a different distro.
