### ISSUE TITLE
Does it work with an Fsync-1 clear kernel?

### ISSUE THREAD

**Issue by artivision** [Frogging-Family/wine-tkg-git#477]
Does it work with an Fsync-1 clear kernel? Or Fsync-1 doesn't work?

**Comment by ErdeFB** [comment]
It probably does. As long as you take care all of the other things you need like setting the systemd limits. If you want to make sure a kernel supports fsync, you can just build linux-tkg: https://github.com/Frogging-Family/linux-tkg

**Comment by Tk-Glitch** [comment]
It does.
