### ISSUE TITLE
please make a release of wine 6.14+

### ISSUE THREAD

**Issue by arjunkathuria** [Frogging-Family/wine-tkg-git#479]
Hi, Thanks for your awesome work.

some of us have potato computers that die when compiling wine-staging from source. could you please do a new binary release if it's not too much trouble? 

Thanks again.

**Comment by Tk-Glitch** [comment]
https://github.com/Frogging-Family/wine-tkg-git/releases/tag/6.14.r6.g1bc4da9d

**Comment by arjunkathuria** [comment]
dang. that was fast.

thanks @Tk-Glitch , you're the best!
