### ISSUE TITLE
Consider to disable _update_winevulkan by default

### ISSUE THREAD

**Issue by drizzt** [Frogging-Family/wine-tkg-git#48]
I found that ` _update_winevulkan` + DXVK breaks Battle.Net (with or without the battlenet revert applied).
It gives a BattleNet is crashed error after login.
I tried with Lutris DXVK 1.6.1 and with yours DXVK (dxvk-tools) and I've got the same error.

I tried last wine-staging commit AND 5.8.0 tag, same result.

I don't use vkd3d since, on Fedora, it's much slower than DXVK and to update to the fork branch requires a big work since it requires a newer version of libvulkan and probably other dependencies.

This is my complete `wine-tkg.cfg`:
```
_use_vkd3d="false"
_dxvk_dxgi="false"
_warframelauncher_fix="false"
_childwindow_fix="false"
_update_winevulkan="true"
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_protonify="true"
_community_patches=""
_NOINITIALPROMPT="true"
```

**Comment by drizzt** [comment]
![image](https://user-images.githubusercontent.com/211316/82580139-0ed9ba00-9b8f-11ea-9ee8-53bf904599ae.png)

**Comment by Tk-Glitch** [comment]
Interesting.. Thanks for reporting!

**Comment by Sporif** [comment]
It seems to be one of the alloca related patches that are the cause, these work fine:

```
Subject: [PATCH] winevulkan: use swapchain format for fshack image + view
Subject: [PATCH] winevulkan: Implement VK_KHR_get_surface_capabilities2 and
 fake support for VK_EXT_full_screen_exclusive
Subject: [PATCH] make exts optional
Subject: [PATCH] winevulkan: Nuke unsupported pNexts from vkCreateSwapchainKHR
```

**Comment by Tk-Glitch** [comment]
Woah, thanks for bisecting! I was planning to do that once the 5.9 release noise was behind. That'll make it much faster, and might give me a reason to annoy Josh 🐸.

**Comment by drizzt** [comment]
> It seems to be one of the alloca related patches that are the cause, these work fine:
> 
> ```
> Subject: [PATCH] winevulkan: use swapchain format for fshack image + view
> Subject: [PATCH] winevulkan: Implement VK_KHR_get_surface_capabilities2 and
>  fake support for VK_EXT_full_screen_exclusive
> Subject: [PATCH] make exts optional
> Subject: [PATCH] winevulkan: Nuke unsupported pNexts from vkCreateSwapchainKHR
> ```

After a bisect I found that the problem is in "[PATCH] winevulkan: Use alloca for struct conversions". If I enable this subpatch it fails so I splitted the patch and I'm only applying:

    Subject: [PATCH] winevulkan: Eliminate shared conversion structs
    Subject: [PATCH] winevulkan: Regenerate thunks
    Subject: [PATCH] winevulkan: use swapchain format for fshack image + view
    Subject: [PATCH] winevulkan: Implement VK_KHR_get_surface_capabilities2 and
    Subject: [PATCH] make exts optional
    Subject: [PATCH] winevulkan: Nuke unsupported pNexts from vkCreateSwapchainKHR 

And it works
