### ISSUE TITLE
Roblox does not work using wine-tkg or wine-staging

### ISSUE THREAD

**Issue by karimrir1** [Frogging-Family/wine-tkg-git#480]
Today, due to a roblox update, some users of the grapejuice wrapper have reported that they have a FFlag called "FFlagDetectWine", after a couple of hours of the roblox update being pushed, many MANY, grapejuice users have reported that roblox just instantly crashes on launch using wine-tkg or wine-staging, regardless of the wine version, wheter it's 6.11 or 6.14 or 6.9

There are no current logs that can be found.

My OS and renderer: Direct3D11 using DXVK, Artix Linux 64 bit.

Screenshot of roblox crashing
[https://imgur.com/a/S7sZFyi](url)

**Comment by hippozz** [comment]
"FFlagDetectWine" has nothing to do with the recent crashes at all, and is rather used for metrics and filtering out Wine users from the crash report system; it's not even enabled at the moment.
While the coincidence may be funky, it appears to have started happening after a Roblox update.

**Comment by karimrir1** [comment]
My bad, thought it was related in some way.

**Comment by guihkx** [comment]
Fixed by https://github.com/wine-staging/wine-staging/commit/b09fe464be719947bf584cc569294a49089c8be3

**Comment by karimrir1** [comment]
Fixed by wine-staging/wine-staging@b09fe46
