### ISSUE TITLE
PROTON_BYPASS_SHADERCACHE_PATH set by default in release?

### ISSUE THREAD

**Issue by Kiwii** [Frogging-Family/wine-tkg-git#481]
The latest proton-tkg release (6.14.r6) seems to have PROTON_BYPASS_SHADERCACHE_PATH set to "/run/media/tk/T5/mesa_cache" in user_settings.py (and it's not commented out). 

Is this by design? And is it an issue if it's set to a non-existing path? 

Asking as I do have pre-caching disabled in Steam.

**Comment by Tk-Glitch** [comment]
Little oversight on my end it seems. My release script didn't overwrite my own config for that value. Commenting the line out will restore the default behavior. I'm not sure how non-existing paths are handled. Maybe defaulting to `$HOME/.cache` I guess?

**Comment by Tk-Glitch** [comment]
I have corrected my release script and the 6.16 based release will use default path by default again. Closing.
