### ISSUE TITLE
Latest commit seems to break first-time setups for games, causing them to crash on launch.

### ISSUE THREAD

**Issue by cyrv6737** [Frogging-Family/wine-tkg-git#488]
Building proton_tkg_6.15.r3.gdc0aa10a with fe3bec099023e0769465bd5652ba3dbb06cfb93f causes the Steam client to not run the first-time setup, which then causes the games to instantly crash on launch. I've tried deleting the prefix and generating a new one, which did not work.

Reverting to 8bc9fd5de3084418b7311d8896aabf4c809c6b72 fixes the issue entirely and first-time setups run as expected. Official proton 6.3-6rc also seems to be generating prefixes/first-time setups fine.

Let me know if I can provide any more relevant information.

**Comment by CartoonFan** [comment]
Hello, @cyrv6737! I also encountered an issue with prefix creation; is your issue similar to mine (TypeError: try_copy() got an unexpected keyword argument 'optional', more details in #487)? Thanks!

**Comment by cyrv6737** [comment]
b23bccdae70da86629ea899d48e78f2f2cdabb48 seems to have fixed it, thanks! Closing
