### ISSUE TITLE
[wine-tkg] Mouse behaving weirdly in Gothic 2

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Frogging-Family/wine-tkg-git#49]
Since 2020-05-21 (after wine-tkg rebuild) mouse movements are reversed most of the time in Gothic 2. Moving mouse to one side for long time (feels like multiple screens) bugs it out in a way that any movement causes character movement in previous direction (the one done for long time). Moving cursor in other direction for long time then reverses it, but with some jumpiness.
When movement is exact reverse of what it should be, both vertical an horizontal axes are inverted.
This weirdness was probably present for quite some time (at least since 2020-05-20) when in-game resolution was lower than native. At that time I assumed it's FS hack bug and just switched to native resolution and problem was gone, but since 2020-05-21, same thing happens all the time even without FS hack and with native screen resolution.

config:
```
_NOINITIALPROMPT="true"
_hotfixes_no_confirm="true"
_user_patches_no_confirm="true"

_MIME_NOPE="true"
_FOAS_NOPE="true"

# also tested without these 3
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_protonify="true"
```

Older wine (https://github.com/wine-mirror/wine/commit/55ba3648379d90642f174e74809b84130d6d1ddc - before X11 fixes) behaves the same way.

**Comment by neVERberleRfellerER** [comment]
This is now happening with vanilla wine 5.9. So closing and will report upstream unless I find another report.

**Comment by Tk-Glitch** [comment]
Yeah it's an upstream regression for sure. Possibly introduced by `https://source.winehq.org/git/wine.git/commitdiff/d9855df17f905da97b4bd92227427c4f899babf1`.
You can try grabbing https://github.com/wine-mirror/wine/commit/d9855df17f905da97b4bd92227427c4f899babf1.patch then dropping it into your wine-tkg-userpatches dir with a `.myrevert` file extension, then try a rebuild.

It'll hopefully be the culprit, and reverting it will be enough of a fix (for that game, at least).

**Comment by neVERberleRfellerER** [comment]
Thanks, but bisection shows the problem was something seemingly unrelated to input handling:
https://github.com/wine-mirror/wine/commit/8ca9e0b1abba7640e288df7b55b60903bc52fc9d
https://bugs.winehq.org/show_bug.cgi?id=49228
Maybe it breaks mouse velocity calculations in some way, I don't know.

**Comment by Tk-Glitch** [comment]
Yeah I just saw the issue. That looks annoying at first glance 🐸
