### ISSUE TITLE
Wine commit 10ca57f4f56f86b433686afbdbe140ba54b239bb breaks fsync-unix-staging.patch

### ISSUE THREAD

**Issue by e666666** [Frogging-Family/wine-tkg-git#492]
A commit on vanilla Wine few days ago changed server/device.c in a way that patch hunk no longer succeeds. This asks for either of the two actions:
1. Revert the commit before patching as a workaround
2. Rebase the patch against latest Wine commit.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/80e118df29b48032f2f11c917fb5298cee883460
