### ISSUE TITLE
Wine-tkg Staging (6.16) Won't Compile

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#493]
[logs.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7071529/logs.zip)
[wine-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7071531/wine-tkg.cfg.zip)

I tried compiling Wine-tkg 6.16 (Staging) and compilation stops every time when I reach this point in compilation:
```
ccache x86_64-w64-mingw32-gcc -c -o dlls/webservices/error.cross.o ../wine-mirror-git/dlls/webservices/error.c -Idlls/webservices \
  -I../wine-mirror-git/dlls/webservices -Iinclude -I../wine-mirror-git/include \
  -I../wine-mirror-git/include/msvcrt -D__WINESRC__ -D_UCRT -DWINE_CROSS_PE -Wall \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Winit-self \
  -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value \
  -Wno-format -Wformat-overflow -Wnonnull -mcx16 -pipe -O3 -ftree-vectorize -march=native -mtune=native -minline-all-stringops
../wine-mirror-git/dlls/vbscript/parser.y: warning: 8 shift/reduce conflicts [
```

**Comment by Tk-Glitch** [comment]
Using kde plasma?

**Comment by ptr1337** [comment]
Mhm, your compile flags are really much also weird. 

_GCC_FLAGS="-pipe -O3 -ftree-vectorize -march=native -mtune=native -minline-all-stringops"


try to compile with:

_GCC_FLAGS=" -march=native -pipe -O2 -ftree-vectorize" (O3 already have -ftree-vectorize enabled if used) 

And higher compile flags, does not more performance for your compiled stuff.

**Comment by ThisNekoGuy** [comment]
> Using kde plasma?

@Tk-Glitch Yeah

**Comment by Tk-Glitch** [comment]
> > Using kde plasma?
> 
> @Tk-Glitch Yeah

That's actually a bug with konsole. Using konsole-git from AUR fixes the issue.

**Comment by ThisNekoGuy** [comment]
Seems to work fine with Yakuake too; thanks :ok_hand:
