### ISSUE TITLE
Error In Patching

### ISSUE THREAD

**Issue by MrSwedish** [Frogging-Family/wine-tkg-git#494]
```
==> WARNING: Hotfix: Protonify staging syscall emu
  -> Hotfixing...
  -> ## Applying hotfix for wine-staging: protonify_stg_syscall_emu-005.mystagingpatch
==> ERROR: Patch application has failed. The error was logged to /home/me/dev/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
  ```
  
  Here is my [customization.cfg](https://gist.github.com/MrSwedish/dc8ad2cdf386d52fd7f57877c3cca119) and my [prepare.log](https://gist.github.com/MrSwedish/15ac0bb0e45cbad27f8befef2fd171bc).
  I have no userpatches in the userpatch directory

**Comment by Tk-Glitch** [comment]
Was fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/4a132d045731643dcd6bdbe8e6e92804db61c5a6 btw

**Comment by MrSwedish** [comment]
I updated before.. it was some minutes ago tho
