### ISSUE TITLE
Tokyo Xanadu eX+ crashes when trying to play videos with builtin quartz

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#5]
While searching for a solution to https://github.com/Tk-Glitch/PKGBUILDS/issues/503, I found that using builtin quartz causes a crash when the game tries to play videos. I tried with the mainline and staging presets and the same thing happens. It's likely an upstream bug, but I wanted to get an opinion here first.

P.S. If it goes to WineHQ, can I just call mainline "Wine git" or "Wine 5.5" instead of "wine-5.5.r0.g123c0543e0 ( TkG Plain )" or something similar? I'd like to not mention the TkG thing over there unless it's absolutely required. Thanks!

**Comment by Tk-Glitch** [comment]
Definitely looks like an upstream issue indeed. You can most definitely call it mainline on winehq because it's exactly what it is unless you've used your own userpatches with it :)

**Comment by CartoonFan** [comment]
Awesome, thanks for the response. Now to navigate Wine's Bugzilla, I guess.

**Comment by CartoonFan** [comment]
This seems to be fixed for me as of mainline Wine 5.7.

Closing #5 for now.

**Comment by Tk-Glitch** [comment]
🎉

**Comment by CartoonFan** [comment]
I'm happy, too, although there's still more wine bugs: The game hangs at certain spots and has significantly lower volume with builtin xaudio2_7 (fixed by winetricks xact), and occasionally has a black screen, black background, or missing menu items on the menu (fixed with dxvk). Additionally, I recently experienced an issue with stuttering playback when using native xact, which, aside from being weird, effectively prevents me from fixing the hanging problems :confused:.  The issues are also present with the mainline preset. I don't want to flood the issue tracker with bugs, though, and I'm not sure if the xaudio bugs belong here, on WineHQ, or the FAudio git. Do you want me to post the other bugs here, and if so, do you want one bug per issue or some other grouping method?

Thanks again, @Tk-Glitch!

**Comment by CartoonFan** [comment]
Hey, @Tk-Glitch! Things have improved somewhat since I closed this bug. However, the game now crashes with builtin qasf in the same way as my original comment. Should I make a new bug or reopen this issue? Like before, the issue is also present in mainline Wine, if that helps. Thanks as always!
