### ISSUE TITLE
MHW requring updated graphics driver

### ISSUE THREAD

**Issue by nutta-git** [Frogging-Family/wine-tkg-git#50]
When using `proton-tkg-5.9.r0.g7b5a0e5a` MHW will launch and a notification will be issued 
- "Your NVIDIA graphics driver is out of date. " 

The game is still playable, but the notification won't close. Also I used AMD graphics.  

[steam-582010.log](https://github.com/Frogging-Family/wine-tkg-git/files/4671832/steam-582010.log)
![mhw](https://user-images.githubusercontent.com/59726608/82731973-4142fe80-9cd8-11ea-863d-4e2818fac4e7.png)

**Comment by Valmar33** [comment]
Have you disabled nvapi, for a start?

**Comment by nutta-git** [comment]
Disabling nvapi form user_settings.py has fixed this issue. 
Thank you @Valmar33!

**Comment by Tk-Glitch** [comment]
Nvapi is enabled in the log:
```
23739.701:00b8:00c8:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\nvapi64.dll" at 0x7fb7a64b0000: builtin
```

You can try disabling it your `user_settings.py` by uncommenting the `"PROTON_NVAPI_DISABLE": "1",` line:
```
    #Disable nvapi and nvapi64
     "PROTON_NVAPI_DISABLE": "1",
```
Weird that it believes you have a Nvidia GPU though. I'll try to reproduce it on my end, but I can attest there's no popup with nvapi disabled, at least.

**Comment by Tk-Glitch** [comment]
Lol, I only now see nutta-git's answer and the fact the issue is closed. How weird. Glad it's fixed! :)

**Comment by nutta-git** [comment]
@Tk-Glitch I will reopen this issue back up for further investigation:

 "Weird that it believes you have a Nvidia GPU though. I'll try to reproduce it on my end,"

**Comment by Tk-Glitch** [comment]
I could reproduce the issue on my end, by the way. It might be a case of weird assumptions on Capcom's side (wouldn't be the first time). Maybe something like "let's try amd_ags, and if it doesn't find an AMD GPU (it won't with RADV), we consider it's a Nvidia one and fallback to nvapi".

**Comment by nutta-git** [comment]
Thank you @Tk-Glitch for the explanation
