### ISSUE TITLE
Xone controller stopped working

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#502]
As in title
is working with 6.16.r2.g4b48df50 but doesn't work with 6.16.r3.gf3b03ce5
sdl patch disabled in both the builds

**Comment by Tk-Glitch** [comment]
There has been quite a few changes upstream touching inputs in the last patchwave. I'll forward this to the author.

**Comment by rbernon** [comment]
Thanks, it would be nice if you could provide `WINEDEBUG=+xinput,+winexinput,+plugplay` logs in both cases, also if you could report this to https://bugs.winehq.org

**Comment by rbernon** [comment]
Note I'm not completely confident about it but maybe it's just a matter of re-initializing the prefix, so maybe confirm with a fresh one.

**Comment by shaumux** [comment]
Tested as @rbernon suggested, new prefix seems to have fixed the problem, but something weird happened, i had to recreate the prefix twice, the first time i tried to do it it would just hand at launch with a blanks screen deleted the prefix again and everything seems to be working fine

**Comment by shaumux** [comment]
I did tests with a few more games with the exact same behaviour, If I try to update the prefix from any  previous version the controllers don't work on 6.16.r3.gf3b03ce5 but going back to 6.16.r2.g4b48df50 they work.
Deleting a prefix and letting 6.16.r3.gf3b03ce5 create a fresh prefix makes them work.

@rbernon Would the different logs be of any use or help given these findings?

**Comment by rbernon** [comment]
I think I see where the problem comes from, thanks, I don't think logs are going to be useful for now. Also I don't think it's a big issue but also that there's nothing to do about it for these versions at least. I'll see if there's a way to make future prefix upgrade fix the problem, when done from an old version, as long as the intermediate version is skipped.

**Comment by shaumux** [comment]
It's not a big issue, and yes not much to do with incompatible upgrades.
I didn't understand what you mean by intermediate version is skipped, I tried 6.15->6.16.r3 and 6.16.r2->6.16.r3 with the same results.
I'll close the issue since not much can be done for now
