### ISSUE TITLE
Proton-tkg Fails to Build With 32-bit GStreamer Enabled

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#503]
Proton-tkg is currently failing to build if `_lib32_gstreamer` is set to `="true"`. I've tried with a fresh git-clone and everything. If `_build_gstreamer` is set to true alone, then the build succeeds, but as soon as `_lib32_gstreamer="true"`, the build will fail. 

https://gist.github.com/gardotd426/fa89e6e3527c20124c7f2dc15267411c

**Comment by Tk-Glitch** [comment]
You're missing `lib32-libbs2b` (available on AUR)

**Comment by CartoonFan** [comment]
I ran into a build error as well, but in my case, it was with libltc.so, which doesn't appear to have a 32-bit package☹️
https://gist.github.com/CartoonFan/863c828875f49eb1aaa0c5a422cd3447

**Comment by Tk-Glitch** [comment]
What do you need libltc for? Getting rid of it (the x86_64 package) should work fine. I'll check if I can disable support for it altogether.

**Comment by CartoonFan** [comment]
OK.I don't think I'm using it, so I'll give your suggestion a try. Thanks!

**Comment by gardotd426** [comment]
@Tk-Glitch hey so I installed lib32-libbs2b and tried again, and it's failing again, only now it's failing with gsttimecode being the only error. Like before, disabling `_lib32_gstreamer` causes the build to succeed, it only fails with `_lib32_gstreamer="true"`. I installed `lib32-gst-plugins-bad` from the AUR, because that provides `/usr/lib32/gstreamer-1.0/libgsttimecode.so` but the build still fails with the same error. 

Here's the error, and it's the only line beginning with `FAILED:`

```
[423/744] Linking target gst/timecode/libgsttimecode.so
FAILED: gst/timecode/libgsttimecode.so
gcc -m32  -o gst/timecode/libgsttimecode.so gst/timecode/libgsttimecode.so.p/plugin.c.o gst/timecode/libgsttimecode.so.p/gsttimecodestamper.c.o gst/timecode/libgsttimecode.so.p/gstavwait.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libgsttimecode.so -Wl,-Bsymbolic-functions /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib/libgstbase-1.0.so /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib/libgstreamer-1.0.so /usr/lib32/libgobject-2.0.so /usr/lib32/libglib-2.0.so /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib/libgstaudio-1.0.so /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib/libgsttag-1.0.so /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib/libgstvideo-1.0.so /usr/lib/libltc.so -lm -Wl,--end-group
/usr/bin/ld: /usr/lib/libltc.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

**Comment by gardotd426** [comment]
Ugh nevermind I see now that the error was with libltc so I removed the 64-bit package like you mentioned since there's no 32-bit package and sure enough the build succeeded. I'll go ahead and close now.
