### ISSUE TITLE
Patch conflict on RE8 hotfix and protonify-staging syscall

### ISSUE THREAD

**Issue by korewaChino** [Frogging-Family/wine-tkg-git#504]
I'm getting patch revert conflicts when trying to build wine-staging between the syscall patch and the RE8 patch.

**Comment by Tk-Glitch** [comment]
I'm on it. Yesterday's patchwave has broken multiple other patchsets :frog:

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/e32fad67c2f70a6f047ae4bda19ffb6418b13212
