### ISSUE TITLE
Applying GLSL-toggle.patch fails

### ISSUE THREAD

**Issue by 123-123-nil** [Frogging-Family/wine-tkg-git#505]
GLSL toggle patch fails. Found the below in the prepare.log :)
```
GLSL-toggle.patch -- ( Applied GLSL toggle patch )
patching file programs/winecfg/resource.h
Hunk #1 succeeded at 218 (offset -1 lines).
patching file programs/winecfg/staging.c
Hunk #1 succeeded at 118 with fuzz 1 (offset -15 lines).
Hunk #2 FAILED at 157.
Hunk #3 succeeded at 187 (offset -22 lines).
1 out of 3 hunks FAILED -- saving rejects to file programs/winecfg/staging.c.rej
patching file programs/winecfg/winecfg.rc
Hunk #1 succeeded at 322 (offset -2 lines).
```

**Comment by Tk-Glitch** [comment]
Are you sure you're using the latest tree? This should been resolved with https://github.com/Frogging-Family/wine-tkg-git/commit/e32fad67c2f70a6f047ae4bda19ffb6418b13212

**Comment by 123-123-nil** [comment]
I ran TkgThingy script and selected option 3 before running makepkg. Doing so must put me on the latest tree, right?

**Comment by Tk-Glitch** [comment]
My bad, I had another patch in mind actually. Totally forgot that GLSL patch existed :frog:

Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/9ef7303447bd7b4d6300faf4a0aae15f43e721a5
