### ISSUE TITLE
Cursos locked inside the game(Diablo 3).

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#516]
I play the game on fullscreen inside the Wine virtual desktop to force 800x600 resolution. This game has an option to lock the cursor, but I keep it disabled. This doesn't happen using Arch's repository wine. 

My [customization.cfg](https://pastebin.com/uVxehes0).

Is there any way to avoid that?

![Screenshot_20210921_153315](https://user-images.githubusercontent.com/1186150/134228400-fd3b66c3-34ea-45d1-b0da-7b42fe1a3762.png)

**Comment by rizzini** [comment]
Awesome. Thanks for the tip.

Since I have an Intel 4th gen., I'll close this. lol I'll reopen if I need to.

**Comment by Tk-Glitch** [comment]
Alternatively, if you have the option to use borderless instead of fullscreen, that might work

**Comment by Kiwii** [comment]
Isn't that just this checkbox in winecfg? I believe Proton has it checked by default while stock Wine has it unchecked.

![image](https://user-images.githubusercontent.com/1112890/134735709-04c2928e-30f0-4462-b638-7e777219bbf6.png)
