### ISSUE TITLE
Git errors when building proton 

### ISSUE THREAD

**Issue by CtrlAltLilith** [Frogging-Family/wine-tkg-git#523]
fatal: destination path 'gstreamer' already exists and is not an empty directory.
HEAD is now at eacb7aa8d1 Release 1.18.4
HEAD is now at eacb7aa8d1 Release 1.18.4
fatal: destination path 'gst-plugins-base' already exists and is not an empty directory.
HEAD is now at ce69d1068 Release 1.18.4
HEAD is now at ce69d1068 Release 1.18.4
fatal: destination path 'gst-plugins-good' already exists and is not an empty directory.
HEAD is now at 941312f3d Release 1.18.4
HEAD is now at 941312f3d Release 1.18.4
fatal: destination path 'gst-plugins-bad' already exists and is not an empty directory.
HEAD is now at 8cb03bdf0 Release 1.18.4
HEAD is now at 8cb03bdf0 Release 1.18.4
fatal: destination path 'gst-plugins-ugly' already exists and is not an empty directory.
HEAD is now at bb3f9de2 Release 1.18.4
HEAD is now at bb3f9de2 Release 1.18.4
fatal: destination path 'gst-libav' already exists and is not an empty directory.
HEAD is now at e896aab Release 1.18.4
HEAD is now at e896aab Release 1.18.4
fatal: destination path 'ffmpeg' already exists and is not an empty directory.
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Can't repro on my end:
```
 > git clone https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg.git
Cloning into 'ffmpeg'...
remote: Enumerating objects: 610861, done.
remote: Counting objects: 100% (19106/19106), done.
remote: Compressing objects: 100% (5835/5835), done.
remote: Total 610861 (delta 13846), reused 16987 (delta 13247), pack-reused 591755
Receiving objects: 100% (610861/610861), 152.69 MiB | 8.02 MiB/s, done.
Resolving deltas: 100% (487278/487278), done.
 > cd ffmpeg
 > git reset --hard HEAD
HEAD is now at 31efd11a70 meson: Fix old revision lookup in libavutil/version.py
```
Maybe try deleting your current `wine-tkg-git/proton-tkg/external-resources/Proton/ffmpeg` dir and see how it goes?
