### ISSUE TITLE
Building Proton-Tkg fails in a fresh cloned repo.

### ISSUE THREAD

**Issue by besentv** [Frogging-Family/wine-tkg-git#525]
Running ./proton-tkg.sh the following happens:

 -> ## Applying hotfix for plain-wine: 215195.mypatch
 ==> ERROR: Patch application has failed. The error was logged to /home/bernhard/Documents/programming/repos/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.

From the log: 

Applying hotfix 215195.mypatch
patching file dlls/hidclass.sys/device.c
Hunk #1 FAILED at 116.
Hunk #2 FAILED at 654.
Hunk #3 FAILED at 677.
3 out of 3 hunks FAILED -- saving rejects to file dlls/hidclass.sys/device.c.rej
patching file dlls/hidclass.sys/hid.h
Hunk #1 FAILED at 123.
1 out of 1 hunk FAILED -- saving rejects to file dlls/hidclass.sys/hid.h.rej
patching file dlls/hidclass.sys/pnp.c
Hunk #1 FAILED at 387.
Hunk #2 succeeded at 489 with fuzz 2 (offset -9 lines).
1 out of 2 hunks FAILED -- saving rejects to file dlls/hidclass.sys/pnp.c.rej

**Comment by hurricane-dorian** [comment]
wine-tkg also fails with the same error.

**Comment by Nolij** [comment]
I am also experiencing this error

**Comment by besentv** [comment]
> Temporary fix: use `_staging_version="v6.17"`

Doesn't really work for me either: 

-> Applying proton-steam-bits-72449b7.patch
./non-makepkg-build.sh: line 166: /home/bernhard/Documents/programming/repos/wine-tkg-git/wine-tkg-git/proton-steam-bits-72449b7.patch: No such file or directory
 ==> ERROR: Patch application has failed. The error was logged to /home/bernhard/Documents/programming/repos/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.

**Comment by besentv** [comment]
> Try a fresh clone.

Didn't do the trick. Still get the error I posted last.
