### ISSUE TITLE
[BUG_ERROR] ==> ERROR: Patch application has failed. 

### ISSUE THREAD

**Issue by Stratos-Crimson** [Frogging-Family/wine-tkg-git#526]
#526 /home/solus/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer: line 900: patch: command not found
 ==> ERROR: Patch application has failed. The error was logged to /home/solus/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
This is the error I am getting whilst trying to compile wine-tkg-git with the roblox mouse patch.

**Comment by Stratos-Crimson** [comment]
It's not avaliable on solus apparently

**Comment by hurricane-dorian** [comment]
wow, those are very basic developer tools.

**Comment by Stratos-Crimson** [comment]
can I compile them?

**Comment by Stratos-Crimson** [comment]
I am also having a hard time making gnome boxes work on this(I am on kde plasma).

**Comment by Stratos-Crimson** [comment]
I am hopping to opensuse
