### ISSUE TITLE
[ERROR_BUG] the build was done without any issues but there is no non-makepkg-builds folder

### ISSUE THREAD

**Issue by Stratos-Crimson** [Frogging-Family/wine-tkg-git#528]
hello
distro: opensuse tumbleweed

**Comment by Tk-Glitch** [comment]
Considering the hugely problematic distro, are you sure the build was "done without any issue"?

**Comment by Stratos-Crimson** [comment]
It didn't pop out any error that I was able to see, I checked the prepare log as well. Opensuse's wiki provides dependancies for building wine as well as wine's page so I am not sure what happened. However, I will try to recompile it again.

**Comment by Stratos-Crimson** [comment]
once I recompile it, I will post the prepare.log and the other last build config file.

**Comment by Stratos-Crimson** [comment]
I have recompiled it three times and apparently I am missing the 32bit development libraries.I am trying to get them.

**Comment by Stratos-Crimson** [comment]
Although I have the wine 32bit build development packages
