### ISSUE TITLE
Crash With Injustice 2

### ISSUE THREAD

**Issue by psppwner300** [Frogging-Family/wine-tkg-git#54]
So, a new Proton GE build was [released](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-1-NR) a few hours ago, and I tried to play Injustice 2. It gets past the splash screen, then gets to the credits, but after that it crashes. Not sure where to report about this, as the Proton GE Github page doesn't allow issues to be posted.

Setup is as follows:
-i5-8400
-GTX 1050 Ti
-8 GB RAM
-Arch Linux
-NVIDIA driver 440.82
-Proton GE 5.9

**Comment by Tk-Glitch** [comment]
Sorry, but we're not doing tech support for random custom proton builds. If GE doesn't want his users to report issues or provide support to them, that's his own choice and responsibility.

If you can reproduce the issue on a fresh build of Proton-tkg, I invite you to join the https://github.com/Frogging-Family/wine-tkg-git/issues/42 discussions. You'll also find information there regarding prerequisites for MK11/Injustice 2 (they are the same for both games).
