### ISSUE TITLE
Latest build Fails

### ISSUE THREAD

**Issue by ManuLinares** [Frogging-Family/wine-tkg-git#542]
```
  ...
  -> Hotfixing...
  -> ## Applying hotfix for wine-staging: protonify_stg_syscall_emu-006.mystagingpatch
  -> Applying childwindow.patch
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches... 
     Staging overrides used, if any: -W ntdll-NtAlertThreadByThreadId -W Pipelight -W winex11-Vulkan_support -W bcrypt-ECDHSecretAgreement
==> ERROR: Patch application has failed. The error was logged to /home/mb/scripts/wine-tkg-git/prepare.log for your convenience.
  -> To use the last known good mainline version, please set _plain_version="" in your .cfg
  -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```

tail /home/mb/scripts/wine-tkg-git/prepare.log

```
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 524 (offset 84 lines).

CSMT-toggle.patch -- ( Applied CSMT toggle logic patch )
patching file patches/patchinstall.sh
Hunk #1 succeeded at 3811 (offset -3782 lines).
patching file patches/winecfg-Staging/0006-winecfg-Toggle-upstream-CSMT-implementation.patch

Applying wine-staging patches...
ERROR: Wrong usage of -W commandline argument, expected patchname.
```

**Comment by KokoseiJ** [comment]
It seems like a patchset `bcrypt-ECDHSecretAgreement` was not included in patchinstall.sh came with staging v6.19, also proton bcrypt patchset seems to be broken too.

I have made a dirty hack which gets rid of problematic parts. I haven't tested them yet but it patches and builds with no problem.

[staging_619_patches.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/7315170/staging_619_patches.tar.gz)

`staging_619_prepare.patch` applies to `wine-tkg-scripts/prepare.sh`;
`staging_619_proton_tkg_staging.patch` applies to `wine-tkg-patches/proton-tkg-specific/proton-tkg-staging.patch`;
and `wine-tkg-patches/proton/proton-bcrypt-staging.patch` should be emptied.

**Comment by karimrir1** [comment]
How can this be applied, I tried to apply it manually but it complained about some files not passing the "validity check"

**Comment by Tk-Glitch** [comment]
Indeed. Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/f8421c4b40c9785a22217a5d234390d90bc2fae5
