### ISSUE TITLE
"Protonify staging syscall emu" hotfix raises an error

### ISSUE THREAD

**Issue by Morxemplum** [Frogging-Family/wine-tkg-git#550]
Hi! I'm running Manjaro Linux XFCE and I am currently trying to make the package. The only modification that I made changes to in the configuration.cfg file was to add a community patch "roblox_fix_mouse.mypatch", but that doesn't seem to have relevance to my problem.

When running `makepkg -si` and getting to the hotfixes section, one of the hot fixes is "Hotfix: Protonify staging syscall emu
." This seems to be causing the issue because the error message happens after the message `## Applying hotfix for wine-staging: protonify_stg_syscall_emu-006.mystagingpatch`

When looking in prepare.log in regards to the the emu patch, these seem to be the failing lines
```
Applying hotfix protonify_stg_syscall_emu-006.mystagingpatch
patching file patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 47.
Hunk #3 succeeded at 70 (offset 6 lines).
Hunk #4 FAILED at 162.
Hunk #5 FAILED at 170.
4 out of 5 hunks FAILED -- saving rejects to file patches/ntdll-Syscall_Emulation/0001-ntdll-Support-x86_64-syscall-emulation.patch.rej
```
I am clueless as to what this patch is because when I look back at the customization file, "_protonify" is set to false, which means this shouldn't even be hotfixing in the first place. Why am I getting a hotfix for something I don't want a hotfix to?

I'm hoping to at least get an answer on why this error may be happening. Maybe this is a glitch and it could be fixed.

**Comment by Tk-Glitch** [comment]
It's just in need for a rebase following upstream changes. I'll push a fix soon.
