### ISSUE TITLE
Latest build fails

### ISSUE THREAD

**Issue by invertedEcho** [Frogging-Family/wine-tkg-git#551]
Hello,
tried building wine-tkg.
It fails with this error
`
../wine-mirror-git/dlls/bcrypt/bcrypt_main.c:117:8: error: ‘BCRYPT_ECDH_P384_ALGORITHM’ undeclared here (not in a function); did you mean ‘BCRYPT_ECDSA_P384_ALGORITHM’?
`
Not sure wether BCRYPT_ECDSA_P384_ALGORITHM is actually the correct function, otherwise i would have made a PR.

**Comment by Tk-Glitch** [comment]
I have built current master ~10 times today with no issue :thinking: 
Could you please give more details about the configuration used, distro.. ? Thanks!

**Comment by Tk-Glitch** [comment]
Oh wait, are you building without mingw maybe?

**Comment by azndd** [comment]
Do I also need mingw 32 bit or only 64 bit?

**Comment by Tk-Glitch** [comment]
You'll need both, and you'll also likely need pthread support.
In case you have issues, I'm offering https://github.com/Frogging-Family/mostlyportable-gcc to build matching gcc/mingw in an easy way.
