### ISSUE TITLE
No sound in The Outer Worlds 

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#561]
Tried `the outer worlds` with `proton-tkg_6.20.r0.g3fb6eb99` and no sound, tested a couple of other games which have sound.

I just hear a loud bursty pop after the intro screen and on exit

Also tested `The outer worlds` with `proton_tkg_6.19.r6.g688eeca0` which works perfectly

Here are the logs in case
[steam-578650.log](https://github.com/Frogging-Family/wine-tkg-git/files/7415286/steam-578650.log)
[proton_tkg_token.txt](https://github.com/Frogging-Family/wine-tkg-git/files/7415295/proton_tkg_token.txt)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/7415297/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7415299/prepare.log)

**Comment by Tk-Glitch** [comment]
Is it still happening?

**Comment by t14462** [comment]
> Is it still happening?

Music in fallout New Vegas was fixed. So maybe its to

**Comment by shaumux** [comment]
Audio is working again with 6.20.r10.gdf26057d
Thanks for your work
