### ISSUE TITLE
Jedi Fallen Order high constant sound screech after video intro.

### ISSUE THREAD

**Issue by mixalis1987** [Frogging-Family/wine-tkg-git#564]
Jedi Fallen Order creates 3 sound channels.
One has the constant high screech and the other has the normal game sound and the last has nothing.

To play without the screech we can just mute the channel that has it. This is the Origin version using Lutris.
Using wine-tkg-staging 6.20.

Don't know why that is because other games I used this wine version on hasn't had this issue.

**Comment by Tk-Glitch** [comment]
Is it still happening?

**Comment by mixalis1987** [comment]
> Is it still happening?

@Tk-Glitch 
I will let you know soon. I need to download the game again. I swapped wine versions too many times and EA banned me from starting the game.

**Comment by mixalis1987** [comment]
@Tk-Glitch 
Download on Origin kept stopping so took some time to download.

The game no longer has constant high screech. Still has 3 audio channels but I don't know if that was always like that.
Did you do anything or was this fixed upstream?
