### ISSUE TITLE
Unable to finish installing

### ISSUE THREAD

**Issue by HumingCloud** [Frogging-Family/wine-tkg-git#569]
Note: I am using a community patch: "roblox_mouse_fix.mypatch"

Running this on MX Linux (debian based)

When I run non-makepkg-build.sh runs for a bit, but it ends out with an error: 
/wine-tkg-git/wine-tkg-git/src/wine-staging-git/patches/patchinstall.sh: autoreconf: not found
ERROR: 'autoreconf -f' failed.
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7445515/prepare.log)

**Comment by Tk-Glitch** [comment]
You need to install the autotools or autoconf package.

**Comment by HumingCloud** [comment]
It worked
