### ISSUE TITLE
compile proton without fshack

### ISSUE THREAD

**Issue by chorriwuarri** [Frogging-Family/wine-tkg-git#57]
is it possible to build proton without fshack?
I have disable fshack in config but when I start ./proton-tkg.sh it fails
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4711972/prepare.log)

**Comment by Tk-Glitch** [comment]
Yes it's totally possible but there was an edge case that wasn't covered. Someone refusing the hotfixes + having fs hack disabled.

You should accept the hotfixes to begin with if you want a working build 🐸 
I just pushed a fix for people like you refusing the hotfixes and having fshack disabled: https://github.com/Frogging-Family/wine-tkg-git/commit/03ba40e68fd67ecee91d9b2517c4dd124ce844d8

You should be good to go :)

**Comment by chorriwuarri** [comment]
Okay, I've accepted the revisions, but it still fails.
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4712080/prepare.log)

**Comment by Tk-Glitch** [comment]
That one was fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/d1244308a98f1e6a0fab3c9a5817342ba4e2fb71

**Comment by chorriwuarri** [comment]
Now it's compiling, thanks :)

**Comment by Tk-Glitch** [comment]
You're welcome :)
