### ISSUE TITLE
Proton-tkg is Hanging on Generating Default Prefix

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#570]
As of today, trying to build proton-tkg fails at "Generating default prefix..." I thought it might be some option I had set, so I cloned a fresh git and tried it again with completely default options, and it still hangs. 

wine-tkg-git is on 909b7e4
wine is on 5f93c683ab0
wine-staging is on 56fd61a7 (that reminds me, `c9c7130-hotfix.mypatch` is no longer needed, building fails in the first place unless this patch is removed)
dxvk is on 8912c7ad
vkd3d-proton is on 430c77d3

**Comment by Tk-Glitch** [comment]
I couldn't reproduce the issue when you posted it (I was fixing things after the patch wave as usual) and couldn't do it since either. If it's still a thing, please attach your `proton-tkg.log`.

**Comment by gardotd426** [comment]
Yeah, must have been a timing thing. Closing.
