### ISSUE TITLE
I am not able to finish setting up wine-tkg

### ISSUE THREAD

**Issue by HumingCloud** [Frogging-Family/wine-tkg-git#571]
When I run ./non-makepkg-build.sh, it runs for a bit then comes up with the error:
`configure: error: gstreamer-1.0 base plugins 64-bit development files not found, GStreamer won't be supported.
This is an error since --with-gstreamer was requested.`
I already installed GStreamer

**Comment by Iglu47** [comment]
`gstreamer-1.0 base plugins` is usually named `gst-plugins-base` or something.
just core GStreamer is not enough.

**Comment by Kron4ek** [comment]
You need `libgstreamer-plugins-base1.0-dev`.
