### ISSUE TITLE
Merge conflict in dlls/wmvcore/tests/wmvcore.c

### ISSUE THREAD

**Issue by AesaraB** [Frogging-Family/wine-tkg-git#579]
Hi, while trying to compile wine-tkg-git I got a merge conflict, unfortunately I don't know too much about git to be too helpful here but is there anything I could do to fix this? I've added the prepare.log file below.

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7472358/prepare.log)

**Comment by CartoonFan** [comment]
I'm not an expert, but usually that means that @Tk-Glitch has to update something (patches, hotfixer, etc.) because of a recent Wine change. It's more or less a waiting game at this point.

**Comment by AesaraB** [comment]
Oh, gotcha; I'll just leave this issue up until it gets patched, then.

**Comment by rizzini** [comment]
Same here.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/c0e73c59ea55a1f83e6000a8872cc7a4f6ae707f
