### ISSUE TITLE
Multiple configuration patches not applying

### ISSUE THREAD

**Issue by MalonnBethesda** [Frogging-Family/wine-tkg-git#581]
I don't know if this is a bug or a user error, but there is no other place I can find to post my issue except here, so here goes.
I built the latest Wine and attempted to apply multiple patches, however only the first one was applied.  I copied the patch names from GitHub, separated each patch with a space, and only the first patch got applied.  What's odd is just prior to attempting the build, I tried with 3 patches, two of which were applied (not 3), and one patch generated an error.  So I rebuilt without the patch that caused an error and only the first patch in the file was applied.
?

**Comment by Tk-Glitch** [comment]
Please give more detail. Which patches?

**Comment by MalonnBethesda** [comment]
Sorry about that, Tk-Glitch.  Thanks for the response.

The first build I used "kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-no-staging.mypatch", "Shell32-CreateDirectoryInDestinationInFileOp-Move-multiop.mypatch" and "Don-t-Skip-adding-public-symbols-Required-for-FakePDB.mypatch".  The build failed on the latter, but only was going to apply 2.

The second build, I skipped the failing patch and tried "kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-no-staging.mypatch", "Shell32-CreateDirectoryInDestinationInFileOp-Move-multiop.mypatch", but skipped the latter.  I followed the instructions in the configuration.cfg file to the T.

**Comment by Tk-Glitch** [comment]
I'm pretty sure `kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-no-staging.mypatch` is dead at this point

**Comment by Tk-Glitch** [comment]
Regarding some patches getting skipped, we have *some* rules to ignore some patches depending on the wine version target. See https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer

**Comment by MalonnBethesda** [comment]
Okay.  It looks like the "Shell32-CreateDirectoryInDestinationInFileOp-Move-multiop.mypatch" is skipped because I'm not on staging.  Any idea why?  Just curious.  Does staging support "things" (sorry for the lack of a technical term) that development branches do not?

And why is "kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-no-staging.mypatch" dead?  Has it been fixed upstream (I think that's the right term)?  I mean have the Wine developers patched it?

**Comment by llde** [comment]
Don-t-Skip-adding-public-symbols-Required-for-FakePDB.mypatch seems to be unnecessary in latest wine.

kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM-no-staging.mypatch should work, it works for me at least. (this patch should work on mainline and recent stagings)
Maybe the last rebase introduced some dependancy to another patchset? I do  use the LFH and QPC proton patchsets

**Comment by MalonnBethesda** [comment]
Thanks, llde.  The GMEM_MOVEABLE patch applied for me and seems to restore drag and drop in Bash.

Fake-PDB wouldn't apply, but I guess it's not necessary.

Move-multiop seems to be for staging only.

I'll go ahead and close this issue.  I never intended to truly "raise an issue", just couldn't find an outlet other than this for an answer.  Like a forum or something.

**Comment by Tk-Glitch** [comment]
Many are doing it that way. The discord could be used for that but ultimately it's not too bad doing it here. No worries.

**Comment by MalonnBethesda** [comment]
Dern.  I didn't even know there was a Discord.  I'll go there next time I have a problem that may not be a bug.

Thanks.

**Comment by t14462** [comment]
> Dern. I didn't even know there was a Discord. I'll go there next time I have a problem that may not be a bug.
> 
> Thanks.

WELCOME!
