### ISSUE TITLE
Ability to create RPM package

### ISSUE THREAD

**Issue by soredake** [Frogging-Family/wine-tkg-git#583]
Would be nice if there a way to create rpm package for fedora from wine-tkg. `_GENERATE_FEDORA_PACKAGE="true"`

**Comment by itspngu** [comment]
I might have a stab at this and set up a copr for it.

**Comment by jrobeson** [comment]
Just nightly ones to package up the the newly generated artifacts? Or will it be more like a regular rpm where it runs the scripts by itself (nightly or not).   

Also, should wine-tkg run the package scripts itself after generating the artifacts? That would avoid the need for a user created package repositories, and thus be seen as a safer choice.  It'll also be less likely to go out of date.

Whether the result should end up in PPA, COPR, or OBS is also something to consider as well.

**Comment by soredake** [comment]
https://copr.fedorainfracloud.org/coprs/patrickl/wine/

**Comment by soredake** [comment]
>Also, should wine-tkg run the package scripts itself after generating the artifacts? 
Yes, i want something like `_GENERATE_DEBIAN_PACKAGE="false"` but for fedora RPM.

**Comment by bayazidbh** [comment]
> https://copr.fedorainfracloud.org/coprs/patrickl/wine/

Hm, seems like it's modified with a lot of the patches turned off? Is there still any particular plus over just using normal `winehq-staging` ?

**Comment by itspngu** [comment]
I've given this some thought and came to the conclusion that it wouldn't make sense to package this as the whole point of the tkg repos is to have a manageable way of running custom versions of stuff.

**Comment by bayazidbh** [comment]
I personally would have liked something along the lines of [chaotic-aur](https://aur.chaotic.cx/)'s build of [wine-tkg-staging-fsync-git](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/3/), though failing that, a simplified install/build script like that of linux-tkg's.

**Comment by arjunkathuria** [comment]
+1 for rpms

**Comment by soredake** [comment]
> [copr.fedorainfracloud.org/coprs/patrickl/wine](https://copr.fedorainfracloud.org/coprs/patrickl/wine/)

https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg-testing/ new repo
