### ISSUE TITLE
Not all Bcrypt patches are applied (Steep can't login)

### ISSUE THREAD

**Issue by tannisroot** [Frogging-Family/wine-tkg-git#586]
I'm not sure why, but some time ago `proton-bcrypt-staging.patch` stopped being applied, and instead patches like `0001-proton-bcrypt_rdr2_fixes.mypatch` `0002-bcrypt-Add-support-for-calculating-secret-ecc-keys.mypatch` `a608ef1.mypatch` are applied instead. However, these patches are missing some important bits from `proton-bcrypt-staging.patch`, notably `bcrypt: Allow multiple backends to coexist.` (and some other ones).
As a result (from what I've observed), games like "Steep", which utilize bcrypt, stopped working and can no longer login.
I've tried to apply the missing bits manually but there are lots of conflicts, and some stuff was probably already upstreamed.
Let me know if I can do anything to help you resolve this.

**Comment by Tk-Glitch** [comment]
The main problem is staging's bcrypt-ECDHSecretAgreement being disabled as of https://github.com/wine-staging/wine-staging/commit/9e1a4bdb736333f3b60f55c0f066a31c6beb2411 due to upstream changes.

**Comment by tannisroot** [comment]
Wasn't it disabled anyway via the -W option in order to apply the custom patch?

**Comment by Tk-Glitch** [comment]
Yes, but it was based on Staging's patch, only with additions. When it got broken by upstream changes, our patch got broken as well.

**Comment by liberodark** [comment]
wine-proton have same issue :(

**Comment by tannisroot** [comment]
This is fixed now
