### ISSUE TITLE
Patch League of Legends not applying

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#59]
Hi frogs,

It's all in the title, here's the error file [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4725737/prepare.log)

Thanks again for all :100:

**Comment by IroAlexis** [comment]
Hello, nothing to signal for repare this patch ? We just need to wait when ntdll "rework" is a good state 😦 🐸

**Comment by Tk-Glitch** [comment]
Absolutely

**Comment by Tk-Glitch** [comment]
I have added a note regarding the last working commit when the patch is enabled in your .cfg.

**Comment by IroAlexis** [comment]
I see this ! Btw I didn't use this commit on my side (it was older : 8be56c2). It's perfect for the moment :+1:

**Comment by Tk-Glitch** [comment]
Weird.. I have always built my lol testing builds with mingw and the game was working just fine :thinking:

**Comment by IroAlexis** [comment]
Yesterday, I was never able to get the client started but by building without mingw, I succeeded and I was able to play without any problem.

I can retry today for see if I can reproduce him.

**Comment by IroAlexis** [comment]
Indeed, I can't reproduce the non-launch of the client. On the other hand, I can't build Wine with the use of the suggested commit (c81093882b2b9ce4a5830437cecdc58b8807d29b).

Here is the log file [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/5240243/prepare.log)

**Comment by Tk-Glitch** [comment]
You're actually right. It was excluding c8109388 and not including it. Thanks to you I was able fix an issue with that legacy hotfix though. I'll fix the hash, thanks.

**Comment by Samega7Cattac** [comment]
> Edit 2 : From time to time, the client stops working just after the LoL logo appears. Just restart it (several times ; it is very rare) and it will succeed in starting up. thinking But I have no idea if it's the compilation with mingw that's causing this and anyway I'm not sure

For me it happens every time, that issue seems to be happening to almost everyone (should deserve it's own issue tho)

**Comment by IroAlexis** [comment]
> > Edit 2 : From time to time, the client stops working just after the LoL logo appears. Just restart it (several times ; it is very rare) and it will succeed in starting up. thinking But I have no idea if it's the compilation with mingw that's causing this and anyway I'm not sure
> 
> For me it happens every time, that issue seems to be happening to almost everyone (should deserve it's own issue tho)

Today, unable to launch the client. Yesterday, it works "fine".
I tried compile with the suggestion that used by wine-lol for seeing :hourglass:

**Comment by IroAlexis** [comment]
I confirm that using `_NOMINGW="true"` (wine-tkg-profiles/advanced-customization.cfg) fix the problem

**Comment by Samega7Cattac** [comment]
ppl have been able to play if they delete the riot client folder and force league to start using the old client
But no access to friends list and other stuff

**Comment by IroAlexis** [comment]
@Tk-Glitch So I can close this issue so ? :frog:

**Comment by Tk-Glitch** [comment]
This shouldn't be an issue anymore and a warning is now issued as a helper to get a working build. Closing.
