### ISSUE TITLE
./non-makepkg-build.sh returning error

### ISSUE THREAD

**Issue by MiloMikoreyBarber** [Frogging-Family/wine-tkg-git#595]
Hi, 
when I run /non-makepkg-build.sh, I get following error:

/home/milomb/wine-tkg-git/wine-tkg-git/src/wine-staging-git/patches/patchinstall.sh: 969: autoreconf: not found
ERROR: 'autoreconf -f' failed.

What do I do to fix this? 
Can't find an answer on google.

Thanks!

**Comment by ReperakDev** [comment]
Do you have autoconf installed?

**Comment by MiloMikoreyBarber** [comment]
Yes, I do now. It still doesn't work. At the beginning it says libk something cant be found 3 (different requirements). Can't install them using sudo apt install.

**Comment by ReperakDev** [comment]
Please share actual error messages.

**Comment by MiloMikoreyBarber** [comment]
Here it is: `E: Unable to locate package libkdb5-9
E: Unable to locate package libkadm5clnt-mit11
E: Unable to locate package libkadm5srv-mit11
`

**Comment by MiloMikoreyBarber** [comment]
After the above errors, I get the following: 
` -> Using staging patchset
 -> Using fsync patchset
 -> Using pba patchset
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 ==> WARNING: ! Staging has disabled mfplat support on this revision, so video playback will not work in games using mfplat !
 -> Changing wine HEAD to the wine-staging base commit...
Note: switching to 'b5b77ed6acad6a20bd4c5bfc98cfce178eef1d0c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b5b77ed6aca winecoreaudio.drv: Place output message before return statement.
 -> Using '/home/milomb/community-patches' as community-patches repo root
 -> Updating community-patches repo...
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/Frogging-Family/community-patches
 * branch            master     -> FETCH_HEAD
Already up-to-date.
ln: failed to create symbolic link '/home/milomb/wine-tkg-git/wine-tkg-git/roblox_mouse_fix.mypatch': File exists
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
`

**Comment by itspngu** [comment]
You manually messed with files in the community-patches repo. Move the folder somewhere else or rename it and run non-makepkg-build.sh again.

**Comment by MiloMikoreyBarber** [comment]
Which folder? wine-tkg-git? and if so there are two, which?

**Comment by itspngu** [comment]
No, the community-patches folder. It's in the same directory you cloned wine-tkg-git into.

**Comment by MiloMikoreyBarber** [comment]
I just cloned wine-tkg-git, didn't put it into a specific directory.

**Comment by itspngu** [comment]
Well it surely is *somewhere*, right? Go there and delete the community-patches folder next to it.

**Comment by MiloMikoreyBarber** [comment]
Followed this guide: 

![Screenshot from 2021-11-23 19-08-53](https://user-images.githubusercontent.com/74494622/143080465-dc62de8d-d4fb-4b2f-ba03-cc14dc6fbeaf.png)

**Comment by MiloMikoreyBarber** [comment]
Oh, I see. Sorry for being an idiot.
