### ISSUE TITLE
commit-64a9d9f.mystagingpatch broken by upstream wine-staging rebase

### ISSUE THREAD

**Issue by itspngu** [Frogging-Family/wine-tkg-git#597]
The patch for the patch patcher has been patched in staging, tried to patch it myself but got confused and now I feel very patchy :frog: 

https://github.com/wine-staging/wine-staging/commit/68918863dcab756a407a58cf6b6869c21557e3d0#diff-b43f69f613909b08dcbf6af8c2fe9a138f74cd84ca7e011aa10457198c073814

```
Applying hotfix commit-64a9d9f.mystagingpatch
patching file patches/patchinstall.sh
Hunk #1 succeeded at 1318 (offset 4 lines).
Hunk #2 succeeded at 1327 (offset 4 lines).
patching file patches/eventfd_synchronization/0001-configure-Check-for-sys-eventfd.h-ppoll-and-shm_open.patch
Hunk #1 FAILED at 124.
1 out of 1 hunk FAILED -- saving rejects to file patches/eventfd_synchronization/0001-configure-Check-for-sys-eventfd.h-ppoll-and-shm_open.patch.rej
patching file patches/eventfd_synchronization/0046-server-Create-eventfd-descriptors-for-pseudo-fd-obje.patch
Hunk #1 succeeded at 31 with fuzz 1.
```

Building proton off staging 6.22 works fine.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/9eac3d2121c7bace2cf5162c24765fb1e9a8cd04
