### ISSUE TITLE
failed patching on proton-tkg

### ISSUE THREAD

**Issue by makrker** [Frogging-Family/wine-tkg-git#601]
Applying /home/mark/wine-tkg-git/wine-tkg-git/src/wine-staging-git/patches/ntdll-Serial_Port_Detection/0001-ntdll-Do-a-device-check-before-returning-a-default-s.patch
error: patch failed: dlls/mountmgr.sys/device.c:27
error: dlls/mountmgr.sys/device.c: patch does not apply
ERROR: Failed to apply patch, aborting!

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7606723/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/4d03d610b5ac8196b5285c9eb60237f50b8b2340
