### ISSUE TITLE
proton-tkg gstreamer build issues

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#606]
Hello! I stumbled upon an issue where the latest proton-tkg doesn't compile gstreamer correctly.

An interesting result before the compilation:
```bash
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 4: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton_tkg_token: No such file or directory
```

Here it seems like it's an openexr thing with gst-plugins-bad:
```c
Run-time dependency openexr found: YES 3.1.3
```

```c
[838/875] Compiling C++ object ext/zxing/libgstzxing.so.p/gstzxing.cpp.o
../../gst-plugins-bad/ext/zxing/gstzxing.cpp: In function ‘GstFlowReturn gst_zxing_transform_frame_ip(GstVideoFilter*, GstVideoFrame*)’:
../../gst-plugins-bad/ext/zxing/gstzxing.cpp:330:29: warning: ‘ZXing::Result ZXing::ReadBarcode(int, int, const uint8_t*, int, ZXing::BarcodeFormats, bool, bool)’ is deprecated [-Wdeprecated-declarations]
  330 |   auto result = ReadBarcode (width, height, (unsigned char *) data, width,
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  331 |       { BarcodeFormatFromString (barcode_formats[zxing->format].value_name) },
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  332 |       zxing->rotate, !zxing->faster);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../gst-plugins-bad/ext/zxing/gstzxing.cpp:60:
/usr/include/ZXing/ReadBarcode.h:104:8: note: declared here
  104 | Result ReadBarcode(int width, int height, const uint8_t* data, int rowStride,
      |        ^~~~~~~~~~~
[873/875] Compiling C++ object ext/ope...libgstopenexr.so.p/gstopenexrdec.cpp.o
FAILED: ext/openexr/libgstopenexr.so.p/gstopenexrdec.cpp.o 
ccache c++ -Iext/openexr/libgstopenexr.so.p -Iext/openexr -I../../gst-plugins-bad/ext/openexr -I. -I../../gst-plugins-bad -Igst-libs -I../../gst-plugins-bad/gst-libs -I/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/orc-0.4 -I/usr/include/OpenEXR -I/usr/include/Imath -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wno-non-virtual-dtor -fvisibility=hidden -fno-strict-aliasing -Wformat-nonliteral -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Wformat -Wformat-security -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wvla -Wpointer-arith -fPIC -pthread -DHAVE_CONFIG_H -MD -MQ ext/openexr/libgstopenexr.so.p/gstopenexrdec.cpp.o -MF ext/openexr/libgstopenexr.so.p/gstopenexrdec.cpp.o.d -o ext/openexr/libgstopenexr.so.p/gstopenexrdec.cpp.o -c ../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp
In file included from /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/gstreamer-1.0/gst/base/base.h:35,
                 from ../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:27:
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/gstreamer-1.0/gst/base/gstbytereader.h: In function ‘guint8* gst_byte_reader_dup_data_unchecked(GstByteReader*, guint)’:
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/gstreamer-1.0/gst/base/gstbytereader.h:365:30: warning: ‘void* g_memdup(gconstpointer, guint)’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
  365 |   return (guint8 *) g_memdup (data, size);
      |                     ~~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
                 from /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/gst/include/gstreamer-1.0/gst/gst.h:27,
                 from ../../gst-plugins-bad/ext/openexr/gstopenexrdec.h:24,
                 from ../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:25:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
  257 | gpointer              g_memdup         (gconstpointer mem,
      |                       ^~~~~~~~
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp: At global scope:
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:45:11: error: ‘Int64’ does not name a type; did you mean ‘gint64’?
   45 |   virtual Int64 tellg ();
      |           ^~~~~
      |           gint64
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:46:23: error: ‘Int64’ has not been declared
   46 |   virtual void seekg (Int64 pos);
      |                       ^~~~~
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:66:1: error: ‘Int64’ does not name a type; did you mean ‘gint64’?
   66 | Int64 MemIStream::tellg ()
      | ^~~~~
      | gint64
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:72:1: error: variable or field ‘seekg’ declared void
   72 | MemIStream::seekg (Int64 pos)
      | ^~~~~~~~~~
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:72:20: error: ‘Int64’ was not declared in this scope; did you mean ‘gint64’?
   72 | MemIStream::seekg (Int64 pos)
      |                    ^~~~~
      |                    gint64
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp: In function ‘GstFlowReturn gst_openexr_dec_handle_frame(GstVideoDecoder*, GstVideoCodecFrame*)’:
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:343:43: error: invalid new-expression of abstract class type ‘MemIStream’
  343 |             (decoder)), map.data, map.size);
      |                                           ^
../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:36:7: note:   because the following virtual functions are pure within ‘MemIStream’:
   36 | class MemIStream:public IStream
      |       ^~~~~~~~~~
In file included from /usr/include/OpenEXR/ImfAttribute.h:18,
                 from /usr/include/OpenEXR/ImfHeader.h:26,
                 from /usr/include/OpenEXR/ImfRgbaFile.h:23,
                 from ../../gst-plugins-bad/ext/openexr/gstopenexrdec.cpp:30:
/usr/include/OpenEXR/ImfIO.h:82:25: note:     ‘virtual uint64_t Imf_3_1::IStream::tellg()’
   82 |     virtual uint64_t    tellg () = 0;
      |                         ^~~~~
/usr/include/OpenEXR/ImfIO.h:90:25: note:     ‘virtual void Imf_3_1::IStream::seekg(uint64_t)’
   90 |     virtual void        seekg (uint64_t pos) = 0;
      |                         ^~~~~
ninja: build stopped: subcommand failed.
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 262: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton-tkg-userpatches/gstreamer-ugly: No such file or directory
```
Thanks!

**Comment by gardotd426** [comment]
What distro are you on? Because on Arch I just built proton-tkg 3 times in a row with no errors - once with `_build_gstreamer="true"`, once with both that and `_lib32_gstreamer="true"`, and once with both set to true and with `openxr` installed (the other two were without it installed). 

Do you have a VR headset? If not there's no need to have openxr installed. Also you really don't need `_build_gstreamer` or `_lib32_gstreamer`  set to true if you have the requisite packages installed through your distro's package manager.

Plus as long as you enable `_build_mediaconv` you shouldn't really need gstreamer in your proton build, especially if you have all the gstreamer and gst-plugin packages installed.

**Comment by CartoonFan** [comment]
I'm on Arch :smile:.

> Do you have a VR headset? If not there's no need to have openxr installed.

I'll take your word for it :smile:.  Still, I just want to gently point out that the issue seems to be with openexr (image software) rather than openxr (VR software). I haven't installed the latter :smile:.

> Plus as long as you enable _build_mediaconv you shouldn't really need gstreamer in your proton build, especially if you have all the gstreamer and gst-plugin packages installed.

This is probably true, but I generally prefer to have proton-tkg do it, if I can. It makes bug reporting a little easier, you know?

**Comment by gardotd426** [comment]
Oops my bad, It was like 5 AM local time when I commented and I had just spent hours making a patch to fix some other issue someone was having on here, I read `openxr` every single time lol. 

Anyway everything I said except the first bit about VR still stands. I have `openexr` installed, and it never failed to build once under any of those conditions, in three attempts. 

>This is probably true, but I generally prefer to have proton-tkg do it, if I can. It makes bug reporting a little easier, you know?

Well in this case it would almost certainly be an upstream bug in either proton or gstreamer, but yeah I get what you're saying. 

I'd try building again and see if it still fails. If it does, then you'll need to actually post your configs because this isn't just a universal issue (like I said I couldn't force it to happen with any combination of relevant configs and with `openexr` installed). At least the contents of `proton-tkg.cfg` and the output of `pacman -Q | grep openexr`

**Comment by CartoonFan** [comment]
Sure, here you go.

Proton-tkg config:
[proton-tkg.cfg.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/7636583/proton-tkg.cfg.tar.gz)

Pacman -Q output:
```console
jesus% pacman -Q | grep openexr                        
lib32-openexr 3.0.5-1
openexr 3.1.3-1
```
I just want to clarify that the actual proton-tkg compilation works fine (including the cleaning portion at the end); it's the gstreamer compilation which fails, causing the libs to not be copied, which prevents Proton from doing anything gstreamer related.

**Comment by gardotd426** [comment]
>I just want to clarify that the actual proton-tkg compilation works fine (including the cleaning portion at the end); it's the gstreamer compilation which fails, causing the libs to not be copied, which prevents Proton from doing anything gstreamer related.

Yeah mine doesn't fail. It goes through all the 119 or 113 steps or whatever, for both 32-bit and 64-bit, then moves on to vkd3d-proton/dxvk with no errors. 

Is there some reason why you need `lib32-openexr`? That's the only thing I don't have installed (and I'm not aware of any possible reason for it). I'm building again with it installed, to see if that triggers it.

Also, whenever you have an issue like this that other people can't reproduce (or really even before you report it), it's always best to try and build in a fresh git clone as a sanity check to make sure it builds without errors there. Like literally clone the repo next to where the original is, cd into it, and change nothing except the gstreamer options and see if you still get the error.

**Comment by CartoonFan** [comment]
> Also, whenever you have an issue like this that other people can't reproduce (or really even before you report it), it's always best to try and build in a fresh git clone as a sanity check to make sure it builds without errors there. Like literally clone the repo next to where the original is, cd into it, and change nothing except the gstreamer options and see if you still get the error.

Good to know. I'll try doing that, I guess.

**Comment by gardotd426** [comment]
Hold on a second, what makes you think the gstreamer files aren't included? Where in the build did you look? Because I just logged the build with `lib32-openexr` and I get those same warnings, but they are just for individual gstreamer components (probably because they conflict with what you have installed, there have been issues posted here before that were caused by out of date system-installed gstreamer packages). 

See here:

```
[823/864] Compiling C object ext/webrtc/libgstwebrtc.so.p/webrtcdatachannel.c.o
In file included from ../../gst-plugins-bad/ext/webrtc/webrtcdatachannel.c:36:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h: In function ‘gst_byte_reader_dup_data_unchecked’:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h:365:3: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
  365 |   return (guint8 *) g_memdup (data, size);
      |   ^~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
                 from /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/gst.h:27,
                 from ../../gst-plugins-bad/ext/webrtc/webrtcdatachannel.h:23,
                 from ../../gst-plugins-bad/ext/webrtc/webrtcdatachannel.c:33:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
  257 | gpointer              g_memdup         (gconstpointer mem,
      |                       ^~~~~~~~
[824/864] Compiling C++ object ext/webrtcdsp/libgstwebrtcdsp.so.p/gstwebrtcdsp.cpp.o
[825/864] Compiling C++ object ext/webrtcdsp/libgstwebrtcdsp.so.p/gstwebrtcechoprobe.cpp.o
[826/864] Compiling C object ext/webp/libgstwebp.so.p/gstwebp.c.o
In file included from ../../gst-plugins-bad/ext/webp/gstwebpdec.h:28,
                 from ../../gst-plugins-bad/ext/webp/gstwebp.c:28:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h: In function ‘gst_byte_reader_dup_data_unchecked’:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h:365:3: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
  365 |   return (guint8 *) g_memdup (data, size);
      |   ^~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
                 from /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/gst.h:27,
                 from ../../gst-plugins-bad/ext/webp/gstwebp.c:26:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
  257 | gpointer              g_memdup         (gconstpointer mem,
      |                       ^~~~~~~~
[827/864] Compiling C object ext/webp/libgstwebp.so.p/gstwebpdec.c.o
In file included from ../../gst-plugins-bad/ext/webp/gstwebpdec.h:28,
                 from ../../gst-plugins-bad/ext/webp/gstwebpdec.c:26:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h: In function ‘gst_byte_reader_dup_data_unchecked’:
/home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/base/gstbytereader.h:365:3: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
  365 |   return (guint8 *) g_memdup (data, size);
      |   ^~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
                 from /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/gst.h:27,
                 from ../../gst-plugins-bad/ext/webp/gstwebpdec.h:24,
                 from ../../gst-plugins-bad/ext/webp/gstwebpdec.c:26:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
  257 | gpointer              g_memdup         (gconstpointer mem,
      |                       ^~~~~~~~
[828/864] Compiling C object ext/webp/libgstwebp.so.p/gstwebpenc.c.o
[829/864] Compiling C object ext/wildmidi/libgstwildmidi.so.p/gstwildmididec.c.o
[830/864] Compiling C object tools/gst-transcoder-1.0.p/gst-transcoder.c.o
[831/864] Compiling C object ext/zxing/libgstzxing.so.p/gstzxingplugin.c.o
[832/864] Compiling C object ext/zbar/libgstzbar.so.p/gstzbar.c.o
[833/864] Compiling C object tools/gst-transcoder-1.0.p/utils.c.o
[834/864] Compiling C++ object ext/zxing/libgstzxing.so.p/gstzxing.cpp.o
../../gst-plugins-bad/ext/zxing/gstzxing.cpp: In function ‘GstFlowReturn gst_zxing_transform_frame_ip(GstVideoFilter*, GstVideoFrame*)’:
../../gst-plugins-bad/ext/zxing/gstzxing.cpp:330:29: warning: ‘ZXing::Result ZXing::ReadBarcode(int, int, const uint8_t*, int, ZXing::BarcodeFormats, bool, bool)’ is deprecated [-Wdeprecated-declarations]
  330 |   auto result = ReadBarcode (width, height, (unsigned char *) data, width,
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  331 |       { BarcodeFormatFromString (barcode_formats[zxing->format].value_name) },
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  332 |       zxing->rotate, !zxing->faster);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../gst-plugins-bad/ext/zxing/gstzxing.cpp:60:
/usr/include/ZXing/ReadBarcode.h:104:8: note: declared here
  104 | Result ReadBarcode(int width, int height, const uint8_t* data, int rowStride,
      |        ^~~~~~~~~~~
[835/864] Compiling C object ext/wayland/libgstwaylandsink.so.p/wlbuffer.c.o
```

And it goes right on to finish building and installing:

```
[853/864] Compiling C object ext/srtp/libgstsrtp.so.p/gstsrtpdec.c.o
[854/864] Compiling C object ext/srtp/libgstsrtp.so.p/gstsrtpenc.c.o
[855/864] Compiling C object ext/srtp/libgstsrtp.so.p/meson-generated_.._gstsrtp-enumtypes.c.o
[856/864] Compiling C object ext/srt/libgstsrt.so.p/meson-generated_.._gstsrt-enumtypes.c.o
[857/864] Compiling C object ext/srtp/libgstsrtp.so.p/gstsrtp.c.o
[858/864] Linking target ext/srtp/libgstsrtp.so
[859/864] Compiling C object ext/srt/libgstsrt.so.p/gstsrtsink.c.o
[860/864] Compiling C object ext/srt/libgstsrt.so.p/gstsrt.c.o
[861/864] Compiling C object ext/srt/libgstsrt.so.p/gstsrtsrc.c.o
[862/864] Compiling C object ext/srt/libgstsrt.so.p/gstsrtobject.c.o
[863/864] Linking target ext/srt/libgstsrt.so
[863/864] Installing files.
Installing gst-libs/gst/uridownloader/libgsturidownloader-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/adaptivedemux/libgstadaptivedemux-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/audio/libgstbadaudio-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/basecamerabinsrc/libgstbasecamerabinsrc-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/codecparsers/libgstcodecparsers-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/codecs/libgstcodecs-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/insertbin/libgstinsertbin-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/interfaces/photography-enumtypes.h to /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/interfaces
Installing gst-libs/gst/interfaces/libgstphotography-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/isoff/libgstisoff-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/mpegts/gstmpegts-enumtypes.h to /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/mpegts
Installing gst-libs/gst/mpegts/libgstmpegts-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/player/libgstplayer-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/sctp/libgstsctp-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/transcoder/libgsttranscoder-1.0.so.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/wayland/libgstwayland-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst-libs/gst/webrtc/webrtc-enumtypes.h to /home/matt/dev/wine-tkg-git/proton-tkg/gst/include/gstreamer-1.0/gst/webrtc/
Installing gst-libs/gst/webrtc/libgstwebrtc-1.0.so.0.1804.0 to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64
Installing gst/accurip/libgstaccurip.so to /home/matt/dev/wine-tkg-git/proton-tkg/gst/lib64/gstreamer-1.0
```

The build has all the same files as Proton-GE and upstream Proton, as well as previous builds of proton-tkg, except for a few 32-bit gstreamer libs, but all the other ones are installed. Note that these will pretty much never effect you.

>Good to know. I'll try doing that, I guess. Also, openexr seems to be used by GIMP and opencv, since you asked.

Not `lib32-openexr`, GIMP is 64-bit, and only depends on the 64-bit build of `openexr`. GIMP nor any gstreamer package/plugins on Arch require `lib32-openexr`.

**Comment by CartoonFan** [comment]
I hear you. I'm pretty sure the issue happened on 64-bit openexr with 64-bit gst-plugins-bad, which was partly why I was so confused. I'm doing a build now, so we'll see if a fresh clone is what was needed.

**Comment by gardotd426** [comment]
I mean like I said I'm getting the errors too but they don't actually prevent anything from getting installed except for a few files

It looks like the lib32-gst-plugins-bad being installed locally breaks the stuff. Which isn't surprising as there are probably version mismatches (Arch and the AUR are on 1.18.5, upstream is on 1.19.2 or something).

Go ahead and run `find ~/.steam/root/compatibilitytools.d/proton_tkg<whateverversion>/ | grep lib\\/ | grep gstreamer-1.0` and you'll see all the 32-bit gstreamer files that do get installed, and replace `lib\\/` with `lib64\\/` to see the 64-bit.

**Comment by gardotd426** [comment]
FWIW, they're more or less identical to what Proton-GE includes. There are 32 gstreamer-related files total different (out of like 260-290) between the two.

**Comment by CartoonFan** [comment]
> FWIW, they're more or less identical to what Proton-GE includes. There are 32 gstreamer-related files total different (out of like 260-290) between the two.

Huh, didn't know that. Interesting.

Here's my gstreamer directory contents:

lib:
```console
find ~/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb | grep lib\\/ | grep gstreamer-1.0
/home/jeremiah/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb/files/lib/gstreamer-1.0
/home/jeremiah/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb/files/lib/gstreamer-1.0/libprotonmediaconverter.so
```
lib64:
```console
find ~/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb | grep lib64\\/ | grep gstreamer-1.0
/home/jeremiah/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb/files/lib64/gstreamer-1.0
/home/jeremiah/.steam/steam/compatibilitytools.d/proton_tkg_6.22.r8.g3b7c98eb/files/lib64/gstreamer-1.0/libprotonmediaconverter.so
```
So yeah, nothing there for me.

**Comment by gardotd426** [comment]
Okay that's really weird, because I have the identical errors you have, and yet my proton-tkg results are 264 files (vs my GE results of like 296 or something). 

Here's the list. This is with `lib32-openxr` not installed (though the results are the same either way), and `pacman -Q | grep gst` returning:
```
gst-libav 1.18.5-1
gst-plugin-pipewire 1:0.3.40-1
gst-plugins-bad 1.18.5-3
gst-plugins-bad-libs 1.18.5-3
gst-plugins-base 1.18.5-1
gst-plugins-base-libs 1.18.5-1
gst-plugins-good 1.18.5-2
gst-plugins-ugly 1.18.5-2
gstreamer 1.18.5-1
gstreamer-vaapi 1.18.5-1
lib32-gst-plugins-base 1.18.4-1
lib32-gst-plugins-base-libs 1.18.4-1
lib32-gst-plugins-good 1.18.5-1
lib32-gstreamer 1.18.5-1
obs-gstreamer 0.3.2-1
phonon-qt5-gstreamer 4.10.0-2
```

[files.txt](https://github.com/Frogging-Family/wine-tkg-git/files/7637136/files.txt)

**Comment by CartoonFan** [comment]
So, I had gstreamer 1.19.3 (and the rest of the relevant gst packages) installed, and on the off chance that it somehow affected proton-tkg's gstreamer, I reinstalled the 1.18.5 release. However, I got the same result. I guess I'll just have to disable gstreamer building for now.

**Comment by Tk-Glitch** [comment]
Please give it another try following https://github.com/Frogging-Family/wine-tkg-git/commit/11356ec9d845e0804eddfdf90149c83afc615f94 and https://github.com/Frogging-Family/wine-tkg-git/commit/e95fd60918a82f3f02b67d01b20976ead65b2d5b

**Comment by CartoonFan** [comment]
After the mentioned commits, gstreamer seems to build properly. However, the libs still don't seem like they're getting copied over to the steam directory. I haven't tried a fresh clone yet, so that's probably next. Also, I can't really test if it works due to Wine giving me an "unimplemented function shell32.dll.SHGetFolderPathW" error ([steam log](https://github.com/Frogging-Family/wine-tkg-git/files/7652068/proton_tkg_622_r11_steam_log.txt)).

Still seeing the token error, too:
```console
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 4: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton_tkg_token: No such file or directory
```
Thanks as always!

**Comment by gardotd426** [comment]
Yeah that's really weird, cause I just sent the entire build to a log file `./proton-tkg.sh 2>&1 | tee protonlog` and no lines mentioning "No such file" or `proton_tkg_token` show up.

**Comment by CartoonFan** [comment]
Good idea! I've attached my own protonlog below.
[protonlog.txt](https://github.com/Frogging-Family/wine-tkg-git/files/7652919/protonlog.txt)

Of note, there are a few files that the script isn't finding:
```console
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 125: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton-tkg-userpatches/gstreamer-base: No such file or directory
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 228: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton-tkg-userpatches/gstreamer-bad: No such file or directory
/home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/proton_template/gstreamer.sh: line 263: /home/jeremiah/Downloads/workshop/vcs/PKGBUILDS/wine-tkg-git/proton-tkg/Proton/proton-tkg-userpatches/gstreamer-ugly: No such file or directory
```
These files exist in proton-tkg/proton-tkg-userpatches, but not proton-tkg/Proton/proton-tkg-userpatches. Maybe that's also part of it?

**Comment by gardotd426** [comment]
No, the thing is, while building, the stuff from `external-resources` (which includes `Proton`) gets moved to the base `proton-tkg` directory. As soon as the build fails or completes, the script automatically removes all that stuff. So there will never be a `proton-tkg/Proton` directory *except* when the build itself is running (you can check this for yourself during a build process).

**Comment by CartoonFan** [comment]
Hmm...something seems strange, though. The script seems to be looking in Proton (or external-resources, if you prefer) instead of in the base directory for a handful of things( proton_tkg_token, the gstreamer patches). Could it be an issue with where $_nowhere is pointing? Not for the entire build process, of course, but maybe it changes at some point, causing the script to look in the wrong place.

**Comment by gardotd426** [comment]
Yeah, that's not supposed to be needed (and will probably break things very shortly). 

This is how it's supposed to work:

 - `external-resources` contains the submodules (git repos) for the projects used in the script. 

 - When you run `./proton-tkg.sh`, the script creates symlinks (or copies, I don't remember) of everything in `external-resources` into `$PWD`, which is `proton-tkg` (which is `$_where`). 
 - Once the script finishes, whether it completes, fails, or is killed with CTRL+C, the cleanup built into the builder begins, and all of those things get erased (as does the src directory in your makepkg builddir). 
 - In `proton-tkg.sh`, `$_nowhere` = `$_where`. But in the `gstreamer.sh` script, it actually equals "onedirectory above `$PWD`"

So yeah, if you hardcode it, I can just about guarantee it will break stuff at some point. These build programs are thousands and thousands of lines long and messing up one little line (or even permanently setting one little variable) can break everything.

**Comment by CartoonFan** [comment]
This has been fixed for a while :smile: 
Closing #606.
