### ISSUE TITLE
Patch application has failed.

### ISSUE THREAD

**Issue by gentuwu** [Frogging-Family/wine-tkg-git#607]
`==> ERROR: Patch application has failed. The error was logged to /home/aura/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.` is the error that I am currently dealing with; not sure at all what causes it. additional relevant logs: `==> ERROR: A failure occurred in prepare().` `error: could not revert 2adf4376d86... winex11.drv: Pass size in bytes to RegQueryValueExW().`

**Comment by gentuwu** [comment]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7629828/prepare.log)

**Comment by gardotd426** [comment]
Can confirm

**Comment by gardotd426** [comment]
So wine made a commit `548bc54` 4 hours ago that changed some winex11.drv files. But wine-staging made a commit `4c51f4f` 2 hours ago that rebased against it. And their patch does cleanly apply to the wine base. So it's not a wine staging issue, it's got to be in the Hotfixer. 

But anyway, @TK-Glitch hopefully that's enough info for you to know exactly where to go to get it sorted. The hotfixer is a black box as far as I'm concerned lol, it's like black magic. 

Anyway, @gentuwu if you want to build before TKG gets around to fixing this, you can just use `_plain_version="f374e9c"` and `staging_version="65ca056"` in your `customization.cfg`.

**Comment by gentuwu** [comment]
> So wine made a commit `548bc54` 4 hours ago that changed some winex11.drv files. But wine-staging made a commit `4c51f4f` 2 hours ago that rebased against it. And their patch does cleanly apply to the wine base. So it's not a wine staging issue, it's got to be in the Hotfixer.
> 
> But anyway, @Tk-Glitch hopefully that's enough info for you to know exactly where to go to get it sorted. The hotfixer is a black box as far as I'm concerned lol, it's like black magic.
> 
> Anyway, @gentuwu if you want to build before TKG gets around to fixing this, you can just use `_plain_version="f374e9c"` and `staging_version="65ca056"` in your `customization.cfg`.

Ty, appreciate it!

**Comment by gentuwu** [comment]
> So wine made a commit `548bc54` 4 hours ago that changed some winex11.drv files. But wine-staging made a commit `4c51f4f` 2 hours ago that rebased against it. And their patch does cleanly apply to the wine base. So it's not a wine staging issue, it's got to be in the Hotfixer.
> 
> But anyway, @Tk-Glitch hopefully that's enough info for you to know exactly where to go to get it sorted. The hotfixer is a black box as far as I'm concerned lol, it's like black magic. Otherwise I'd track it down and file a PR for you. I've been meaning to try and figure out how to debug that kind of stuff in the hotfixer, hopefully I can get around to that soon to try and help out.
> 
> Anyway, @gentuwu if you want to build before TKG gets around to fixing this, you can just use `_plain_version="f374e9c"` and `staging_version="65ca056"` in your `customization.cfg`.

Unrelated- can I apply patches to kernels like you can with wine via git?

**Comment by gardotd426** [comment]
This is unrelated, but yes. 

Put them in `wine-tkg-userpatches` (or `proton-tkg-userpatches`). If you want them applied at the end of the hotfixes and staging patch application, you give them the extension `.mypatch` for patches or `myrevert` for reverts. If you want them applied to the wine-staging source before the wine-staging patches get applied, then it's `.mystagingpatch` and `.mystagingrevert`. That's all you have to do and you'll be asked if you want to apply them during the build at the appropriate time. 

For any other questions it's probably a better idea to take them elsewhere like the Discord or something, so we can keep this readable (and because TKG is gonna get emailed every time we post here). 

Refer to `wine-tkg-git/wine-tkg-userpatches/README.md` for more information.

**Comment by gentuwu** [comment]
> This is unrelated, but yes.
> 
> Put them in `wine-tkg-userpatches` (or `proton-tkg-userpatches`). If you want them applied at the end of the hotfixes and staging patch application, you give them the extension `.mypatch` for patches or `myrevert` for reverts. If you want them applied to the wine-staging source before the wine-staging patches get applied, then it's `.mystagingpatch` and `.mystagingrevert`. That's all you have to do and you'll be asked if you want to apply them during the build at the appropriate time.
> 
> For any other questions it's probably a better idea to take them elsewhere like the Discord or something, so we can keep this readable (and because TKG is gonna get emailed every time we post here).
> 
> Refer to `wine-tkg-git/wine-tkg-userpatches/README.md` for more information.

what about good ol vanilla linux? and after building wine-tkg my fps is far worse now than it was using a release, not sure why :(

**Comment by gardotd426** [comment]
Oh you were asking about linux-tkg, I thought you were asking about wine-tkg. Anyway yes. Look at the READMEs in the linux-tkg repo. It explains everything, it's all there. 

>and after building wine-tkg my fps is far worse now than it was using a release, not sure why :(

I don't know, and this isn't the thread for that discussion.
