### ISSUE TITLE
Hotfixer is failing to apply patches due to some upstream commits

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#608]
So, someone opened an issue #607 about this earlier, but closed it inappropriately.

So I figured I'd give you a heads up in case you didn't know, I'll just paste my findings from #607:

So wine made a commit `548bc54` 4 hours ago that changed some `winex11.drv` files. But wine-staging made a commit `4c51f4f` 2 hours ago that rebased against it. And their patch does cleanly apply to the wine base. So it's not a wine staging issue, it's got to be in the Hotfixer.

But anyway, @Tk-Glitch hopefully that's enough info for you to know exactly where to go to get it sorted. The hotfixer is a black box as far as I'm concerned lol, it's like black magic. Otherwise I'd track it down and file a PR for you. I've been meaning to try and figure out how to debug that kind of stuff in the hotfixer, hopefully I can get around to that soon to try and help out.

Anyway, @gentuwu if you want to build before TKG gets around to fixing this, you can just use `_plain_version="f374e9c"` and `staging_version="65ca056"` in your `customization.cfg`.

**Comment by gentuwu** [comment]
Apologies. I appreciate your help!

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/1d7fab60fde00f021513b33fa3399460a1635471
