### ISSUE TITLE
wine/port.h missing

### ISSUE THREAD

**Issue by gentuwu** [Frogging-Family/wine-tkg-git#611]
`../wine-mirror-git/server/fsync.c:22: error: wine/port.h: No such file or directory`
What could be causing this file to not be downloaded or have smth happen to it?

**Comment by ThisNekoGuy** [comment]
For reference, I did reproduce this (coincidentally), I'll include a full log and my Proton-tkg.cfg:
[Proton-tkg.cfg and Terminal Output Log.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7645124/Proton-tkg.cfg.and.Terminal.Output.Log.zip)

**Comment by CartoonFan** [comment]
Just want to add that this and #612 are the same bug, in case they get separated.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/0f4864d5aa2e47b135e6282fec7aae01e88e4359
