### ISSUE TITLE
Post-script Version Management is Gone? Doesn't Install

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#614]
I was expecting the usual version management to show up after this part (also, the generate part was almost instant - not sure if it failed?) but it didn't show up; is this intentional?

```bash
...
Fixed up PE:  ./shell32.dll

Generating default prefix...
neko-san@ARCH ~/w/proton-tkg (master)> 
```

It seems it did fail though, because it didn't install it into the Steam directory at all :/

**Comment by itspngu** [comment]
Check your proton-tkg.log file. Does it say something like this?

```
Proton-tkg - 12-03-2021 19:19:45
[...]
wine: created the configuration directory '/home/pngu/wine-tkg-git/proton-tkg/proton_tkg_6.22.r11.g61c3c024/files/share/default_pfx'
wineserver: using server-side synchronization.
wine: Unhandled page fault on read access to 000000000000000B at address 00007FABAFCA7B27 (thread 002c), starting debugger...
wine: could not load kernel32.dll, status c0000135
Traceback (most recent call last):
  File "/home/pngu/wine-tkg-git/proton-tkg/proton_template/default_pfx.py", line 118, in <module>
    make_default_pfx(sys.argv[1], sys.argv[2], None)
  File "/home/pngu/wine-tkg-git/proton-tkg/proton_template/default_pfx.py", line 105, in make_default_pfx
    subprocess.run(runtime_args + ["/bin/bash", "-c",
  File "/home/pngu/.asdf/installs/python/3.8.2/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/bash', '-c', '/home/pngu/wine-tkg-git/proton-tkg/proton_tkg_6.22.r11.g61c3c024/files/bin/wine wineboot && /home/pngu/wine-tkg-git/proton-tkg/proton_tkg_6.22.r11.g61c3c024/files/bin/wineserver -w']' returned non-zero exit status 53.
```

For me the fix is to compile with _staging_version="7f17af3a420edfc37ea445b91bd532dd63d084ec" until somebody smarter figures out what's going on. See also #613

**Comment by ThisNekoGuy** [comment]
> Check your proton-tkg.log file. Does it say something like this?

I was about to until an unfortunate series of events occurred this morning and now the log is gone :upside_down_face: 
I was about to try again just now when the patch application phase failed :skull_and_crossbones:

**Comment by ThisNekoGuy** [comment]
Ah, I managed to get it to do it again this time:
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/7655171/proton-tkg.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7655172/proton-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment]
This happens if your wine build is broken and can't create a prefix.

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch Yeah, I read the log Lol
Problem is, I have no idea what's broken about it

**Comment by Tk-Glitch** [comment]
Possibly fixed following https://github.com/Frogging-Family/wine-tkg-git/commit/e3f85471501ff283fa31c8d713f0dda2aad28fb5
