### ISSUE TITLE
[wine-tkg 6.22] Dotnet40 installation broken with TKG

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#617]
Using the staging configuration for TKG, dotnet40 installation with winetricks is broken, but works in wine-staging from arch repository.
Tomorrow I will try to check with patch or option cause this regression

**Comment by llde** [comment]
IT's one of the community patches.
Closing

**Comment by Tk-Glitch** [comment]
Which one?

**Comment by llde** [comment]
The kernel32-implement-Windows-NT-style-GMEM_MOVEABLE-LM patches.
