### ISSUE TITLE
[wine-tkg ] Libldap isn't recognized in configure

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#619]
Wine configure script fails to recongnize 2.5+ libLdap packages on ArchLinux

Adding   `sed 's/-lldap_r/-lldap/' -i $srcdir/$_winesrcdir/configure` to the PKGBUILD fix the issue
Debian apparently has a workaround using symlinks in the libldap package

**Comment by julmajustus** [comment]
I'm still getting build error for wldap32 when building on arch with this fix [ 2cad614](https://github.com/Frogging-Family/wine-tkg-git/commit/2cad614ba06f3fee2793a396b502a3b48a7cf5e9).

```
make: *** [Makefile:224017: dlls/wldap32/error.o] Error 1
In file included from ../wine-mirror-git/dlls/wldap32/init.c:35:
../wine-mirror-git/dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
```

**Comment by Tk-Glitch** [comment]
lib32-ldap package installed?

**Comment by julmajustus** [comment]
Yep.

`warning: lib32-libldap-2.6.0-1 is up to date -- reinstalling`

**Comment by Tk-Glitch** [comment]
Weird. I just built wine twice in a row and faced no issue :thinking:
