### ISSUE TITLE
wine-staging-6.23 + fshack - Mouse issues

### ISSUE THREAD

**Issue by SveSop** [Frogging-Family/wine-tkg-git#620]
I built as "bareboned" wine as i could, and ended up with this:
wine-reverts:
```
548bc54bf396d74b5b928bf9be835272ddda1886 reverted (hotfix)
b502a3e3c6b43ac3947d85ccc263e729ace917fa reverted (hotfix)
963589ee296ae90003dab3e8204766ab4e4c0045 reverted (hotfix)
2adf4376d86119b8a6f7cde51c9a972564575bac reverted (hotfix)
6dcaff421f87a93efe18b2efe0ec64d94ed1d483 reverted (hotfix)
b54199101fd307199c481709d4b1358ba4bcce58 reverted (hotfix)
dedda40e5d7b5a3bcf67eea95145810da283d7d9 reverted (hotfix)
bd27af974a21085cd0dc78b37b715bbcc3cfab69 reverted (hotfix)
```
staging-patches:
```
hotfix staging-6dcaff42.mystagingpatch
hotfix staging-4c51f4f.mystagingpatch
hotfix protonify_stg_syscall_emu-008.mystagingpatch
```
staging installed with `-W winex11-WM_WINDOWPOSCHANGING -W winex11-_NET_ACTIVE_WINDOW`
Added `valve_proton_fullscreen_hack-staging.patch`

This causes mouse issues with Unigine Valley and Heaven benchmarks in fullscreen, where the mouse seem to be locked to around 1/4 of the screen (upper left 1/4 of visible screenspace). Alt+tab out of this, and clicking something else, then click the taskbar to switch back to the benchmark window will "fix" the issue, and mouse moves freely again.

This did not happen with wine-staging-6.22+fshack, so for me atleast, this is something new.

Tips? Anyone able to test Unigine Valley and see if the mouse is "normal" in fullscreen for them? Is it a mutter/gnome issue perhaps that has reared its ugly head in some changes with

**Comment by SveSop** [comment]
Thank The Glorious eggroll :+1: 

wine with no reverts + staging with only `protonify_stg_syscall_emu` and `-W winex11-WM_WINDOWPOSCHANGING -W winex11-_NET_ACTIVE_WINDOW` made this work fine:
[https://github.com/GloriousEggroll/proton-ge-custom/blob/master/patches/proton/41-valve_proton_fullscreen_hack-staging-tkg.patch](https://github.com/GloriousEggroll/proton-ge-custom/blob/master/patches/proton/41-valve_proton_fullscreen_hack-staging-tkg.patch)

May be one of those x11drv<->gdi upstream patches that TKG reverted caused something weird? Or it is possibly one of the added patches in GE's fshack patch?

Ill leave this one up a couple of days incase someone wanna look into it.

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/a4a78c5898ce468dd0e34ce6460dc280737e5236
