### ISSUE TITLE
fdf3015816168678c919ab282cf4e88704e931bc breaks josh-flat-theme.patch

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#621]
As title say commit fdf3015816168678c919ab282cf4e88704e931bc breaks josh's theme patch
(offset 77 lines).

josh-flat-theme.patch -- ( Add Josh's better-theme )
patching file dlls/user32/sysparams.c
Hunk #1 FAILED at 1453.
1 out of 1 hunk FAILED -- saving rejects to file dlls/user32/sysparams.c.rej
patching file dlls/comctl32/tab.c
patching file dlls/user32/uitools.c
Hunk #1 succeeded at 167 (offset -1 lines).
Hunk #2 succeeded at 476 (offset -1 lines).
Hunk #3 succeeded at 1496 (offset -2 lines).
patching file dlls/comctl32/treeview.c
patching file dlls/user32/uitools.c
Hunk #1 succeeded at 1488 (offset -2 lines).

**Comment by dylanwright** [comment]
On the off chance someone is not aware - it's possible to set the `_use_josh_flat_theme` flag to false in customization.cfg and it will build fine.
