### ISSUE TITLE
fastsync-staging patches fail to apply with latest wine-tkg (2cad614)

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#622]
Hello there! I'm on Arch, and with 2cad614ba06f3fee2793a396b502a3b48a7cf5e9, the fastsync-staging patches don't apply correctly for me. Tried with a fresh clone as well, with no changes.

Hopefully these files will help:
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7678588/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/7678589/last_build_config.log)
[wine-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/7678594/wine-tkg.cfg.txt)
 
 Thanks as always!

**Comment by Iglu47** [comment]
thanks for report, i'll see soon

**Comment by CartoonFan** [comment]
Thanks!

**Comment by Iglu47** [comment]
It's due to `_protonify="true"`. The same problem on proton-tkg.
This requires a little change, but I cannot successfully build proton-tkg right now due to some other error.

**Comment by CartoonFan** [comment]
Thanks! I'll try it now.
