### ISSUE TITLE
proton-tkg-staging.patch -- ( Using Steam-specific Proton-tkg patches (staging) 2/3 ) fail to apply

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#627]
patching file dlls/winevulkan/loader_thunks.c
Hunk #1 succeeded at 1653 (offset 85 lines).
patching file dlls/winevulkan/loader.c
Hunk #1 FAILED at 18.
Hunk #2 succeeded at 355 (offset 11 lines).
Hunk #3 succeeded at 382 (offset 11 lines).
Hunk #4 succeeded at 403 with fuzz 1 (offset 11 lines).
1 out of 4 hunks FAILED -- saving rejects to file dlls/winevulkan/loader.c.rej

**Comment by Tk-Glitch** [comment]
Should be all good now

**Comment by llde** [comment]
Something Wrong happened
wine-tkg-git/wine-tkg-git/PKGBUILD: riga 419: _prepare: command not found

**Comment by llde** [comment]
Ok solved (goddamit the shell error message are awful). All seems to work
Asseghimma
