### ISSUE TITLE
unable to build proton-tkg with LAA.patch

### ISSUE THREAD

**Issue by gcaliber** [Frogging-Family/wine-tkg-git#63]
Unable to build proton with LAA.patch after selecting yes to apply hotfixes. This is using the advanced configuration with no changes. I am able to use the PKGBUILD for wine, just building proton is a problem.

<details>
  <summary>last_build_config.log</summary>

> Local cfg files used
> 
> Wine (plain) version: 5.10.r0.g3cc3b44575
> 
> NOT using VKD3D for d3d12 translation
> 
> use_clock_monotonic.patch -- ( Applied clock_monotonic patch )
> steam.patch -- ( Applied steam crossover hack )

</details>

<details>
  <summary>prepare.log</summary>

> fatal: destination path 'wine-mirror-git' already exists and is not an empty directory.
> Fetching origin
> Cloning into '/home/mike/hdd/wine-tkg-git/wine-tkg-git/src/wine-mirror-git'...
> done.
> Switched to a new branch 'makepkg'
> HEAD is now at 3cc3b44575 Release 5.10.
> 
> use_clock_monotonic.patch -- ( Applied clock_monotonic patch )
> patching file dlls/ntdll/time.c
> Hunk #1 succeeded at 119 (offset 5 lines).
> patching file server/request.c
> Hunk #1 succeeded at 536 with fuzz 2 (offset 10 lines).
> 
> steam.patch -- ( Applied steam crossover hack )
> patching file dlls/kernelbase/process.c
> Hunk #1 succeeded at 468 (offset 28 lines).
> 
> LAA.patch -- ( Applied large address aware override support )
> patching file dlls/kernel32/heap.c
> Hunk #1 succeeded at 47 (offset -28 lines).
> Hunk #2 succeeded at 549 (offset -828 lines).
> Hunk #3 succeeded at 593 (offset -828 lines).
> patching file dlls/ntdll/loader.c
> Hunk #1 succeeded at 2383 with fuzz 1 (offset 398 lines).
> Hunk #2 FAILED at 3671.
> 1 out of 2 hunks FAILED -- saving rejects to file dlls/ntdll/loader.c.rej
> patching file dlls/ntdll/ntdll.spec
> Hunk #1 succeeded at 1592 (offset 85 lines).
> patching file dlls/ntdll/ntdll_misc.h
> Hunk #1 FAILED at 189.
> 1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/ntdll_misc.h.rej
> patching file dlls/ntdll/virtual.c
> Hunk #1 FAILED at 2442.
> 1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/virtual.c.rej

</details>

**Comment by Tk-Glitch** [comment]
Ok I was able to reproduce the issue with esync disabled, which makes sense actually. I'll see what I can do.

**Comment by Tk-Glitch** [comment]
Please update your tree to https://github.com/Frogging-Family/wine-tkg-git/commit/3640aaf2c087f028c4bbc392c021a598b136763f and give it another try. Your issue should be fixed.

**Comment by gcaliber** [comment]
Issue is fixed.
