### ISSUE TITLE
`wine_wayland_driver.mypatch` Fails

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#630]
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7696514/proton-tkg.cfg.zip)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7696515/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/7696516/last_build_config.log)

**Comment by TheComputerGuy96** [comment]
The patch there is out-of-date 🐸

**Comment by hurricane-dorian** [comment]
Updated in pull request https://github.com/Frogging-Family/community-patches/pull/88

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/community-patches/commit/58102e0a48bfee2683ca63616e48b5fe277ed391
