### ISSUE TITLE
amd_fsr_fshack.mypatch is broken after a2fcffc

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#633]
So, I had typed up a decently long issue report early this morning at like 5AM local time, and after all the commits earlier today I figured it might have been fixed so I started building and went to queue up the issue to close it (if it was fixed), and turns out I never actually posted it, and GH usually saves issue drafts but it didn't in this case.

Anyway, amd_fsr_fshack being enabled causes any builds using later-than a2fcffc staging tree. I tried like hell to find the bad commit but because my revert patches could only be applied after the staging and hotfix patches, or to the staging tree itself, I couldn't use any myrevert patches (even ones built off simple `git format-patch` would fail to apply in wne-tkg-git). 

After the updates today, it's still broken after a2fcffc

**Comment by Tk-Glitch** [comment]
You're talking about https://github.com/Frogging-Family/community-patches/issues/86 ?

**Comment by Tk-Glitch** [comment]
The patch is effectively a community patch so you did well with your first issue btw

**Comment by gardotd426** [comment]
Lmao OMG *that's* why I couldn't find it. Sorry Etienne man, my bad. Closing.
