### ISSUE TITLE
7.0-rc2: Merge conflict in dlls/winegstreamer/wm_asyncreader.c

### ISSUE THREAD

**Issue by KokoseiJ** [Frogging-Family/wine-tkg-git#639]
```
could not revert 21dc092b910... winegstreamer: Implement IWMReader::Start().
```

Log:
```
21dc092b910f80616242761a00d8cdab2f8aa7bd reverted (hotfix)
Auto-merging dlls/wmvcore/tests/wmvcore.c
Auto-merging dlls/winegstreamer/wm_asyncreader.c
CONFLICT (content): Merge conflict in dlls/winegstreamer/wm_asyncreader.c
```

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7739000/prepare.log)
[proton-tkg.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/7739001/proton-tkg.cfg.txt)

rc2 was released less than an hour ago, so I suppose this is due to breaking changes in upstream.
I'll try to build with rc1 and report back.

**Comment by KokoseiJ** [comment]
Update: hotfixes are being applied without issues in rc1.

**Comment by Tk-Glitch** [comment]
Should have been fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/bc1f4283af8bfa52723e69509c41af72f7a88600

**Comment by llde** [comment]
Works for me. with bc1f4283af8bfa52723e69509c41af72f7a88600

**Comment by KokoseiJ** [comment]
I temporarilly don't have access to my system. I'll check it tomorrow and report back if it indeed fixes the issue.
