### ISSUE TITLE
issue applying patches to main head

### ISSUE THREAD

**Issue by robzombie91** [Frogging-Family/wine-tkg-git#64]
-> ## Applying reverting hotfix for wine-staging: 06877e55b1100cc49d3726e9a70f31c4dfbe66f8-13.mystagingrevert
==> ERROR: Patch application has failed. The error was logged to /home/rob/Documents/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
  -> ## Applying hotfix for wine-staging: 934a09585a15e8491e422b43624ffe632b02bd3c-3.mystagingpatch
  -> ## Applying hotfix for wine-staging: ntdll-ForceBottomUpAlloc-044cb93.mystagingpatch
  -> Applying use_clock_monotonic.patch
  -> Applying childwindow.patch
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches...
==> ERROR: Patch application has failed. The error was logged to /home/rob/Documents/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by robzombie91** [comment]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4767477/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/de8cf696cba768e5b26f2b3fa54824fcbcd779e5 and https://github.com/Frogging-Family/wine-tkg-git/commit/46a8883bbc52ce0fc9ff3fac720e98b8fd26ae68
