### ISSUE TITLE
Error building with futex_waitv patch

### ISSUE THREAD

**Issue by v1993** [Frogging-Family/wine-tkg-git#643]
The error I'm encountering is described here: https://github.com/ValveSoftware/wine/issues/131. It seems to be caused by having system headers that already define futex-related variable `__NR_futex_waitv`.

**Comment by v1993** [comment]
Note: linked issue also provides a hotfix for this problem, which seems to work when added as user patch.

**Comment by Iglu47** [comment]
what does it mean already defined?
are you talking about compatibility not only with linux-tkg? I have not tested with anything else.

**Comment by v1993** [comment]
I'm using linux-tkg with futex_waitv patchset currently and that seems to be the exact source of problem.

**Comment by Iglu47** [comment]
can't repro, can you share at least the .cfg files?

**Comment by Iglu47** [comment]
@v1993 what version of this package do you have on your system?
https://archlinux.org/packages/core/any/linux-api-headers/
`pacman -Qs linux-api-headers`

**Comment by v1993** [comment]
None, because I'm on KUbuntu :stuck_out_tongue:. I have version `5.15.11-tkg-pds-1` of `linux-libc-dev` tho (which was built with futex_waitv patch).

**Comment by Iglu47** [comment]
Ok that makes sense.
Yes, it will be useful to explicitly separate those definitions by the number of files to which they are defined, but it will be necessary to add a check for include `linux/futex.h`. Looks simple, I'll take a look later.

**Comment by Iglu47** [comment]
@v1993 can you download and check this patch for wine-tkg, please
https://github.com/Iglu47/wine-tkg-git/commit/17ea486c128a40fbb3882b221dd92d874601a6f1.patch
```
cd wine-tkg-git
patch -Np1 <  17ea486c128a40fbb3882b221dd92d874601a6f1.patch
```
I would like to know if this works correctly for another distribution before submitting it to TkG.

**Comment by liberodark** [comment]
Hi,

Have see your patch i think is better to upstream your patch to https://github.com/ValveSoftware/wine/
If you are ok with that?

Best Regards

**Comment by Iglu47** [comment]
well, over time the Proton build environment will use kernel-5.16+, and only then are such changes likely to be needed.
