### ISSUE TITLE
[hotfix issue] restore_staging_winepulse - Split Second

### ISSUE THREAD

**Issue by leipero** [Frogging-Family/wine-tkg-git#645]
With wine-tkg as well as lutris-ge, Split Second crashes at startup, it doesn't happen with wine-staging or standard lutris builds (they have another issue with the game, pausing when pressing any KB button and ignoring keypress).

When building default wine-tkg-git, when asked: "Hotfix: Staging's winepulse pulseaudio support patchset is currently disabled, leading to audio skips and crackling in various games.
  Restore it?"
default answer is No, if you bild it with that option, game works fine, if you restore it (y), game crashes at startup.

I suspect some other games do crash because of it as well. I can see in notes that games affected are Cyberpunk 2077 and Forza Horizon 4, is that still the case? Latest wine-tkg and proton-tkg 6.17.r0.g5f19a815 release is built with that option enabled it seems, since it crashes.

**Comment by CartoonFan** [comment]
For me, with c3b65427ccd0cfa75524b49e9c1605c63d12b367, Forza Horizon 4 seems to crash regardless of what I do. I've only gotten it to work consistently (albeit partially) with proton-ge.

**Comment by leipero** [comment]
@CartoonFan That seems to be another issue, but it would be nice to test Forza Horizon 4 (and/or Cyberpunk 2077) without restore_staging_winepulse patchset in order to see if cracking sound is still an issue, because if it isn't, there's no need for this patchset since it makes at least one game crash (and probably more).

**Comment by leipero** [comment]
Since this patchset is dropped, the issue is no longer present, it can be closed.

**Comment by leipero** [comment]
Not going to open an issue, since it is a patch issue, but with latest changes Split Second is crashing again. To avoid crash, build with _staging_pulse_disable="true"
