### ISSUE TITLE
Can't start FFXIV Launcher [TKG 6.17]

### ISSUE THREAD

**Issue by RochaLAJ** [Frogging-Family/wine-tkg-git#658]
Procedure

* Downloaded proton TKG [wget https://github.com/Frogging-Family/wine-tkg-git/releases/download/6.17.r0.g5f19a815/proton_tkg_6.17.r0.g5f19a815.release.tar.gz]
* Extracted to ~/.steam/root/compatibilitytools.d 
* Selected on steam play 
![image](https://user-images.githubusercontent.com/43121804/148991978-292e41be-7e85-44c8-b089-27bffae1bac2.png)

Terminal when i press 'play'
```
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.
Installing breakpad exception handler for appid(steam)/version(1639697812)
pid 17195 != 17194, skipping destruction (fork without exec?)
Game process removed: AppID 39210 "/home/rochalaj/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=39210 -- '/home/rochalaj/.local/share/Steam/compatibilitytools.d/Proton-6.17-TKG'/proton waitforexitandrun '/home/rochalaj/.local/share/Steam/steamapps/common/FINAL FANTASY XIV Online/boot/ffxivboot.exe' -issteam", ProcID 17189 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.

```
Later i noticed that any game isn't launching with TKG while Proton-GE and experimental work without any issue.

System
Kernel: 5.16.0-rc6-230-tkg-cfs
Arch Linux x86_64
20GB Ram
SSD 1TB NVME
RX 6600

**Comment by Tk-Glitch** [comment]
This should work fine these days.
I'll release prebuilt binaries soon (7.3 based), but building yourself works.
