### ISSUE TITLE
Those patches are causing a build failure

### ISSUE THREAD

**Issue by SolarAquarion** [Frogging-Family/wine-tkg-git#66]
'use_clock_monotonic.patch' # Perf
		'use_clock_monotonic-2.patch' # Addon for the patch above, needed on 13e11d3+

**Comment by SolarAquarion** [comment]
0c14b1a962573ee125940f2008c646befe597226 reverted (hotfix)
Auto-merging dlls/ntdll/unix/unix_private.h

683583faf2f4b00874f702429393b127aca8eef4 reverted (hotfix)
Auto-merging dlls/ntdll/signal_x86_64.c
CONFLICT (content): Merge conflict in dlls/ntdll/signal_x86_64.c
CONFLICT (modify/delete): dlls/ntdll/signal_powerpc.c deleted in HEAD and modified in parent of 683583faf2... ntdll: Remove support for setting custom signal handlers.. Version parent of 683583faf2... ntdll: Remove support for setting custom signal handlers. of dlls/ntdll/signal_powerpc.c left in tree.
Auto-merging dlls/ntdll/signal_i386.c
CONFLICT (content): Merge conflict in dlls/ntdll/signal_i386.c
Auto-merging dlls/ntdll/signal_arm64.c
CONFLICT (content): Merge conflict in dlls/ntdll/signal_arm64.c
Auto-merging dlls/ntdll/signal_arm.c
CONFLICT (content): Merge conflict in dlls/ntdll/signal_arm.c
Auto-merging dlls/ntdll/ntdll.spec

**Comment by SolarAquarion** [comment]
proton-winevulkan-nofshack.patch -- ( Using Proton winevulkan patches (nofshack) )
patching file dlls/winevulkan/make_vulkan
Hunk #1 succeeded at 102 (offset 7 lines).
Hunk #3 succeeded at 189 with fuzz 2 (offset 2 lines).
Hunk #4 succeeded at 219 (offset 5 lines).
Hunk #5 succeeded at 2238 (offset -17 lines).
Hunk #6 succeeded at 2264 (offset -17 lines).
patching file dlls/winevulkan/vulkan.c
Hunk #1 succeeded at 128 (offset 7 lines).
Hunk #2 succeeded at 146 (offset 7 lines).
Hunk #3 succeeded at 233 (offset 7 lines).
Hunk #4 succeeded at 244 (offset 7 lines).
Hunk #5 succeeded at 271 (offset 7 lines).
Hunk #6 succeeded at 1052 (offset -7 lines).
patching file dlls/winevulkan/vulkan_private.h
Hunk #1 succeeded at 133 (offset -42 lines).
patching file dlls/winevulkan/vulkan_thunks.c
Hunk #1 succeeded at 4434 (offset 664 lines).
Hunk #2 succeeded at 4906 (offset 762 lines).
Hunk #3 succeeded at 5299 (offset 822 lines).
Hunk #4 succeeded at 5489 with fuzz 1 (offset 840 lines).
Hunk #5 succeeded at 5533 with fuzz 2 (offset 845 lines).
Hunk #6 succeeded at 5608 (offset 856 lines).
Hunk #7 succeeded at 5679 (offset 856 lines).
Hunk #8 succeeded at 5793 with fuzz 1 (offset 869 lines).
Hunk #9 succeeded at 5823 (offset 870 lines).
patching file dlls/winevulkan/vulkan_thunks.h
Hunk #2 succeeded at 54 (offset -3 lines).
Hunk #3 FAILED at 70.
Hunk #4 succeeded at 668 with fuzz 2 (offset 137 lines).
Hunk #5 succeeded at 1001 (offset 168 lines).
Hunk #6 succeeded at 1383 with fuzz 1 (offset 222 lines).
Hunk #7 succeeded at 1486 with fuzz 2 (offset 239 lines).
Hunk #8 succeeded at 1611 (offset 262 lines).
Hunk #9 succeeded at 1813 with fuzz 1 (offset 279 lines).
Hunk #10 succeeded at 1856 with fuzz 2 (offset 284 lines).
Hunk #11 succeeded at 1922 with fuzz 1 (offset 295 lines).
1 out of 11 hunks FAILED -- saving rejects to file dlls/winevulkan/vulkan_thunks.h.rej
patching file include/wine/vulkan.h
Hunk #1 succeeded at 361 with fuzz 1 (offset 13 lines).
Hunk #2 succeeded at 1617 (offset 212 lines).
Hunk #3 succeeded at 2289 (offset 369 lines).
Hunk #4 succeeded at 2849 (offset 426 lines).
Hunk #5 succeeded at 4680 (offset 119 lines).
Hunk #6 succeeded at 6236 with fuzz 2 (offset 1101 lines).
Hunk #7 succeeded at 7333 with fuzz 2 (offset 240 lines).
Hunk #8 succeeded at 7538 with fuzz 1 (offset 259 lines).
Hunk #9 succeeded at 7595 with fuzz 1 (offset 267 lines).
Hunk #10 succeeded at 7624 with fuzz 2 (offset 268 lines).
Hunk #11 succeeded at 7650 with fuzz 1 (offset 273 lines).
Hunk #12 succeeded at 7855 with fuzz 1 (offset 292 lines).
Hunk #13 succeeded at 7912 with fuzz 1 (offset 300 lines).
Hunk #14 succeeded at 7941 with fuzz 2 (offset 301 lines).
patching file dlls/winevulkan/vulkan.c
Hunk #1 succeeded at 149 (offset 7 lines).
Hunk #2 succeeded at 833 (offset 18 lines).
Hunk #3 succeeded at 857 (offset 18 lines).
patching file dlls/winex11.drv/vulkan.c
Hunk #1 succeeded at 59 with fuzz 2 (offset 3 lines).
Hunk #2 succeeded at 149 (offset 12 lines).
Hunk #3 succeeded at 662 with fuzz 1 (offset 41 lines).

**Comment by Tk-Glitch** [comment]
Those truncated logs aren't helpful though. Please attach both your `last_build_config.log` and `prepare.log` files.

I'll remove those copy/pastes above for readability.

**Comment by SolarAquarion** [comment]
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4810454/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4810455/prepare.log)

**Comment by Tk-Glitch** [comment]
Your tree seems to be deeply outdated. It looks like it's based on https://github.com/Frogging-Family/wine-tkg-git/commit/0153beff5af24447d8e8012f8f648ad108aadeea, which is 2 weeks old at this point.

**Comment by SolarAquarion** [comment]
i didn't git pull --recurse-submodules or whatever

**Comment by Tk-Glitch** [comment]
Could you please try to reproduce the issue on a clean clone?
```
git clone https://github.com/Frogging-Family/wine-tkg-git.git
cd wine-tkg-git/wine-tkg-git
makepkg -si (or ./non-makepkg-build.sh if you're not using a pacman distro)
```

**Comment by SolarAquarion** [comment]
i can close it now

**Comment by Tk-Glitch** [comment]
Good! Enjoy 😉
