### ISSUE TITLE
Empty line causing OpenRC binfmt error

### ISSUE THREAD

**Issue by mochaaP** [Frogging-Family/wine-tkg-git#660]
OpenRC will pass binfmt line-by-line to `/proc/sys/fs/binfmt_misc/register`, even if it's an empty line.

There is a trailing line in `/usr/lib/binfmt.d/wine.conf`, which could lead to this error:

```shell
binfmt                       | * Loading custom binary format handlers ...
binfmt                       |/usr/lib/openrc/sh/binfmt.sh: line 33: /proc/sys/fs/binfmt_misc/: Is a directory
binfmt                       |/usr/lib/openrc/sh/binfmt.sh: line 35: echo: write error: Invalid argument
binfmt                       |binfmt: invalid entry on line 3 of `/usr/lib/binfmt.d//wine.conf'
```

~~This seems to be an upstream issue, should we patch this here?~~

update: <https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/wine-binfmt.conf> not an upstream issue

**Comment by openglfreak** [comment]
https://www.freedesktop.org/software/systemd/man/binfmt.d.html
> Empty lines and lines beginning with ";" and "#" are ignored.
Sounds like an issue with OpenRC, report there

**Comment by mochaaP** [comment]
tracked in <https://github.com/OpenRC/openrc/issues/492>
