### ISSUE TITLE
Is there a way to change the external folder name?

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#663]
I want to change to something more static, so I don't need to update the path in my scripts.

I thought `_nomakepkg_nover` would suffice. I even tried `_PKGNAME_OVERRIDE`, which I know only changes the package name, but I was out of ideas. lol

It keeps installing at `/opt/wine-tkg-git-staging-7.0rc6.r0.g0111d074/`, which, of course, the versions string constantly changes.

I'm on Arch.

As a workaround I created a simple script at [/usr/bin/wine_tkg](https://github.com/rizzini/Dotfiles.system/blob/master/usr/bin/wine_tkg):
```
#!/bin/bash
wine_path='/opt/wine-tkg-git-staging-7.0rc6.r0.g0111d074/bin/wine'
exec $wine_path "$@"
```
Every time the folder name changes, I just edit this script instead of the rest of my system.

**Comment by MCPO-Spartan-117** [comment]
Sounds like the global config is overwriting it.

**Comment by rizzini** [comment]
I'm using PKGBUILD. Thanks!

**Comment by Tk-Glitch** [comment]
The option you want to use is `_EXTERNAL_NOVER`.

**Comment by rizzini** [comment]
Oh.. I didn't see that option. Sorry!
