### ISSUE TITLE
Patch application failed (7.0-rc6)

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/wine-tkg-git#664]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7883319/prepare.log)

Welcome back TkG

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/1ed610382e67536d8097a3f771bc119460a59c1d

**Comment by ninelore** [comment]
new error

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/7885050/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/f5b6ca3e7afb18dc9e8ffa16c8a035593b668e00

**Comment by ninelore** [comment]
ty

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
