### ISSUE TITLE
Connection issue with Uplay

### ISSUE THREAD

**Issue by nutta-git** [Frogging-Family/wine-tkg-git#67]
Title 
Tkg-version: proton-tkg-5.11.r0.g3d9a9272

[steam-365590.log](https://github.com/Frogging-Family/wine-tkg-git/files/4811729/steam-365590.log)
![division](https://user-images.githubusercontent.com/59726608/85259417-05b26600-b437-11ea-9fc7-967e199a396a.png)

Uplay runs fine with vanilla Proton

**Comment by Tk-Glitch** [comment]
I'm noticing this:
```
err:secur32:SECUR32_initSchannelSP TLS library not found, SSL connections will fail
```
Make sure you have `gnutls` & `lib32-gnutls` packages installed on your distro. I'll try for a repro on my end.

**Comment by nutta-git** [comment]
```
$ dnf list installed gnutls*
Installed Packages
gnutls.i686                            3.6.14-2.fc32                     @updates
gnutls.x86_64                          3.6.14-2.fc32                     @updates
gnutls-c++.x86_64                      3.6.14-2.fc32                     @updates
gnutls-dane.x86_64                     3.6.14-2.fc32                     @updates
gnutls-devel.x86_64                    3.6.14-2.fc32                     @updates
gnutls-guile.x86_64                    3.6.14-2.fc32                     @updates
gnutls-utils.x86_64                    3.6.14-2.fc32                     @updates

```


```

**Comment by nutta-git** [comment]
So I tried to reinstall the 32bit libraries from:  https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies 
and this resulted in this: 


`Dependencies resolved.
=================================================================================
 Package               Architecture Version                  Repository     Size
=================================================================================
```
Installing:
 gcc-c++               i686         10.0.1-0.11.fc32         fedora         11 M
 gnutls-devel          i686         3.6.14-2.fc32            updates       2.1 M
Installing dependencies:
 gnutls-c++            i686         3.6.14-2.fc32            updates        30 k
 gnutls-dane           i686         3.6.14-2.fc32            updates        33 k
Downgrading:
 cpp                   x86_64       10.0.1-0.11.fc32         fedora        9.4 M
 gcc                   x86_64       10.0.1-0.11.fc32         fedora         30 M
 gcc-c++               x86_64       10.0.1-0.11.fc32         fedora         11 M
 gcc-gdb-plugin        x86_64       10.0.1-0.11.fc32         fedora        125 k
 libgomp               i686         10.0.1-0.11.fc32         fedora        254 k
 libgomp               x86_64       10.0.1-0.11.fc32         fedora        246 k
 libstdc++             i686         10.0.1-0.11.fc32         fedora        657 k
 libstdc++             x86_64       10.0.1-0.11.fc32         fedora        613 k
 libstdc++-devel       i686         10.0.1-0.11.fc32         fedora        2.0 M
 libstdc++-devel       x86_64       10.0.1-0.11.fc32         fedora        2.0 M
```

Transaction Summary
`

**Comment by Tk-Glitch** [comment]
Ok, fedora.
Is there anything that seems wrong/related in the output of:
`./non-makepkg-build.sh --deps64`
or
`./non-makepkg-build.sh --deps32`
?

**Comment by nutta-git** [comment]
```
configure: libhal 64-bit development files not found, no legacy dynamic device support.
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: libcapi20 64-bit development files not found, ISDN won't be supported.
```

**Comment by Tk-Glitch** [comment]
Seems fine

**Comment by nutta-git** [comment]
> So I tried to reinstall the 32bit libraries from: https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies
> and this resulted in this:
> # `Dependencies resolved.
> # Package Architecture Version Repository Size
> 
> ```
> Installing:
>  gcc-c++               i686         10.0.1-0.11.fc32         fedora         11 M
>  gnutls-devel          i686         3.6.14-2.fc32            updates       2.1 M
> Installing dependencies:
>  gnutls-c++            i686         3.6.14-2.fc32            updates        30 k
>  gnutls-dane           i686         3.6.14-2.fc32            updates        33 k
> Downgrading:
>  cpp                   x86_64       10.0.1-0.11.fc32         fedora        9.4 M
>  gcc                   x86_64       10.0.1-0.11.fc32         fedora         30 M
>  gcc-c++               x86_64       10.0.1-0.11.fc32         fedora         11 M
>  gcc-gdb-plugin        x86_64       10.0.1-0.11.fc32         fedora        125 k
>  libgomp               i686         10.0.1-0.11.fc32         fedora        254 k
>  libgomp               x86_64       10.0.1-0.11.fc32         fedora        246 k
>  libstdc++             i686         10.0.1-0.11.fc32         fedora        657 k
>  libstdc++             x86_64       10.0.1-0.11.fc32         fedora        613 k
>  libstdc++-devel       i686         10.0.1-0.11.fc32         fedora        2.0 M
>  libstdc++-devel       x86_64       10.0.1-0.11.fc32         fedora        2.0 M
> ```
> 
> Transaction Summary
> `

Tried to reinstall missing libraries from  https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies to see if i was missing something. Which prompted me to Upgrade 
` gcc-c++               i686         10.0.1-0.11.fc32         fedora         11 M`
`gnutls-devel          i686         3.6.14-2.fc32            updates       2.1 M`

But in doing this upgrade I had to downgrade: 
```
 cpp                   x86_64       10.0.1-0.11.fc32         fedora        9.4 M
 gcc                   x86_64       10.0.1-0.11.fc32         fedora         30 M
 gcc-c++               x86_64       10.0.1-0.11.fc32         fedora         11 M
 gcc-gdb-plugin        x86_64       10.0.1-0.11.fc32         fedora        125 k
 libgomp               i686         10.0.1-0.11.fc32         fedora        254 k
 libgomp               x86_64       10.0.1-0.11.fc32         fedora        246 k
 libstdc++             i686         10.0.1-0.11.fc32         fedora        657 k
 libstdc++             x86_64       10.0.1-0.11.fc32         fedora        613 k
 libstdc++-devel       i686         10.0.1-0.11.fc32         fedora        2.0 M
 libstdc++-devel       x86_64       10.0.1-0.11.fc32         fedora        2.0 M

```

**Comment by Tk-Glitch** [comment]
Can you have both gnutls-devel i686 and x86_64 installed at the same time?

**Comment by nutta-git** [comment]
Yes

**Comment by Tk-Glitch** [comment]
Ok, good. I asked due to the output of `dnf list installed gnutls*` missing the i686 package in https://github.com/Frogging-Family/wine-tkg-git/issues/67#issuecomment-647513041.

**Comment by nutta-git** [comment]
GOOD NEWS 
Recompiled Proton and now it works, 
but I do wanna test again with the previous upgrade reverted.

**Comment by Tk-Glitch** [comment]
Good!
I cannot reproduce the issue on Arch. Your results seem to point to either a weirdness that happened to your OS or a Fedora issue. If things are working again with those changes reverted I guess it's the former 🐸

**Comment by nutta-git** [comment]
Thank you TKG!

**Comment by nutta-git** [comment]
So I believe the problem was caused by `gcc-c++`, 
Upgrading this package removed the 32 version of gnutls. 

Command `dnf upgrade --best --allowerasing`
replaced the misbehaving` gcc-c++` with a different version while not removing the gnutls packages

**Comment by Tk-Glitch** [comment]
Interesting quirk. Slightly annoying for people building on Fedora :/
At least you now know what's going on 😃 
You're welcome!
