### ISSUE TITLE
New Hotfixes Failing (Or: How long should we wait before reporting?)

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#68]
So I know this is *almost* always a matter of timing and the build will succeed shortly after, but since that's not always the case, mainly I'm trying to figure out how long we should wait before reporting a failed patch/hotfix application. That way we can avoid bugging you with something that's going to work in 15 minutes/an hour/what have you. 

Right now, the current hotfix (which it seems you just pushed recently) is failing:

```
 ==> WARNING: Hotfix: Upstream commits 01150d7 to e854ea3 broke esync patchset (which has been disabled in staging as a result) leading to fsync getting broken as well.
Wanna bring back esync/fsync ?
> N/y : y
 -> ## Applying reverting hotfix for wine-staging: 06877e55b1100cc49d3726e9a70f31c4dfbe66f8-27.mystagingrevert
 ==> ERROR: Patch application has failed. The error was logged to /home/matt/dev/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> ## Applying hotfix for wine-staging: 934a09585a15e8491e422b43624ffe632b02bd3c-3.mystagingpatch
 -> ## Applying hotfix for wine-staging: ntdll-ForceBottomUpAlloc-97fbe3f.mystagingpatch
 -> Applying use_clock_monotonic.patch
 -> Applying plasma_systray_fix.patch
 -> Applying FS_bypass_compositor.patch
 -> Applying staging-44d1a45-localreverts.patch
 -> Applying childwindow.patch
 -> Applying steam.patch
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches...
 ==> ERROR: Patch application has failed. The error was logged to /home/matt/dev/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

When I hit `n` at the prompt to bring back esync, it says:

```
 ==> WARNING: Hotfix: Upstream commits 01150d7 to e854ea3 broke esync patchset (which has been disabled in staging as a result) leading to fsync getting broken as well.
Wanna bring back esync/fsync ?
> N/y : n
fatal: Not a valid commit name 683583faf2f4b00874f702429393b127aca8eef4
 ==> WARNING: You have refused hotfixes. Due to regressions and refactoring upstream, the following features have been forcefully disabled: Esync, Fsync, Proton-rawinput, LAA, Protonify, native/builtin msvcrt, clock monotonic. If you want any of those features back, you need to accept all currently available hotfixes.
Press enter to continue anyway...^C -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

Just in case that can provide some information

Also, I didn't want to file a separate issue for this, but would it be possible to change the pacman command in `wine-tkg-git/wine-tkg-scripts/deps` to `pacman -S --needed amillionpackages` instead of having to reinstall them every time? I have an 8-core 3800X overclocked to 4.4GHz on all cores and it still takes a good few minutes to get through all that reinstallation without the `--needed` flag, and I have everything locally in the pacman cache so I'm not even having to download anything. Just a suggestion? If there's some reason why the flag isn't there, that's fine. Better to have to wait a few minutes than not be able to use this repo at all. 

Oh, and yes I did try building proton in a fresh git clone, same error

**Comment by robzombie91** [comment]
Try using an older staging version or try deleting the current pkgbuild folder and just cloning the wint-tkg-git one

**Comment by robzombie91** [comment]
the last one that worked for me was df2fd22

**Comment by gardotd426** [comment]
@robzombie91 like I said, I tried this in a fresh `git clone` elsewhere on the machine (after the usual one failed). The fresh one had no changes to the config file or anything, and grabbed a fresh source, and still failed. 

If I have to, I'll try df2fd22, but I'm sure Etienne would still like to be aware if something's broken.

**Comment by robzombie91** [comment]
Yeah usually i see them fixed a couple hours after an its released but its still early morning for some people

**Comment by gardotd426** [comment]
Right, that's what I said in the report. Which is why I also asked how long we should wait (which I also said was the other main reason I filed this issue in the first place). 

Like I said, I'm not too terribly concerned with not being able to build a proton build right this second, or even whether this will get fixed (I know it will), but sometimes there are actual problems and patches have to get fixed/removed, so that's why I asked what a good time to wait would be so in the future, we all know to wait at least however long with patch/hotfix issues before reporting them, y'know?

**Comment by gardotd426** [comment]
Setting `df2fd22` in the `_plain_version` field had no effect. But like I said, I'll just wait, no big deal.

**Comment by robzombie91** [comment]
staging, not plain version

**Comment by gardotd426** [comment]
Yep, just figured that out lol

**Comment by Tk-Glitch** [comment]
> So I know this is almost always a matter of timing

Indeed. I'll push the update asap.

**Comment by Tk-Glitch** [comment]
It should now be fixed with https://github.com/Frogging-Family/wine-tkg-git/compare/56656dcbbf1d4d91e80d7465c18ee8711ae42b20...3ec8970a0e709bcca82aad1d81c02362387e2b94
