### ISSUE TITLE
[Proton-tkg] Offcial (default) Batman Arkham Asylum Launcher Doesn't Run

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#684]
[steam-35140.log](https://github.com/Frogging-Family/wine-tkg-git/files/7967700/steam-35140.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7967591/proton-tkg.cfg.zip)

Proton version: `proton_tkg_7.0.r1.g95bf6698`

`protontricks 35140 -q mdx d3dcompiler_43 d3dcompiler_47 physx win10`

Attempting to run the default launcher for the game with the minimum amount of protontricks flags to play the game in a reportedly playable state (on ProtonDB) (and without explicitly using D9VK) doesn't permit it to run.
(I also added d3dcompiler_43 and 47 but that shouldn't have made a difference...)

EDIT: Adding `d3dx9` to force with Protontricks with D9VK doesn't fix it either (The Proton github page for the game also has some who suggested this); the game is listed as a regression upstream

**Comment by Tk-Glitch** [comment]
Can't reproduce that either. I just installed the game and ran it with `proton_tkg_7.0.r1.g95bf6698`. Launcher works. Game needs native d3dx9_43.dll but will launch with it installed.
Steam client will install physx and proton-tkg is already set to win10 by default btw.

![Screenshot_20220201_151824](https://user-images.githubusercontent.com/741977/151987558-8a3bf4b2-6944-409a-bf6e-10c4719ebe20.png)
