### ISSUE TITLE
[Proton-tkg] Batman Arkham City Doesn't Run

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#685]
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/7967591/proton-tkg.cfg.zip)
[steam-200260.log](https://github.com/Frogging-Family/wine-tkg-git/files/7968217/steam-200260.log)
[steam-200260 (pc settings configure option).log](https://github.com/Frogging-Family/wine-tkg-git/files/7968219/steam-200260.pc.settings.configure.option.log)

Proton version: `proton_tkg_7.0.r1.g95bf6698`

`protontricks -q mdx d3dcompiler_43 d3dcompiler_47 d3dx9 physx`

![Screenshot_20220130_225732](https://user-images.githubusercontent.com/28468662/151741211-245d414a-4e1e-46a1-bfba-938ae6a8367e.png)

**Comment by Tk-Glitch** [comment]
Game is running on my end just by installing in Steam client. No protontricks involved. I'm hitting a mesa issue that renders red garbage as an overlay but that's a different issue altogether.
