### ISSUE TITLE
[Wine-TKG] Fails to build, 30-win32-ailiases.conf missing.

### ISSUE THREAD

**Issue by Orangian** [Frogging-Family/wine-tkg-git#689]
Hi,
When building wine-tkg, the following error occurs almost immediately. The strange thing is, though, proton-tkg builds fine, other than the issue mentioned in #688. Here is the log:
 
```
==> Making package: wine-tkg-git-zen2 0-326 (Wed 02 Feb 2022 07:08:27 AM EST)

==> Checking runtime dependencies...

==> Checking buildtime dependencies...

==> Retrieving sources...

  -> Updating wine-mirror-git git repo...

Fetching origin

  -> Updating wine-staging-git git repo...

Fetching origin

==> ERROR: 30-win32-aliases.conf was not found in the build directory and is not a URL.

  -> Removed BIG_UGLY_FROGMINER - Ribbit

  -> Removed Proton-tkg token - Valve Ribbit

  -> exit cleanup done

```

**Comment by Orangian** [comment]
Issue lasted from 02/01 to 02/02 and resolved itself.

**Comment by Orangian** [comment]
Whoops, appears I closed it too early. Builds are failing again with

```
==> Retrieving sources...
  -> Updating wine-mirror-git git repo...
Fetching origin
From https://github.com/wine-mirror/wine
 + 9c5d105aa06...e13d5c0d29b refs/pull/16/merge -> refs/pull/16/merge  (forced update)
  -> Updating wine-staging-git git repo...
Fetching origin
==> ERROR: 30-win32-aliases.conf was not found in the build directory and is not a URL.
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```

**Comment by Iglu47** [comment]
last time I saw a problem with `30-win32-aliases.conf` here https://github.com/Frogging-Family/wine-tkg-git/issues/602
but it looks like now I have no idea what it is related to, are there still dependencies associated with symbolic links or local files permissions?
also it somehow doesn't interfere with automatic builds https://github.com/Frogging-Family/wine-tkg-git/runs/5238750247?check_suite_focus=true#step:4:1536

**Comment by Orangian** [comment]
Thanks for showing me that action, the issues could be related to the way I automated it. Will look at the official way to automate it and the way I did to see if theres a disparity. Another layer adding to this is the fact that this is running in a systemd nspawnd container under Debian, so that adds a lot more ways this could go wrong.

**Comment by Tk-Glitch** [comment]
That part is responsible for making a copy of the file in the root dir so makepkg can link it to the build dir:
```
if [ ! -e "$_where"/BIG_UGLY_FROGMINER ]; then
  find "$_where"/wine-tkg-patches -type f -not -path "*hotfixes*" -exec cp -n {} "$_where" \; && # copy patches inside the PKGBUILD's dir to preserve makepkg sourcing and md5sum checking
  cp "$_where"/wine-tkg-userpatches/*.my* "$_where" 2>/dev/null # copy userpatches inside the PKGBUILD's dir
fi
```
It seems to be the breaking point on your end as the file just doesn't get copied for some reason.

**Comment by Orangian** [comment]
This could be the reason why, as I am creating a file called BIG_UGLY_FROGMINER in order to suppress the user prompts in order to automate the process (I may be wrong, I wrote the scripts to automate this quite a while ago, so I could be misremembering.) I shall investigate further.

**Comment by Tk-Glitch** [comment]
Oh, indeed, create that file will break stuff.

You can skip the prompts with:
```
_NOINITIALPROMPT="true"
_user_patches_no_confirm="true"
_hotfixes_no_confirm="true"
```

**Comment by Orangian** [comment]
Thanks for that! Removed the BIG_UGLY_FROGMINER bit, and set the flags which you stated (which I had not noticed before) and the automation works perfectly! Thank you for your help yet again!

**Comment by Tk-Glitch** [comment]
You helped me to help you! :wink:
