### ISSUE TITLE
Patch application has failed

### ISSUE THREAD

**Issue by colourfuloctopus** [Frogging-Family/wine-tkg-git#690]
>WARNING: Hotfix: Staging's mfplat support patchset is currently disabled, breaking video playback in various games
  Restore it?
> N/y : ==> WARNING: Hotfix: Fix for Riot Client updates
==> WARNING: Hotfix: Revert Quartz changes breaking Tokyo Xanadu Xe+
==> WARNING: Hotfix: Bcrypt fixes for RDR2
==> WARNING: Hotfix: Prefer external FAudio for WMA playback
==> WARNING: Hotfix: Protonify staging syscall emu
==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
  -> Hotfixing...
  -> ## Applying hotfix for wine-staging: protonify_stg_syscall_emu-009.mystagingpatch
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches... 
     Staging overrides used, if any: -W xactengine3_7-callbacks
  -> Applying use_clock_monotonic-staging.patch
  -> Applying fsync-unix-staging.patch
  -> Applying fsync_futex_waitv.patch
  -> Applying LAA-unix-staging.patch
  -> Applying rdr2.patch
  -> Applying josh-flat-theme.patch
  -> ## Applying reverting hotfix for plain-wine: f0cd33c.myrevert
==> ERROR: Patch application has failed. ``

I selected N when prompted to restore the staging's mfplat support patchset. Log https://pastebin.com/PeLjmEpM.

**Comment by xraech** [comment]
not a proper solution, but if you want to "just work" for now, you can use a few days older staging build, i.e "ecf05ee" would work just fine

**Comment by Tk-Glitch** [comment]
It'll need a bit more testing but fix on its way

**Comment by Tk-Glitch** [comment]
It was fixed in some way before, but it's now properly fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/cf22508d1590df3a02edb49ea42127aad2b46651
