### ISSUE TITLE
Wineserver crashes on start after commit 5b56bad on mainline

### ISSUE THREAD

**Issue by e666666** [Frogging-Family/wine-tkg-git#691]
With the default configuration and new wineprefix, wineserver always crash on startup, making the build completely unusable:
```
wineserver crashed, please enable coredumps (ulimit -c unlimited) and restart.
Backtrace:
#0  0x000000000040e40d in free_kernel_objects ()
#1  0x000000000042248b in release_object ()
#2  0x0000000000437840 in call_req_handler ()
#3  0x0000000000441948 in thread_poll_event ()
#4  0x00000000004134e3 in main_loop_epoll ()
#5  0x000000000041373e in main_loop ()
#6  0x0000000000403b34 in main ()
```

It also happens with staging disabled.

With help from git bisect, it turns out the crash happens after commit https://github.com/wine-mirror/wine/commit/5b56bad50b85acb05244894990053f8b0de2e458

Both I and `Karimrir#2###` tested latest vanilla Wine and got no crash, which means that one of the wine-tkg-git patch is causing the crash.

**Comment by karimrir1** [comment]
Yes it is me, I am going to try wine-tkg now.

**Comment by StarterX4** [comment]
The last commit and all the latest Wine Arch Linux CI actions' builds up to 425 are unusable.
The last working commit is #Frogging-Family/wine-tkg-git@2b43eac

In my case, the _explorer.exe_ process becomes zombie and I have to kill all the wine processes.

The output I get:
r12.gb5193cb7 (actions 430)
![image](https://user-images.githubusercontent.com/21229864/153716429-d224a6cc-e818-4648-9075-be50c3104bfd.png)

r13.gb9f7ec5c (actions 431)
![image](https://user-images.githubusercontent.com/21229864/153716546-1d6d9c75-548a-4c91-b946-4d7ce51a21bd.png)

**Comment by MalonnBethesda** [comment]
I crash too.  No application I use with Wine will launch with either Wine-dev 7.1 or 7.2.  Wine 7.0 and earlier are fine.
```wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG  is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
wineserver crashed, please enable coredumps (ulimit -c unlimited) and restart.```
