### ISSUE TITLE
[Wine-TKG] Vulkan child window patch not applying

### ISSUE THREAD

**Issue by Devorlon** [Frogging-Family/wine-tkg-git#698]
I recently built wine-tkg-git and starting CEMU I get the error:

`Error when initializing Vulkan renderer: Cannot create a Win32 Vulkan surface: -9`

I also tried the nightly build and I uncommented the patch in the PKGBUILD directly, after building again to test.

**Comment by Devorlon** [comment]
https://gist.github.com/Devorlon/386d039e795c88a929f94ebf471bfb81

Gist with logs

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/b192efc506b6d3c02a0a8154fa20521bbc3bf0ce

**Comment by Devorlon** [comment]
Danke
