### ISSUE TITLE
[Wine-TKG] Fsync can not be enabled

### ISSUE THREAD

**Issue by das-bub** [Frogging-Family/wine-tkg-git#699]
Up to date Arch Linux with kernel version `5.16.10.zen1-1` and current wine-tkg-git master with default config.

Setting the usual environment variables `WINEESYNC=1`, `WINEFSYNC=1` and `WINEFSYNC_FUTEX2=1` only ever reports `esync: up and running.`

If I disable esync `WINEESYNC=0` nothing at all is reported and performance tanks.

Is it just me, or can fsync currently not be enabled?

**Comment by rizzini** [comment]
You need to enable `_futex_waitv="false"` at the [customization.cfg](https://github.com/Frogging-Family/linux-tkg/blob/5f36c6353e578342b24dc7823e66f00cb3f64c38/customization.cfg#L164) before compiling the Kernel.

**Comment by das-bub** [comment]
I'm sorry, but I don't quite understand.

The config clearly states:
"**Requires 5.16 kernel** or kernel with backported patches"

As I said above I am on `5.16.10.zen1-1`, which should be sufficient.
The zen kernel had the futex patches long before 5.16, so it used to work fine just a few months ago.

Does it really only work with `linux-tkg `now?
If that is the case, the config really should be updated to say as much.

**Comment by rizzini** [comment]
> Does it really only work with linux-tkg now?
Yes, it does:

- [Vanilla Kernel: ](https://imgur.com/a/awBobWB)
- [linux-tkg-git](https://imgur.com/a/JtXPe9E)

> As I said above I am on 5.16.10.zen1-1, which should be sufficient.

I misread your comment. I thought you also tested with linux-tkg-git with the default config, so I explained you need to enable fsync before compiling it.

It seems you need to check with Zen what's going on.

**Comment by rizzini** [comment]
> Does it really only work with linux-tkg now?

No, not just:

- [linux-tkg-git](https://imgur.com/a/NMcVGeC)
- [Kernel from Arch repository](https://imgur.com/a/KnKXMO0)

> As I said above I am on 5.16.10.zen1-1, which should be sufficient.

I misread your comment. I thought you also tested with **linux**-tkg-git with the default config, so I explained you need to enable fsync before compiling it.

It seems you need to check with Zen what's going on, @das-bub.

**Comment by Iglu47** [comment]
For kernel-tkg 5.16 `_futex_waitv` can be safely ignored, since for kernel 5.16, backported patches are not required.

atm wine-tkg-git doesn't build for me with the settings from git. What settings did you use? try specifying to use wine-staging 7.2. This will probably help temporarily.

**Comment by das-bub** [comment]
@rizzini
OK, I'm going to try the plain arch kernel first to see if its a zen only issue.

@Iglu47
I've used [this config](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg) with only two changes `_PKGNAME_OVERRIDE="none"` and `_nvidia_hate="true"`.
Builds and runs fine, apart from the broken fsync that is.
Also, unless the default `_use_staging="true"` toggle does nothing, it's wine-staging 7.2 already.

**Comment by das-bub** [comment]
I've tried the plain arch kernel and the problem is unfortunately the same.
Since `wine-tkg` received some updates a few hours ago I've recompiled that too, sadly version 7.2.r9.gbcfed21e-326 made no difference either.

I've also installed `bpftrace`, which doesn't show anything apart from:
`Attaching 1 probe...`
So, safe to say that it's definitely not working, right?

I guess all that's left to try is compiling `linux-tkg`.

**Comment by Iglu47** [comment]
> it's wine-staging 7.2 already.

Strange, should work exactly on this tag. It will be useful to show `prepare.log` at least.

**Comment by Tk-Glitch** [comment]
It's working fine on my end with a tkg kernel installed. I guess I'll check with Arch's again.

**Comment by das-bub** [comment]
Well, I guess I'm the odd one out.
I've compiled linux-tkg version 5.16.11-246-tkg-cfs just now but unfortunately fsync still doesn't work.

I've recompiled wine-tkg-git too, made no difference either.
Here is the [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8128098/prepare.log).

Anything else I can try?

**Comment by rizzini** [comment]
Oh, man.. It must be something in your environment.

**Comment by Tk-Glitch** [comment]
Your prepare.log looks fine as well.. That's an interesting issue to say the least.

**Comment by Iglu47** [comment]
> Oh, man.. It must be something in your environment.

@das-bub could you please open the `Wine configuration` window (looks like this <https://wiki.winehq.org/File:Staging-winecfg.png> the same way you experienced WINEFSYNC and don't close it, then separately open the terminal and give the output from next command while `Wine configuration` window is showing.

```bash
ps e -ww $(pgrep winecfg.exe) | tr ' ' '\n' | grep WINEFSYNC
```
this will help to find out if there are unrecorded settings in environment variables that you can not guess about

**Comment by das-bub** [comment]
Sorry, I've been somewhat preoccupied with current events.

I've just recompiled everything once more, still no change unfortunately.

@Iglu47
Here is the output of the command:
```
WINEFSYNC=1
WINEFSYNC=1
```

Commandline stills only says `esync: up and running` though.

I've also ran `cat /proc/kallsyms | grep futex_waitv` which prints this:
```
0000000000000000 T __ia32_sys_futex_waitv
0000000000000000 T __x64_sys_futex_waitv
0000000000000000 d event_exit__futex_waitv
0000000000000000 d event_enter__futex_waitv
0000000000000000 d __syscall_meta__futex_waitv
0000000000000000 d args__futex_waitv
0000000000000000 d types__futex_waitv
0000000000000000 d __event_exit__futex_waitv
0000000000000000 d __event_enter__futex_waitv
0000000000000000 d __p_syscall_meta__futex_waitv
0000000000000000 d _eil_addr___ia32_sys_futex_waitv
0000000000000000 d _eil_addr___x64_sys_futex_waitv
```
So the syscall itself is definitely available.

Is it maybe possible, that the syscall availability check is broken somehow?

**Comment by Iglu47** [comment]
> So the syscall itself is definitely available.
> 
> Is it maybe possible, that the syscall availability check is broken somehow?

about verification: if possible just check if fsync works with official proton7.0 on this machine (this is a public build for which the kernel patch was conceived and previously required.)

**Comment by das-bub** [comment]
Nope, proton won't work either.
At this point I think I should just be happy that at least esync is working and just give up.

**Comment by Tk-Glitch** [comment]
So definitely an issue with your setup, somewhere. Fun.

**Comment by das-bub** [comment]
So, after leaving it be for two months, I actually got it to work... by doing nothing at all.
Apart from all the system updates in between, it is the exact same setup as it was on March 7th.

So, whatever it was, it appears to be fixed now :smiley:
