### ISSUE TITLE
 [Wine-TKG] Among Us crashes on start up

### ISSUE THREAD

**Issue by alou-S** [Frogging-Family/wine-tkg-git#709]
#### System Information
Kernel : `5.16.11-246-tkg-cacule`
Wine Version : `wine-tkg-staging-fsync-git 7.3.r0.gaf985310-326`

#### Bug Report
Among Us crashes on startup on `wine-tkg-staging-fsync 7.3` but works just fine on `wine-staging 7.3`

Backtrace : [backtrace.txt](https://github.com/Frogging-Family/wine-tkg-git/files/8158685/backtrace.txt)

**Comment by Tk-Glitch** [comment]
I can reproduce the issue with both mainline and staging 7.3, both clean of any patch. 7.2 works fine. Somehow the wine-staging 7.3 package from Arch repo works. I'll investigate.

**Comment by Tk-Glitch** [comment]
Bisected the culprit as being `7b233f3032e4850b0f387faef4aae5ed6d5175de` (`ntdll: Map explicitly loaded apiset dlls to their target library.`) from mainline. It reverts cleanly so let's do that for now.

**Comment by Riesi** [comment]
Did you report the regression on WineHQ already?
I couldnt find any thing referencing this hash on WineHQ.
