### ISSUE TITLE
Fix for Riot Client updates conflict on latest Wine

### ISSUE THREAD

**Issue by e666666** [Frogging-Family/wine-tkg-git#711]
```
 ==> WARNING: Hotfix: Fix for Riot Client updates
(Trimmed)
 -> Hotfixing...
(Trimmed)
 -> ## Applying hotfix for plain-wine: Return_nt_filename_and_resolve_DOS_drive_path.mypatch
 ==> ERROR: Patch application has failed. The error was logged to /sources/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
```
For the record, I got this error after applying workaround from https://github.com/Frogging-Family/wine-tkg-git/issues/710
Workaround: Remove line 703~707 from wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer

**Comment by Tk-Glitch** [comment]
fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/fc24fb7cea8ad86ddb28440728c7c72592a4aa7a
