### ISSUE TITLE
[Wine-TKG] FSync causes CPU to be 100% used. (COD: World at War and other games)

### ISSUE THREAD

**Issue by alou-S** [Frogging-Family/wine-tkg-git#712]
### System Info
CPU: Intel Core i3 540 (4) @ 3.067GHz
Kernel: `5.16.11-246-tkg-cacule`
Wine: `wine-tkg-staging-fsync-git 7.3.r5.ga79a08a6-327`

### Problem Description 
Enabling FSync causes CPU usage to be unusually high for no reason. Same behavior not seen in ESync.

CPU usage in COD WaW when not using Fsync (in main menu) : 35%
CPU usage in COD Waw when using Fsync  (in main menu) : 270%

This is basically causes my CPU to be fully utilized and turning it into a space heater whenever I play with FSync enabled. And since the game is still in the main menu the said utilization is unexplained (It continues as long as the game is running)

Similar behavior can be seen in other games I have tested being : Mirrors Edge and Among Us, but unlike World at War their usage jumps from 30% or so to 100% (probably eating up an entire core) (Again only tested the 30% in main menu)

### Other Info
Another note is that this issue can be severely effecting battery life on devices like the Steam Deck if the issue is further upstream.

**Comment by Tk-Glitch** [comment]
That's new. I'll check that out on my main machine. I haven't noticed any perf change nor battery runtime issues on the Deck, but that's also with the Deck's kernel which is currently 5.13 based.

**Comment by Kron4ek** [comment]
After more investigation i found out that wine-tkg compiled on Arch Linux (with gcc and mingw 11.2.0) has this issue with FSYNC, but wine-tkg compiled on Ubuntu 18.04 (with gcc 9.4.0 and mingw 9.3.0) does not have it. In both case the source code is the same and CFLAGS too. So it seems like a bug in newer versions of gcc or something.

**Comment by SveSop** [comment]
Is this an "all" apps thing, or so far just WoW/COD that has this problem? 

Could you check if there is any differences with Unigine Superposition or Valley or one of those benches that can show a fps difference and everyone can download? I am intrigued enough to compile wine-tkg on Ubuntu 20.04 w/gcc-11.1 and MingW 10.3 to see if it is gcc related.

**Comment by Kron4ek** [comment]
@SveSop I would say this is an all 32-bit apps thing. I can reproduce the issue in Unigine Valley (32-bit), but can't in Superposition (64-bit). Also the issue is reproducible in 32-bit teeworlds, but not in 64-bit teeworlds.

In Unigine Valley i get 150% CPU usage with Esync and 300% with Fsync. In teeworlds 10% with Esync and 80% with Fsync.

**Comment by Tk-Glitch** [comment]
On the Arch side, MinGW hasn't moved for a while, but GCC was updated pretty recently: https://github.com/archlinux/svntogit-packages/commits/packages/gcc/trunk

**Comment by SveSop** [comment]
@Kron4ek 
Weird. I have not gotten around to testing wine-tkg yet tho, but i have my own custom wine version based on a various mix of patches picked from tkg and ge ++, and none of my cores go > 30% load with fsync or esync when running Unigine Valley.
This is with Ubuntu 20.04 using gcc-11.1 and mingw-w64-10.3. I had random peaks total % of 110-115, but i would say average 85-90% usage. (8700K 6core/12thread)

If you want i could test wine-tkg, but i assume we should have exactly the same patches.. so either i need your .cfg files or you could zip down the actual sourcetree for me after tkg patch scripts are done? I did try wine-7.3 on my custom wine, but i had some random and horrible crashing issues with DAZ Studio4 using 7.3, so i ended up going back to 7.2. I am not sure if that is a upstream issue, or if it is a fsync/waitv issue (or something else of the added patches i use)... but it was not a fshack issue :smile: 

I use these flags when i compile for myself locally:
`CPPFLAGS='-O2 -march=native -msse2avx -ftree-vectorize -Wall -Wdate-time -D_FORTIFY_SOURCE=2' CFLAGS='-O2 -march=native -msse2avx -ftree-vectorize -Wall -Wformat -Werror=format-security' CROSSCFLAGS='-O2 -mavx2 -msse2avx -ftree-vectorize -Wall -gdwarf-2 -gstrict-dwarf' LDFLAGS='-march=native -msse2avx -Wl,-O2,--sort-common,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro' CROSSLDFLAGS='-mavx2 -msse2avx -Wl,-O2,--sort-common,--as-needed`

**Comment by Kron4ek** [comment]
@SveSop The generated sources which i use are [here](https://github.com/Kron4ek/wine-tkg). This is a really weird issue since i can only reproduce it with manually compiled builds, i can't reproduce it with the builds from Github Actions, despite they are compiled on Arch Linux too. No idea what the heck is going on.

My CFLAGS and CROSSCFLAGS: `-march=x86-64 -msse3 -mfpmath=sse -O2 -ftree-vectorize`. But i also tried ` -O2 -ftree-vectorize` and that didn't change anything.

**Comment by SveSop** [comment]
Hmm.. Not really seeing an extreme difference for me here tho.

Do you have any threads going > 90% when running? Mostly i get around <30% on thread 0+1 and some usage on other threads, with some rare 60+ peaks. Was just watching htop.

Running a benchmark yielded these results:
```
TKG: Fps: 126.2 - Score 5281 (Min:50.4/Max:213.2)
7-2(own): 125.8 - Score 5264 (Min:49.4/Max:212.6)
```
Mostly within margin of error i would say, although the tkg build was ahead :smile: 

I built the tkg source you linked above, with the flags i posted with Ubuntu 20.04 using a Docker image, as Ubuntu is increasingly being a shitty place to build sources with :disappointed:

**Comment by Kron4ek** [comment]
> Do you have any threads going > 90% when running?

No, haven't seen 90% or more, however i get around 80% on all my four threads when running Unigine Valley with Fsync opposed to 30-40% with Esync.

There is also a FPS difference, noticeable but not that big:
```
Esync: FPS: 124.0 Score: 5190 Min FPS: 37.4 Max FPS: 206.2
Fsync: FPS: 105.8 Score: 4427 Min FPS: 33.6 Max FPS: 190.7
```

**Comment by SveSop** [comment]
`TKG(Esync): Fps: 126.4 - Score 5288 (Min: 36.0/Max: 213.5)`
I would say "no change" for me between esync/fsync.
