### ISSUE TITLE
Cannot Launch Any Game When Using Proton Tkg Git Builds

### ISSUE THREAD

**Issue by Lumenor** [Frogging-Family/wine-tkg-git#714]
Official builds of Proton work fine it seems (the experimental build of Proton worked just fine on Batman Arkham Origins where proton-tkg-git did not). I have tried deleting the prefix, using the preferred method of using proton-tkg.sh, updating Nvidia drivers, updating the Linux kernel, as well as reinstalling the entire OS multiple times. I am on Artix Linux, a rolling release Arch-based distro. I have installed the dependencies (I think) from the PKGBUILD file. It used to work, and now it doesn't. Here is the log:
[steam.log](https://github.com/Frogging-Family/wine-tkg-git/files/8211408/steam.log)

Interestingly, once the official build of Proton has been used on the game, it seems that proton-tkg-git works for whatever reason. However its effectiveness as a fix is dubious as well as its performance (I think).

Edit: Proton GE Custom works just fine.

**Comment by Tk-Glitch** [comment]
It seems to be related to some nvidia files handling from experimental that I synced with kinda recently. The issue doesn't exist on my AMD system so I didn't notice. It should be an easy fix.

**Comment by Lumenor** [comment]
> It seems to be related to some nvidia files handling from experimental that I synced with kinda recently. The issue doesn't exist on my AMD system so I didn't notice. It should be an easy fix.

My thanks! Looking forward to it, and I also want to say I appreciate your work on this project. Gaming on Linux has never seemed so optimized, and that has of course helped not only me but I assume other people in not only using better computing in their day-to-day lives while keeping the recreation of playable games. I really do appreciate it. At any rate, again, I look forward to the fix, lol.
