### ISSUE TITLE
valve_proton_fullscreen_hack-staging.patch failed to be applied

### ISSUE THREAD

**Issue by sr-tream** [Frogging-Family/wine-tkg-git#717]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8314927/prepare.log)
[customization.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/8314935/customization.cfg.txt)

Wine-staging  7.4. Disabling or enabling other patches has no effect.

With `_proton_fs_hack="false"` and without depended patches all work fine

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/3e30cc131432a4f4f4caeeab2f39680cc41572ae
