### ISSUE TITLE
[Bug] Audio Working with k-lite codec mega pack (update if issues arise (P4G)

### ISSUE THREAD

**Issue by robzombie91** [Frogging-Family/wine-tkg-git#72]
[crash picure](https://i.imgur.com/ikdu4GF.jpg)

**Comment by robzombie91** [comment]
[output.log](https://github.com/Frogging-Family/wine-tkg-git/files/4858332/output.log)

**Comment by robzombie91** [comment]
The suspect was specialk's patch files for persona 4 golden

**Comment by robzombie91** [comment]
[output.log](https://github.com/Frogging-Family/wine-tkg-git/files/4861249/output.log)

**Comment by robzombie91** [comment]
for audio issue log

**Comment by Tk-Glitch** [comment]
Did you figure it out?

**Comment by robzombie91** [comment]
No, i just closed it because you said i should probably report it to the winehq or proton repo?

**Comment by Tk-Glitch** [comment]
I'm pretty sure I also said "if you can reproduce it on a clean mainline or staging build" 🐸 The current situation is quite frustrating and annoying on my end considering the "core" build I'm offering shortcuts to has a huge pile of reverts that won't be valid for testing/reporting an upstream issue. In case you can't reproduce the issue on a clean mainline or staging build, please reopen 😉

**Comment by robzombie91** [comment]
atm by biggest issue wont be an issue anymore since a denuvoless exe was just released

**Comment by robzombie91** [comment]
also according to the proton issue tracker, it uses xaudio2

**Comment by robzombie91** [comment]
https://github.com/ValveSoftware/Proton/issues/3982

**Comment by robzombie91** [comment]
Ok, i got the audio to work with xact and xact64, but the only way for me to bypass the issue with the fmv's is to install lavfilters which plays the video but does not have any audio (fmvs are important to this game due to them being integral to the story)

**Comment by robzombie91** [comment]
First cinematic works with audio when lavfilters is removed and k-lite mega pack is installed, will post if any other issues arrise
