### ISSUE TITLE
Cyberpunk 2077 doesn't work with Wine-7.5

### ISSUE THREAD

**Issue by Freeman310** [Frogging-Family/wine-tkg-git#722]
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 7.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0128:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0134:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000E08FE10
0128:fixme:win:DisableProcessWindowsGhosting : stub
0128:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
0128:fixme:toolhelp:Heap32ListFirst : stub
017c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000000032BAFE10
0128:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
0128:fixme:wbemprox:client_security_SetBlanket 00000002419C1DE0, 0000000000377350, 10, 0, (null), 3, 3, 0000000000000000, 0
0128:fixme:wbemprox:client_security_Release 00000002419C1DE0
0128:fixme:dxgi:dxgi_factory_EnumAdapterByGpuPreference Ignoring GPU preference 0x2.
0128:fixme:dxgi:dxgi_factory_EnumAdapterByGpuPreference Ignoring GPU preference 0x2.
0128:fixme:dxgi:dxgi_output_GetDesc1 iface 000000000054C350, desc 000000000021DCE0 semi-stub!
0128:fixme:dxgi:dxgi_output_GetDesc1 iface 000000000054C3B0, desc 000000000021E290 semi-stub!
fixme:d3d12_device_CheckFeatureSupport: Unhandled feature 0x1e.
fixme:d3d12_device_CheckFeatureSupport: Unhandled feature 0x20.
0128:fixme:dxgi:dxgi_adapter_QueryVideoMemoryInfo Returning fake video memory info.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:vkd3d_create_null_srv: Unhandled view dimension 0x8.
fixme:d3d12_rtv_desc_create_rtv: NULL resource RTV not implemented.
fixme:d3d12_desc_create_sampler: Ignoring border color {0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00}.
fixme:d3d12_desc_create_sampler: Ignoring border color {0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00}.
0130:fixme:graphics:ShutdownBlockReasonCreate (000000000002006E, L"Generating error report"): stub
0130:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
wine: Unhandled exception 0x80000003 in thread 130 at address 0000000140005D32 (thread 0130), starting debugger...
01c4:fixme:imm:ImeSetActiveContext (0x4703d0, 1): stub
01c4:fixme:imm:ImmReleaseContext (00000000000100BC, 00000000004703D0): stub
01d0:fixme:imm:ImeSetActiveContext (0x4603d0, 0): stub
01d0:fixme:imm:ImmReleaseContext (0000000000040082, 00000000004603D0): stub
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01c4:fixme:dbghelp:dump_unwind_info couldn't read memory for UNWIND_INFO at 3be71d110

**Comment by Kron4ek** [comment]
It does not work with the builtin vkd3d, but works with [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton).

**Comment by Freeman310** [comment]
> Он не работает со встроенным vkd3d, но работает с [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton).

I use vkd3d-proton-tkg-git and vkd3d-proton together with wine-tkg-7.5. The interesting thing is that everything was fine in Wine-7.4.

**Comment by Kron4ek** [comment]
@Freeman310 According to your output, you are definitely using the builtin vkd3d, not vkd3d-proton. With vkd3d-proton there should be at least such strings:

```
00f8:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.6.0.
00f8:info:vkd3d_instance_init: vkd3d-proton - build: 3e5aab6fb3e18f8.
```

**Comment by Freeman310** [comment]
@Kron4ek Then tell me how to make vkd3d-proton work. I may be doing something wrong.

**Comment by Kron4ek** [comment]
Download the latest vkd3d-proton release from [here](https://github.com/HansKristian-Work/vkd3d-proton/releases), extract 64-bit d3d12.dll from the downloaded archive to your prefix/drive_c/windows/system32 directory (or to the directory where the game exe is), and then override d3d12 to "Native" in the "Libraries" tab in winecfg.

**Comment by Freeman310** [comment]
And that's how it turned out.
[tkg-log.log](https://github.com/Frogging-Family/wine-tkg-git/files/8403015/tkg-log.log)

**Comment by Kron4ek** [comment]
Unfortunately, i can't say why it crashes now. It works for me with wine-tkg 7.5 and vkd3d-proton. I suppose you use an AMD gpu, what Mesa version are you using?

**Comment by Freeman310** [comment]
@Kron4ek Mesa-tkg-git. And yes, I have an AMD gpu. But the game works fine with Wine 7.4 and Proton-GE 7.9.

**Comment by Kron4ek** [comment]
> But the game works fine with Wine 7.4 and Proton-GE 7.9.

With the same vkd3d-proton version?

To check if it is a tkg issue or an upstream issue, try regular Wine-Staging 7.4 and 7.5.

**Comment by Tk-Glitch** [comment]
> > It does not work with the builtin vkd3d, but works with [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton).
> 
> I use vkd3d-proton-tkg-git and vkd3d-proton together with wine-tkg-7.5. The interesting thing is that everything was fine in Wine-7.4.

If you're talking about the vkd3d-proton-git package, it's useless these days as vkd3d-proton now is standalone. You'll want to install it per-prefix in the same way as dxvk, and setting d3d12 as native.

**Comment by Tk-Glitch** [comment]
Just tested on proton-tkg 7.5.r2 and the game works just fine. So definitely an issue on your side. vkd3d used to be an external module of wine, but it's been merged recently. That's likely what you're experiencing. As said above, setting d3d12.dll as native after installing vkd3d-proton to your prefix (or using proton-tkg) should be all that's needed if the game used to work.

**Comment by Freeman310** [comment]
The reason for the lack of functionality could not be understood. However, everything is fine with Wine 7.6.
