### ISSUE TITLE
[wine-tkg-git] 4ac322f66c8abf878e6aefd77963c871ccc46ab0 A failure occurred in prepare.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#73]
4ac322f66c8abf878e6aefd77963c871ccc46ab0
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4865704/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4865705/prepare.log)
![Screenshot from 2020-07-02 22-00-49](https://user-images.githubusercontent.com/36989404/86389530-dbbb3800-bcaf-11ea-8f2e-926e83d06f9f.png)

**Comment by Kerrung** [comment]
But I still see this bug even with df37b30b7b6f0d806241bf89c128967f31a28777
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4866978/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4866979/prepare.log)

**Comment by Kerrung** [comment]
@Tk-Glitch

**Comment by Tk-Glitch** [comment]
No need to ping me I get email notifications on each message posted here ;)

Is it the exact same error or is it slightly different?

**Comment by Kerrung** [comment]
I just tried with b4d490d9975b6809cbffd47429a07cda7d088a60 , but It is the exact same error:
![Screenshot from 2020-07-03 04-05-08](https://user-images.githubusercontent.com/36989404/86416088-7af92300-bce2-11ea-9f1c-5c7f75d85d3c.png)

**Comment by Tk-Glitch** [comment]
Please try again with the change I just pushed

**Comment by Kerrung** [comment]
> Please try again with the change I just pushed

Fixed now with https://github.com/Frogging-Family/wine-tkg-git/commit/d94384c13b3c02549c5b89a245683a0a8a861f45 , thank you!

**Comment by Tk-Glitch** [comment]
Great news! Thanks for the feedback 👍
