### ISSUE TITLE
Cant build proton-tkg on xubuntu 20.04

### ISSUE THREAD

**Issue by JohnBobbo59** [Frogging-Family/wine-tkg-git#731]
Every time i try to build proton-tkg i get this error i even tried just building it without changing any of the configuration files and same thing

``
gcc: error: Packages/Proton-TKG-Fresh/wine-tkg-git/proton_dist/bin": No such file or directory
make: *** [Makefile:151366: dlls/ntdll/unix/loader.o] Error 1
make: *** Waiting for unfinished jobs....
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real	0m2.898s
user	0m6.912s
sys	0m1.111s
``

**Comment by Tk-Glitch** [comment]
Before your log, some actual error happened :frog:
It might be worth trying again now that https://github.com/Frogging-Family/wine-tkg-git/pull/747 was merged
