### ISSUE TITLE
[Proton-tkg envar] `PROTON_WINETRICKS=1`Fails to Start with Proton 7.6 (Plain Wine)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#742]
This is a somewhat odd issue where, if I try to log it, basically no information about what causes this is provided; this is also the case when running an application/game normally with logging enabled with an application [that's known to work under non-tkg plain Wine 7.6](https://github.com/Frogging-Family/wine-tkg-git/issues/683#issuecomment-1094175360)

The logs look more or less like this, with no other context:
```
======================
Proton: 1649888252 proton-tkg-7.6.r0.ga4e4e19fe0f.FROGGED
SteamGameId: 35140
Command: ['/mnt/extraStorage/Gaming/SteamLibrary/steamapps/common/Batman Arkham Asylum GOTY/Binaries/BmLauncher.exe']
Options: {'pulselowlat', 'noesync', 'enablenvapi', 'winetricks', 'logcommandtoprefix'}
Kernel: Linux 5.17.2-256-tkg-pds-llvm #1 TKG SMP PREEMPT Wed, 13 Apr 2022 20:30:30 +0000 x86_64
======================
```

I was going to test  `PROTON_WINETRICKS=1` for this issue:
- https://github.com/Frogging-Family/wine-tkg-git/issues/730

with Proton 7.6 (plain-based), but it doesn't seem capable of running anything else other than Steam's startup scripts and `winecfg` :/

[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/8485075/proton-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment]
Tested on the same game, just in case, it's slow due to the reaper spam (going through the UI to open a commandline shell might bypass that issue though) but it works fine on my end. Are you running Wayland maybe? Does winetricks UI works for you when launching it from a shell?

[!(renamed webm)](https://user-images.githubusercontent.com/741977/163323291-cacdc28e-77e8-4380-a9c5-8f74e9b2435a.mp4)

**Comment by Tk-Glitch** [comment]
Ok, I have pushed a simple fix for the slow/spammy launch: https://github.com/Frogging-Family/wine-tkg-git/commit/80f4f7e8c067e686eaf066e22f52da739b4de868

**Comment by ThisNekoGuy** [comment]
I'll try again but it doesn't look like you're using the same revision of the build?
Mine is: `proton_tkg_7.6.r0.ga4e4e19fe0f`

But no, I'm running Xorg, so I have no clue why it's behaving like this for me

**Comment by ThisNekoGuy** [comment]
I rebuilt it for the new clean log output:
```
======================
Proton: 1649943891 proton-tkg-7.6.r0.ga4e4e19fe0f.FROGGED
SteamGameId: 35140
Command: ['/mnt/extraStorage/Gaming/SteamLibrary/steamapps/common/Batman Arkham Asylum GOTY/Binaries/BmLauncher.exe']
Options: {'logcommandtoprefix', 'winetricks', 'pulselowlat'}
Kernel: Linux 5.17.2-256-tkg-pds-llvm #1 TKG SMP PREEMPT Wed, 13 Apr 2022 20:30:30 +0000 x86_64
======================
ERROR: ld.so: object '/home/neko-san/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/neko-san/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Executing mkdir -p /mnt/extraStorage/Gaming/SteamLibrary/steamapps/compatdata/35140
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 0
drwxr-xr-x 1 neko-san neko-san 110 Apr 14 09:00 .
drwxr-xr-x 1 neko-san neko-san 140 Apr 14 09:01 ..
drwxr-xr-x 1 neko-san neko-san  18 Apr 14 09:00 ProgramData
drwxr-xr-x 1 neko-san neko-san 118 Apr 14 09:00 Program Files
drwxr-xr-x 1 neko-san neko-san 164 Apr 14 09:00 Program Files (x86)
drwxr-xr-x 1 neko-san neko-san  30 Apr 14 09:00 users
drwxr-xr-x 1 neko-san neko-san 522 Apr 14 09:00 windows

Registry info:
/mnt/extraStorage/Gaming/SteamLibrary/steamapps/compatdata/35140/pfx//system.reg:#arch=win64
/mnt/extraStorage/Gaming/SteamLibrary/steamapps/compatdata/35140/pfx//userdef.reg:#arch=win64
/mnt/extraStorage/Gaming/SteamLibrary/steamapps/compatdata/35140/pfx//user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------

```

**Comment by ThisNekoGuy** [comment]
I rebuilt the latest plain 7.6 today and it works, so... Guess I'll close the issue?

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch Also, running `PROTON_ENABLE_NVAPI=1` with said build prevents Proton from running for some reason?

**Comment by Tk-Glitch** [comment]
> @Tk-Glitch Also, running `PROTON_ENABLE_NVAPI=1` with said build prevents Proton from running for some reason?

Yes, it's here: https://github.com/Frogging-Family/wine-tkg-git/tree/master/proton-tkg#special-options-and-builtin-features-
