### ISSUE TITLE
"Patch application has failed", "A failure occured in Prepared()" errors when trying to build wine-tkg

### ISSUE THREAD

**Issue by RedstonerCKZ** [Frogging-Family/wine-tkg-git#743]
My [prepare.log](https://pastebin.com/z23URBfS)
I wanted to play Roblox on Linux but the mouse gets stuck so I followed [this](https://www.youtube.com/watch?v=Hlziv2nghZ0) tutorial and when I tried to build it, it wouldn't work, giving me those errors. I only changed the settings that were in the video, so the Windows 10 setting, no confirm setting, and the roblox_mouse_fix.mypatch.
![674238917061358975230](https://user-images.githubusercontent.com/83525436/163663002-6961e36e-c999-4dd8-9de3-c5a430b8a485.png)

**Comment by llde** [comment]
childwindow patch is frogged again.

Where the patch reference X11DRV_vkCreateWin32SurfaceKHR in winex11.drv/vulkan.c the GetAncestor was translated in NtUserGetAncestor

**Comment by RedstonerCKZ** [comment]
So what do I do, then?

**Comment by llde** [comment]
Should be fixed with the latest commits

**Comment by RedstonerCKZ** [comment]
It worked, thanks for the help.

**Comment by Tk-Glitch** [comment]
Closing
