### ISSUE TITLE
Proton-tkg Rust Build Error

### ISSUE THREAD

**Issue by Arr4y** [Frogging-Family/wine-tkg-git#749]
I've been struggling to build Proton-tkg with custom patches. I was looking at a [VRChat video player fix](https://gist.github.com/yshui/6625f4537dd9a7d0b28a59a9a3a79967) but I was recommended to do it over this tool. I copied and pasted the two patch files from it into the proton-tkg-userpatches folder.

Once I ran the "./proton-tkg.sh" (I've also tried "makepkg -si" with the same results), it seemed to properly build everything with the gcc compiler. But right after, it tried to build something in Rust and ended up having issues locating the standard library/core crate and also unable to properly parse the Rust crate library.

I've tried making sure I've installed the stable Rust branch, the nightly branch, and getting rid of it all together. It lead me to the same error. I am not sure what to do at this point because this took me all day as it takes forever to build Wine every time I run this.

My terminal couldn't hold to everything so I only copied to where I think seemed most important. What came before where I copied is just a couple of warnings and compiling output which looks to have built right. Here's my output log:
https://pastebin.com/0LeVksnq

Thanks for any help.

**Comment by Arr4y** [comment]
I found a fix last minute. I didn't see these lines in the output:
= note: the `i686-unknown-linux-gnu` target may not be installed
= help: consider downloading the target with `rustup target add i686-unknown-linux-gnu`

It compiled successfully after I followed these steps.

**Comment by Tk-Glitch** [comment]
I should probably add this bit in to the readme since the dependency alone (through makepkg or the shipped deps script) doesn't seem to cut it.
