### ISSUE TITLE
Input is blocked on wine-tkg - Detroit Become Human

### ISSUE THREAD

**Issue by Ahmed-E-86** [Frogging-Family/wine-tkg-git#75]
I was playing Detroit Become Human using **wine-tkg**, and I had an issue with the part of the game where I play as Kara, and I suppose to ventilate the room, and I couldn't press the buttons to do that using a controller (pressing RT), or a keyboard (pressing L-Shift), changing the keybindings didn't help either.

If you want to know which part of the game I am talking about watch this video >>> https://youtu.be/S9aYYy21ux4?t=204 (I marked the exact time for you (**3:24**), so you don't have to watch the whole video)

I thought at first that it has to be a bug with the game, but I couldn't find any similar issue after searching on the internet. I tried everything possible to fix this issue until I decided to try **normal proton build** instead, and to my surprise it was fixed!

I tried to play the game with normal wine-staging to know if it exists also with it, but the game always freezes during loading when I try to do that.

**Comment by Ahmed-E-86** [comment]
This issue is not related to wine-tkg. It exists with normal wine-staging as well.

**Comment by Tk-Glitch** [comment]
In case it's of interest to you, I was able to test that specific scene of the game on my end and faced no issue. It's very likely a keyboard layout problem and disabling staging's `winex11-key_translation` patchset is a known workaround on affected game/layout combos.

You can do that for your wine/proton-tkg builds by setting `_staging_userargs="-W winex11-key_translation"` in your .cfg.

**Comment by Ahmed-E-86** [comment]
You didn't encounter the same issue with the same game at the same part @Tk-Glitch ?

**Comment by Tk-Glitch** [comment]
Well, I thought my message was pretty clear :smile:
Indeed there was no issue pressing left shift to open that specific window on my end, with 100% success rate after 5 attempts at reproducing your issue. I have not tried with a controller.

**Comment by Ahmed-E-86** [comment]
That is pretty clear. I am so surprised. What is the desktop environment do you use?

**Comment by Tk-Glitch** [comment]
Plasma 5.19, on X11.

**Comment by Ahmed-E-86** [comment]
It is the same as me, but I use older version of Plasma. I am confused now.

**Comment by Ahmed-E-86** [comment]
It is the same as me, but I use older version of Plasma 5.18.5, and I use **US** keyboard layout.

**Comment by Ahmed-E-86** [comment]
I am downloading Manjaro right now to be able to combile wine-tkg, because it is harder to do that on Ubuntu. Anyway, which wine-staging version do you recommend?

**Comment by Ahmed-E-86** [comment]
> In case it's of interest to you, I was able to test that specific scene of the game on my end and faced no issue. It's very likely a keyboard layout problem and disabling staging's `winex11-key_translation` patchset is a known workaround on affected game/layout combos.
> 
> You can do that for your wine/proton-tkg builds by setting `_staging_userargs="-W winex11-key_translation"` in your .cfg.

Actually, this issue also happens with wine-devel, so I don't think that removing wine-staging patch will do any difference. Anyway, Proton builds works just fine.

**Comment by Tk-Glitch** [comment]
Ok so my assumption about the US layout and winex11-key_translation patchset was wrong.

> Proton builds works just fine

I do have some keyboard related patches ported over for proton-tkg (which are also available in wine-tkg optionally), so that's probably it.

**Comment by Ahmed-E-86** [comment]
No, I use Vanilla Proton builds that I got from here >> https://github.com/Kron4ek/Wine-Builds/releases/download/5.0-8-proton/wine-5.0-8-proton-amd64.tar.xz

**Comment by Ahmed-E-86** [comment]
I tried to build wine-tkg on Manjaro inside VM, and it always fails. I tried building it on Ubuntu, and it fails with unmet 32bit dependency that can't be found on Ubuntu, vulkan-headers if I remmember correctly.
