### ISSUE TITLE
Previous Patch Applied Error

### ISSUE THREAD

**Issue by Arr4y** [Frogging-Family/wine-tkg-git#751]
I've been trying to apply a [VRChat video fix patch](https://gist.github.com/yshui/6625f4537dd9a7d0b28a59a9a3a79967) using wine-tkg. I've copied over the two ".patch" files over from it to wine-tkg-userpatches but it didn't seem to detect them. I ended up renaming their filename extensions to ".mypatch" and it seemed to work until I received an error:
==> ERROR: Patch application has failed. The error was logged to /home/shadd/.wine-tkg/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
-> Removed BIG_UGLY_FROGMINER - Ribbit
-> Removed Proton-tkg token - Valve Ribbit
-> exit cleanup done

And looking at the end of the log file:
Applying your own patch 0001-mfplat-Correctly-calculate-url-scheme-length.mypatch
patching file dlls/mfplat/main.c
Reversed (or previously applied) patch detected! Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/mfplat/main.c.rej

I also received a warning at the beginning that looks like it would affect these patches:
==> WARNING: ! Staging has disabled mfplat support on this revision, so video playback will not work in games using mfplat unless a hotfix is available !

I'm not sure if I've done this wrong. Any help is great. Thanks.

**Comment by Iglu47** [comment]
```
Applying your own patch 0001-mfplat-Correctly-calculate-url-scheme-length.mypatch
patching file dlls/mfplat/main.c
Reversed (or previously applied) patch detected! Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/mfplat/main.c.rej
```
this first patch already in Wine since 7.3 https://github.com/wine-mirror/wine/commit/4662dbd796a8feac494de1ae26c6ab6005e829da

**Comment by Arr4y** [comment]
I guess I'm back to square one. I assume both patches are already in since they both fail. Thanks.

**Comment by Iglu47** [comment]
> I assume both patches are already in since they both fail.

no, I don't see the second patch in upstream.
