### ISSUE TITLE
Error reading winmm_dll_s00052.o: No such file or directory

### ISSUE THREAD

**Issue by gel-crabs** [Frogging-Family/wine-tkg-git#755]
/usr/bin/x86_64-w64-mingw32-dlltool: dlls/winmm/libwinmm.cross.a: error reading winmm_dll_s00052.o: No such file or directory
winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:228975: dlls/winmm/libwinmm.cross.a] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/x86_64-w64-mingw32-dlltool: dlls/winmm/libwinmm.delay.a: error reading winmm_dll_t.o: No such file or directory
winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:228975: dlls/winmm/libwinmm.delay.a] Error 1

I've been having this error for a few weeks now.

**Comment by Tk-Glitch** [comment]
Afaik this is due to the mingw build available in Arch testing being frogged. It's all fine on the stable package.

**Comment by gel-crabs** [comment]
Ahh, I see. Thank you

**Comment by Sukid** [comment]
Its doing that to me now and I'm not on arch-testing. :(

**Comment by gel-crabs** [comment]
Yeah, the testing mingw build got moved to community.
