### ISSUE TITLE
Error: "could not revert ef8e4b7e3e3... winex11: Use libc for driver memory allocation."

### ISSUE THREAD

**Issue by SeanOMik** [Frogging-Family/wine-tkg-git#756]
Trying to build `proton-tkg` but the build fails with this error:
```
could not revert ef8e4b7e3e3... winex11: Use libc for driver memory allocation. 
```
I fixed that error by setting `_staging_version` to commit [`7b5a66b852f71b161914e0cc7c2a52e29ed0ed96`](https://github.com/wine-staging/wine-staging/commit/7b5a66b852f71b161914e0cc7c2a52e29ed0ed96) in `proton-tkg.cfg`

After fixing it I used the same terminal to continue the build, so I no longer have the full logs from that attempt since tmux decided to limit the number of lines.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/0e39b5b9eb9db8fd403b83462b2d1256f6ff8251
