### ISSUE TITLE
fsync-staging.patch fails with v5.11

### ISSUE THREAD

**Issue by aufkrawall** [Frogging-Family/wine-tkg-git#76]
Hello Etienne,
when setting v5.11 as head, applying of `fsync-staging.patch` fails when answering the hotfix prompt with yes.
Log: 
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4872735/prepare.log)

Reason for me setting v5.11 is a regression of HotS not starting anymore with 5.12. I'd think that this might be a regression in wine-staging itself and not your patches, at least it also doesn't work when disabling all the bells and whistles in customization.cfg.

**Comment by aufkrawall** [comment]
Thanks, everything works with v5.11 now. Will test vanilla-staging 5.12 when it hits Arch repo.

**Comment by Tk-Glitch** [comment]
I think I have found the culprit commits regarding 5.12.

**Comment by aufkrawall** [comment]
Can confirm that, great!
