### ISSUE TITLE
Build error: could not revert b8732c80b11... win32u: Move caret APIs from user32.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#760]
OS: Arch Linux;
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8608958/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8608960/last_build_config.log)

![Screenshot from 2022-05-03 12-48-36](https://user-images.githubusercontent.com/36989404/166419836-6bae165c-5f65-467c-be67-409aa56c7933.png)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/cbb278139a745d04c4b89cbdbe5c96bdfee7c79e
