### ISSUE TITLE
cant build from source i get this message every time i'm on arco

### ISSUE THREAD

**Issue by gil938271** [Frogging-Family/wine-tkg-git#762]
Assembler messages:
Error: can't open rpcrt4_dll_h.s for reading: No such file or directory
/usr/bin/x86_64-w64-mingw32-dlltool: /usr/bin/x86_64-w64-mingw32-as exited with status 1
/usr/bin/x86_64-w64-mingw32-dlltool: failed to open temporary head file: rpcrt4_dll_h.o: No such file or directory
winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:178382: dlls/rpcrt4/librpcrt4.delay.a] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
  -> Compilation time for 64-bit wine: 

real	1m47.537s
user	12m34.707s
sys	0m29.512s

**Comment by Nanotwerp** [comment]
I get this same error. Are you also on Fedora Rawhide, or using a distro that has GCC and MinGW updated to version 12? It seems to be an issue relating to an incompatibility with newer versions of these.

**Comment by KuKuRuZ1337** [comment]
sudo pacman -U /var/cache/pacman/pkg/mingw-w64-binutils-2.36.1-1-x86_64.pkg.tar.zst

**Comment by loathingKernel** [comment]
As a workaround building wine with one makejob seems to avoid the issue.

**Comment by Tk-Glitch** [comment]
There is known issue with binutils 2.38 release. It's already fixed upstream, but the release tarballs don't include the fix, so Arch's package is broken as it is right now. Rolling back is the simplest fix. I'll open a PSA ticket about it.

**Comment by Tk-Glitch** [comment]
See https://github.com/Frogging-Family/wine-tkg-git/issues/764
