### ISSUE TITLE
[Proton-tkg] ERROR: Patch application has failed.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#763]
OS: Arch Linux;
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8644283/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8644284/prepare.log)
![Screenshot from 2022-05-07 07-30-51](https://user-images.githubusercontent.com/36989404/167234543-50035c11-9cf9-4a18-bd0c-2a6c79d35dfb.png)

**Comment by MalonnBethesda** [comment]
I'm getting a bunch of patch applied errors too.  First was with wine staging patches, second was with esync under plain wine, and third was with one/some of the community patches under plain wine.

Proton-tkg is a hot mess.  No logs, cuz I was on a mission.  A mission to not build proton.  And I succeeded in that mission.

**Comment by Tk-Glitch** [comment]
We should be good to go on the staging fshack/childwindow BS side of things following the last commits.
I'll have a look at mainline now.

**Comment by Tk-Glitch** [comment]
Ok, should be also fine on mainline now. Closing.
