### ISSUE TITLE
PSA: binutils 2.38 release breaks wine compilation

### ISSUE THREAD

**Issue by Tk-Glitch** [Frogging-Family/wine-tkg-git#764]
https://sourceware.org/bugzilla/show_bug.cgi?id=28885

The git tree was updated, but the release binaries shipped by most ditros (Arch included) aren't. The easiest fix for the affected distros is to rollback to the previous package while waiting for either a package update against the upstream patch for 2.38 or for binutils 2.39 release.

For Arch, `sudo pacman -U https://archive.archlinux.org/packages/m/mingw-w64-binutils/mingw-w64-binutils-2.36.1-1-x86_64.pkg.tar.zst` will do just that and will work even if you nuked your package cache.

**Comment by Tk-Glitch** [comment]
Alternatively, you can use our tool https://github.com/Frogging-Family/mostlyportable-gcc as a distro-agnostic solution, which was updated to use the fixed binutils tree.

**Comment by Iglu47** [comment]
related Archlinux bug report https://bugs.archlinux.org/task/74718

**Comment by Tk-Glitch** [comment]
The package was updated on Arch repos, fixing the issue.
