### ISSUE TITLE
wineboot.exe not found

### ISSUE THREAD

**Issue by Anti-Apple4life** [Frogging-Family/wine-tkg-git#769]
When I try to run `winecfg` or any other app with wine-tkg, it crashes and displays below text:
```
wineserver: using server-side synchronization.
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007
```

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue on my end. Please give more details.

Are you building yourself, and if yes on which distro, with which config changes..? Anything that could be of help here.

**Comment by Anti-Apple4life** [comment]
I built wine-tkg-git on ArchLinux with the makepkg default settings. no config changes.

**Comment by Tk-Glitch** [comment]
Make sure you're not hitting this: https://github.com/Frogging-Family/wine-tkg-git/issues/764

Compilation should just stop there, but I haven't tested with makepkg tbh. Maybe it actually packages the broken binaries and installs it..

**Comment by Anti-Apple4life** [comment]
I will test it when I get back to my arch machine

Sent from my Android phone

**Comment by Anti-Apple4life** [comment]
```
❯ pacman -Q binutils
binutils 2.36.1-1
```
```
❯ wine explorer.exe
wineserver: using server-side synchronization.
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
```

**Comment by Iglu47** [comment]
> ```
> ❯ pacman -Q binutils
> binutils 2.36.1-1
> ```
@Anti-Apple4life the requested package is called `mingw-w64-binutils`
also the `binutils` package seems to be outdated (are you using non-archlinux distribution?)

```
$ pacman -Qs binutils 
local/binutils 2.38-5 (base-devel)
    A set of programs to assemble and manipulate binary and object files
local/mingw-w64-binutils 2.38-2 (mingw-w64-toolchain mingw-w64)
    Cross binutils for the MinGW-w64 cross-compiler
```

**Comment by Anti-Apple4life** [comment]
```
❯ pacman -Q mingw-w64-binutils
mingw-w64-binutils 2.36.1-1
```

**Comment by Anti-Apple4life** [comment]
I did the other one just to be safe

**Comment by Iglu47** [comment]
> ```
> ❯ pacman -Q mingw-w64-binutils
> mingw-w64-binutils 2.36.1-1
> ```

if the build environment is correct, then only the preparation and compilation logs can probably clarify the situation
> I downgraded the other one just to be safe

rather restore and do not touch such a package without a reason.

**Comment by Anti-Apple4life** [comment]
> if the build environment is correct, then only the preparation and compilation logs can probably clarify the situation

I will send in the compilation logs this afternoon when I get back to my computer. Just to confirm, `makepkg -Lsi` is what you are looking for?

**Comment by Iglu47** [comment]
I just built and checked `wine-tkg-staging-fsync-git-7.8.r3.ge31ff0a9-327-x86_64`.
can't reproduce the problem.
<details><summary>screenshot</summary>

<p>
![wineboot-test](https://user-images.githubusercontent.com/25866099/169543100-81423c83-7128-4a97-b015-1f74625bddcf.png)
</p>

</details>

there doesn't seem to be a problem with wine-tkg at least, but more information is needed to help.

**Comment by Anti-Apple4life** [comment]
what classes (fixme, err, warn, trace) and channels (atom, win, font, etc) do you want me to log?

**Comment by Iglu47** [comment]
@Anti-Apple4life could you just try fresh prefix (specify an empty folder)? like
WINEPREFIX="/home/user/games_dir/test/pfx" WINEARCH=win64 winecfg

**Comment by Anti-Apple4life** [comment]
```
❯ WINEPREFIX=/home/$USER/testpfx WINEARCH=win64 winecfg
wineserver: using server-side synchronization.
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
```

**Comment by Iglu47** [comment]
> ```
> ❯ WINEPREFIX=/home/$USER/testpfx WINEARCH=win64 winecfg
> wineserver: using server-side synchronization.
> wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
> 0024:err:environ:run_wineboot failed to start wineboot c000007b
> wine: failed to load start.exe: c000007b
> ```

is this the full output?

**Comment by Anti-Apple4life** [comment]
Yes

Sent from my Android phone
________________________________

**Comment by Iglu47** [comment]
if it's the full log, then it's probably not even a vanilla Wine issue, since there is no message about creating a prefix.
something prevents this: some problems with permissions, runtime environment problems or other problems related to the initial setup.
not enough information.

**Comment by Iglu47** [comment]
> wine: failed to load start.exe: c000007b

@Anti-Apple4life try to copy this file manually and run the winecfg command again.
`cp ~/testpfx/drive_c/windows/command/start.exe ~/testpfx/drive_c/windows/syswow64/`

**Comment by Anti-Apple4life** [comment]
```
❯ rm -rf .wine testpfx
❯ winecfg
wine: created the configuration directory '/home/johne/.wine'
wineserver: using server-side synchronization.
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
```

**Comment by Tk-Glitch** [comment]
Could you upload the package somewhere for us to try and reproduce the issue on our end?

**Comment by Anti-Apple4life** [comment]
Yes
https://drive.google.com/uc?export=download&id=1fp8AOREQOgq2ZsXyHMv3_3lf74oiOQUC

**Comment by Tk-Glitch** [comment]
Ok I can reproduce the issue with that build, so the build is broken somehow.

**Comment by Anti-Apple4life** [comment]
I am not sure what the issue could be, for now I will use a precompiled build from Github Actions

**Comment by Tk-Glitch** [comment]
Checking the logs out, there's a common warning about a section being too large.
I deleted the prefix, then ran `strip` in both `x86_64-windows` and `i386-windows` dirs, and now.. it runs.

**Comment by Tk-Glitch** [comment]
Could it be your compiler being frogged?

**Comment by Anti-Apple4life** [comment]
Probably, although I got no warning

**Comment by Iglu47** [comment]
Testing the build on another machine clears things up a lot (thanks TKG).
Since the build environment has already been checked by the `wine` and `wine-staging` build scripts, in `wine-tkg-config.txt` only ccache is suspicious. Although it is not clear why the libraries remained unstripped.

@Tk-Glitch why is this enabled by default for usual end users, maybe it should just be left as a toggle option that is disabled by default?

**Comment by Tk-Glitch** [comment]
@Anti-Apple4life  I have added our own stripping mechanism for the makepkg path, which *should* fix your issue. It's unclear why, on your machine, makepkg's own stripping mechanism doesn't do its job, but ultimately wine shouldn't refuse to load even large debug binaries, so that's still pretty weird. We're clear that it never worked for you before, right? Else if it used to work and broke at some point, Iglu47 might be onto something with the ccache theory. Clearing ccache might help.

@Iglu47 It's enabled if ccache is installed (which is optional). Tbh it was just due to popular demand. It shouldn't be much of a problem for most users though. Ccache only failed on me on power outtages or system instabilities (mostly due to overclocking, which is usually a bad idea on a production machine). But yeah maybe we could add an actual toggle if you feel like it's needed.

**Comment by Tk-Glitch** [comment]
If you can confirm it fixed your issue, feel free to close. Else we might need more stripping :frog:
