### ISSUE TITLE
[Proton-tkg] error: pathspec 'experimental' did not match any file(s) known to git

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#774]
I'm glad my distro is Arch Linux and not an [apt](https://github.com/Frogging-Family/wine-tkg-git/issues/773) based one - that's happiness in my opinion.

0b3a029
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8746872/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8746874/prepare.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/8746879/proton-tkg.cfg.zip)

![Screenshot from 2022-05-21 07-47-16](https://user-images.githubusercontent.com/36989404/169633115-affb7fdf-2dc3-48a1-b7a0-f9df144fc3cf.png)

**Comment by Iglu47** [comment]
there is no proton branch "experimental"
the full list is here, but I'm not sure if any of them are supported.: https://github.com/ValveSoftware/Proton/branches/all

**Comment by Tk-Glitch** [comment]
Indeed, the correct branch for current experimental is `experimental_7.0` and not `experimental`. And yes it is supported.
