### ISSUE TITLE
[Proton-tkg] makedep: error: open /stable/viewporter/viewporter.xml : No such file or directory

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#775]
0b3a029 
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/8747763/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/8747764/prepare.log)
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/8747766/proton-tkg.cfg.zip)
![Screenshot from 2022-05-21 19-18-00](https://user-images.githubusercontent.com/36989404/169655753-352c58a0-9949-47da-91e4-af24c224c141.png)

**Comment by Tk-Glitch** [comment]
That missing file is from the `wayland-protocols` package. Since you're using the `wine_wayland_driver` patch, you'll need that package.

**Comment by Kerrung** [comment]
> That missing file is from the `wayland-protocols` package. Since you're using the `wine_wayland_driver` patch, you'll need that package.

![Screenshot from 2022-05-21 20-03-41](https://user-images.githubusercontent.com/36989404/169657416-15c5e826-e3e1-4ad2-b961-aecbc85557c2.png)

**Comment by Tk-Glitch** [comment]
Ok so either your package is broken or the patchset is broken. In both cases, it's not on our end.

**Comment by Tk-Glitch** [comment]
It looks like your `WAYLAND_PROTOCOLS_DATADIR` env var isn't set or gets emptied. But again, that's not our bug.

**Comment by Kerrung** [comment]
> Ok so either your package is broken or the patchset is broken. In both cases, it's not on our end.

I just checked and made sure that the viewporter.xml file is in fact contained in the current version of the [wayland-protocols](https://archlinux.org/packages/extra/any/wayland-protocols) package from Arch Linux official repo that I using.
You can verify this yourself if you manually download this package and then unpack it with an archiver. In this case, you can find the viewporter.xml file among the unpacked files and folders.
![Screenshot from 2022-05-21 20-30-36](https://user-images.githubusercontent.com/36989404/169658567-79a2f568-4460-4dd1-b9bf-941bf0f4bfff.png)

**Comment by Kerrung** [comment]
> It looks like your `WAYLAND_PROTOCOLS_DATADIR` env var isn't set or gets emptied. But again, that's not our bug.

And in which directory should I point it?

**Comment by Tk-Glitch** [comment]
I have added a hack that should make it work.
