### ISSUE TITLE
Video decoders for games

### ISSUE THREAD

**Issue by Emerald-glitch** [Frogging-Family/wine-tkg-git#778]
I have a game The lion's song, it uses wmv files for some of the media in the game and it also needs child window patch. That is what i wanted to use wine-tkg for well child window related issues disappeared but it can't find decoders which i have installed.
I tested it with another game that needs decoders but not child window patches (Bully) and it showed the same error it is a reencoded video from the one provided with game file

Missing decoder: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)121056e500, rate=(int)44100, channels=(int)2)
Missing decoder: MPEG-4 Video (Simple Profile) (video/mpeg, mpegversion=(int)4, systemstream=(boolean)false, profile=(string)simple, level=(string)1, codec_data=(buffer)000001b001000001b58913000001000000012000c48d8ba98528045a1443000001b24c61766335382e3133342e313030, width=(int)1280, height=(int)720, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1, colorimetry=(string)bt709)

Or when i used the original video

Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)

This is same as what i found when running lion's song. And i can confirm bully's cutscenes work just file with wine-ge and lutris-wine. I tried h264 too same error.
And running lion's song with other wine versions give me child window errors.

I did see the config file for custom build but i could not find any variable to use system gstreamer lib if it is possible can you tell me how to?

And i used the already build package provided for arch in github releases

**Comment by Iglu47** [comment]
> This is same as what i found when running lion's song. And i can confirm bully's cutscenes work just file with wine-ge and lutris-wine. I tried h264 too same error.

I'm not sure exactly what you're asking, but at the moment mfplat related patches are being actively accepted upstream.
like https://gitlab.winehq.org/wine/wine/-/merge_requests/139/commits https://gitlab.winehq.org/wine/wine/-/merge_requests/140/commits

but the patches for ~wine-7.0 should still work for wine-ge and lutris-wine, as they don't currently follow upstream wine versions.
https://github.com/wine-staging/wine-staging/commit/05ea40b9366e4ee28a2baa461853b778230cbad1#diff-940bd9120a9e3bf7d428faea663fa64e5cfca747f2085b600890ea346bc21c40R2

**Comment by Emerald-glitch** [comment]
I don't really know about mfplat, i tried searching around but could not find much about it, is it the part in wine which does video decoding using gstreamer?

Anyway the problem i have is that gstreamer plugins that i think are used for decoding, work as expected in wine-ge or lutris-wine but in wine tkg it gives me error that it cannot find those decoders.

**Comment by Iglu47** [comment]
> I don't really know about mfplat, i tried searching around but could not find much about it, is it the part in wine which does video decoding using gstreamer?

Yes, these are the patches that are kept in [Wine-Staging](https://github.com/wine-staging/wine-staging/tree/05ea40b9366e4ee28a2baa461853b778230cbad1/patches/mfplat-streaming-support) (and they are [disabled](https://github.com/wine-staging/wine-staging/commit/05ea40b9366e4ee28a2baa461853b778230cbad1#diff-940bd9120a9e3bf7d428faea663fa64e5cfca747f2085b600890ea346bc21c40R2) by the commit from the link above), so right now there is no version of them compatible with wine-7.9

wine-ge and lutris-wine should work fine because their builds are old and based on versions of wine that are compatible with them.
For current versions of Wine, some of the patches have already been accepted, but the work is still actively in progress, so it is expected that some things stopped working on Wine-Staging based builds.

**Comment by Emerald-glitch** [comment]
I see so will an older version of wine tkg work? Thanks for answering.

**Comment by Iglu47** [comment]
probaly should work wirh `_staging_version="bcfed21ea1925e06c1f0db0e86cb2380300b8aa9"`

**Comment by Emerald-glitch** [comment]
I will take it as you want me to build wine from source, I think i will pass, i am on a limited internet connection, with a 4 core 2.1ghz cpu, nah,
Thanks tho, if i get bored enough maybe i will then.

**Comment by Iglu47** [comment]
@Emerald-glitch try it, it should still be available https://github.com/Frogging-Family/wine-tkg-git/actions/runs/1974373461

**Comment by Emerald-glitch** [comment]
Thanks, I will try.

**Comment by Emerald-glitch** [comment]
I did try to download it twice, it got corrupted both the times. But i did find a version of wine with both child window patch and decoding in working condition. 
Well it also needs open shared memory so, no luck.
