### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/wine-tkg-git#779]
archlinux

```
In file included from /usr/include/X11/Xlib.h:44,
                 from ../wine-mirror-git/dlls/winex11.drv/systray.c:31:
../wine-mirror-git/include/processthreadsapi.h:43:11: error: expected identifier or ‘(’ before numeric constant
   43 |     ULONG ControlMask;
      |           ^~~~~~~~~~~

```

**Comment by Kerrung** [comment]
I can confirm it too
![Screenshot from 2022-05-25 05-04-47](https://user-images.githubusercontent.com/36989404/170856379-da64b90e-0d9f-4b80-b84e-7d3fb80a9990.png)

**Comment by 112batman** [comment]
Looking at CI the last working commit seems to be `e27b32fbd2358e1dc70c59a18d74cd62cd08db49`

**Comment by e666666** [comment]
Bisecting the issue on https://github.com/e666666/robloxWineBuildGuide/issues/18

**Comment by NyanCatTW1** [comment]
The faulty commit is https://github.com/wine-mirror/wine/commit/1e7c6d73c8f558668c6140d4a97fae0ad51d71eb

**Comment by NyanCatTW1** [comment]
Temporary workaround that reverts the faulty commit + commits that depend on it
The build is still running, caveat emptor.
```bash
	# Append this after Line 669 (source "$_where"/wine-tkg-patches/reverts) of wine-tkg-git/wine-tkg-scripts/prepare.sh
	if git merge-base --is-ancestor 1e7c6d73c8f558668c6140d4a97fae0ad51d71eb HEAD; then
		_committorevert=1e7c6d73c8f558668c6140d4a97fae0ad51d71eb && nonuser_reverter
		_committorevert=bf86dfbcadbe0e79ae07afb57e469f388a9104a7 && nonuser_reverter
		echo -e "( Experimental ControlMask build error fix reverts applied )\n" >> "$_where"/last_build_config.log
	fi
```

**Comment by Nolij** [comment]
Using that commit I was able to create this patch, which allows building and appears to produce a functional build with the previously mentioned reverts removed (ie without reverting anything):
```patch
--- a/dlls/winex11.drv/systray.c
+++ b/dlls/winex11.drv/systray.c
@@ -28,6 +28,7 @@
 #include <stdio.h>
 #include <unistd.h>
 
 #include <X11/Xlib.h>
+#undef ControlMask
 
 #define NONAMELESSUNION
 #include "windef.h"

```

**Comment by Nolij** [comment]
Alright potentially related runtime issue: successful staging build with above patch had a black screen on first launch of Roblox post install, however I'm not seeing it anymore after a few re-launches.

**Comment by Nolij** [comment]
This issue isn't necessarily solved yet, I'd prefer to keep it open. Sidetracked by work as far as the PR goes, will have that ready some time in next couple hours.

**Comment by Tk-Glitch** [comment]
> ```
> /usr/bin/x86_64-w64-mingw32-dlltool: dlls/winmm/libwinmm.cross.a: error reading winmm_dll_s00028.o: No such file or directory
> winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
> make: *** [Makefile:229057: dlls/winmm/libwinmm.cross.a] Error 1
> make: *** Waiting for unfinished jobs....
> /usr/bin/x86_64-w64-mingw32-dlltool: dlls/winmm/libwinmm.delay.a: error reading winmm_dll_t.o: No such file or directory
> winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
> make: *** [Makefile:229057: dlls/winmm/libwinmm.delay.a] Error 1
> ```
> 
> ```
> 
> /usr/bin/x86_64-w64-mingw32-dlltool: reopening winmm_dll_s00004.o: No such file or directory
> 
> /usr/bin/x86_64-w64-mingw32-dlltool: dlls/winmm/libwinmm.delay.a: error reading winmm_dll_s00004.o: No such file or directory
> winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
> make: *** [Makefile:229057: dlls/winmm/libwinmm.delay.a] Error 1
> make: *** Waiting for unfinished jobs....
> /usr/bin/x86_64-w64-mingw32-dlltool: dlls/wintrust/libwintrust.cross.a: error reading wintrust_dll_h.o: file truncated
> winebuild: /usr/bin/x86_64-w64-mingw32-dlltool failed with status 1
> make: *** [Makefile:230681: dlls/wintrust/libwintrust.cross.a] Error 1
> ```

https://github.com/Frogging-Family/wine-tkg-git/issues/764
