### ISSUE TITLE
Update Chaotic-AUR profiles

### ISSUE THREAD

**Issue by dr460nf1r3** [Frogging-Family/wine-tkg-git#782]
Both of the existing Chaotic-AUR profiles don't work as of now. 
- wine-tkg-staging [logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)
`patching file dlls/msvcrt/heap.c
patching file dlls/ntdll/heap_lfh.c
patching file dlls/ntdll/string.c
patching file dlls/ntdll/heap_lfh.c
Hunk #1 succeeded at 246 (offset 8 lines).
patching file dlls/ntdll/heap.c
Hunk #1 FAILED at 2229.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/heap.c.rej`
- wine-tkg-upstream [logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-upstream.log)
`/usr/sbin/x86_64-w64-mingw32-dlltool: dlls/rpcrt4/librpcrt4.cross.a: error reading rpcrt4_dll_s00053.o: No such file or directory
tools/winebuild/winebuild -b x86_64-w64-mingw32 -w --implib -o dlls/sechost/libsechost.cross.a --export \
  ../wine-mirror-git/dlls/sechost/sechost.spec
winebuild: /usr/sbin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:177721: dlls/rpcrt4/librpcrt4.cross.a] Error 1
make: *** Waiting for unfinished jobs....
/usr/sbin/x86_64-w64-mingw32-dlltool: dlls/rpcrt4/librpcrt4.delay.a: error reading rpcrt4_dll_t.o: No such file or directory
winebuild: /usr/sbin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:177721: dlls/rpcrt4/librpcrt4.delay.a] Error 1
==> ERROR: A failure occurred in build`

It would be nice if they would be updated so we can continue to provide `wine-tkg-git` builds to our users.
Alternatively, we could change the toolbox to build other profiles, I would need to know which ones then, though :) 

Thanks! 🤗

**Comment by Tk-Glitch** [comment]
The second issue (with dlltool) is due to an upstream regression from binutils 2.38. The fix was pushed today with the last package update of mingw-binutils. I'll disable LFH from the profile regarding the first issue.
