### ISSUE TITLE
`make: bison: Permission denied` - Strange Permission Issue Durring Build

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#789]
Not sure what's causing this issue but I get the feeling it isn't related to the user config file? :/
I had just done a fresh clone of the repo to build, so I don't understand what's going on here

Was trying to do an upstream-wine Proton build
```make
ccache gcc -m64 -c -o tools/widl/write_sltg.o ../wine-mirror-git/tools/widl/write_sltg.c -Itools/widl \
  -I../wine-mirror-git/tools/widl -I../wine-mirror-git/tools/wrc -Iinclude \
  -I../wine-mirror-git/include -D__WINESRC__ -Wall -pipe -fcf-protection=none -fno-stack-protector \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Winit-self \
  -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -O3 -pipe -ftree-vectorize -march=znver2 -mtune=znver2 -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
bison -o tools/widl/parser.tab.c -d ../wine-mirror-git/tools/widl/parser.y
make: bison: Permission denied
make: *** [Makefile:279216: tools/widl/parser.tab.h] Error 127
make: *** Waiting for unfinished jobs....
../wine-mirror-git/tools/widl/write_sltg.c: In function ‘add_func_desc’:
../wine-mirror-git/tools/widl/write_sltg.c:1363:60: warning: ‘arg_desc_offset’ may be used uninitialized [-Wmaybe-uninitialized]
 1363 |                 type_offset = (arg_offset + arg_desc_offset[i]);
      |                                             ~~~~~~~~~~~~~~~^~~
../wine-mirror-git/tools/widl/write_sltg.c:1235:29: note: ‘arg_desc_offset’ was declared here
 1235 |     short ret_desc_offset, *arg_desc_offset, arg_offset;
      |                             ^~~~~~~~~~~~~~~
In function ‘union_memsize’,
    inlined from ‘write_union_tfs’ at ../wine-mirror-git/tools/widl/typegen.c:3341:12,
    inlined from ‘write_type_tfs’ at ../wine-mirror-git/tools/widl/typegen.c:3658:16:
../wine-mirror-git/tools/widl/typegen.c:1859:18: warning: ‘dummy’ may be used uninitialized [-Wmaybe-uninitialized]
 1859 |     unsigned int align = *pmaxa;
      |                  ^~~~~
../wine-mirror-git/tools/widl/typegen.c: In function ‘write_type_tfs’:
../wine-mirror-git/tools/widl/typegen.c:3330:18: note: ‘dummy’ was declared here
 3330 |     unsigned int dummy;
      |                  ^~~~~
ccache gcc -m64 -o tools/winebuild/winebuild tools/winebuild/import.o tools/winebuild/main.o tools/winebuild/parser.o \
  tools/winebuild/relay.o tools/winebuild/res16.o tools/winebuild/res32.o tools/winebuild/spec16.o \
  tools/winebuild/spec32.o tools/winebuild/utils.o -Wl,-O3,--sort-common,--as-needed,-z,relro
bison -o tools/widl/parser.tab.c -d ../wine-mirror-git/tools/widl/parser.y
make: bison: Permission denied
make: *** [Makefile:279216: tools/widl/parser.tab.h] Error 127
make: *** Waiting for unfinished jobs....
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real    0m0.249s
user    0m0.217s
sys     0m0.030s

neko-san@ARCH ~/w/proton-tkg (master) [2]> 
```

**Comment by ThisNekoGuy** [comment]
This issue is quite baffling to me given that I'm running this in my home folder

**Comment by ThisNekoGuy** [comment]
Could this perhaps be related to the `src` folder being symlinked from `tmp` for the build process?

**Comment by Fox2Code** [comment]
It's seems execute permission on `bison` is not set... Strange...
And I don't think it has anything to do with symlinks.
The command `chmod +x file` is used to set the execute permission.

**Comment by ThisNekoGuy** [comment]
@Fox2Code It says it has execute permission...? :/
![Screenshot_20220627_130639](https://user-images.githubusercontent.com/28468662/176007155-3e7d9080-219e-41fb-b8d0-bbd042033d81.png)

**Comment by Tk-Glitch** [comment]
I cannot reproduce this on my end :/

**Comment by ThisNekoGuy** [comment]
Weird; I have no idea what's causing this
I'll check it out again soon when I have a moment; I've been out this weekend

**Comment by ThisNekoGuy** [comment]
Yeah, I still have no idea what's causing this...
Wait, I do have *one* idea... I've heard editing `sudoers`without using `visudo`can cause occasional permission issues but I've not personally experienced this before... unless this is it?

I usually use `doas` instead of sudo, but I know the script uses sudo, so maybe that's what's going on?
I tried using visudo just now to test that and it didn't seem to fix it but maybe because the damage is already done?
In which case... I would I fix this `sudoers`? :thinking:

**Comment by ThisNekoGuy** [comment]
What I *really* don't get here, is that doing this bison command by hand in that same directory, myself, works fine
There's no clue as to what's throwing permission fits, because doing it myself isn't a problem... :woozy_face:

**Comment by ThisNekoGuy** [comment]
Considering the issue, I'm going to upload my configuration in hopes that it would help in identifying what's going on :v
[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9089524/proton-tkg.cfg.txt)

**Comment by ThisNekoGuy** [comment]
Changing `umask` doesn't seem to fix it either

**Comment by Tk-Glitch** [comment]
- `CUSTOM_GCC_PATH="/usr"` is probably a bad idea. Try without it.
- `--without-mingw` in userargs is also a bad idea. Not only do we offer an option for that, but Wine will fail to build without MinGW more often than not these days (and since it's seemingly not tested, you'll face random issues as well), it'll also break Battleye and EAC. Better always build with MinGW. It's in the Arch repos, no excuses :P

**Comment by Tk-Glitch** [comment]
If it still fails after that, there's something broken with your install. We have multiple CI builders using Arch (https://github.com/Frogging-Family/wine-tkg-git/actions) and they never faced an issue like yours (neither did I ever face that myself).

**Comment by ThisNekoGuy** [comment]
> `CUSTOM_GCC_PATH="/usr"` is probably a bad idea. Try without it.

The reason I had this set (because of a suggest you made to me in the past) was because the script kept picking GCC from `/opt/cuda`; ever since, doing this made sure that the intended compiler was used. I have something in `makepkg.conf` that fixes that, but I haven't tried building this that way yet.

Attempting to remove `--without-mingw` didn't fix it, by the way

Also, this is a relatively new Arch install (I only recently installed it and this isn't the first time I've had this problem before; it tends to be sporadic for some reason); additionally, someone else I know has a similar issue but it throws the same error on `ccache` instead (I asked them to share their information here several times but they never did)

That said, clean reinstalling `bison` made no difference for me

**Comment by ThisNekoGuy** [comment]
Running `makepkg` doesn't almost immediately error out though, it seems to be building

**Comment by Tk-Glitch** [comment]
> The reason I had this set (because of a suggest you made to me in the past) was because the script kept picking GCC from /opt/cuda; ever since, doing this made sure that the intended compiler was used. I have something in makepkg.conf that fixes that, but I haven't tried building this that way yet.

Oh yeah now I remember about that BS :cold_sweat: This is absolutely horrendous, still. The cuda build should never take precedence over system-wide GCC unless you ask it to.

> Running makepkg doesn't almost immediately error out though, it seems to be building

But makepkg proton is poo poo bugfest.

> mingwdoesn't seem to like building with full relro though; it fails to link

Yeah your flags are kinda asking for trouble, but who am I to judge heh.

**Comment by ThisNekoGuy** [comment]
> But makepkg proton is poo poo bugfest.

I wouldn't know, I don't usually do that :joy: 

This line fixes the cuda issue in my `makepkg.conf`, by the way:
`export PATH=$(echo ${PATH} | awk -v RS=: -v ORS=: '/cuda/ {next} {print}' | sed 's/:*$//')`

Could probably fix it if we add it in the build script

> Yeah your flags are kinda asking for trouble, but who am I to judge heh.

Which other flags make you say that? Lol

**Comment by ThisNekoGuy** [comment]
I get a build error thought... :thinking: 

```make
/home/neko-san/wine-tkg-git/wine-tkg-git/src/proton_dist-64-build/tools/winebuild/winebuild -b \
  i686-w64-mingw32 --lib-suffix=.cross.a -Wl,--wine-builtin -mwindows -municode -mno-cygwin \
  programs/wscript/arguments.cross.o programs/wscript/host.cross.o programs/wscript/main.cross.o \
  programs/wscript/ihost_l.res libs/uuid/libuuid.cross.a dlls/shell32/libshell32.cross.a \
  dlls/oleaut32/liboleaut32.cross.a dlls/ole32/libole32.cross.a dlls/user32/libuser32.cross.a \
  dlls/advapi32/libadvapi32.cross.a dlls/winecrt0/libwinecrt0.cross.a \
  dlls/ucrtbase/libucrtbase.cross.a dlls/kernel32/libkernel32.cross.a dlls/ntdll/libntdll.cross.a \
  -Wl,-O3,--sort-common,--as-needed -Wl,--file-alignment,4096
ccache gcc -m32 -o dlls/capi2032/capi2032.so -shared -Wl,-Bsymbolic -Wl,-soname,capi2032.so -Wl,-z,defs dlls/capi2032/unixlib.o \
  dlls/ntdll/ntdll.so -Wl,-O3,--sort-common,--as-needed
ccache gcc -m32 -o dlls/crypt32/crypt32.so -shared -Wl,-Bsymbolic -Wl,-soname,crypt32.so -Wl,-z,defs dlls/crypt32/unixlib.o \
  dlls/ntdll/ntdll.so -Wl,-O3,--sort-common,--as-needed
ccache gcc -m32 -o dlls/ctapi32/ctapi32.so -shared -Wl,-Bsymbolic -Wl,-soname,ctapi32.so -Wl,-z,defs dlls/ctapi32/unixlib.o \
  dlls/ntdll/ntdll.so -Wl,-O3,--sort-common,--as-needed
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_isinstalled':
unixlib.c:(.text+0x13): undefined reference to `capi20_isinstalled'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_get_profile':
unixlib.c:(.text+0x3b): undefined reference to `capi20_get_profile'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_get_serial_number':
unixlib.c:(.text+0x6a): undefined reference to `capi20_get_serial_number'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_get_version':
unixlib.c:(.text+0x9d): undefined reference to `capi20_get_version'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_get_manufacturer':
unixlib.c:(.text+0xfa): undefined reference to `capi20_get_manufacturer'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_waitformessage':
unixlib.c:(.text+0x12a): undefined reference to `capi20_waitformessage'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_get_message':
unixlib.c:(.text+0x15b): undefined reference to `capi20_get_message'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_put_message':
unixlib.c:(.text+0x18b): undefined reference to `capi20_put_message'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_release':
unixlib.c:(.text+0x1b8): undefined reference to `capi20_release'
/usr/bin/ld: dlls/capi2032/unixlib.o: in function `capi_register':
unixlib.c:(.text+0x1f2): undefined reference to `capi20_register'
collect2: error: ld returned 1 exit status
make: *** [Makefile:16282: dlls/capi2032/capi2032.so] Error 1
make: *** Waiting for unfinished jobs....
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
 -> Compilation time for 64-bit wine: 

real    3m18.979s
user    46m16.259s
sys     4m11.938s

 -> Compilation time for 32-bit wine: 

real    0m0.773s
user    0m4.456s
sys     0m2.341s

neko-san@ARCH ~/w/proton-tkg (master) [2]> 
```

**Comment by Tk-Glitch** [comment]
Are the headers for your kernel installed?

**Comment by ThisNekoGuy** [comment]
Yes, I use the linux-tkg kernel

**Comment by Tk-Glitch** [comment]
Did you install libcapi from AUR maybe? You'd likely need to also install the lib32 version, else set `--without_capi`. We're not building wine with libcapi usually (notably because it's only in AUR, and useless for 99%+ users).

**Comment by ThisNekoGuy** [comment]
Ah, yeah
The reason why I had it installed was because of crossover
I haven't used crossover in a while though because it kind of busted after an update for me some time ago

**Comment by ThisNekoGuy** [comment]
Builds after your suggestion
Should probably do that thing about cuda though... Lol
Had to shove into the scripts to avoid it

**Comment by Tk-Glitch** [comment]
Yeah sounds like something we could add indeed.

**Comment by ThisNekoGuy** [comment]
> else set `--without_capi`

I just tried this though and it said it was an unrecognized option?
```
 -> Building Wine-64...
configure: error: unrecognized option: `--without_capi'
Try `../wine-mirror-git/configure --help' for more information
```

**Comment by ThisNekoGuy** [comment]
And if I get rid of it, now I get this...(plain wine)?
```
 -> Building Wine-64...
configure: WARNING: unrecognized options: --with-xattr, --without-vkd3d
```

**Comment by Tk-Glitch** [comment]
Sorry, should be `--without-capi`

**Comment by Tk-Glitch** [comment]
Those are just legacy and expected. You can ignore them.

**Comment by ThisNekoGuy** [comment]
Except it stops the build all of a sudden, so...

**Comment by Tk-Glitch** [comment]
They never stopped anything here

**Comment by Tk-Glitch** [comment]
Check the prepare.log maybe there's something else blocking

**Comment by ThisNekoGuy** [comment]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9203423/prepare.log)

**Comment by Tk-Glitch** [comment]
I guess that's the previous one? Zero error in there.

**Comment by ThisNekoGuy** [comment]
Uhhhh. for more context? :thinking: 
```
 -> Building Wine-64...
configure: WARNING: unrecognized options: --with-xattr, --without-vkd3d
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... ccache gcc
checking whether the C compiler works... no
configure: error: in `/home/neko-san/wine-tkg-git/wine-tkg-git/src/wine-tkg-fsync-git-64-build':
configure: error: C compiler cannot create executables
See `config.log' for more details
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

**Comment by Tk-Glitch** [comment]
Here's a log from my machine (same thing for CI anyway since we're basically always passing `--without-vkd3d`). It's not blocking anything.
```
 -> Building Wine-64...
configure: WARNING: unrecognized options: --without-vkd3d
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... ccache gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
```

**Comment by Tk-Glitch** [comment]
> Uhhhh. for more context? thinking
> 
> ```
>  -> Building Wine-64...
> configure: WARNING: unrecognized options: --with-xattr, --without-vkd3d
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking whether make sets $(MAKE)... yes
> checking for gcc... ccache gcc
> checking whether the C compiler works... no
> configure: error: in `/home/neko-san/wine-tkg-git/wine-tkg-git/src/wine-tkg-fsync-git-64-build':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
>  -> Removed BIG_UGLY_FROGMINER - Ribbit
>  -> Removed Proton-tkg token - Valve Ribbit
>  -> exit cleanup done
> ```

Ok so it has nothing to do with those configure flags. It's just your GCC path being frogged yet again.

**Comment by ThisNekoGuy** [comment]
I set it back to the default this time though! :skull_and_crossbones: 
I don't understand

**Comment by Tk-Glitch** [comment]
Check `src/proton_dist-64-build/config.log` and you'll see what's going on. Attach it here if you can't find the issue by yourself.

**Comment by Tk-Glitch** [comment]
This is wine's configure btw, not something on our end.

**Comment by ThisNekoGuy** [comment]
[wine-tkg-fsync-git-64-build-config.log](https://github.com/Frogging-Family/wine-tkg-git/files/9203488/config.log)

**Comment by Tk-Glitch** [comment]
`cc1: error: unrecognized argument to '-flto=' option: 'thin'`

Wine cannot be properly built with lto anyway, so you should get rid of that flag altogether.

**Comment by ThisNekoGuy** [comment]
Yeah, I just realized; I feel stupid

**Comment by Tk-Glitch** [comment]
Happens to the best of us !

**Comment by Tk-Glitch** [comment]
So, all good now?

**Comment by ThisNekoGuy** [comment]
Yeah, I just forgot to close the issue; sorry about that
