### ISSUE TITLE
Vulkan child window buffer copy happens at the wrong point

### ISSUE THREAD

**Issue by pac85** [Frogging-Family/wine-tkg-git#790]
Normally the copy is done in vkAcquireNextImageKHR ( [relevant line](https://github.com/Tk-Glitch/wine-tkg/blob/af025a6db4e8c7392a241c7747a11fc6ede52d77/dlls/winex11.drv/vulkan.c#L366) ) but it would make more sense to do it after a call to vkQueuePresentKHR. This causes a bug in SeriousEditor (and potentially other programs) where the ui is displayed with a 1 event delay   making it unusable (as well as showing uninitialized buffers whenever they are reinitialized). [This](https://github.com/pac85/wine-tkg/commit/0e4cb30a9e3b03c9ae66a20331b0f63b470642c1) is a quick fix I made.

Although less noticeable it could also cause a 1 frame input lag in games that make use of child window rendering, my patch should also fix it.

**Comment by pac85** [comment]
I mistakingly made a PR to the repo with generated source code. In any case that PR also has a commit with a bit of cleanup.

**Comment by Tk-Glitch** [comment]
In case you wanted to create a new PR:
The current patch can be found here: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch .
The relevant line you linked seems to be based on wine 7.3.0, which *might* have used that patch instead: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow.patch (which we don't use anymore on newer trees).

The current patch is a rebase of the Proton patch found here: https://github.com/ValveSoftware/wine/commit/6e57f48457f8df1d67a894a7497b1d70d43f784f

While I'm all fine integrating your changes here and grateful for your contribution, sending a PR for Wine's Proton integration sounds like a good idea to me. Is that something you'd be up to?

**Comment by pac85** [comment]
> In case you wanted to create a new PR: The current patch can be found here: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch . The relevant line you linked seems to be based on wine 7.3.0, which _might_ have used that patch instead: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow.patch (which we don't use anymore on newer trees).
> 
> The current patch is a rebase of the Proton patch found here: [ValveSoftware/wine@6e57f48](https://github.com/ValveSoftware/wine/commit/6e57f48457f8df1d67a894a7497b1d70d43f784f)
> 
> While I'm all fine integrating your changes here and grateful for your contribution, sending a PR for Wine's Proton integration sounds like a good idea to me. Is that something you'd be up to?

I assume by wine's proton you mean [Proton's wine](https://github.com/ValveSoftware/wine) right?

I agree that it would be a good idea, I've ported my fix to proton, [here is the commit]( https://github.com/pac85/wine-1/commit/ec9cc82572ac59ff41c51ab651030b62b396a31f) and I'm gonna make a PR there as soon as I can. Do you think the comment I made for this issue would be appropriate for the PR? I guess I should give a more proper explanation of the issue it fixes.

**Comment by pac85** [comment]
Thank you for being so kind. I've made a PR to this repo. I wasn't sure on how to add my commit to the patch, I catted my patch to the end. Let me know if I need to do it differently (I was thinking of making it into a separate patch so it could be disabled if needed) and I'll edit the PR. Also let me know if I have to add the change to the other versions of the patch as well.

**Comment by Tk-Glitch** [comment]
>Thank you for being so kind.

Thank **you** for offering your time and efforts to the community!

That's perfect. That will allow for better history tracking! :)
Porting it over to the other version of the patch isn't necessary imho, as legacy trees aren't used much and we're currently using pretty large revert lists to make things play well with those proton fshack and vk childwindow patchsets so the current patch actually affects quite a few versions behind as well.

However, adding your changes to the staging fshack patchset (which contains pretty much the same implementation for vk child window rendering support) would be useful for sure (you can find it here: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton/valve_proton_fullscreen_hack/valve_proton_fullscreen_hack-staging.patch). Please let me know if you want me to add your changes to that patch or if you're up for a second PR (or updating the existing one, as you please).

**Comment by pac85** [comment]
Give me a moment and I'll update my PR

**Comment by pac85** [comment]
Made another commit. Thanks again, I'm glad to give my contribution.
