### ISSUE TITLE
Asking to choose a "_LOCAL_PRESET" template when building.

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#794]
This menu didn't use to show up before. I have a custom `~/.config/frogminer/wine-tkg.cfg`, what option do I need to go for there to maintain my changes? Default? Or doesn't it matter, since `~/.config/frogminer/wine-tkg.cfg` will override the variables of the profiles?

OS: archlinux

```
  -> External config loaded
  -> No _LOCAL_PRESET set in .cfg. Please select your desired base (or hit enter for default) :
  ->   0 - default
  ->   1 - mainline
  ->   2 - mwo
  ->   3 - osu
  ->   4 - protonified
  ->   5 - staging
  ->   6 - valve
  ->   7 - valve-exp-bleeding
  ->   8 - valve-exp
```

**Comment by Tk-Glitch** [comment]
Just set `_LOCAL_PRESET=none` in your config to silence the prompt and have the same result as before.

> Or doesn't it matter, since ~/.config/frogminer/wine-tkg.cfg will override the variables of the profiles?

It'll actually be the other way around in this case and your frogminer .cfg options will be overridden by the selected profile (only the entries that are part of the selected profile though).

**Comment by rizzini** [comment]
Thank you, man!
