### ISSUE TITLE
(Presumebly) Network Issues With Latest Builds of Proton-tkg on both `valve` and `wine staging` branches of the package

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/wine-tkg-git#798]
# System Information
* Latest Packages on Arch Linux (Mesa 22.1.3, Linux 5.18.9, glibc 2.35-6)

# Problem
Whenever I go load games like Among Us or Bloons TD 6, which both require a network connection, the games freeze at the point where I assume they're waiting for content/a network connection. For among us, this is before the menu loads, and for Bloons TD 6, it's whenever it's downloading content for the first time. I have attached both of the debug logs I got from the games below
[steam-960090 (bloons td 6).log](https://github.com/Frogging-Family/wine-tkg-git/files/9042638/steam-960090.bloons.td.6.log)
[steam-945360 (among us).log](https://github.com/Frogging-Family/wine-tkg-git/files/9042639/steam-945360.among.us.log)

## Edit: More Information
I was able to launch among us and get to the menu by launching Among Us with `wine-tkg-staging-fsync-git 7.12.r0.g8699d2c2-327` using Among Us' compdata prefix. Maybe there is a proton-tkg patch causing this problem?

This problem doesn't exist on Proton 7.0-3
# Steps to reproduce
* Compile proton-tkg with either the `valve` or `wine staging` branch with all default settings and patches
* Download a game that requires an active internet connection (Among us, Bloons TD 6)
* Launch Game
* Observe softblock

**Comment by Tk-Glitch** [comment]
Just tested a fresh valve (exp bleeding edge) build against Among us, and it seems fine on my end.
![Screenshot_20220705_223639](https://user-images.githubusercontent.com/741977/177412259-2f4aab52-51d9-4388-8459-345c148ef983.png)

Your log seems to point to some possible permission issue:
```
UnauthorizedAccessException: Access to the path "\com.unity.addressables" is denied.
```

**Comment by HurricanePootis** [comment]
Where would I fix these permission issues? I am able to read/write to my `compdata` and `common` directory just fine, and Among Us did work using normal Proton 7.0-3

**Comment by HurricanePootis** [comment]
I just compiled proton-tkg using the valve experimental bleeding branch, and was able to launch among us. This time, unlike the rest, I used the build-script, instead of `makepkg -s`.

I am going to test out the valve experimental bleeding branch using `makepkg -s`, to see if this is a problem resulting from the makepkg build process.

**Comment by HurricanePootis** [comment]
Nope, looks like bleeding edge experimental works with makepkg
