### ISSUE TITLE
Discussion: Wine on Wayland

### ISSUE THREAD

**Issue by AdelKS** [Frogging-Family/wine-tkg-git#80]
Hello!

Hope you are getting better, and that you are doing well even with all the work you are keeping up with! I am intruding a bit in your schedule to bring up the subject of Wine on Wayland.

I have found this repository : https://github.com/varmd/wine-wayland. It enables playing directly in Wayland. Which is very cool. From the looks of it launchers don't work (for a reason I didn't find given the little time I spent on it for now) and that's about it.

My questions are:
- What are you thoughts on this Wine Wayland situation
- If you think it's possible to include/merge what has been in that other project, then I may just give it a try, maybe PR something, I can also reach the maintainer of the other repository (after I get a better overview of what's different between the two repos): I think that if we unite our workforce into one project it would be better. He is already including patches from Proton to enable esync and fsync. So what you guys are working on is very close.

**Comment by Tk-Glitch** [comment]
Hi again AdelKS,

I'm not having the best time, but it could be worse. Thanks.

> What are you thoughts on this Wine Wayland situation

Currently pretty much none. Wayland is in a pretty rough shape still and I'm not considering using it as a Xorg replacement any time soon.

> If you think it's possible to include/merge what has been in that other project, then I may just give it a try, maybe PR something, I can also reach the maintainer of the other repository (after I get a better overview of what's different between the two repos): I think that if we unite our workforce into one project it would be better. He is already including patches from Proton to enable esync and fsync. So what you guys are working on is very close.

I notice that person is using my rebased fsync patchset and other compat fixes I made for wine/proton-tkg so they're probably familiar with my repos. Everything is possible and if it's something that makes sense, offering a patchset for it (in community patches for a while) would be pretty easy if that's something varmd isn't against, or even would be interested in.

**Comment by AdelKS** [comment]
Hello!

> I'm not having the best time, but it could be worse. Thanks.

Wish you to get better soon!

> Currently pretty much none. Wayland is in a pretty rough shape still and I'm not considering using it as a Xorg replacement any time soon.

Which important features are not offered by Wayland that you consider important ? I have once again very little knowledge on this matter. Just out of curiosity. My initial intent is to try this wine on wayland and see if I don't win some input lag, or better Fullscreen handling: Overwatch on full screen mode doesn't like to lose focus (it doesn't process the mouse as aim input afterwards), windowed fullscreen fixes that.

>I noticed that that person is using my rebased fsync patchset and other compat fixes I made for wine/proton-tkg so they're probably familiar with my repos. 

Oh I didn't go that far into the checks, I see! I wonder why he didn't reach out to you.

>Everything is possible and if it's something that makes sense, offering a patchset for it (in community patches for a while) would be pretty easy if that's something varmd isn't against, or even would be interested in.

Sounds cool! I will open an issue on his repository and ask.

**Comment by AdelKS** [comment]
I will reopen this issue when things get better, one day :D
