### ISSUE TITLE
Unable to build with custom wine source using makepkg

### ISSUE THREAD

**Issue by camperboy1000** [Frogging-Family/wine-tkg-git#804]
Hi, attempting to use a custom wine source with makepkg results in the build failing to find the source files:
```
==> Starting prepare()...
  ->
/home/camperboy1000/tkg/wine-tkg-git/wine-tkg-git/wine-tkg-scripts/prepare.sh: line 493: cd: /home/camperboy1000/tkg/wine-tkg-git/wine-tkg-git/src/ValveSoftware-winegit: Not a directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```
This affects manually setting a custom wine source in the advanced config along with setting the local preset to one of the valve configs, but only when using makepkg. This does NOT affect the `non-makepkg-build.sh` script.

Attached logs
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9067984/prepare.log)

**Comment by Tk-Glitch** [comment]
It might be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/4afb9d9a4f9763a06b58deb12c279d791bf63209

**Comment by Tk-Glitch** [comment]
Could you please try adding `git+` before your repo url string?

**Comment by camperboy1000** [comment]
Adding `git+` to the repo url fixes the issue.
