### ISSUE TITLE
[Proton-tkg] `error: open wine/js_blacklist.h : No such file or directory`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#816]
An error gets thrown before compilation in the setup part (after patch application) for latest Wine-Staging
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/9225414/proton-tkg.log)

**Comment by Tk-Glitch** [comment]
Actually it seems that will not fix it in some cases. Either enable fshack or use a valve tree for now, as I won't be able to check that out today. It works with the fshack enabled though.
