### ISSUE TITLE
[Proton-tkg] Slowdown in DOA6

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#817]
(Unrelated to https://github.com/Frogging-Family/wine-tkg-git/issues/815 )

[steam-838380.log](https://github.com/Frogging-Family/wine-tkg-git/files/9227798/steam-838380.log)

[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9227802/proton-tkg.cfg.txt)
`7.2.r9.gbcfed21e` was used because of its media foundation support

The game has frequent slowdowns in gameplay (that doesn't align with the FPS overlay) and reduced performance in menus at all times.
Not sure why the speed and the framerate can get so disconnected in gameplay, but even then, the performance is bad even when the game isn't slowed as significantly.

This is the case even at the game's lowest settings and resolution; despite being "deck verified."
(I'm not using a Steam Deck, but still)

**Comment by Tk-Glitch** [comment]
Try it with experimental bleeding edge (the default option in proton-tkg profiles or with `_LOCAL_PRESET="valve-exp-bleeding"`). Wine upstream simply cannot compete on the perf front when games are that poorly made.

**Comment by ThisNekoGuy** [comment]
This does seem to make the game run fine; I've no idea what commits actually cause the performance to improve, however

**Comment by Tk-Glitch** [comment]
Wine upstream lacks a large amount of perf optimizations (and with 8.0rc1 the situation got much worse regarding winevulkan overhead notably) so that's expected behavior.
