### ISSUE TITLE
[Wine-Staging-tkg] `error: could not revert 419893519c0... win32u`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#819]
[wine-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9273628/wine-tkg.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9273630/prepare.log)

```make
419893519c0660a765ebb9898b5ccf64c273b0cf reverted (hotfix)
Auto-merging dlls/user32/scroll.c
CONFLICT (content): Merge conflict in dlls/user32/scroll.c
```

**Comment by rizzini** [comment]
Same.

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/321aae323078977ed33e839c4e5d730c99b6a9bb

**Comment by rizzini** [comment]
Yep.. All good now.
