### ISSUE TITLE
nvapi / dlss

### ISSUE THREAD

**Issue by adolfotregosa** [Frogging-Family/wine-tkg-git#820]
Sorry to bother you guys but I am trying and failing. (proton-tkg build)

Could you add it to your scripts ? I am trying to add missing nvapi folders manually, games start ok with  PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 but DLSS option is not available in game. 

What could it be that I'm missing ?

**Comment by Tk-Glitch** [comment]
You'll need to set `_proton_nvapi_disable="false"` in your .cfg (or in `wine-tkg-git/proton-tkg/proton-tkg-profiles/advanced-customization.cfg` if you're not using your own .cfg in frogminer), else the dxvk-nvapi libraries won't be built, leading to the missing feature.

**Comment by adolfotregosa** [comment]
Hi. I have _proton_nvapi_disable="false", nvapi is built but In horizon zero dawn (vkd3d), I do not know what more to do, the dlss option in game does not appear. 

Can you test it out , please ?

Thank you

**Comment by Tk-Glitch** [comment]
I cannot test it myself since I do not have a DLSS capable Nvidia GPU, but it might be fixed with `https://github.com/Frogging-Family/wine-tkg-git/commit/6b62fae379cea7e1863d02788bd16144f930e447`

**Comment by adolfotregosa** [comment]
> I cannot test it myself since I do not have a DLSS capable Nvidia GPU, but it might be fixed with [6b62fae](https://github.com/Frogging-Family/wine-tkg-git/commit/6b62fae379cea7e1863d02788bd16144f930e447)

Indeed, it works, thank you. I was pulling my hair with this. Fixed.
