### ISSUE TITLE
[wine-tkg-git] ERROR: Patch application has failed. A failure occurred in prepare().

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#83]
a8c2a5587c4b66c7e0e321670f3df62700dc228d
Arch Linux
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4907607/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4907608/last_build_config.log)
![Screenshot from 2020-07-12 02-06-32](https://user-images.githubusercontent.com/36989404/87233856-aec00100-c3e4-11ea-9a1b-f8703f508a3a.png)

**Comment by Tk-Glitch** [comment]
That was fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/32c605cf5d31468494a09cf4371f6360a992b39f

**Comment by Kerrung** [comment]
> That was fixed by [32c605c](https://github.com/Frogging-Family/wine-tkg-git/commit/32c605cf5d31468494a09cf4371f6360a992b39f)

Thank you!
