### ISSUE TITLE
Hotfixing fails

### ISSUE THREAD

**Issue by niobium93** [Frogging-Family/wine-tkg-git#833]
```
  -> Hotfixing...
error: could not revert 2c75490c3e6... win32u: Use NtUserMessageCall for NtUserSpyGetMsgName.
```
[prepare.log and my config](https://gist.github.com/niobium93/290b0f6d1675f87cb929dd1806f27e42)

**Comment by Tk-Glitch** [comment]
Fixes with https://github.com/Frogging-Family/wine-tkg-git/commit/66c0f95e75f890c6bf21ee8df365cf43c8ddf827
