### ISSUE TITLE
Futex_multiple_wait

### ISSUE THREAD

**Issue by compicat** [Frogging-Family/wine-tkg-git#834]
Thanks again for amazing work. I ve just compiled 5.15.60 tt with futexmw patch and wine-tkg-git with latest futex patch. No winesync/fastsync etc. When i load both of them, unfortunately i m not seeing "fsync is up and working" message on terminal during launching wine app. I set environment as WINEFSYNC=1. How can i check futexmw is working correct? Thanks in advance

**Comment by Iglu47** [comment]
First need to make sure that the kernel actually works correctly with fsync. The most reliable simple way is just to start the official Proton and see `fsync: up and running.`
@compicat could you attach the output of this command for me? `cat /proc/kallsyms | grep futex_waitv`

**Comment by compicat** [comment]
Thanks for your help. I m adding here:
![cat-proc-kallsyms](https://user-images.githubusercontent.com/49899468/184994550-

e7aa8583-1a76-458e-bebf-2230bbb7caf9.png)

**Comment by Iglu47** [comment]
looks fine, everything should work.
@compicat could you describe how exactly you run the application?

**Comment by Iglu47** [comment]
@compicat could you try to make a wine-tkg build with this patch?

https://gist.githubusercontent.com/Iglu47/79deb6aebadb14be58d3e1ff243f2ef0/raw/fec1f81e2e455385b00b840014a1dcd97978f9ef/linux_futex_h.myrevert

put it into `wine-tkg-userpatches` and answer `y` on such question:
```
  -> Found 1 'to revert' userpatches for plain-wine:
/home/i47/wine-tkg-git/wine-tkg-git/linux_futex_h.myrevert
Do you want to install it/them? - Be careful with that ;)
> N/y : y
  -> ######################################################
  -> 
  -> Reverting your own plain-wine patch /home/i47/wine-tkg-git/wine-tkg-git/linux_futex_h.myrevert
  -> 
  -> ######################################################
```

**Comment by compicat** [comment]
> @compicat could you try to make a wine-tkg build with this patch?
> 
> https://gist.githubusercontent.com/Iglu47/79deb6aebadb14be58d3e1ff243f2ef0/raw/fec1f81e2e455385b00b840014a1dcd97978f9ef/linux_futex_h.myrevert
> 
> put it into `wine-tkg-userpatches` and answer `y` on such question:
> 
> ```
>   -> Found 1 'to revert' userpatches for plain-wine:
> /home/i47/wine-tkg-git/wine-tkg-git/linux_futex_h.myrevert
> Do you want to install it/them? - Be careful with that ;)
> > N/y : y
>   -> ######################################################
>   -> 
>   -> Reverting your own plain-wine patch /home/i47/wine-tkg-git/wine-tkg-git/linux_futex_h.myrevert
>   -> 
>   -> ######################################################
> ```

Thanks for your all help. I found the problem. That was my stupidness. I was choosing "staging" via customization file, but i wasnt aware of that, fsync and futex are "false" in tkg-staging.cfg under tkg-git-profiles. Stupidest mistake i ve ever made. now i compiled again by making them true under profiles, fsync up and working. I guess i shouldnt see "futex up" as futex2.0, right? only fsync.

**Comment by Iglu47** [comment]
ah, ok.

all other fsync interfaces except futex_waitv are deprecated.
yea, with futex_waitv you should still see the same `fsync: up and running.`

**Comment by compicat** [comment]
> ah, ok.
> 
> all other fsync interfaces except futex_waitv are deprecated. yea, with futex_waitv you should still see the same `fsync: up and running.`

Thanks again for your help and time.

**Comment by Iglu47** [comment]
yea, I also did not immediately understand exactly how it works when I met this change for the first time.
just set `_LOCAL_PRESET="default-tkg"` in `customization.cfg` so that the promt never asks and you can't accidentally make a mistake.

**Comment by compicat** [comment]
You re definitely right. This will be easier. Thanks again.

**Comment by Tk-Glitch** [comment]
So we should make this clearer I guess!

**Comment by compicat** [comment]
at least, giving some info about "default-tkg" preset in order to use settings directly from customization may be more clear for everyone. Thanks for amazing work again.

**Comment by Tk-Glitch** [comment]
Some additions to the .cfg comments are likely desirable, but this should help people running the script as is without modification to any .cfg file, which is the most sensitive case imo https://github.com/Frogging-Family/wine-tkg-git/commit/967a62d0a7042ad5a3dc643da131a8228983d02e
I think this can be closed.
