### ISSUE TITLE
[Proton-Staging-tkg] `proton-vr-fshack.patch` Fails to Patch `vulkan.c` (Non-Valve)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#839]
[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9388617/proton-tkg.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9388616/prepare.log)

`proton-vr-fshack.patch -- ( Enable Proton vr-related wined3d additions )` -- Fails to patch `vulkan.c`
```
. . .
patching file dlls/winevulkan/vulkan.c
Hunk #1 FAILED at 386.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winevulkan/vulkan.c.rej
patching file dlls/winevulkan/vulkan.c
Hunk #1 FAILED at 368.
Hunk #2 FAILED at 386.
Hunk #3 succeeded at 561 with fuzz 1 (offset 166 lines).
Hunk #4 succeeded at 881 (offset 188 lines).
Hunk #5 FAILED at 718.
3 out of 5 hunks FAILED -- saving rejects to file dlls/winevulkan/vulkan.c.rej
. . .
```

**Comment by Iglu47** [comment]
`_shared_gpu_resources` somehow applies to `_proton_branch="proton_7.0"` but it shouldn't really.

**Comment by Iglu47** [comment]
@Tk-Glitch could you look it up yourself, I'm not sure I know how to fix proton-tkg stuff properly.

**Comment by Iglu47** [comment]
wait, something is wrong. The attached cfg gives other error

**Comment by Iglu47** [comment]
probably attached cfg from another error, but `_shared_gpu_resources` still shouldn't be applied at the same time as `_steamvr_support` anyway.

**Comment by Tk-Glitch** [comment]
> probably attached cfg from another error, but `_shared_gpu_resources` still shouldn't be applied at the same time as `_steamvr_support` anyway.

`_steamvr_support` is a hard dependency for Proton builds.

**Comment by Iglu47** [comment]
@Tk-Glitch oh, you found the way to keep the order patches applying, thanks for that.
