### ISSUE TITLE
[NonValve-Proton-Staging-tkg] FSR Patches Are Being Falsely Disabled

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#842]
[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9410370/proton-tkg.cfg.txt)

The script is disabling (both) FSR (patches) because it thinks `_proton_fs_hack` is set to false when it's actually set to `true`.
```
. . .
 -> Using staging patchset
 -> Using fsync patchset
 -> Installing to /home/neko-san/.steam/root/compatibilitytools.d/proton_tkg
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 ==> WARNING: Disabling the amd_fsr_fshack community patch because its _proton_fs_hack dependency is disabled
. . .
```

**Comment by Tk-Glitch** [comment]
The warning wasn't updated along with the _shared_gpu_resources check addition. Now it'll be explicit.
