### ISSUE TITLE
[NonValve-Proton-Staging-tkg] `hide-prefix-update-window.mypatch` Fails to Apply

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#843]
[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9428550/proton-tkg.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9428552/prepare.log)
```make
Applying your own patch hide-prefix-update-window.mypatch
patching file programs/wineboot/wineboot.c
Reversed (or previously applied) patch detected!  Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file programs/wineboot/wineboot.c.rej
```

**Comment by Tk-Glitch** [comment]
Please open community patches issues in the community patches issue tracker.
https://github.com/Frogging-Family/community-patches/issues

**Comment by Tk-Glitch** [comment]
Closing here following the issue opened in the correct repo
