### ISSUE TITLE
[NonValve-Proton-Staging-tkg] `proton_winex11_Let_the_WM_focus_our_windows_by_default.mypatch` Fails to Apply

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#844]
[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9428568/proton-tkg.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9428566/prepare.log)

```make
Applying your own patch proton_winex11_Let_the_WM_focus_our_windows_by_default.mypatch
patching file dlls/winex11.drv/x11drv_main.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/winex11.drv/x11drv_main.c.rej
```

**Comment by Tk-Glitch** [comment]
Please open community patches issues in the community patches issue tracker.
https://github.com/Frogging-Family/community-patches/issues

**Comment by Tk-Glitch** [comment]
Closing here following the issue opened in the correct repo
