### ISSUE TITLE
[wine-tkg-git] ==> ERROR: A failure occurred in build(). Aborting... 99dfb2dd75b4aee01e1d34943b7edea0d49a7013

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#85]
wine-tkg-git: 99dfb2dd75b4aee01e1d34943b7edea0d49a7013
Arch Linux;
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4911994/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4911995/prepare.log)
![Screenshot from 2020-07-13 16-01-46](https://user-images.githubusercontent.com/36989404/87297622-2e071f00-c522-11ea-8232-a2b0b55dd6f6.png)

**Comment by Tk-Glitch** [comment]
Is it possible for you to spot the actual error in your term output? Search for lines starting with stars, higher up than what you have in the pic. I've been trying to reproduce the issue for the past hour with zero success.

**Comment by YourSandwich** [comment]
I had the same issue after i abortet makepgk. Deleting the folders and git clone again solved this issue

**Comment by Kerrung** [comment]
> Is it possible for you to spot the actual error in your term output? Search for lines starting with stars, higher up than what you have in the pic. I've been trying to reproduce the issue for the past hour with zero success.

![Screenshot from 2020-07-13 23-26-54](https://user-images.githubusercontent.com/36989404/87339676-63326200-c560-11ea-9f72-c137290d8100.png)

======================================================================================================================================================================================================

![Screenshot from 2020-07-13 23-24-52](https://user-images.githubusercontent.com/36989404/87339463-19497c00-c560-11ea-8f20-77ab6830153d.png)

**Comment by Tk-Glitch** [comment]
Ok now that's explicit! Thanks

**Comment by Tk-Glitch** [comment]
Could you please provide your `config.log` found in the `wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/` dir?

**Comment by Kerrung** [comment]
> Could you please provide your `config.log` found in the `wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/` dir?

Now need a new rebase...
![Screenshot from 2020-07-14 05-59-36](https://user-images.githubusercontent.com/36989404/87368478-38173500-c597-11ea-96a8-2dbeb81e1134.png)

**Comment by Tk-Glitch** [comment]
Yeah I'll hop on it soon

**Comment by queenburtis** [comment]
I had this issue earlier but after the latest hotfix its building properly now 😄

**Comment by Kerrung** [comment]
> Could you please provide your `config.log` found in the `wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/` dir?

c19ad8c9d4572b0a377e1b879fce9d548cef0c30
[config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4928859/config.log)

**Comment by Tk-Glitch** [comment]
What's the output of `ls /usr/include/vkd3d` ?

**Comment by Kerrung** [comment]
> What's the output of `ls /usr/include/vkd3d` ?

I dont know. What should I do?

**Comment by Kerrung** [comment]
> What's the output of `ls /usr/include/vkd3d` ?

$ ls /usr/include/vkd3d
ls: cannot access '/usr/include/vkd3d': No such file or directory

**Comment by Tk-Glitch** [comment]
Ok that's your problem. For whatever reason you're missing the headers. Maybe you were simply unlucky and built vkd3d-proton right when it was getting refactored for standalone building. Rebuilding vkd3d-proton should fix your issue. I have verified that current tree populates `/usr/include/vkd3d` properly.

**Comment by Kerrung** [comment]
> Ok that's your problem. For whatever reason you're missing the headers. Maybe you were simply unlucky and built vkd3d-proton right when it was getting refactored for standalone building. Rebuilding vkd3d-proton should fix your issue. I have verified that current tree populates `/usr/include/vkd3d` properly.

![Screenshot from 2020-07-16 08-14-50](https://user-images.githubusercontent.com/36989404/87622388-77cb5180-c73c-11ea-88d3-275d0202564c.png)

**Comment by Tk-Glitch** [comment]
That is not the current version. We're at r2524.4e9b341.

**Comment by Kerrung** [comment]
> That is not the current version. We're at r2524.4e9b341.

But i have a same error with the current version.
![Screenshot from 2020-07-16 08-31-36](https://user-images.githubusercontent.com/36989404/87623445-d265ad00-c73e-11ea-81a1-2318e5879fa3.png)

**Comment by Tk-Glitch** [comment]
Have you set `_fork_disable_meson="false"` in your vkd3d config? Because you must **not** do it as this will lead to missing headers.

**Comment by Kerrung** [comment]
Yes, I use _fork_disable_meson="false"

> Have you set `_fork_disable_meson="false"` in your vkd3d config? Because you must **not** do it as this will lead to missing headers.
Yes, i use _fork_disable_meson="false", and when I do it, then I noticed that spirv-headers is not automatically installed before starting the build as makedepend, but is installed automatically if I use autotools.

**Comment by Kerrung** [comment]
Builds fine with  _fork_disable_meson="true". Thank you!
