### ISSUE TITLE
[NonValve-Proton-Staging-tkg] Hotfixing fails with wine-staging 7.16

### ISSUE THREAD

**Issue by cyrv6737** [Frogging-Family/wine-tkg-git#853]
`error: could not revert 0d0f2067f89... user32: Pass window name as UNICODE_STRING to NtUserCreateWindowEx.`

[proton-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9448354/proton-tkg.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9448357/prepare.log)

**Comment by rizzini** [comment]
Same here.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/945ffd6f43d353e3f4aa5b2a441ccbb021560311
