### ISSUE TITLE
Shared GPU resources patch fails to apply on latest staging

### ISSUE THREAD

**Issue by Ember2528** [Frogging-Family/wine-tkg-git#857]
On the current wine staging (7.16.r1) the shared GPU resources patch fails to apply

**Comment by Iglu47** [comment]
yea, should be fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/85b60a1dc393a21d248de83a982ad7b3c2a31df3 or is issue still present for you?

**Comment by Ember2528** [comment]
Still present on my end, here is my log
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9482661/prepare.log)
