### ISSUE TITLE
[wine-tkg-git] ==> ERROR: Patch application has failed.  A failure occurred in prepare(). 557d8cd7395d3ef213f35a1a683d508bd4944f76

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#86]
557d8cd7395d3ef213f35a1a683d508bd4944f76
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4924567/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/4924569/last_build_config.log)
![Screenshot from 2020-07-15 15-35-03](https://user-images.githubusercontent.com/36989404/87535351-ca5f2c00-c6b0-11ea-9c5c-3eb69bebeae3.png)

**Comment by rizzini** [comment]
Yep. I have exactly the same output.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/9f7cca284d00aedab46a6c031c8dc8b98c8cd249
