### ISSUE TITLE
Shared GPU resources patchset doesn't apply

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#860]
`sharedgpures-textures.patch -- ( Applied shared texture resources support patchset )
patching file dlls/vulkan-1/tests/vulkan.c
patching file dlls/winevulkan/make_vulkan
Hunk #1 succeeded at 111 with fuzz 2.
Hunk #2 succeeded at 126 (offset 1 line).
Hunk #3 succeeded at 191 (offset 1 line).
Hunk #4 FAILED at 199.
Hunk #5 succeeded at 237 (offset 1 line).
Hunk #6 succeeded at 267 (offset 1 line).
Hunk #7 FAILED at 1103.
Hunk #8 succeeded at 1269 (offset 7 lines).
Hunk #9 succeeded at 2203 (offset 7 lines).
Hunk #10 succeeded at 2345 (offset 7 lines).
2 out of 10 hunks FAILED -- saving rejects to file dlls/winevulkan/make_vulkan.rej
patching file dlls/winevulkan/vulkan.c
Hunk #1 FAILED at 24.
Hunk #3 succeeded at 383 (offset 8 lines).
Hunk #4 succeeded at 398 (offset 3 lines).
Hunk #5 succeeded at 1306 (offset 3 lines).
Hunk #6 succeeded at 1365 (offset 3 lines).
Hunk #7 succeeded at 1378 (offset 3 lines).
Hunk #8 FAILED at 1963.
2 out of 8 hunks FAILED -- saving rejects to file dlls/winevulkan/vulkan.c.rej
patching file dlls/winevulkan/vulkan_private.h
Hunk #1 succeeded at 226 (offset 22 lines).
patching file dlls/winevulkan/make_vulkan
Hunk #1 FAILED at 204.
Hunk #2 succeeded at 280 (offset -2 lines).
1 out of 2 hunks FAILED -- saving rejects to file dlls/winevulkan/make_vulkan.rej
patching file dlls/winevulkan/vulkan.c
Hunk #1 succeeded at 1383 (offset -11 lines).
Hunk #2 succeeded at 2000 with fuzz 2 (offset -289 lines).
patching file configure.ac
Hunk #1 succeeded at 3075 (offset 4 lines).
patching file dlls/sharedgpures.sys/Makefile.in
patching file dlls/sharedgpures.sys/shared_resource.c
patching file dlls/sharedgpures.sys/sharedgpures.sys.spec
patching file dlls/winevulkan/vulkan.c
Hunk #1 FAILED at 28.
Hunk #2 succeeded at 1329 (offset -11 lines).
Hunk #3 succeeded at 1340 (offset -11 lines).
Hunk #4 succeeded at 1353 (offset -11 lines).
Hunk #5 succeeded at 1408 (offset -11 lines).
Hunk #6 succeeded at 1428 (offset -11 lines).
Hunk #7 FAILED at 2014.
Hunk #8 FAILED at 2084.
Hunk #9 FAILED at 2102.
Hunk #10 FAILED at 2111.
Hunk #11 FAILED at 2184.
Hunk #12 FAILED at 2198.
Hunk #13 FAILED at 2274.
Hunk #14 succeeded at 2030 (offset -289 lines).
8 out of 14 hunks FAILED -- saving rejects to file dlls/winevulkan/vulkan.c.rej
patching file dlls/winevulkan/vulkan_private.h
Hunk #1 succeeded at 263 (offset 22 lines).

`

**Comment by llde** [comment]
Also are the content of sharedgpures_fixup patchset actually related to sharedgpures? It seems like a collecton of mf changes that could be applied separately.

**Comment by K1ngfish3r** [comment]
This is caused by a wine version mismatch, I fixed this by pointing the staging version to the wine version I had.

**Comment by Iglu47** [comment]
thanks for the report, it's due https://github.com/wine-mirror/wine/compare/1f9ece9e32c1195e81f8e19cdbba5831cf2b7c11...e553be7e776282fea77b8b60304298d9de90bd8b (so temporarily please use Wine version that does not yet contain these commits. Honestly, I already tried to resolve this conflict few days ago, but this weekend I hope to look at it again more closely.)

yea, `sharedgpures-fixup.patch` are indeed "fixes" of the Media Foundation source, but at this moment it's only required for sharedgpures with DXVK and probably has no effect on anything else.

**Comment by llde** [comment]
@Iglu47 In the commit descriptions of some of the patches, there are claims that they improve situation with some applications and games. I'm not sure if it's true however.
To ease the burden of maintaining the patchset  we can scorporate the mf and gstreamer changes (why even format changes are needed for a resource sharing functionality I wonder), and force include the new patchset when activating sharegpu resources. 
Also internally having 2 full fledged and self containe dpatchset should  be more easy to maintain then having a patch file with numerous small patchset often self-dependant which each other. The patch with the sharedgpu driver could also be scoproated ina a separate patch.

**Comment by llde** [comment]
Ok I did reimplment the content of the sharedgpu texture patchset for winevulkan, and made a new patch with a single commit. The sharedgpu driver stuffs and related were moved to a sharedgpu_driver patch, the gstreamer and mf changes all in the sharedgpu_fixup patchset. 
Now the fence patchset

**Comment by llde** [comment]
@Iglu47 while trying to fix up the fence patchset, there is something I don't understand.
In the wine_vkQueuePresentKHR function added in the patch there is a
`     free_VkSemaphore_array(host_semaphores, present_info->waitSemaphoreCount); `
 call. However the host_semaphores parameter is declared at the beginning of the function but never assigned. How is this supposed to work?

**Comment by Iglu47** [comment]
> @Iglu47 while trying to fix up the fence patchset, there is something I don't understand. In the wine_vkQueuePresentKHR function added in the patch there is a ` free_VkSemaphore_array(host_semaphores, present_info->waitSemaphoreCount);` call. However the host_semaphores parameter is declared at the beginning of the function but never assigned. How is this supposed to work?

fence part pretty dirty and provide minimally modified original patches, probably these part were needed at fshack

**Comment by llde** [comment]
This is not the fshack version however

**Comment by llde** [comment]
Basically done.  I need to fix an error during rebase (prevneting d3d11 app to load with dxvk) and test.
