### ISSUE TITLE
Mod Organizer 2 fails to read random files in latest staging

### ISSUE THREAD

**Issue by Ember2528** [Frogging-Family/wine-tkg-git#863]
When you are running Mod Organizer (I am using Mod Organizer 2.5.0alpha-3 on a Skyrim Special Edition install through Windows Steam in its own prefix) Mod Organizer will fail to read random directories and files from the mods you have installed. The issue becomes more likely to show up and more severe the more mods you have installed (I have 502).

The bug occurs as of 1ed196f0effa262b297705f36975261f44001417 with 533337e25e4ca728ecf75816236f2757d3e6938f being the last version

**Comment by llde** [comment]
Is this an issue with vanilla wine-staging? What about the linked official wine version?

In these case you should prefers reporting upstreams.

**Comment by Ember2528** [comment]
Alright, upstream bug is here https://bugs.winehq.org/show_bug.cgi?id=53683 SHould I close this or leave it open so other people can more easily find it if they run into the same issue?

**Comment by llde** [comment]
I' m not sure if it's possible to disable reparse points  patchset when 1ed196f0effa262b297705f36975261f44001417 is the ancestor in TKG.

**Comment by Ember2528** [comment]
We would need to revert to the older version of the patchset to fix the issue since it's needed for Mod Organizers VFS to work at all

**Comment by Ember2528** [comment]
Fixed upstream in 769ddd9f009d8b209e840a8d32bb05f43cbe4295
