### ISSUE TITLE
Compilation Error: "error: ‘BCRYPT_RSA_ALG_HANDLE’ undeclared"

### ISSUE THREAD

**Issue by Devorlon** [Frogging-Family/wine-tkg-git#865]
Compiling latest git wine and I've attached the [customisation.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/9584777/customization.txt)

> ../wine-mirror-git/dlls/ncrypt/main.c: In function ‘NCryptCreatePersistedKey’:
../wine-mirror-git/dlls/ncrypt/main.c:176:40: error: ‘BCRYPT_RSA_ALG_HANDLE’ undeclared (first use in this function); did you mean ‘BCRYPT_RNG_ALG_HANDLE’?
  176 |         status = BCryptGenerateKeyPair(BCRYPT_RSA_ALG_HANDLE, &object->key.bcrypt_key, default_bitlen, 0);
      |                                        ^~~~~~~~~~~~~~~~~~~~~
      |                                        BCRYPT_RNG_ALG_HANDLE
../wine-mirror-git/dlls/ncrypt/main.c:176:40: note: each undeclared identifier is reported only once for each function it appears in
../wine-mirror-git/dlls/ncrypt/main.c: In function ‘NCryptImportKey’:
../wine-mirror-git/dlls/ncrypt/main.c:396:38: error: ‘BCRYPT_RSA_ALG_HANDLE’ undeclared (first use in this function); did you mean ‘BCRYPT_RNG_ALG_HANDLE’?
  396 |         status = BCryptImportKeyPair(BCRYPT_RSA_ALG_HANDLE, NULL, type, &object->key.bcrypt_key, data, datasize, 0);
      |                                      ^~~~~~~~~~~~~~~~~~~~~
      |                                      BCRYPT_RNG_ALG_HANDLE
make: *** [Makefile:153066: dlls/ncrypt/main.cross.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
  -> Compilation time for 64-bit wine: 

Thanks

**Comment by compicat** [comment]
same here while compiling last staging commit. r9 has no problem with it.

**Comment by logan001** [comment]
same

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/959df9f524fd7675fafbacf0bd2295d48310ce1e
