### ISSUE TITLE
Hotfixing error: `could not revert 7384591c717...`

### ISSUE THREAD

**Issue by dougty** [Frogging-Family/wine-tkg-git#872]
`error: could not revert 7384591c717... win32u: Broadcast WM_DISPLAYCHANGE message on display settings change.`

[customization.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/9769465/customization.cfg.txt)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9769466/prepare.log)

Edit:
`_staging_version=""` produces the error, however it works if I specify `_staging_version="fe476e72411fbea9338488e5ce70d3676674b772"` for 7.18

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/979655b06359a80af9435f8cf7d8ec06f658af50
