### ISSUE TITLE
Cannot build osu profile

### ISSUE THREAD

**Issue by ZhaoZuohong** [Frogging-Family/wine-tkg-git#873]
I'm on the latest commit `94a42b2aa9b62b0467e4d732d8ded71351de0ff8`, installed dependencies manually, and built the default profile successfully with `non-makepkg-build.sh` in a `ubuntu:jammy` container.

However, I cannot build the `osu` profile.

- When choosing profile, I have first selected osu, but there is an error saying "Patch application has failed." Here are the [output of console](https://github.com/Frogging-Family/wine-tkg-git/files/9791022/log1.txt) and [prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9791024/prepare.log).
- I then read the blog of ThePooN, the original author of the osu patch, and he said that his patch only works on wine-stating 3.12. So I modified `customization.cfg` and changed the line of staging version to `_staging_version=v3.12`. However, when I compile again, there is another error complaining about missing files. [Here](https://github.com/Frogging-Family/wine-tkg-git/files/9791027/log2.txt) is the output of console.

Is osu profile still usable? Are there any fixes or workarounds for this? Thanks.

---

Update:

I have encountered a compiling error when building wine-staging v3.12 with default profile:

```
Assembler messages:
Error: can't open wintrust_dll_h.s for reading: No such file or directory
/usr/bin/i686-w64-mingw32-dlltool: /usr/bin/i686-w64-mingw32-as exited with status 1
/usr/bin/i686-w64-mingw32-dlltool: failed to open temporary head file: wintrust_dll_h.o: No such file or directory
winebuild: /usr/bin/i686-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:238647: dlls/wintrust/libwintrust.delay.a] Error 1
```

When selecting `3 - staging` profile, with wine-staging v3.12, there is another error:

```
/usr/bin/x86_64-w64-mingw32-dlltool: bfd_open failed reopen stub file: rpcrt4_dll_s00136.o: No such file or directory
```

**Comment by Tk-Glitch** [comment]
Regarding the first issue, the osu profile has been abandoned, kinda. Recent wine versions mostly fixed the initial latency issue and unless you're using pulseaudio, which you can use the `_lowlatency_audio_pulse="true"` option with (without `_lowlatency_audio="true"` which is ThePooN's patch), osu *should* play fine these days. I'll check if the changes can be rebased though, still.

For the v3.12 specific problem, this looks like a few months old dlltool issue (https://sourceware.org/bugzilla/show_bug.cgi?id=28885).

**Comment by ZhaoZuohong** [comment]
> Regarding the first issue, the osu profile has been abandoned, kinda. Recent wine versions mostly fixed the initial latency issue and unless you're using pulseaudio, which you can use the `_lowlatency_audio_pulse="true"` option with (without `_lowlatency_audio="true"` which is ThePooN's patch), osu _should_ play fine these days. I'll check if the changes can be rebased though, still.
> 
> For the v3.12 specific problem, this looks like a few months old dlltool issue (https://sourceware.org/bugzilla/show_bug.cgi?id=28885).

Thanks! I will try the `_lowlatency_audio_pulse="true"` option with latest wine version. Since the patch from ThePooN is no longer needed, I will close this issue.

**Comment by Tk-Glitch** [comment]
Alright, I pushed rebased patches so both options will work on current wine HEAD
