### ISSUE TITLE
Error building: "error: could not revert 1587e9db88c"

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#877]
`error: could not revert 1587e9db88c... win32u: Implement NtUserGetRegisteredRawInputDevices on the client side.` 
prepare.log: https://pastebin.com/HMRbDyz8

I put the logs at the pastebin, since the file has ~400 lines. If you guys prefer them to be posted here, just let us know.

**Comment by logasans** [comment]
same issue here

**Comment by Nanotwerp** [comment]
Fixed in the latest FS hack revert updates.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/5efd4cd23a88dfe11e994944bf28df850e4eb9dc
