### ISSUE TITLE
[Proton-tkg 198006c] ERROR: Patch application has failed.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#881]
Proton-tkg commit: [198006c](https://github.com/Frogging-Family/wine-tkg-git/commit/198006cdebd3607d7b24f3aae12056433812ccd3)
OS: Arch Linux;
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/9923324/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9923325/prepare.log)

![изображение](https://user-images.githubusercontent.com/36989404/199578398-29f8b958-28b7-42dd-a7a0-7018165ebc57.png)

![Screenshot from 2022-11-02 23-54-40](https://user-images.githubusercontent.com/36989404/199578451-09cc9be0-cbe2-41da-acbf-b22f835a7303.png)

**Comment by llde** [comment]
grab the sharedgpures-fixup.patch from the #861 pull request

**Comment by Tk-Glitch** [comment]
`shared-gpu-resources` is disabled on a5e39c4+ these days, let's close
