### ISSUE TITLE
unable to build protonified preset of wine

### ISSUE THREAD

**Issue by ocse22** [Frogging-Family/wine-tkg-git#887]
HEAD is now at 1d636da205e winegstreamer: Reject incompatible output types in MPEG layer-3 decoder.
patching file /home/matt/test/wine-tkg-git/wine-tkg-git/src/wine-mirror-git/include/wine/server_protocol.h
Hunk #1 succeeded at 6338 (offset 14 lines).
[detached HEAD baccc45be95] server_protocol_755
 1 file changed, 1 insertion(+), 1 deletion(-)
==> WARNING: Hotfix: Fix for Riot Client updates
==> WARNING: Hotfix: Bcrypt fixes for RDR2
==> WARNING: Hotfix: Protonify staging syscall emu
==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
==> WARNING: Hotfix: Fixup for Battle.net failing with a Qt error
==> WARNING: Hotfix: Fixup for Overwatch 2 crashing on 7.14+
  -> cherry picking...
  -> Hotfixing...
error: could not revert 5b41a4816bb... winevulkan: Support optional dispatch handles.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
==> ERROR: Patch application has failed. The error was logged to /home/matt/test/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
  -> To use the last known good mainline version, please set _plain_version="" in your .cfg
  -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit

and here is prepare.log

 -> Cleaning wine-staging source code tree...
HEAD is now at eff142bc Rebase against 1d636da205e39436bbd71849ceeebc5420bf98a9.
  -> Cleaning wine source code tree...
HEAD is now at 1d636da205e winegstreamer: Reject incompatible output types in MPEG layer-3 decoder.
Removing .gitignore
Removing include/wine/server_protocol.h.orig

a2c03e23565779d2743f5750c37de0be3f7222bf reverted (hotfix)
Auto-merging dlls/wined3d/swapchain.c

4d81825f3a489c5e36eae1cc8a46834a104e5894 reverted (hotfix)
Auto-merging dlls/wined3d/wined3d_private.h

0c38bb0b2bafca5eb232396e39c77a3e60de05fc reverted (hotfix)

572dd0b466c546adc77f7ad95a25e348bcef0088 reverted (hotfix)
Auto-merging dlls/winevulkan/loader_thunks.c
Auto-merging dlls/winevulkan/make_vulkan

5b41a4816bb50c3d8c45896d375772ee2f224d74 reverted (hotfix)
Auto-merging dlls/winevulkan/make_vulkan
CONFLICT (content): Merge conflict in dlls/winevulkan/make_vulkan
Auto-merging dlls/winevulkan/vulkan_thunks.c
CONFLICT (content): Merge conflict in dlls/winevulkan/vulkan_thunks.c

This is on archlinux, and with no modifications done other than selecting protonify preset.

**Comment by Tk-Glitch** [comment]
Should be okay as of https://github.com/Frogging-Family/wine-tkg-git/commit/d003109621d881af87ba2aaf1432feb44a09f966
If you want the fs_hack however, you'll want to target an older tree like v7.20.
