### ISSUE TITLE
Re-add 0002-proton_LFH.mypatch to chaotic-staging.cfg

### ISSUE THREAD

**Issue by niobium93** [Frogging-Family/wine-tkg-git#889]
Commit `3ffbb88` removed `0002-proton_LFH.mypatch` from the `_community_patches=` line in `chaotic-staging.cfg` because that patch was broken in the past. It has since been updated and now works. Chaotic recently started building `wine-tkg` packages again, so it would be nice to revert that commit and re-add this patch.

**Comment by Tk-Glitch** [comment]
It was rebroken with thhe recent heap/ntdll changes upstream :frog:

**Comment by NyanCatTW1** [comment]
In case someone wants to build recent Wine with LFH support, you may do one of the following:
1. Set _plain_version to ef25dd2446e9c39b71a6199d8235a3734d1d20b4
2. Set _staging_version to 49ed7ae4a001a5d84141f65064081cce3c136137
Do 2. if you are building staging, or 1. if you are building mainline.

**Comment by niobium93** [comment]
Looks like the patch was renamed. It can't find it anymore.
```
==> WARNING: The requested community patch "0002-proton_LFH.mypatch" wasn't found in the community-patches repo.
```
