### ISSUE TITLE
Proton-tkg error (3a050fc)

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#891]
OS: Arch Linux;
commit: [3a050fc](https://github.com/Frogging-Family/wine-tkg-git/commit/3a050fc714e630c372e33b978f9f0c7cbc126fd9)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/9996612/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/9996613/last_build_config.log)

![Screenshot from 2022-11-13 11-38-33](https://user-images.githubusercontent.com/36989404/201509342-28ceb7e9-4dff-49fe-9d6c-f168d39f258d.png)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/bf06041051cbbf8f7d16588eb14bf3eca0bc68c0
