### ISSUE TITLE
error: called object is not a function or function pointer.

### ISSUE THREAD

**Issue by stackglock** [Frogging-Family/wine-tkg-git#896]
When I first built wine-tkg, I got the error "could not revert 5b41a4816bb... winevulkan: Support optional dispatch handles". I tried changing the staging version as sayed [here](https://github.com/Frogging-Family/wine-tkg-git/issues/887) But another error occurs. I have tried different versions of wine-staging including 7.19 and 7.20, but nothing helps. To be honest, I don't even know how to fix the code, because the path to the file specified in the error is simply missing from my system.

```bash
../wine-mirror-git/dlls/winex11.drv/mouse.c: In function ‘X11DRV_ClipCursor’:
../wine-mirror-git/dlls/winex11.drv/mouse.c:1654:27: error: called object is not a function or function pointer
 1654 |         if (foreground == NtUserGetDesktopWindow())
      |                           ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:230225: dlls/winex11.drv/mouse.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```

**Comment by stackglock** [comment]
The build was successful without community patches.

**Comment by stackglock** [comment]
Yes, removing `winex11-fs-no_above_hate.my patch` from my patch list solved the problem.

**Comment by llde** [comment]
Do you have the Fshack? There should be a specific version winex11-fs-no_above_state for that

**Comment by stackglock** [comment]
Sorry, I don't fully understand what "Do you have the Fshack?" means. Should I install it? I have enabled _proton_fs_hack="true" in the config file. Thanks for the reply.
