### ISSUE TITLE
Shared GPU resources patch fails (again)

### ISSUE THREAD

**Issue by alou-S** [Frogging-Family/wine-tkg-git#897]
Well I guess the title is self explanatory at this point so I guess leave this issue open till its fixed? (again) 
[filtered-prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10047651/filtered-prepare.log)

**Comment by llde** [comment]
With #861 you can build until 49ed7ae4a001a5d84141f65064081cce3c136137 staging commit (7.20)
I will also rebase for latest changes
