### ISSUE TITLE
saving rejects to file dlls/ntdll/heap.c.rej

### ISSUE THREAD

**Issue by sbot50** [Frogging-Family/wine-tkg-git#901]
Wine: 7.21
wine-tkg-git version: i cloned it today so i would assume `git clone --depth=1 https://github.com/Frogging-Family/wine-tkg-git.git` gives me the latest version.
Added this patch so i can install ~~spyware~~ roblox: `curl https://raw.githubusercontent.com/NyanCatTW1/robloxWineBuildGuide/main/roblox-wine-staging-v2.5.patch --output roblox-wine-staging-v2.5.patch`

Linux: linuxmint with the xanmod kernal 6.0.9

Heres the full log:
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10077113/prepare.log)

**Comment by Tk-Glitch** [comment]
Remove `0002-proton_LFH` from your wine-tkg config's `_community_patches` array. This is not compatible with wine 7.21.
