### ISSUE TITLE
[Gstreamer32] Fails to Link Due to Unrecognized File Format

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#906]
For some reason, when I try to compile Gstreamer32, specifically, the script continues but throws errors that it couldn't build Gstreamer32 because it wasn't able to link some libraries due to them somehow being an "unrecognized file format"

**Comment by Tk-Glitch** [comment]
That usually happens when you have a 64-bit optional dependency installed without its 32-bit counterpart. Meson will attempt to build with feature parity by default and try to link against the 64-bit libs if the 32-bit ones aren't installed.
Which lib did you encounter the issue with?

**Comment by ThisNekoGuy** [comment]
A made a log for it; there's a lot of error messages
[gst32.log](https://github.com/Frogging-Family/wine-tkg-git/files/10118010/gst32.log)

But it looks like these are the ones?
```
libgstamrnb.so
libgstamrwbdec.so
libgstdvdread.so
libgstmpeg2dec.so
libgstcdio.so
libgstx264.so
```

**Comment by Tk-Glitch** [comment]
Yep, seems correct (those are the ones failing to link against your libs).

The needed packages aren't available as lib32 through Arch's repositories, but they are available on AUR with the following names:
```
lib32-opencore-amr
lib32-libdvdread
lib32-libmpeg2
lib32-libcdio
lib32-x264
```

Either installing those or removing their 64-bit version will get rid of the errors. We could definitely disable at least cdio and dvdread on our end though.
