### ISSUE TITLE
[proton-tkg-git] ==> ERROR: A failure occurred in build(). e7397736eee474b1a4ca63099d74fb8b17274338 

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#91]
e7397736eee474b1a4ca63099d74fb8b17274338
Arch Linux
GPU: AMD Radeon HD7850 with amdgpu kernel driver.
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/4929697/proton-tkg.zip)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4941589/prepare.log)

![Screenshot from 2020-07-18 17-03-33](https://user-images.githubusercontent.com/36989404/87852125-a7cf4c00-c918-11ea-8da4-94fd9effd0a1.png)

![Screenshot from 2020-07-18 16-52-11](https://user-images.githubusercontent.com/36989404/87852001-90dc2a00-c917-11ea-8cc1-c46744e9da55.png)

**Comment by Tk-Glitch** [comment]
Is this still an issue? I'm pretty sure that got fixed in the flow a couple days ago.

**Comment by Kerrung** [comment]
> Is this still an issue? I'm pretty sure that got fixed in the flow a couple days ago.

I just tried it again with 9e5a19f7071ff56ac5d04611da7d4b060279b8f4 , but it still won't to build with exactly the same error about dlls/nvcuda missing on my Radeon GPU...

**Comment by Kerrung** [comment]
I just tried it again with https://github.com/Frogging-Family/wine-tkg-git/commit/3d27dc9ba5e333abe78e3747baa7d0a24eb9e142 , but it still won't to build with exactly the same error

**Comment by Tk-Glitch** [comment]
prepare.log please

**Comment by Kerrung** [comment]
And, if that I forcefully disabled _protonify because I want to check if this is the reason that with Proton I only have a black screen with sound in Skyrim SE, while with vanilla Wine Staging everything works fine for some reason.

**Comment by Kerrung** [comment]
> prepare.log please

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4953045/prepare.log)

**Comment by Tk-Glitch** [comment]
The hotfix doesn't get picked up in your log.. Are absolutely sure you have the changes from https://github.com/Frogging-Family/wine-tkg-git/commit/3d27dc9ba5e333abe78e3747baa7d0a24eb9e142 ?

**Comment by Kerrung** [comment]
> The hotfix doesn't get picked up in your log.. Are you absolutely sure you have the changes from [3d27dc9](https://github.com/Frogging-Family/wine-tkg-git/commit/3d27dc9ba5e333abe78e3747baa7d0a24eb9e142) ?

Yes, I am sure, but if you want I can try it again.

**Comment by Tk-Glitch** [comment]
I mean, using your config on my end the corresponding hotfix got applied and it compiled fine. So unless you have changed it somehow since, there's no reason for it to get skipped.

![Screenshot_20200721_132959](https://user-images.githubusercontent.com/741977/88049972-4f858d80-cb56-11ea-8c9d-469c4d9c3f6c.png)

**Comment by Tk-Glitch** [comment]
`8898a695-staging-noprotonify-fixup` is the one that needs to be there.

**Comment by Kerrung** [comment]
If you look at my screenshots, you will see this error lines about nvcuvid (NVIDIA proprietary dll), but I use Radeon GPU :

> make[1]: *** [Makefile:180: nvcuvid.o] Error 1
> make[1]: Leaving directory '/run/media/user/Arch-Home/user/Other/wine-tkg-git/src/proton_dist-64-build/dlls/nvcuvid'
> make: *** [Makefile:9516: dlls/nvcuvid] Error 2

![Screenshot from 2020-07-21 17-06-14](https://user-images.githubusercontent.com/36989404/88052967-836fab80-cb74-11ea-877c-d5bf67c520ce.png)

**Comment by Tk-Glitch** [comment]
This has nothing to do with your GPU though. Staging has stub implementations of nvcuvid/cuda and friends and they will be built independently of your hardware.

**Comment by Kerrung** [comment]
If you want, I can record a video from the screen, which will show you how I download the latest commit from your repository, then I see that this new hotfix is missing in the hotfix folder, then I set up the config, then I see a compilation failure.

**Comment by Kerrung** [comment]
![Screenshot from 2020-07-21 17-13-23](https://user-images.githubusercontent.com/36989404/88053611-815a1c80-cb75-11ea-84b7-ccc76fdc0121.png)

**Comment by Tk-Glitch** [comment]
Simpler: send your `hotfixer` file.

**Comment by Tk-Glitch** [comment]
> then I see that this new hotfix is missing in the hotfix folder
You're not looking at the right place.

The file has been there for two weeks now, it's nothing new.
https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/hotfixes/01150d7f/8898a695-staging-noprotonify-fixup.mypatch

What has changed is the step where it decides if it should or shouldn't apply it.

**Comment by Kerrung** [comment]
I apologize for being somewhat wrong. The point was that I updated the files in the proton-tkg folder, but did not update in the wine-tkg-git folder, because I did not know that these folders were related to each other, so I did not have this hotfix.

But now I have a different problem. I previously compiled Proton with vkd3d-proton enabled, but now I disabled any vkd3d at all. And now, when building, nevertheless, for some reason, apparently, the search for vkd3d still occurs, and at this point the compilation crashes.

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/4954278/prepare.log)


![Screenshot from 2020-07-21 19-40-52](https://user-images.githubusercontent.com/36989404/88070625-529b7080-cb8c-11ea-9b9a-08aea885d9ce.png)

**Comment by Tk-Glitch** [comment]
Proton-tkg wraps around wine-tkg and depends on it indeed. Most of the "active" stuff is on the wine-tkg side. That's also why they are in the same repo and not separate.

Regarding your issue with vkd3d, the behavior was changed recently and I missed a typo in the PKGBUILD, that should now be fixed after https://github.com/Frogging-Family/wine-tkg-git/commit/58820a610615829b76820a978ba4811e3c28da58

**Comment by Kerrung** [comment]
> Proton-tkg wraps around wine-tkg and depends on it indeed. Most of the "active" stuff is on the wine-tkg side. That's also why they are in the same repo and not separate.
> 
> Regarding your issue with vkd3d, the behavior was changed recently and I missed a typo in the PKGBUILD, that should now be fixed after [58820a6](https://github.com/Frogging-Family/wine-tkg-git/commit/58820a610615829b76820a978ba4811e3c28da58)

Thank you!

**Comment by Tk-Glitch** [comment]
I'm noticing another potential issue with the makepkg path. I'll add a fix for it as well :frog:

**Comment by Tk-Glitch** [comment]
Ok. Should be all good now.
