### ISSUE TITLE
wine staging fails to build

### ISSUE THREAD

**Issue by jaypgriff** [Frogging-Family/wine-tkg-git#915]
getting an error after makepkg -si today:

`legacy-LAA-staging.patch -- ( Applied large address aware override support (legacy) )
patching file dlls/kernel32/heap.c
Hunk #1 succeeded at 82 with fuzz 2 (offset 7 lines).
Hunk #2 FAILED at 1377.
Hunk #3 succeeded at 467 (offset -950 lines).
1 out of 3 hunks FAILED -- saving rejects to file dlls/kernel32/heap.c.rej
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 2690 with fuzz 1 (offset 547 lines).
Hunk #2 FAILED at 3888.
Hunk #3 FAILED at 3908.
2 out of 3 hunks FAILED -- saving rejects to file dlls/ntdll/loader.c.rej
patching file dlls/ntdll/ntdll.spec
Hunk #1 FAILED at 1510.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/ntdll.spec.rej
patching file dlls/ntdll/ntdll_misc.h
Hunk #1 FAILED at 194.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/ntdll_misc.h.rej
can't find file to patch at input line 227
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/dlls/ntdll/virtual.c b/dlls/ntdll/virtual.c
|index 66c7b079e..8faade545 100644
|--- a/dlls/ntdll/virtual.c
|+++ b/dlls/ntdll/virtual.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored`

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/f80323b36919208793dc92c6478cf2b67aff2dde
