### ISSUE TITLE
Not fixed. PROTON_ENABLE_NVAPI=1 still fails to launch 

### ISSUE THREAD

**Issue by adolfotregosa** [Frogging-Family/wine-tkg-git#918]
Not fixed. None of the proton options 1, 2, or 3 work. nvapi is there on lib and lib64

![image](https://user-images.githubusercontent.com/7437931/205487863-879f2ff5-5aa9-4e4e-b94b-424525a1f379.png)

![image](https://user-images.githubusercontent.com/7437931/205487877-6814bbe9-a52d-4702-9e66-d8c35a6a4e45.png)

_Originally posted by @adolfotregosa in https://github.com/Frogging-Family/wine-tkg-git/issues/912#issuecomment-1336387268_

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue. Does it also happen on a clean prefix?

**Comment by adolfotregosa** [comment]
I just did a clean git clone, just and only enabled nvapi, ./proton-tkg.sh option 2, new steam prefix. I don't even have set  PROTON_ENABLE_NVAPI=1 and I get this. Games do not start now.

![image](https://user-images.githubusercontent.com/7437931/205995339-6d0bc2cb-bd28-4433-9669-77a1fb2e86ea.png)

**Comment by adolfotregosa** [comment]
Seam to be fixed, thank you !
