### ISSUE TITLE
32bit (i386) packages broken on KDE neon

### ISSUE THREAD

**Issue by acopier** [Frogging-Family/wine-tkg-git#927]
I know that debian-based distros dont go well with multilib packages but it seems from this log that the packages are broken
I have all dependencies installed
Can someone help?

[log](https://pastebin.com/raw/is39fGWc)

Some packages could not be installed. This may mean that you require
an impossible situation or, if you are using an unstable distribution, that
the required packages have not yet been created or moved from the Incoming Queue.
The following information may help you resolve this situation:

The following packages have unmet dependencies:
 libsane1:i386 : Depends on: libpoppler-glib8:i386 (>= 0.18.0) but will not install
                 Recommended: sane-airscan:i386 but will not install
 neon-desktop : Depends on: distro-release-notifier but will not install
                Depends on: kio-extras but will not install
                Depends on: software-properties-common but will not install
                Depends on: ubuntu-drivers-common but will not install
                Depends on: ubuntu-release-upgrader-qt but will not install
                Depends on: xorg but will not install
                Recommended by: firefox but will not install
                Recommends: hplip but will not install
                Recommends: plasma-firewall but will not install
 sddm : Depends on: xserver-xorg but will not install or
                     xserver
E: Error, pkgProblemResolver::Resolve creates failures, this may be caused by held packages.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

**Comment by Tk-Glitch** [comment]
If you're sure you have all the dependencies installed already, set `_nomakepkg_dep_resolution_distro=""` again (removing its current `debuntu` value) and run the build script again.

In the Debian world, Debian testing is the closest to acceptable multilib support. Ubuntu needs hacks and will break randomly every couple weeks. All other Debian or Ubuntu based distros are untested and often completely broken and unable to build multilib wine for the adventurous enough users to try that out. The worst yet is Pop_OS!, which shamelessly ships a system with half of the packages broken in some way.

**Comment by acopier** [comment]
Thanks! Worked
