### ISSUE TITLE
fsync support but Lutris says no?¿

### ISSUE THREAD

**Issue by jarrard** [Frogging-Family/wine-tkg-git#93]
I downloaded Proton-tkg 5.13.r1.g26d3815d and placed it in correct folder, loaded up lutris, selected this version and upon launching a application it claims this version of wine doesn't support fsync.  Is it not enabled for the proton build version? 

The only reason I use proton builds is because it links the game into native Linux steam so I don't need to install a windows version of steam.

**Comment by jarrard** [comment]
Enabling FSYNC and ignoring the Lutris warning appears to work anyway.. shrug..

**Comment by Tk-Glitch** [comment]
I'm pretty sure the person who made the fsync check in lutris told me it was broken at some point.
Fsync is supported in all my releases since its introduction.

**Comment by jarrard** [comment]
Yeah, also I discovered that often if you enable esync AND fsync, problems happen so its best to use either one or the other.
