### ISSUE TITLE
e990000 Proton-tkg fails to build

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#932]
Arch Linux
e990000
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10369690/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10369691/proton-tkg.log)
![Screenshot from 2023-01-09 03-57-08](https://user-images.githubusercontent.com/36989404/211223369-13377259-ef7d-4bd1-a8ba-1803d4a36c6b.png)

**Comment by Tk-Glitch** [comment]
Delete your `wine-staging-git` dir and try again

**Comment by Kerrung** [comment]
> Delete your `wine-staging-git` dir and try again

I've already tried about 10 times in a row to delete this and all the src content as it's written in prepare.log, but it never solved the problem.

**Comment by Kerrung** [comment]
@Tk-Glitch Unfortunately, the changes made in the 6b821e500842e25e4a7b96f0efa010b98f7a09fc commit did not bring any changes in any way to solve this problem. But this time I am attaching my cfg file here.
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/10375765/proton-tkg.cfg.zip)

**Comment by Tk-Glitch** [comment]
Is your prepare.log still looking the same?
```
fatal: destination path 'ValveSoftware-winegit' already exists and is not an empty directory.
fatal: destination path 'wine-staging-git' already exists and is not an empty directory.
wine-staging-git is not a clone of wine-staging-git. Please delete wine-staging-git and src dirs and try again.
/run/media/user/Arch-Home/user/Other/wine-tkg-git/wine-tkg-scripts/prepare.sh: line 69: cd: /run/media/user/Arch-Home/user/Other/wine-tkg-git/src/ValveSoftware-winegit: No such file or directory
```
The `cd: /run/media/user/Arch-Home/user/Other/wine-tkg-git/src/ValveSoftware-winegit: No such file or directory` part is really weird. The path is obviously wrong but we didn't even touch any of this with the recent changes.
I'd try a fresh clone. Also, since your .cfg looks like you copy/pasted multiple config files into one, give the default .cfg a try first.
In case you didn't know, `proton-tkg-profiles/sample-external-config.cfg` contains all the settings that are making sense to use on a proton build so you don't have to create some copy/pasta frankenstein'd config.

**Comment by Tk-Glitch** [comment]
btw I just tried with your config on my end and faced no issue.

**Comment by Kerrung** [comment]
https://github.com/Frogging-Family/wine-tkg-git/commit/128f47d991b5595d38a1848df6852e3c6a235072

[Screencast from 2023-01-09 23-57-59.webm](https://user-images.githubusercontent.com/36989404/211386770-ec14532e-11bf-45a4-8d72-0cccbb69373b.webm)

**Comment by Kerrung** [comment]
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10376184/prepare.log)

**Comment by Kerrung** [comment]
@Tk-Glitch Suddenly it started working properly, but I don't know why. It also works fine with my Frankenstein config. Thank you!

**Comment by Tk-Glitch** [comment]
🤷 Cool I guess 🐸 Not sure what happened to be honest.

**Comment by Kerrung** [comment]
@Tk-Glitch Unfortunately, the problem has returned. I've had this happen with the latest commit and with a fresh installation and default settings. I'm attaching here a full video of how this happens to me.

[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10417367/proton-tkg.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10417370/prepare.log)

[Screencast from 2023-01-14 17-35-37.zip](https://github.com/Frogging-Family/wine-tkg-git/files/10417366/Screencast.from.2023-01-14.17-35-37.zip)

**Comment by Kerrung** [comment]
@Tk-Glitch do you have any ideas about this?

**Comment by Tk-Glitch** [comment]
Still scratching my head as I cannot reproduce it :/ It's again hinting at your wine-staging repo using the wrong remote, but if you nuked it there's no reason for that to happen that I can see. I have other things to fix right now but I'll give it another deeper look.
Can you confirm deleting both the wine-staging-git dir in wine-tkg-git and the `/tmp/wine-tkg` or `/tmp/makepkg/wine-tkg-git` dirs aren't fixing the issue?

Thanks

**Comment by Tk-Glitch** [comment]
Please give it another try

**Comment by Kerrung** [comment]
![изображение](https://user-images.githubusercontent.com/36989404/212569477-61322492-5c0f-45ba-b25b-4b45a4324fc7.png)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10421358/prepare.log)
[bcb3ba7](https://github.com/Frogging-Family/wine-tkg-git/commit/bcb3ba72a3c98eac7d04990590deaf101f3bc58e)
@Tk-Glitch

**Comment by Kerrung** [comment]
> Still scratching my head as I cannot reproduce it :/ It's again hinting at your wine-staging repo using the wrong remote, but if you nuked it there's no reason for that to happen that I can see. I have other things to fix right now but I'll give it another deeper look. Can you confirm deleting both the wine-staging-git dir in wine-tkg-git and the `/tmp/wine-tkg` or `/tmp/makepkg/wine-tkg-git` dirs aren't fixing the issue?
> 
> Thanks

If you watched my video, then it shows that I downloaded absolutely everything from scratch into an empty folder and used the default settings.

**Comment by Kerrung** [comment]
I have news after my many experiments, that is, attempts to get around this problem. It turned out that this problem only affects Proton-tkg, but Wine-tkg always works fine. In addition, the most interesting and important thing here is that if you first start compiling Wine-tkg, interrupting the compilation (ctrl + x) at the moment after the download of the source code is finished and starting the compilation itself, and immediately after that start compiling Proton-tkg, then only in this case Proton-tkg will start compiling without any problems.

@Tk-Glitch [93fb6b4](https://github.com/Frogging-Family/wine-tkg-git/commit/93fb6b46f189d8882bb210b491ac4181711a686d)

**Comment by Tk-Glitch** [comment]
Ok that may help. I assume you're building wine-tkg with makepkg, right?

**Comment by Kerrung** [comment]
> Ok that may help. I assume you're building wine-tkg with makepkg, right?

I use makepkg, right. But if it helps to fix this problem, then I can try running sh-script directly if you ask me to. Just tell me how else I can help fix this problem.

**Comment by Tk-Glitch** [comment]
Okay the issue happens with makepkg proton only. Nothing else is affected.

**Comment by Tk-Glitch** [comment]
Found the issue. Why didn't I delete that BS proton PKGBUILD already? It sounds like a broken record at this point.

**Comment by Kerrung** [comment]
@Tk-Glitch With the commit https://github.com/Frogging-Family/wine-tkg-git/commit/be9e743bb05c38bfbe181339ca0193a9237dea9f everything works fine for me now. Thank you for your excellent work!
But how do I turn off the warning about your dislike of makepkg?
("If you understand yet still want this, press enter to continue... (CTRL+C to exit)")
I use makepkg because using packages is much more convenient for me than using sh script. Because I'm using the bleeding edge, I often run into regressions. I keep my own archive of old versions of proton-tkg packages so that in the event of a regression I can quickly and conveniently roll back to one of the previous versions without having to start compiling the previous version again each time. Compiling proton-tkg takes me from 30 minutes (if there is an up-to-date ccache version) to 3 hours.

**Comment by Tk-Glitch** [comment]
The regular builds are contained in a single directory, and you can just *not delete them* or keep a copy around with ease. There's no valid reason to use the makepkg path which is a buggy pile of garbage I have lost far to much time working on. It's invalid and shouldn't be used by anyone except if you want to have issues.
Expect it to be nuked in a not too distant future.

**Comment by Kerrung** [comment]
> Okay the issue happens with makepkg proton only. Nothing else is affected.



> Okay the issue happens with makepkg proton only. Nothing else is affected.

I previously posted a video here showing the problem. I hope you watched it to the end. In this video, I'm using the sh script as well as makepkg, but this problem happens in both cases. That is, it is not specific to just compiling using makepkg.

**Comment by Tk-Glitch** [comment]
The issue was that the proton makepkg path was trying to use a different source than what was expected. When running a different script afterwards it would then leave you with a broken remote. If you were to trigger the recently added sanity checks, the repo was nuked, allowing a retry but ultimately facing the exact same issue down the line as soon as you would try running makepkg again, "poisoning" your clones.

The fix was to get rid of the proton makepkg specific code path that handled source cloning and to use the main path (used by the regular, non-makepkg builds) for it instead. The problem with that is versioning, since makepkg wants to be aware of the package version early on. The dynamic nature of the project, allowing the user to customize their builds, kinda conflicts with what makepkg expects, and forces us into some hacking to get through.

The changes in https://github.com/Frogging-Family/wine-tkg-git/commit/2e15edc5eba59973e7df0f612d65382520e0df5c are a PITA, but that should be robust enough for a good while, considering the removal of a big potential breaking point in https://github.com/Frogging-Family/wine-tkg-git/commit/a096fefafe555b1b3aa04d2331e0214e55a1988e.
