### ISSUE TITLE
Error during compiling wine-tkg valve

### ISSUE THREAD

**Issue by MAZzzeen** [Frogging-Family/wine-tkg-git#939]
this is what gets printed:
../ValveSoftware-winegit/dlls/winex11.drv/mouse.c: In function ‘X11DRV_RawTouchEvent’:
../ValveSoftware-winegit/dlls/winex11.drv/mouse.c:2202:25: warning: implicit declaration of function ‘NtUserGetVirtualScreenRect’ [-Wimplicit-function-declaration]
 2202 |     RECT virtual_rect = NtUserGetVirtualScreenRect();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../ValveSoftware-winegit/dlls/winex11.drv/mouse.c:2202:25: error: invalid initializer
../ValveSoftware-winegit/dlls/winex11.drv/mouse.c:2203:20: error: ‘clip’ undeclared (first use in this function)
 2203 |     if (!EqualRect(clip, &virtual_rect)) reset_clipping_window();
      |                    ^~~~
../ValveSoftware-winegit/dlls/winex11.drv/mouse.c:2203:20: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:269809: dlls/winex11.drv/mouse.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().

**Comment by Tk-Glitch** [comment]
I cannot reproduce this issue on my end. Tested with the plain "valve" and "valve-experimental-bleeding-edge" targets.
Are you still encountering it? It might have been some froggery in the upstream repo which was fixed since.

**Comment by MAZzzeen** [comment]
im really sorry turns out it was because of one of the patches i added and forgot to remove. thank you for the help.
