### ISSUE TITLE
Proton-tkg compiles properly and the package compresses successfully, but does not install itself automatically.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#942]
Arch Linux
makepkg
https://github.com/Frogging-Family/wine-tkg-git/commit/be9e743bb05c38bfbe181339ca0193a9237dea9f
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10461147/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/10461156/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10461157/prepare.log)

I use a setting in my frogminer CFG that makes the package name constant (proton-tkg-git.tar.zst), regardless of all other settings. But as I see it, now it has become broken.

![изображение](https://user-images.githubusercontent.com/36989404/213559538-cff7d012-b7d6-4b4e-9e64-dd8689078834.png)

![изображение](https://user-images.githubusercontent.com/36989404/213559806-5ae6c379-ef52-4e0e-ada7-466f1c9c9db7.png)

**Comment by Tk-Glitch** [comment]
I don't see how we can fix that properly without destroying versioning. I'll stop supporting the makepkg path for proton-tkg. It's just not manageable and serves no purpose.
I won't delete the PKGBUILD just yet but it will not receive any update nor fix anymore going forward.

**Comment by Kerrung** [comment]
> I don't see how we can fix that properly without destroying versioning. I'll stop supporting the makepkg path for proton-tkg. It's just not manageable and serves no purpose. I won't delete the PKGBUILD just yet but it will not receive any update nor fix anymore going forward.

I've been using wine-tkg-git almost since the beginning of your wonderful project. I later switched to proton-tkg-git when it came out. I've always used makepkg exclusively, but I've never had makepkg-specific problems. And just in the last month, for the first time in all these years, I discovered problems with the compilation, which were fixed today, but they were fixed in such a way that other problems appeared. What specific changes took place during approximately December 2022 - January 2023 that led to such problems that have not been in all these years that your great project exists?

**Comment by Tk-Glitch** [comment]
From a development standpoint, the proton-tkg PKGBUILD and makepkg path were always a headache. It was a terrible experience to make, fix and maintain, and only kinda made sense in the very early days of proton, when the Steam client didn't handle missing compatibility tools gracefully. The way it works is extremely brittle and a complete hack I'm really not proud of. I'll try to come up with yet another hack to workaround this issue, but after that I'll be done with it.
Luckily, the last changes fixing your previous issue removed a nice chunk of complexity, relying more on the non-makepkg path as a result. This should allow that monstrosity to work for a while without any maintenance.
