### ISSUE TITLE
Proton-tkg makepkg exiting during build()

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#943]
[d530404](https://github.com/Frogging-Family/wine-tkg-git/commit/d530404913b8b31f70f9abeb4d7db333a947a766)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10470143/proton-tkg.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10470147/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/10470148/last_build_config.log)
![Screenshot from 2023-01-21 01-22-54](https://user-images.githubusercontent.com/36989404/213802879-302546dc-a1ee-4691-aa5a-3d5c0a6246ff.png)

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue.

**Comment by Kerrung** [comment]
> I cannot reproduce the issue.

makepkg only

**Comment by Tk-Glitch** [comment]
Well, yes, but it builds fine on my end. Your issue doesn't happen here.

**Comment by Tk-Glitch** [comment]
Also tested in a clean chroot to make sure it wasn't something in my env. Nope, built fine as well.

**Comment by Tk-Glitch** [comment]
Could you please send the .cfg used when hitting that issue?

**Comment by Kerrung** [comment]
[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/10483142/proton-tkg.cfg.zip)


> Could you please send the .cfg used when hitting that issue?

**Comment by Kerrung** [comment]
Last time I tried to build using makepkg with commit fba3cf0fff0159cfaee7d15cc300c3eee8873621 and everything compiled to the end and works fine. I'm closing this issue. Thank you so much for your great work!
![изображение](https://user-images.githubusercontent.com/36989404/214136343-3641310d-6a30-4321-a6cf-f0b97eebe1de.png)
