### ISSUE TITLE
trying to build wine-8.1 and higher(git version) with wine-staging set to false fails at prepare

### ISSUE THREAD

**Issue by silverhikari** [Frogging-Family/wine-tkg-git#955]
profile selected: default-tkg (only variables changed in customization.cfg is setting use-wine-staging to "false" and setting plain-wine to "wine-8.1")

terminal log and prepare.log: https://paste.ee/p/tmSIg

when trying to build wine-8.1 the build fails with the above error in the logs, removed wine-8.1 and tried to build with git master but that fails with the same issues.

enabling wine-staging seems to allow for this to work as i was able to create a working git version and a working wine-8.1.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/034b68bb1b32a02a77ba2b7af31be9a56c545d72
