### ISSUE TITLE
[Proton] ERROR: Patch application has failed.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#959]
Arch Linux, makepkg, https://github.com/Frogging-Family/wine-tkg-git/commit/fd53a4b8971368025614bb12e54f982e87cddb3c
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10797737/proton-tkg.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10797739/prepare.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/10797740/last_build_config.log)
![Screenshot from 2023-02-22 02-00-28](https://user-images.githubusercontent.com/36989404/220457973-ee0a575f-60c5-49e2-893e-80a9621a24e4.png)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/9935cc255bf8f7274f0b595334bf39ad74f9326a
