### ISSUE TITLE
proton-winevulkan-nofshack.patch failure with staging disabled

### ISSUE THREAD

**Issue by corecontingency** [Frogging-Family/wine-tkg-git#96]
Compiling `wine-tkg-git` with wine 5.13 (the latest development version), and staging disabled. Here are my only changes from default settings:

```
diff --git a/wine-tkg-git/customization.cfg b/wine-tkg-git/customization.cfg
index 63808e9..492262a 100644
--- a/wine-tkg-git/customization.cfg
+++ b/wine-tkg-git/customization.cfg
@@ -35,10 +35,10 @@ _GENERATE_DEBIAN_PACKAGE="false"
 # plain wine commit or version tag if you want to use a specific wine version. Can use e.g. "64d9f30", "wine-3.16" or "wine-4.0"
 # !!! Only affects non-staging builds (you want to edit the staging_version below for staging builds) !!!
 # Leave empty to use latest master - https://github.com/wine-mirror/wine/commits/master
-_plain_version=""
+_plain_version="wine-5.13"
 
 # staging
-_use_staging="true"
+_use_staging="false"
 # staging commit or version tag if you want to use a specific staging version. Can use e.g. "7cfceb7", "v3.16" or "v4.0"
 # Leave empty to use latest master - https://github.com/wine-staging/wine-staging/commits/master
 _staging_version=""
```

I applied all hotfixes with no further prompt. Here is the patch application failure:

```
  -> Applying esync-no_kernel_obj_list.patch
  -> Applying fsync-mainline.patch
  -> Applying LAA.patch
  -> Applying proton-winevulkan-nofshack.patch
==> ERROR: Patch application has failed. The error was logged to /home/user/src/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```
However, if I set `_update_winevulkan` to `false` in `customization.cfg`, then everything works fine.

The `prepare.log` for the patch application failure is [here](https://paste.ubuntu.com/p/kJsRpYDVHh/).

I'm curious here. What does the _update_winevulkan patches actually do? I assume it updates wine to use the newest vulkan extensions. If that is the case, do I need to be using the NVIDIA vulkan dev drivers? Will I encounter bugs if I use the stable NVIDIA drivers, since it doesn't support the newest vulkan extensions that wine with the patchset is trying to use?

Thanks for all the work, I found your set of repos a couple of weeks ago, and it is quite amazing!

**Comment by Tk-Glitch** [comment]
Thank you for your report and kind words :) I'll push a fix shortly.

That specific patchset is quite changing as time and upstreaming cycles are passing.
Currently it adds the following:
 - VK_EXT_full_screen_exclusive support, which is needed by some vulkan native games;
 - makes a couple extensions optional so it doesn't die on you if your driver doesn't support them;
 - sets swapchain maxImageCount to 16 to please games such as Strange Brigade, No Man's Sky or Path of Exile when using their vulkan renderers.

It might get other features pretty soon.

> do I need to be using the NVIDIA vulkan dev drivers
> Will I encounter bugs if I use the stable NVIDIA drivers

You shouldn't "need" the absolute latest and the current stable release is supposed to work fine. However you will be missing *some* improvements, that *might* affect your performances depending on your hardware. If you're happy with the results you're getting currently, no reason to switch imho :)
