### ISSUE TITLE
"ERROR: Patch application has failed" for proton-tkg-steamclient-swap.patch

### ISSUE THREAD

**Issue by Valmar33** [Frogging-Family/wine-tkg-git#961]
-> Applying proton-tkg-steamclient-swap.patch
 ==> ERROR: Patch application has failed. The error was logged to /run/media/valmar/IronWolfRAID1/Packages/Arch/AUR/Tk-Glitch/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.

[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10826018/prepare.log)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/0b211231a12ec9356b5b314e9861ef3041c4999d
