### ISSUE TITLE
Wine fails to finish the prep stage, failing with patchinstall.py

### ISSUE THREAD

**Issue by Nanotwerp** [Frogging-Family/wine-tkg-git#963]
```
Already up to date.
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fixup for Battle.net failing with a Qt error
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 -> cherry picking...
 -> Hotfixing...
 -> Applying CSMT-toggle.patch
 -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: 
sed: can't read /home/nanotwerp/wine-tkg-git/wine-tkg-git/src/wine-git/libs/wine/Makefile.in: No such file or directory
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
```

**Comment by Glitch1441** [comment]
Have the same issue:
`  ->
  -> Changing wine HEAD to the wine-staging base commit...
  -> Using upstream-commit file
HEAD is now at 3fb2a5d55e9 bcrypt: Add wow64 support for PSS padding.
==> WARNING: fshack (and associated patches) currently disabled until conflicts are resolved
==> WARNING: Hotfix: Fix for Riot Client updates
==> WARNING: Hotfix: Bcrypt fixes for RDR2
==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
==> WARNING: Hotfix: Fixup for Battle.net failing with a Qt error
==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
==> WARNING: Hotfix: Fix NosTale mouse bug
  -> cherry picking...
  -> Hotfixing...
  -> Applying steam.patch
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches using staging/patchinstall.py...
     Staging overrides used, if any:
sed: can't read /home/albert/rep/wine-tkg-git/wine-tkg-git/src/wine-git/libs/wine/Makefile.in: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done`
Tried different presets. Doesn't compile.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/8d639b0b6c8294d9df28cf18918946ff20b52506
