### ISSUE TITLE
[Proton-tkg] meson.build:68:0: ERROR: Program 'x86_64-w64-mingw32-widl' not found or not executable

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#964]
Arch makepkg, https://github.com/Frogging-Family/wine-tkg-git/commit/0b211231a12ec9356b5b314e9861ef3041c4999d
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/10841430/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/10841431/prepare.log)

![изображение](https://user-images.githubusercontent.com/36989404/221611124-a34fa491-6e5f-470c-8501-bd1e83f608f3.png)

**Comment by ViNi-Arco** [comment]
As far as I can tell, this one is using Wine's [WIDL](https://github.com/HansKristian-Work/vkd3d-proton/blob/7f20e3efde44cb3c06461b60fc35108f54fe811e/meson.build#L68), do you have Wine installed on your system?

![WineWIDL](https://user-images.githubusercontent.com/57958460/221669613-a5f5520d-2a61-41f9-9878-7cd749c9d953.png)

**Comment by Kerrung** [comment]
> As far as I can tell, this one is using Wine's [WIDL](https://github.com/HansKristian-Work/vkd3d-proton/blob/7f20e3efde44cb3c06461b60fc35108f54fe811e/meson.build#L68), do you have Wine installed on your system?
> 
> ![WineWIDL](https://user-images.githubusercontent.com/57958460/221669613-a5f5520d-2a61-41f9-9878-7cd749c9d953.png)
> 
> 

Wine-tkg I have

**Comment by Tk-Glitch** [comment]
This shouldn't be an issue anymore, as seen with the CI. Closing.
