### ISSUE TITLE
KOF XV stuck in crash loop if prefix created by TKG-Proton 

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#968]
King of Fighters XV get stuck in a crash/restart loop and steam keeps telling me the game wants to add the parameter `--use-gl=osmea` infinitely if no prefix exists and `TKG-Proton` creates the prefix, if I create the prefix and run it once using say `GE-Proton` and then switch to `TKG-Proton` it works without any issues

Screenshot of the steam dialog
![Screenshot_20230304_154525](https://user-images.githubusercontent.com/2377817/222913397-a3643c4e-c163-4dc1-84f6-d4cac31072d2.png)

Logfile when it fails
[steam-1498570.log](https://github.com/Frogging-Family/wine-tkg-git/files/10888921/steam-1498570.log)

Build config
[proton-tkg.cfg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10888927/proton-tkg.cfg.log)

**Comment by Tk-Glitch** [comment]
"Fixed" with https://github.com/Frogging-Family/wine-tkg-git/commit/9f2bf7b82ee6dc025dd7d22070590ab0184f56f3
