### ISSUE TITLE
Build without 32 bit dependencies installed.

### ISSUE THREAD

**Issue by mobedoor** [Frogging-Family/wine-tkg-git#973]
Hi. I've disabled the multilib repo in arch and am trying to build wine with _NOLIB32=true. Compilation fails due to missing 32bit packages. Could the check for 32 bit packages be skipped when building with _NOLIB32=true? Thank you.

**Comment by gabriele2000** [comment]
> Hi. I've disabled the multilib repo in arch and am trying to build wine with _NOLIB32=true. Compilation fails due to missing 32bit packages. Could the check for 32 bit packages be skipped when building with _NOLIB32=true? Thank you.

You need to be sure that you didn't accidentally disabled the cleaning tasks or messed up the source files somehow, yesterday I had the same problem too, I fixed it by redownloading everything from scratch since I had patched something using the `debug` flag on the cleaning stuff and I made a mess.
