### ISSUE TITLE
A new version of the DXVK-ASYNC patch is now available, which is now fully compatible with the current official DXVK-git master and can be used at the same time as graphics pipeline library.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#974]
Improvements:

1) Compatible with dxvk 2.1 (and current git master)
2) Async can be used at same time as graphics pipeline library.
3) Shader cache works with async (async+gpl is unknown as radv does not support shader cache with gpl currently)

https://gitlab.com/Ph42oN/dxvk-gplasync

It still requires DXVK_ASYNC=1 to be enabled.

@Tk-Glitch What do you think about adding this to Wine-tkg and to Proton-tkg?

**Comment by shelterx** [comment]
Not sure if this works with Nvidia, I'm having issues. But it could just be bad Nvidia drivers currently. 515-530 have some bugs.

**Comment by Fox2Code** [comment]
dxvk-gplasync means dxvk gpl + async

gpl here make reference to Graphic Pipeline Library, something that is supposed to replace dxvk async with a GPU supported extension to have no risk of graphical glitches.

While DXVK Async may be slightly faster than using the Graphic Pipeline Library, DXVK Async can still cause massive graphical bugs, and game bans by some anti cheats, but GPL is only available on supported GPUs.

Both technologies are here to avoid shader stuttering, also using dxvk async on top of GPL has no advantages over only using the dxvk async patch without GPL, as both are doing a bit of the same thing.

**Comment by Tk-Glitch** [comment]
@Kerrung I don't see a reason for this. GPL does allow for driver cache on mesa 23.1 and git, and also works on Nvidia. Async doesn't have any reason to live on anymore.

**Comment by Faide2020** [comment]
Hi I am using the new gplasync version but i cant tell if it really is doing async compiling. The version by sporif used to write in the log lines such as 

info:  DXVK: Using 12 compiler threads
and
info:  DXVK: Using 12 async compiler threads

but this one doesnt have the line about async compiler threads only the first line.
Does anyone know if this is correct behaviour for this fork?
Thanks
