### ISSUE TITLE
Elex fails to run missing libgcc_s_dw2-1.dll and steamclient64.dll

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#975]
Tried to run Elex on Gentoo and it fails to start
The error seems to be missing `libgcc_s_dw2-1.dll` and `steamclient64.dll`
I suspect `libgcc_s_dw2-1.dll` is the root cause though.
Proton was compiled on Arch docker container

Attaching the log
[steam-411300.log](https://github.com/Frogging-Family/wine-tkg-git/files/10979515/steam-411300.log)

**Comment by Tk-Glitch** [comment]
Wine 8.2+ has a broken interaction with lsteamclient libs swap. Please try using either an older Wine base or using a Valve based build instead.
I'll attempt to fix this as soon I am able to.

**Comment by shaumux** [comment]
Not sure if this will be helpful, just tried with `8.0.r12` with a fresh prefix and it worked, and after that switched to 8.2 on the same prefix and it still works

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/461f4d9a1d4ed33d2e2ad01a038105ad39b007a1
