### ISSUE TITLE
Proton 8.0 released

### ISSUE THREAD

**Issue by gel-crabs** [Frogging-Family/wine-tkg-git#990]
https://www.phoronix.com/news/Proton-8.0-1

**Comment by Tk-Glitch** [comment]
Support will be added soon!

**Comment by evenmynameistaken** [comment]
Thanks for the note, I've tried (and failed, in over my head) :-)

**Comment by Tk-Glitch** [comment]
Proton 8.0 support is in a good shape as of https://github.com/Frogging-Family/wine-tkg-git/commit/a33a9b8ba87def3e39cbb666febff0f80c762de8
