### ISSUE TITLE
Wayland Driver Community Patch Not Applying on Compile on Latest Default TKG

### ISSUE THREAD

**Issue by Glitch1441** [Frogging-Family/wine-tkg-git#996]
I've done this and redone this on a fresh install. On the default tkg preset (with fs hack and associated patches I know of turned off), the wayland driver community patch fails to apply and then the wrapper does not compile. I'm on Arch Linux, Hyprland, updated, and using the `PKGBUILD`.

I have an AMD Ryzen 5, 5600g and no dGPU if that matters.

The `prepare.log` is here attached:
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/11361367/prepare.log)

Thank you for your work.

**Comment by Glitch1441** [comment]
Tested out reverting the wine-staging version. You can only use up to version 8.3 it seems to me.

**Comment by Glitch1441** [comment]
Proton-TkG does not compile at all, even with setting wine upstream proton profile to v8.3. The patching works but the compilation fails. I've since retried to compile but can most likely reproduce again for a `prepare.log `as it has failed twice now. Using Valve Experimental Bleeding Edge or any other valve-related profile fails since they are just not compatible with the wayland driver community patch, and you can't seem to set an older branch due to my other issue at #997 .

**Comment by Tk-Glitch** [comment]
The wayland driver community patch was mostly upstreamed so that shouldn't be used anymore for mainline/staging based builds. Regarding Valve based builds, our patchset is only compatible with Proton 7.0 currently and we'll offer an update for 8.0 support soon.

**Comment by Glitch1441** [comment]
> The wayland driver community patch was mostly upstreamed so that shouldn't be used anymore for mainline/staging based builds. Regarding Valve based builds, our patchset is only compatible with Proton 7.0 currently and we'll offer an update for 8.0 support soon.

Thanks for the response! This information is noted. Closing this now I suppose.
